import { SellerGuidanceEntry } from './crmSellerGuidance';

const make = (
  key: string,
  title: string,
  shortHelp: string,
  details: Omit<SellerGuidanceEntry, 'key' | 'title' | 'shortHelp'> = {},
): SellerGuidanceEntry => ({ key, title, shortHelp, ...details });

const validationGuidance: Record<string, SellerGuidanceEntry> = {
  'section.sales_validation': make('section.sales_validation', 'Sales Validation', 'Use specialist review when a specific technical, commercial, timeline, compliance/risk or scope question needs an authorized decision before ProFox makes a commitment.', { whyItMatters: 'A review separates Seller discovery from specialist feasibility and constraint decisions without changing client-confirmed facts or advancing the deal.', usefulAnswerExample: 'A custom API requirement can remain a confirmed client requirement while Technical validation separately decides whether ProFox can support it and under what constraints.' }),
  'field.validation_type': make('field.validation_type', 'Validation Type', 'The review domain: Technical, Commercial, Timeline, Compliance/Risk or Scope.', { whyItMatters: 'The type routes the request through the approved role/team policy. It is not a Pipeline stage or quotation approval.', usefulAnswerExample: 'A custom authentication feasibility question is Technical; a pre-proposal nonstandard commercial arrangement is Commercial.' }),
  'field.validation_severity': make('field.validation_severity', 'Validation Severity', 'GREEN is informational, AMBER is material uncertainty, and RED is high-risk or critical unresolved uncertainty.', { whyItMatters: 'Severity is derived server-side from the versioned validation policy. Sellers cannot lower it to bypass later controls.', usefulAnswerExample: 'Compliance/Risk defaults to RED in the current policy; ordinary Technical review defaults to AMBER.' }),
  'field.validation_status': make('field.validation_status', 'Validation Status', 'Pending, In Review, Needs Information, Approved, Rejected, Cancelled or Stale describe the specialist-review lifecycle.', { whyItMatters: 'The status describes only this review question. Approved does not mean Requirements Confirmed, proposal ready, quotation approved, payment received or deal won.' }),
  'action.request_validation': make('action.request_validation', 'Request Review', 'Create an explicit specialist-review request only when current CRM facts show a real uncertainty.', { whyItMatters: 'Opening Package Fit or Requirements stays read-only; review records are created only by an intentional Seller action.', usefulAnswerExample: 'Request review for “Confirm feasibility of one-way HubSpot contact sync.”' }),
  'action.start_validation': make('action.start_validation', 'Start Review', 'An eligible reviewer claims the review and acknowledges the current canonical source before deciding.', { whyItMatters: 'Seller users cannot place a specialist review In Review, and the requester cannot self-review.' }),
  'action.request_more_information': make('action.request_more_information', 'Needs Information', 'Ask a precise question that must be answered in canonical Requirements or Discovery before the review can continue.', { whyItMatters: 'This avoids creating a parallel chat or second truth source inside the review record.', usefulAnswerExample: 'Confirm whether HubSpot synchronization is one-way or bidirectional.', avoid: 'Do not write only “Need more info.”' }),
  'action.resubmit_validation': make('action.resubmit_validation', 'Resubmit Review', 'After canonical CRM information is updated, return the existing review to Pending with an optional short note.', { whyItMatters: 'The clarification loop stays on the same review instead of generating unrelated duplicates.' }),
  'action.approve_validation': make('action.approve_validation', 'Approve Validation', 'Approve the specific review question with a meaningful decision summary and any necessary constraints.', { whyItMatters: 'Approval is auditable and scoped. It does not confirm client facts or approve quotation-specific exceptions.', usefulAnswerExample: 'Approved only for standard OAuth and one-way synchronization.' }),
  'action.reject_validation': make('action.reject_validation', 'Reject Validation', 'Reject only with a meaningful rework or scope reason.', { whyItMatters: 'The requested Requirement remains canonical; rejection tells the Seller what must change or be resolved with the client.', usefulAnswerExample: 'Requested API does not provide the required data access.' }),
  'action.cancel_validation': make('action.cancel_validation', 'Cancel Validation', 'Withdraw a review only under the safe cancellation policy and provide a reason.', { whyItMatters: 'Sales validation history is never hard-deleted; cancellation remains auditable.' }),
  'status.validation_pending': make('status.validation_pending', 'Pending', 'Requested and waiting for eligible reviewer action.', { whyItMatters: 'The issue remains unresolved.' }),
  'status.validation_in_review': make('status.validation_in_review', 'In Review', 'An eligible specialist has started assessment.', { whyItMatters: 'No client commitment should treat the decision as complete yet.' }),
  'status.validation_needs_information': make('status.validation_needs_information', 'Needs Information', 'The reviewer needs a specific clarification before deciding.', { sellerAction: 'Update the canonical CRM source, then resubmit the same review.' }),
  'status.validation_approved': make('status.validation_approved', 'Approved', 'The specific request was validated within any recorded constraints.', { whyItMatters: 'This is not deal approval, Requirements Confirmed or quotation approval.' }),
  'status.validation_rejected': make('status.validation_rejected', 'Rejected', 'The requested approach was not approved.', { sellerAction: 'Resolve the recorded rework reason with the client or revise the canonical Requirement.' }),
  'status.validation_cancelled': make('status.validation_cancelled', 'Cancelled', 'The review was legitimately withdrawn before decision.', { whyItMatters: 'The historical request remains auditable.' }),
  'status.validation_stale': make('status.validation_stale', 'Stale', 'The source Requirement changed after the specialist decision.', { whyItMatters: 'The previous decision remains historical but must not be treated as current approval.', sellerAction: 'Request a fresh review before relying on the previous specialist decision.', usefulAnswerExample: 'One-way HubSpot sync was approved, then the Requirement changed to bidirectional workflow automation.' }),
  'field.approved_constraints': make('field.approved_constraints', 'Approved Constraints', 'Conditions under which the specialist approved this specific request.', { whyItMatters: 'These constraints remain visible and auditable for later proposal and delivery planning unless superseded by a fresh review.', usefulAnswerExample: 'Approved only if synchronization remains one-way.' }),
  'field.validation_decision': make('field.validation_decision', 'Decision Summary', 'A concise specialist conclusion for the specific review question.', { whyItMatters: 'A meaningful decision prevents ambiguous “approved” states.' }),
  'field.validation_rejection_reason': make('field.validation_rejection_reason', 'Rejection / Rework Reason', 'Explain why the requested approach is not supported and what must be resolved.', { whyItMatters: 'The Seller needs an actionable reason, not a blank or generic rejection.' }),
  'type.technical_validation': make('type.technical_validation', 'Technical Validation', 'Confirms whether a specific requested capability is feasible and under what constraints.', { whyItMatters: 'It does not make the underlying client requirement client-confirmed and does not approve commercial terms.' }),
  'type.commercial_validation': make('type.commercial_validation', 'Commercial Validation', 'Reviews nonstandard commercial expectations before proposal preparation.', { whyItMatters: 'Quote-specific discounts, pricing and payment exceptions still use the existing Quotation Approval workflow.' }),
  'type.timeline_validation': make('type.timeline_validation', 'Timeline Validation', 'Checks whether requested timing can reasonably be supported given current scope, catalog guidance and dependencies.', { whyItMatters: 'A client-requested date is not automatically an approved delivery commitment.' }),
  'type.compliance_risk_validation': make('type.compliance_risk_validation', 'Compliance / Risk Validation', 'Use when regulatory, contractual security, privacy, accessibility or sensitive-data requirements need specialist judgment.', { whyItMatters: 'Seller input is not legal or compliance approval.' }),
  'type.scope_validation': make('type.scope_validation', 'Scope Validation', 'Use when standard-vs-custom boundaries or material scope uncertainty need expert interpretation.', { whyItMatters: 'Scope review does not replace Part 6 Package Fit; it resolves a specific ambiguity around current scope.' }),
};

export const getSalesValidationGuidance = (key: string): SellerGuidanceEntry => validationGuidance[key] || validationGuidance['section.sales_validation'];
