import type { SellerGuidanceEntry } from './crmSellerGuidance';

const entries: Record<string, SellerGuidanceEntry> = {
  scope_conditions: {
    key: 'part9.scope_conditions',
    question: 'What belongs in Scope Conditions?',
    whatItMeans: 'Only material assumptions, exclusions, dependencies, client responsibilities, and scope boundaries that must be explicit before proposal preparation.',
    whyWeAsk: 'A Requirement can describe a need without being safe proposal wording. Scope Conditions are the explicit reconciliation layer.',
    whatToDoNext: 'Reconcile every material source Requirement. Create or link a condition, or document why it is Not Material for Proposal.',
    example: 'Client will provide final product photography before the agreed content handoff date.',
  },
  condition_source: {
    key: 'part9.condition_source',
    question: 'Why record the source?',
    whatItMeans: 'The source shows where this proposal boundary came from and preserves traceability back to discovery, validation, or a meeting.',
    whyWeAsk: 'Without evidence, future Sellers cannot tell whether wording was client-confirmed, specialist-constrained, or internally inferred.',
    whatToDoNext: 'Choose the closest source and add enough evidence to let another Seller verify the origin.',
    example: 'Requirement: Client dependencies — confirmed during Sep 8 discovery meeting.',
  },
  condition_validation: {
    key: 'part9.condition_validation',
    question: 'What is validation alignment?',
    whatItMeans: 'It records whether the Scope Condition wording sits within current specialist-approved constraints.',
    whyWeAsk: 'A validation approval can contain limits. The condition must not silently exceed those limits.',
    whatToDoNext: 'Link the current validation and mark Within constraints only after comparing the exact wording to approved constraints.',
    example: 'Timeline wording stays within the specialist-approved 6–8 week range.',
  },
  condition_activate: {
    key: 'part9.condition_activate',
    question: 'What happens when I activate a condition?',
    whatItMeans: 'The Draft becomes a current proposal boundary. Future material changes require a revision so previous wording remains historical truth.',
    whyWeAsk: 'Proposal preparation must use current, traceable boundaries without erasing what was previously agreed internally.',
    whatToDoNext: 'Review the source, wording, and validation alignment before activating.',
    example: 'Activate only after the dependency wording matches the current Requirement and specialist constraints.',
  },
  condition_revision: {
    key: 'part9.condition_revision',
    question: 'Why create a revision instead of editing?',
    whatItMeans: 'Active and stale conditions are history-safe. A revision creates a new Draft while preserving the previous version.',
    whyWeAsk: 'Silent edits would destroy the audit trail and make older proposal preparation impossible to reconstruct.',
    whatToDoNext: 'Create the revision, change the wording, then activate the revision when it is ready.',
    example: 'Revise “client provides copy” to “client provides approved legal copy by Sep 20”.',
  },
  not_material: {
    key: 'part9.not_material',
    question: 'When should I use Not Material for Proposal?',
    whatItMeans: 'The Requirement remains discovery truth, but you explicitly document that it does not need a proposal boundary.',
    whyWeAsk: 'Ignoring a material Requirement is unsafe; explicitly classifying it creates accountable reconciliation.',
    whatToDoNext: 'Write a meaningful reason. Do not use this to bypass an unresolved scope dependency.',
    example: 'Analytics preference is operational setup detail and does not change scope, price, dependency, or delivery boundary.',
  },
  promise_register: {
    key: 'part9.promise_register',
    question: 'What is a Promise?',
    whatItMeans: 'A Promise is a material commitment ProFox actually communicated to the client. Internal preparation, client requests, hypotheses, and package recommendations are not automatically Promises.',
    whyWeAsk: 'The system must preserve what was truly communicated even when that communication was premature or still needs approval.',
    whatToDoNext: 'Keep preparation as Draft. Record it as active only when the commitment was actually communicated and the source is documented.',
    example: '“We will launch by Oct 15” becomes a Promise only if ProFox actually communicated that commitment to the client.',
  },
  promise_source: {
    key: 'part9.promise_source',
    question: 'What evidence does a Promise need?',
    whatItMeans: 'Every active Promise must point to the communication or evidence that proves it was actually made.',
    whyWeAsk: 'A CRM note that merely sounds like a promise must not become commitment truth by accident.',
    whatToDoNext: 'Use a completed meeting when applicable, or describe the real client communication in Source / evidence.',
    example: 'Email to client on Sep 9: confirmed migration would be completed before launch.',
  },
  promise_confirm: {
    key: 'part9.promise_confirm',
    question: 'Why do I need to confirm client communication?',
    whatItMeans: 'Activation is an explicit truth statement that ProFox actually communicated this material commitment to the client.',
    whyWeAsk: 'This prevents internal drafts and sales preparation from silently becoming active commitments.',
    whatToDoNext: 'Only check the confirmation when the commitment really was communicated. If it was not, leave it as Draft.',
    example: 'A prepared discount offer is still Draft until it is actually communicated.',
  },
  unapproved_commitment: {
    key: 'part9.unapproved_commitment',
    question: 'Why show an unapproved commitment instead of hiding it?',
    whatItMeans: 'The Promise is real because it was communicated, but it is unsafe because required specialist validation is missing, stale, rejected, or conflicting.',
    whyWeAsk: 'History must reflect reality. Approval problems should block readiness, not erase the commitment.',
    whatToDoNext: 'Open Sales Validation, resolve the required specialist decision, then reconcile the Promise wording to approved constraints.',
    example: 'A communicated timeline remains recorded even if Timeline validation is still pending.',
  },
  future_quote: {
    key: 'part9.future_quote',
    question: 'Does this mean the quotation is ready to send?',
    whatItMeans: 'No. Part 9 is pre-quotation integrity. Promise Coverage, Final Scope Reconciliation, and Quotation Snapshot Coverage are intentionally future workflow dimensions.',
    whyWeAsk: 'Part 9 must not create a second quotation authority or silently activate the final send gate.',
    whatToDoNext: 'Use Scope & Commitments to prepare safe proposal context. Quotation reconciliation remains Part 10.',
    example: 'A clean Promise Register does not prove the final quotation snapshot contains every commitment.',
  },
};

export const getScopeCommitmentGuidance = (key: keyof typeof entries | string): SellerGuidanceEntry | null => entries[key] || null;
