export const DISCOVERY_FOCUS_ENTRIES = [
  ['business_what_do_you_offer', 'Clarify what the business actually sells or provides today, including the main offer customers pay for.'],
  ['business_priority_service', 'Identify which offer or business area the client most wants this project to grow, rather than assuming every service is equally important.'],
  ['business_current_lead_sources', 'Understand where enquiries currently come from and how prospects make first contact.'],
  ['business_current_process', 'Map the current path from initial interest to becoming a customer so gaps and handoffs are visible.'],
  ['business_current_tools', 'Identify the website, CRM, booking, marketing and internal tools already in use before suggesting changes.'],
  ['problem_main', 'Identify the primary business problem the client wants solved in their own words, not a Seller diagnosis.'],
  ['problem_current_site', 'Understand the specific website or digital-process friction the client experiences today.'],
  ['problem_customer_dropoff', 'Locate where prospects stall, abandon, fail to convert or need extra help in the current journey.'],
  ['problem_internal_team', 'Find the manual work, repeated effort or internal frustration the current process creates for staff.'],
  ['problem_previous_attempts', 'Learn what the client already tried, what happened, and what they believe did or did not work.'],
  ['impact_business', 'Clarify the business consequence of the problem in practical terms such as growth, operations, customer experience or risk.'],
  ['impact_leads_revenue', 'Understand any effect on leads, sales, revenue or acquisition using client-provided examples or estimates only.'],
  ['impact_team_time', 'Estimate how much staff time or operational effort the problem consumes without inventing a number.'],
  ['impact_customer_experience', 'Understand how the current problem affects what customers experience before, during or after conversion.'],
  ['impact_do_nothing', "Explore the likely consequence of leaving the current situation unchanged; record the client's view, not manufactured urgency."],
  ['outcome_success', "Clarify what meaningful improvement would change for the business from the client's perspective."],
  ['outcome_success_definition', "Capture the client's practical definition of a successful project so success is not reduced to 'a better website'."],
  ['outcome_metric', 'Identify any measurable result the client cares about, while keeping estimates separate from guarantees.'],
  ['outcome_user_action', 'Identify the single most important action users should take and what should happen after they take it.'],
  ['audience_ideal_customer', 'Define who the client most wants to reach, including customer type, problem, buying context and meaningful exclusions.'],
  ['audience_geography', 'Clarify the locations or markets that matter to the client so scope and targeting are not assumed.'],
  ['audience_motivation', 'Understand what tends to make the target customer seek help, compare options or take action.'],
  ['audience_objections', 'Identify common concerns, delays or blockers customers raise before taking action.'],
  ['audience_segments', 'Find whether different customer groups need materially different messages, journeys or experiences.'],
  ['scope_new_or_redesign', 'Confirm whether this is a new build, redesign or improvement to an existing system because each has different dependencies.'],
  ['scope_pages', 'Identify the pages or main sections the client already knows are required without treating the list as final scope automatically.'],
  ['scope_features', 'Capture what users must actually be able to do, separating required behavior from vague feature labels.'],
  ['scope_forms', 'Clarify the forms, enquiry paths, applications or lead-capture flows needed and what happens after submission.'],
  ['scope_conversion', 'Understand the post-conversion path: routing, confirmation, booking, sales handoff or other next step.'],
  ['scope_multilingual', 'Confirm whether multiple languages are genuinely required and which content/audiences they apply to.'],
  ['content_existing', 'Identify usable existing copy, images, video, documents and other content instead of assuming everything is ready or needs replacing.'],
  ['content_copy_owner', 'Clarify who will create, supply and approve copy; do not imply copywriting is included unless commercial scope says so.'],
  ['content_photos', 'Identify usable visual assets, gaps and ownership/approval needs without promising media production.'],
  ['content_proof', 'Capture legitimate reviews, testimonials, certifications, case studies or proof that can support trust.'],
  ['content_compliance', 'Identify legal, regulatory or industry content constraints that may need specialist/legal input; do not give legal advice.'],
  ['brand_existing', 'Confirm which brand assets are final and usable: logo, guidelines, fonts, colours, tone and approved files.'],
  ['brand_change', 'Clarify whether the client expects the existing identity to be followed or a visual/branding change, without promising branding services.'],
  ['brand_examples', 'Use examples to learn the reasons behind visual preferences, not to copy another brand.'],
  ['commercial_timeline', 'Capture the desired go-live timing separately from feasibility; a requested date is not a delivery promise.'],
  ['commercial_deadline_reason', 'Understand what drives the requested date so urgency and dependencies can be assessed accurately.'],
  ['commercial_budget', "Understand the client's investment context without pressuring, inventing a budget, promising discounts or changing approved pricing."],
  ['commercial_priority', "Clarify the client's trade-off priority when scope, time and budget compete; do not turn this into an automatic package decision."],
  ['decision_who_involved', 'Identify everyone who evaluates, influences or approves the project without assuming the current contact has final authority.'],
  ['decision_final_approval', 'Identify who can give final approval and what that approval covers.'],
  ['decision_criteria', 'Understand the factors the client will use to choose a solution or provider, such as capability, risk, timing, support or price.'],
  ['decision_process', 'Map the internal steps required before the client can proceed, including reviews and approvals.'],
  ['decision_alternatives', 'Understand other agencies, internal options, alternative approaches or doing nothing without disparaging competitors.'],
  ['complex_economic_buyer', 'Identify who ultimately controls or approves the commercial budget in a complex decision.'],
  ['complex_procurement', 'Identify procurement, legal, contract, vendor or security steps that can affect timing and approval.'],
  ['complex_champion', 'Identify the internal person most invested in the project succeeding, without asking them to bypass other stakeholders.'],
  ['integration_any', 'Establish whether external systems must connect before discussing technical feasibility.'],
  ['integration_which_systems', 'Name the exact systems that need to connect and who owns them.'],
  ['integration_purpose', "Clarify the business outcome the integration must produce rather than accepting 'integrate X' as sufficient scope."],
  ['integration_direction', 'Map which data moves from which system to which destination, including one-way or two-way movement.'],
  ['integration_account', 'Confirm whether required third-party accounts exist and who controls them; never request credentials in normal CRM notes.'],
  ['integration_criticality', 'Separate launch-critical integrations from work that can happen later so dependencies are visible.'],
  ['integration_api_custom', 'Determine whether a known standard connector may work or custom API work may be required; do not promise feasibility before validation.'],
  ['ecommerce_need', 'Confirm whether customers must purchase or pay online and what the intended checkout journey is.'],
  ['ecommerce_products', 'Understand the product/service catalogue size, variations and complexity that affect store scope.'],
  ['ecommerce_payments', 'Identify required payment providers/methods and currencies without collecting card data, secret keys or payment credentials.'],
  ['ecommerce_shipping', 'Understand delivery/shipping regions, methods, rules and fulfilment expectations where relevant.'],
  ['ecommerce_tax', 'Identify tax-handling expectations that may require accounting/legal confirmation; do not give tax advice.'],
  ['ecommerce_inventory', 'Determine whether stock is managed only in the store or must synchronize with another system.'],
  ['ecommerce_subscription', 'Clarify recurring billing, subscription periods, changes/cancellations and provider expectations where applicable.'],
  ['booking_need', 'Confirm whether customers need to book and what kind of appointment, consultation or service they schedule.'],
  ['booking_provider', 'Identify the current or intended booking/calendar platform without requesting account passwords.'],
  ['booking_rules', 'Capture availability, staff, location, appointment-type, buffer and time-zone rules that shape booking logic.'],
  ['booking_notifications', 'Clarify confirmations and reminders, timing, channels and recipients for the booking journey.'],
  ['seo_importance', 'Understand how important organic search is to the project without promising rankings or traffic.'],
  ['seo_services', 'Identify the services/topics the client most wants search visibility for, using business priorities rather than guaranteed keywords.'],
  ['seo_locations', 'Identify the locations or markets SEO should focus on without promising local rankings.'],
  ['seo_existing', 'Identify existing rankings, Search Console data, pages and SEO assets that may need preserving during change.'],
  ['seo_migration', 'Confirm whether URLs/content move and whether redirects or migration planning are required to protect existing value.'],
  ['analytics_current', 'Identify current analytics/tracking platforms and ownership without requesting passwords in CRM notes.'],
  ['analytics_conversions', 'Define which business/user actions should count as conversions so tracking goals are meaningful.'],
  ['analytics_events', 'Identify specific user behaviours/events the client needs measured beyond headline conversions.'],
  ['analytics_reporting', 'Clarify who needs reports, what decisions they make, and what information they need to see.'],
  ['technical_domain', 'Identify the current domain, registrar/controller and coordination needs; do not store passwords or recovery credentials.'],
  ['technical_hosting', 'Identify current hosting/provider and whether migration may be needed; do not request login secrets in free text.'],
  ['technical_platform', 'Identify the current CMS/platform and relevant version/customization context before assuming a migration approach.'],
  ['technical_migration', 'Clarify exactly what content, users, data, URLs or assets must move from the current system.'],
  ['technical_login', 'Clarify account, login, authentication and recovery needs at a requirements level; feasibility/security details need appropriate validation.'],
  ['technical_roles', 'Define different user roles and the access each role needs, without making unapproved security assumptions.'],
  ['technical_dashboard', 'Clarify who needs a private portal/dashboard, what they need to see and what actions they need to take.'],
  ['technical_security', 'Capture security, privacy, compliance and data-handling needs without collecting secrets or promising compliance before review.'],
  ['technical_accessibility', 'Identify required accessibility standards or obligations and flag unclear compliance requirements for appropriate validation.'],
  ['app_users', 'Identify application user types and their goals before defining screens or permissions.'],
  ['app_workflow', 'Map the end-to-end business workflow the application must support, including handoffs and exceptions.'],
  ['app_permissions', 'Define what each application role can view, create, change or approve; security feasibility needs technical review.'],
  ['app_data', 'Identify data the application must store, import, export or synchronize, including source and sensitivity.'],
  ['app_notifications', 'Clarify which events send notifications, to whom, by which channel and with what timing.'],
  ['app_admin', 'Identify the internal operations administrators need to perform rather than assuming a generic admin panel.'],
  ['app_reporting', 'Define required reports/dashboards, audiences, metrics and decisions they support.'],
  ['app_scale', 'Capture expected users, records, transactions or locations as planning context, not a guaranteed capacity commitment.'],
  ['app_acceptance', 'Define observable acceptance criteria the client can use to decide whether the application meets the agreed requirement.'],
  ['risk_dependencies', 'Identify what the client/team must provide or approve for delivery to move, including timing dependencies.'],
  ['risk_known', 'Capture known technical, legal, content, approval or timing risks without presenting assumptions as facts.'],
  ['risk_assumptions', 'List working assumptions that still need confirmation so they cannot silently become scope truth.'],
  ['risk_exclusions', 'Capture what is explicitly outside expected scope so exclusions are visible rather than implied.'],
] as const;

export const DISCOVERY_GUIDANCE_KEYS = DISCOVERY_FOCUS_ENTRIES.map(([key]) => key);
export const DISCOVERY_FOCUS = new Map<string, string>(DISCOVERY_FOCUS_ENTRIES as readonly (readonly [string, string])[]);

export const REQUIREMENT_GUIDANCE_KEYS = [
  'business_objective','current_situation','primary_offer_service','business_model_context','business_priority','current_customer_journey','primary_problem','business_impact','urgency_reason','secondary_problems','cost_of_inaction','desired_outcome','success_definition','success_metrics','target_customer','target_geography','audience_segments','customer_motivations','customer_objections','project_type','existing_digital_state','required_pages','primary_cta','required_functionality','site_structure','forms_lead_capture','conversion_paths','multilingual_requirement','content_status','copywriting_requirement','images_media','trust_proof','legal_compliance_content','logo_status','brand_guidelines_status','brand_assets_status','visual_preferences','branding_work_required','crm_integration','third_party_integrations','api_requirements','automation_requirements','integration_data_flow','ecommerce_required','product_catalog','payment_gateway','shipping_requirement','tax_requirement','inventory_requirement','subscription_requirement','ecommerce_customer_accounts','booking_required','booking_provider','booking_availability_logic','booking_notifications','seo_priority','seo_service_topics','seo_locations','existing_seo_assets','seo_keyword_priorities','seo_redirect_migration','analytics_platform','conversion_tracking','analytics_events','reporting_requirements','domain_status','hosting_status','cms_platform','performance_requirements','migration_requirements','authentication_requirement','user_roles_permissions','portal_dashboard','data_database','security_requirements','accessibility_requirements','mobile_specific_requirement','budget_context','target_timeline','target_launch_date','deadline_reason','decision_maker','primary_approver','decision_criteria','decision_process','competition_alternatives','economic_buyer','procurement_process','internal_champion','stakeholder_map','business_workflows','app_user_types','app_permissions','app_notifications','app_reporting','app_admin_operations','app_usage_scale','acceptance_criteria','training_handover','technical_uncertainties','client_dependencies','assumptions','exclusions','scope_risks','access_required_later',
] as const;
export const REQUIREMENT_GUIDANCE_KEY_SET = new Set<string>(REQUIREMENT_GUIDANCE_KEYS);
