import { supabase } from './supabase';

export type FindingSeverity='E0'|'E1'|'E2'|'E3';
export type FindingStatus='Open'|'In Progress'|'Resolved'|'Verified'|'Waived';
export type FindingSource='Developer Self-Test'|'Code Review'|'QA'|'Security'|'Accessibility'|'Performance'|'UI/UX Implementation QA'|'SEO'|'Analytics'|'UAT'|'Production Monitoring'|'Client';

export interface QualityWorkspace{findings:any[];changeRequests:any[];incidents:any[];releaseBlockers:{e0:number;e1:number;e2:number;e3:number;releaseBlocking:boolean}}
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const id=(value:string,label:string)=>{if(!UUID_RE.test(value))throw new Error(`${label} is invalid.`)};
const fail=(error:any,fallback:string)=>new Error(error?.message||fallback);

export const developmentQualityService={
 async getWorkspace(taskId:string):Promise<QualityWorkspace>{id(taskId,'Task');const{data,error}=await supabase.rpc('development_quality_workspace',{p_task_id:taskId});if(error)throw fail(error,'Unable to load quality findings.');return data as QualityWorkspace;},
 async createFinding(input:{projectId:string;taskId:string;source:FindingSource;severity:FindingSeverity;title:string;description:string;reproductionSteps?:string;expectedResult?:string;actualResult?:string;evidenceUrl?:string;assignedTo?:string|null}){id(input.projectId,'Project');id(input.taskId,'Task');const{data,error}=await supabase.rpc('development_quality_create_finding',{p_project_id:input.projectId,p_task_id:input.taskId,p_source:input.source,p_severity:input.severity,p_title:input.title.trim(),p_description:input.description.trim(),p_reproduction_steps:input.reproductionSteps?.trim()||'',p_expected_result:input.expectedResult?.trim()||'',p_actual_result:input.actualResult?.trim()||'',p_evidence_url:input.evidenceUrl?.trim()||'',p_assigned_to:input.assignedTo||null});if(error)throw fail(error,'Unable to create quality finding.');return data as string;},
 async updateFinding(findingId:string,status:FindingStatus,resolutionNotes='',regressionEvidence=''){id(findingId,'Finding');const{error}=await supabase.rpc('development_quality_update_finding',{p_finding_id:findingId,p_status:status,p_resolution_notes:resolutionNotes.trim(),p_regression_evidence:regressionEvidence.trim()});if(error)throw fail(error,'Unable to update quality finding.');},
 async submitChangeRequest(input:{projectId:string;taskId:string;summary:string;reason:string;effort:string;cost:string;timeline:string;architecture:string;security:string;qaRegression:string;designContentSeo:string}){id(input.projectId,'Project');id(input.taskId,'Task');const{data,error}=await supabase.rpc('development_change_request_submit',{p_project_id:input.projectId,p_task_id:input.taskId,p_request_summary:input.summary.trim(),p_reason:input.reason.trim(),p_effort_impact:input.effort.trim(),p_cost_impact:input.cost.trim(),p_timeline_impact:input.timeline.trim(),p_architecture_impact:input.architecture.trim(),p_security_impact:input.security.trim(),p_qa_regression_impact:input.qaRegression.trim(),p_design_content_seo_impact:input.designContentSeo.trim()});if(error)throw fail(error,'Unable to submit change request.');return data as string;},
 async decideChangeRequest(requestId:string,decision:'Approved'|'Rejected',notes:string){id(requestId,'Change request');const{error}=await supabase.rpc('development_change_request_decide',{p_request_id:requestId,p_decision:decision,p_notes:notes.trim()});if(error)throw fail(error,'Unable to decide change request.');},
 async createIncident(input:{projectId:string;severity:FindingSeverity;title:string;description:string}){id(input.projectId,'Project');const{data,error}=await supabase.rpc('development_incident_create',{p_project_id:input.projectId,p_severity:input.severity,p_title:input.title.trim(),p_description:input.description.trim(),p_owner_id:null});if(error)throw fail(error,'Unable to create incident.');return data as string;},
 async updateIncident(input:{incidentId:string;status:'Detected'|'Contained'|'Service Restored'|'Investigating'|'Resolved'|'Verified'|'Closed';communication?:string;rootCause?:string;whyNotPrevented?:string;whyNotDetected?:string;correctiveActions?:string;preventionActions?:string}){id(input.incidentId,'Incident');const{error}=await supabase.rpc('development_incident_update',{p_incident_id:input.incidentId,p_status:input.status,p_communication_notes:input.communication?.trim()||'',p_root_cause:input.rootCause?.trim()||'',p_why_not_prevented:input.whyNotPrevented?.trim()||'',p_why_not_detected:input.whyNotDetected?.trim()||'',p_corrective_actions:input.correctiveActions?.trim()||'',p_prevention_actions:input.preventionActions?.trim()||''});if(error)throw fail(error,'Unable to update incident.');}
};
