import React,{useEffect,useState}from'react';
import{CheckCircle2,ExternalLink,FileCheck2,Loader2,ShieldCheck}from'lucide-react';
import{supabase}from'../../lib/supabase';

type ReleasedHandover={projectId:string;projectNumber:string;projectName:string;version:number;status:string;clientPackage:Record<string,string>;approvedAt:string;releasedAt:string};
const LABELS:Record<string,string>={productionUrl:'Production URL',documentationReference:'Documentation',releaseEvidence:'Final QA / release evidence',accessOwnership:'Access ownership / transfer',supportBoundary:'Support / warranty boundary',repositoryAccess:'Repository / source access',cmsInstructions:'CMS / admin instructions',integrations:'Integrations',analyticsTracking:'Analytics / tracking',backupRecovery:'Backup / recovery',trainingReference:'Training / walkthrough'};

export default function ClientDevelopmentHandover({projectId}:{projectId:string}){
 const[data,setData]=useState<ReleasedHandover|null>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);supabase.rpc('client_get_released_development_handover',{p_project_id:projectId}).then(({data,error})=>{if(!active)return;setData(error?null:(data as ReleasedHandover|null));setLoading(false)});return()=>{active=false}},[projectId]);
 if(loading)return <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><Loader2 className="h-4 w-4 animate-spin text-[#000080]"/>Checking final handover...</div></section>;
 if(!data)return null;
 const entries=Object.entries(data.clientPackage||{}).filter(([,value])=>String(value||'').trim());
 return <section className="rounded-[2rem] border border-emerald-200 bg-emerald-50/60 p-7 shadow-sm">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-4"><div className="rounded-2xl bg-emerald-100 p-3 text-emerald-700"><FileCheck2 className="h-6 w-6"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Manager-approved final handover</div><h2 className="mt-1 text-xl font-black text-slate-900">Your final project handover is ready</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">This package was prepared by Development and released only after final Project Manager/Management review.</p></div></div><span className="w-fit rounded-full bg-white px-3 py-1 text-[10px] font-black text-emerald-700">Version {data.version}</span></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2">{entries.map(([key,value])=><div key={key} className="rounded-2xl border border-emerald-100 bg-white p-4"><div className="text-[10px] font-black uppercase tracking-wide text-slate-400">{LABELS[key]||key.replace(/([A-Z])/g,' $1')}</div>{/^https?:\/\//i.test(String(value))?<a href={String(value)} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1.5 break-all text-xs font-black text-[#000080]">Open approved reference <ExternalLink className="h-3.5 w-3.5"/></a>:<p className="mt-2 whitespace-pre-wrap text-xs leading-6 text-slate-700">{String(value)}</p>}</div>)}</div>
  <div className="mt-5 flex items-start gap-2 rounded-2xl border border-emerald-100 bg-white/70 p-4 text-[11px] leading-5 text-slate-600"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-700"/><span><strong className="text-slate-800">Secure release:</strong> internal Development review notes and credentials are not exposed here. Sensitive access should be transferred only through the approved secure method referenced in the package.</span></div>
  <div className="mt-4 flex items-center gap-2 text-[10px] font-bold text-emerald-800"><CheckCircle2 className="h-3.5 w-3.5"/>Released {data.releasedAt?new Date(data.releasedAt).toLocaleString():'after Management approval'}</div>
 </section>;
}