import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,ArrowRight,BriefcaseBusiness,CheckCircle2,CircleDollarSign,Clock3,Gauge,Loader2,RefreshCw,Settings2,Target,TrendingUp,UsersRound} from 'lucide-react';
import {Navigate,useNavigate} from 'react-router-dom';
import {useAuth} from '../../lib/AuthContext';
import {BusinessException,BusinessIntelligenceDashboard as Dashboard,ManagementBrief,businessIntelligenceService} from '../../lib/businessIntelligenceService';

type Tab='overview'|'sales'|'delivery'|'finance'|'people';
const periods=[7,30,90];
const severityTone:Record<string,string>={Critical:'border-red-200 bg-red-50 text-red-700',High:'border-amber-200 bg-amber-50 text-amber-800',Medium:'border-blue-200 bg-blue-50 text-[#000080]'};
const healthTone:Record<string,string>={Healthy:'text-emerald-700 bg-emerald-50 border-emerald-200',Watch:'text-amber-700 bg-amber-50 border-amber-200','At Risk':'text-red-700 bg-red-50 border-red-200'};

function money(value:number|undefined,currency:string){try{return new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value||0));}catch{return `${currency} ${Number(value||0).toLocaleString()}`;}}
function pct(value:number|undefined|null){return `${Number(value||0).toFixed(Number(value||0)%1===0?0:1)}%`;}
function roleLabel(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());}

export default function BusinessIntelligenceDashboard(){
  const nav=useNavigate();
  const {user,profile,isAdmin,loading:authLoading}=useAuth();
  const allowed=Boolean(user&&profile?.status==='active'&&isAdmin);
  const [period,setPeriod]=useState(30);
  const [tab,setTab]=useState<Tab>('overview');
  const [data,setData]=useState<Dashboard|null>(null);
  const [brief,setBrief]=useState<ManagementBrief|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');

  const load=async()=>{setLoading(true);setError('');try{const [d,b]=await Promise.all([businessIntelligenceService.getDashboard(period),businessIntelligenceService.getBrief(period)]);setData(d);setBrief(b);}catch(e:any){setError(e?.message||'Unable to load business intelligence.');}finally{setLoading(false);}};
  useEffect(()=>{if(allowed)void load();},[allowed,period]);
  const topExceptions=useMemo(()=>(data?.exceptions||[]).slice(0,8),[data]);

  if(authLoading)return <div className="min-h-screen bg-slate-50"/>;
  if(!allowed)return <Navigate to="/admin" replace/>;

  const primary=data?.primaryCurrency||'USD';
  const revenueChange=data?.finance.primary.revenueChangePercent;

  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur-xl">
      <div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-4 sm:px-8">
        <div className="flex items-center gap-3"><button onClick={()=>nav('/admin/workspace')} className="rounded-xl border border-slate-200 p-2 hover:bg-slate-50" aria-label="All apps"><ArrowLeft className="h-4 w-4"/></button><div><div className="flex items-center gap-2"><h1 className="text-xl font-black">Founder Control</h1><span className="rounded-full bg-blue-50 px-2 py-0.5 text-[9px] font-black uppercase tracking-wider text-[#000080]">Business Intelligence</span></div><p className="text-xs text-slate-500">See business health, exceptions and decisions — then act in the original module.</p></div></div>
        <div className="flex items-center gap-2"><button onClick={()=>nav('/admin/intelligence-settings')} className="hidden items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-slate-600 hover:text-[#000080] sm:inline-flex"><Settings2 className="h-4 w-4"/> KPI rules</button><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
      </div>
    </header>

    <main className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8">
      {error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
      <div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-400">Management window</div><p className="mt-1 text-xs text-slate-500">Financial values are never mixed across currencies. Top-line money cards use {primary} only.</p></div><div className="flex w-fit rounded-xl border border-slate-200 bg-white p-1">{periods.map(p=><button key={p} onClick={()=>setPeriod(p)} className={`rounded-lg px-3 py-1.5 text-xs font-black ${period===p?'bg-[#000080] text-white':'text-slate-500 hover:bg-slate-50'}`}>{p} days</button>)}</div></div>

      {loading&&!data?<div className="flex min-h-[520px] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>:data&&<>
        <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
          <MetricCard icon={Gauge} label="Operational health" value={`${data.health.score}/100`} note={data.health.status} tone={healthTone[data.health.status]||healthTone.Watch}/>
          <MetricCard icon={CircleDollarSign} label="Verified revenue" value={money(data.finance.primary.verifiedRevenue,primary)} note={revenueChange===null?'No prior-period baseline':`${revenueChange!>=0?'+':''}${revenueChange}% vs previous`}/>
          <MetricCard icon={TrendingUp} label="Weighted pipeline" value={money(data.sales.weightedPipelinePrimary,primary)} note={`${data.overview.openOpportunities} open opportunities`}/>
          <MetricCard icon={Target} label="Outstanding" value={money(data.finance.primary.outstanding,primary)} note="Unverified open balance"/>
          <MetricCard icon={AlertTriangle} label="Needs attention" value={String(data.health.openExceptions)} note={`${data.health.critical} critical · ${data.health.high} high`} tone={data.health.critical?'border-red-200 bg-red-50 text-red-700':'border-slate-200 bg-white text-slate-800'}/>
        </section>

        <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
          <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[0.18em] text-red-500">Needs attention</div><h2 className="mt-1 text-xl font-black">Exceptions, not dashboard noise</h2><p className="mt-1 text-xs text-slate-500">Each item opens the same secured source record and its Module 11 next action.</p></div><button onClick={()=>nav('/admin/today')} className="shrink-0 rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-[#000080]">Open Today</button></div>
            <div className="mt-5 space-y-3">{topExceptions.length===0?<div className="rounded-2xl border border-dashed border-emerald-200 bg-emerald-50 p-7 text-center"><CheckCircle2 className="mx-auto h-6 w-6 text-emerald-600"/><div className="mt-2 text-sm font-black text-emerald-900">No detected business exceptions.</div><div className="mt-1 text-xs text-emerald-700">The configured risk rules are currently clear.</div></div>:topExceptions.map(ex=><ExceptionRow key={ex.exceptionKey} ex={ex} onOpen={()=>nav(ex.actionUrl)}/>)}</div>
          </div>

          <div className="rounded-3xl border border-blue-200 bg-[linear-gradient(145deg,#000080,#10106f)] p-6 text-white shadow-xl shadow-blue-950/10">
            <div className="text-[10px] font-black uppercase tracking-[0.18em] text-blue-200">Management brief</div><h2 className="mt-2 text-xl font-black">{brief?.headline||'Business pulse'}</h2><div className="mt-5 space-y-2">{brief?.pulse.map(row=><div key={row.label} className="flex items-center justify-between gap-4 rounded-2xl bg-white/10 px-4 py-3"><span className="text-xs text-blue-100">{row.label}</span><span className="text-sm font-black">{row.value}</span></div>)}</div>{(brief?.decisions.length||0)>0&&<div className="mt-5"><div className="text-[10px] font-black uppercase tracking-wider text-blue-200">Decisions / intervention</div><div className="mt-2 space-y-2">{brief?.decisions.slice(0,3).map((x,i)=><button key={`${x.title}-${i}`} onClick={()=>nav(x.actionUrl)} className="flex w-full items-center justify-between gap-3 rounded-xl bg-white px-3 py-2.5 text-left text-xs font-black text-[#000080]"><span className="line-clamp-1">{x.title}</span><ArrowRight className="h-3.5 w-3.5 shrink-0"/></button>)}</div></div>}
          </div>
        </section>

        <nav className="mt-7 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5">{([['overview','Overview'],['sales','Sales'],['delivery','Delivery'],['finance','Finance'],['people','People']] as [Tab,string][]).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`shrink-0 rounded-xl px-4 py-2 text-xs font-black ${tab===key?'bg-slate-900 text-white':'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</nav>

        <section className="mt-4">
          {tab==='overview'&&<Overview data={data}/>} 
          {tab==='sales'&&<Sales data={data}/>} 
          {tab==='delivery'&&<Delivery data={data}/>} 
          {tab==='finance'&&<Finance data={data}/>} 
          {tab==='people'&&<People data={data}/>} 
        </section>
      </>}
    </main>
  </div>;
}

function MetricCard({icon:Icon,label,value,note,tone='border-slate-200 bg-white text-slate-900'}:{icon:any;label:string;value:string;note:string;tone?:string}){return <div className={`rounded-3xl border p-5 shadow-sm ${tone}`}><Icon className="h-5 w-5 opacity-80"/><div className="mt-4 text-2xl font-black tracking-tight">{value}</div><div className="mt-1 text-xs font-black opacity-80">{label}</div><div className="mt-1 text-[10px] opacity-60">{note}</div></div>}
function ExceptionRow({ex,onOpen}:{ex:BusinessException;onOpen:()=>void}){return <div className="flex flex-col gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2 py-0.5 text-[9px] font-black uppercase ${severityTone[ex.severity]||severityTone.Medium}`}>{ex.severity}</span><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">{ex.area}</span></div><div className="mt-2 text-sm font-black text-slate-900">{ex.title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{ex.detail}</div></div><button onClick={onOpen} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-black text-[#000080] ring-1 ring-slate-200">{ex.actionLabel}<ArrowRight className="h-3.5 w-3.5"/></button></div>}
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="font-black">{title}</h3>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}<div className="mt-5">{children}</div></div>}
function Mini({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-xl font-black">{value}</div><div className="mt-1 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</div>{note&&<div className="mt-1 text-[10px] text-slate-400">{note}</div>}</div>}

function Overview({data}:{data:Dashboard}){return <div className="grid gap-5 lg:grid-cols-2"><Panel title="Business footprint" subtitle="Current operating records, not period-limited vanity totals."><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Mini label="Active leads" value={data.overview.activeLeads}/><Mini label="Open deals" value={data.overview.openOpportunities}/><Mini label="Projects" value={data.overview.activeProjects}/><Mini label="Clients" value={data.overview.clients}/><Mini label="Staff" value={data.overview.activeStaff}/></div></Panel><Panel title="Execution health" subtitle="What can interrupt delivery or momentum right now."><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Mini label="At-risk projects" value={data.delivery.atRiskProjects}/><Mini label="Overdue tasks" value={data.delivery.overdueTasks}/><Mini label="Stuck candidates" value={data.recruitment.stuckCandidates}/><Mini label="Team at capacity" value={data.team.atCapacity}/></div></Panel></div>}
function Sales({data}:{data:Dashboard}){return <div className="grid gap-5 xl:grid-cols-2"><Panel title={`Sales performance · ${data.periodDays} days`}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Mini label="New leads" value={data.sales.leadsCreated}/><Mini label="New opportunities" value={data.sales.opportunitiesCreated}/><Mini label="Meetings" value={data.sales.meetingsCompleted}/><Mini label="Quotes sent" value={data.sales.quotationsSent}/><Mini label="Won" value={data.sales.wonDeals}/><Mini label="Win rate" value={pct(data.sales.winRate)}/><Mini label="Lead → opportunity" value={pct(data.sales.leadToOpportunityRate)}/><Mini label="Sales cycle" value={`${data.sales.averageSalesCycleDays}d`}/></div></Panel><Panel title="Pipeline by currency" subtitle="No currency conversion or accidental mixed totals."><div className="space-y-2">{data.sales.pipelineByCurrency.length===0?<Empty/>:data.sales.pipelineByCurrency.map(r=><div key={r.currency} className="grid grid-cols-3 items-center gap-3 rounded-2xl bg-slate-50 p-4"><div className="text-sm font-black">{r.currency}</div><div><div className="text-xs font-black">{money(r.openPipeline,r.currency)}</div><div className="text-[9px] text-slate-400">Open pipeline</div></div><div><div className="text-xs font-black text-[#000080]">{money(r.weightedPipeline,r.currency)}</div><div className="text-[9px] text-slate-400">Weighted</div></div></div>)}</div></Panel><Panel title="Open pipeline stages"><KeyValue data={data.sales.stageCounts}/></Panel><Panel title="Lead-source quality" subtitle="Volume, opportunity creation and wins from leads created in this window."><div className="space-y-2">{data.sales.sourcePerformance.length===0?<Empty/>:data.sales.sourcePerformance.map(r=><div key={r.source} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div className="truncate text-xs font-black">{r.source}</div><div className="flex gap-4 text-center"><SmallStat value={r.leads} label="Leads"/><SmallStat value={r.opportunities} label="Opps"/><SmallStat value={r.won} label="Won"/></div></div>)}</div></Panel></div>}
function Delivery({data}:{data:Dashboard}){return <div className="grid gap-5 xl:grid-cols-2"><Panel title="Delivery health"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Mini label="Active projects" value={data.delivery.activeProjects}/><Mini label="Completed" value={data.delivery.completedProjects}/><Mini label="At risk" value={data.delivery.atRiskProjects}/><Mini label="Overdue tasks" value={data.delivery.overdueTasks}/><Mini label="Due next 7d" value={data.delivery.tasksDueNext7Days}/><Mini label="Need PM" value={data.delivery.unassignedProjects}/></div></Panel><Panel title="Team capacity" subtitle="A simple workload signal from open delivery tasks, overdue CRM work and upcoming meetings."><Workload rows={data.delivery.workload}/></Panel></div>}
function Finance({data}:{data:Dashboard}){return <div className="grid gap-5 xl:grid-cols-2"><Panel title="Operational finance by currency" subtitle="Verified revenue, collection exposure, commissions and active project value stay separated by currency."><div className="space-y-3">{data.finance.byCurrency.length===0?<Empty/>:data.finance.byCurrency.map(r=><div key={r.currency} className="rounded-2xl bg-slate-50 p-4"><div className="mb-3 text-sm font-black">{r.currency}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-5"><SmallStat value={money(r.verifiedRevenue,r.currency)} label="Revenue"/><SmallStat value={money(r.outstanding,r.currency)} label="Outstanding"/><SmallStat value={money(r.overdue,r.currency)} label="Overdue"/><SmallStat value={money(r.commissionsOutstanding,r.currency)} label="Commissions"/><SmallStat value={money(r.activeProjectValue,r.currency)} label="Projects"/></div></div>)}</div></Panel><Panel title="Primary-currency collection pulse"><div className="grid grid-cols-2 gap-3"><Mini label="Verified revenue" value={money(data.finance.primary.verifiedRevenue,data.primaryCurrency)}/><Mini label="Previous period" value={money(data.finance.primary.previousPeriodRevenue,data.primaryCurrency)}/><Mini label="Revenue change" value={data.finance.primary.revenueChangePercent===null?'—':`${data.finance.primary.revenueChangePercent>=0?'+':''}${data.finance.primary.revenueChangePercent}%`}/><Mini label="Outstanding" value={money(data.finance.primary.outstanding,data.primaryCurrency)}/></div></Panel></div>}
function People({data}:{data:Dashboard}){return <div className="grid gap-5 xl:grid-cols-2"><Panel title="Recruitment"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Mini label="Active candidates" value={data.recruitment.activeCandidates}/><Mini label="New" value={data.recruitment.newCandidates}/><Mini label="Activated" value={data.recruitment.activated}/><Mini label="Stuck" value={data.recruitment.stuckCandidates}/></div><div className="mt-5"><KeyValue data={data.recruitment.stageCounts}/></div></Panel><Panel title="Team operating load"><div className="grid grid-cols-3 gap-3"><Mini label="Active staff" value={data.team.activeStaff}/><Mini label="At capacity" value={data.team.atCapacity}/><Mini label="Day closes · 7d" value={data.team.dayClosesLast7Days}/></div><div className="mt-5"><Workload rows={data.team.workload}/></div></Panel></div>}
function Workload({rows}:{rows:Dashboard['team']['workload']}){return <div className="space-y-2">{rows.length===0?<Empty/>:rows.slice(0,12).map(r=><div key={r.userId} className="flex flex-col gap-2 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{r.name}</div><div className="mt-0.5 text-[9px] text-slate-400">{roleLabel(r.role)}{r.department?` · ${r.department}`:''}</div></div><div className="flex gap-3"><SmallStat value={r.openTasks} label="Tasks"/><SmallStat value={r.overdueActivities} label="Overdue"/><SmallStat value={r.meetingsNext7Days} label="Meetings"/></div>{r.atCapacity&&<span className="rounded-full border border-amber-200 bg-amber-50 px-2 py-1 text-[9px] font-black text-amber-700">At capacity</span>}</div>)}</div>}
function KeyValue({data}:{data:Record<string,number>}){const entries=Object.entries(data||{});return <div className="space-y-2">{entries.length===0?<Empty/>:entries.map(([k,v])=><div key={k} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-4 py-3"><span className="text-xs font-bold text-slate-600">{k}</span><span className="text-sm font-black">{v}</span></div>)}</div>}
function SmallStat({value,label}:{value:string|number;label:string}){return <div className="min-w-[48px] text-center"><div className="text-xs font-black">{value}</div><div className="mt-0.5 text-[8px] font-bold uppercase tracking-wide text-slate-400">{label}</div></div>}
function Empty(){return <div className="rounded-2xl border border-dashed border-slate-200 p-6 text-center text-xs font-semibold text-slate-400">No data yet.</div>}
