import React,{useEffect,useState}from'react';
import{ArrowLeft,Loader2,RefreshCw,Save,ShieldCheck}from'lucide-react';
import{Navigate,useNavigate}from'react-router-dom';
import{useAuth}from'../../lib/AuthContext';
import{supabase}from'../../lib/supabase';
import{trainingService,TrainingModule}from'../../lib/trainingService';

type MissionOption={value:string;label:string};
type Mission={id:string;title:string;objective:string;instructions:string;scenario_data:{facts?:string;options?:MissionOption[];[key:string]:any};sort_order:number;active:boolean};
type Question={id:string;prompt:string;options:string[];correct_index:number;explanation:string;sort_order:number;critical:boolean;active:boolean};
type Ack={id:string;statement:string;sort_order:number;required:boolean;active:boolean};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
export default function ConfidentialityTrainingAdmin(){
 const{isAdmin,loading:authLoading}=useAuth();const navigate=useNavigate();const[module,setModule]=useState<TrainingModule|null>(null);const[missions,setMissions]=useState<Mission[]>([]);const[questions,setQuestions]=useState<Question[]>([]);const[acks,setAcks]=useState<Ack[]>([]);const[tab,setTab]=useState<'missions'|'assessment'|'acks'>('missions');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const mr=await trainingService.getModules(true);if(mr.error)throw mr.error;const m=(mr.data||[]).find(x=>x.slug==='confidentiality-data-protection');if(!m)throw new Error('Module 19 not found.');setModule(m);const[mi,qu,ak]=await Promise.all([supabase.from('confidentiality_training_missions').select('*').eq('module_id',m.id).order('sort_order'),supabase.from('training_assessment_questions').select('*').eq('module_id',m.id).order('sort_order'),supabase.from('training_acknowledgements').select('*').eq('module_id',m.id).order('sort_order')]);if(mi.error)throw mi.error;if(qu.error)throw qu.error;if(ak.error)throw ak.error;setMissions((mi.data||[])as Mission[]);setQuestions((qu.data||[])as Question[]);setAcks((ak.data||[])as Ack[]);}catch(e:any){setError(e?.message||'Controls could not be loaded.');}finally{setLoading(false);}};
 useEffect(()=>{if(isAdmin)void load();},[isAdmin]);
 const saveScore=async()=>{if(!module)return;setBusy(true);const n=Math.max(1,Math.min(100,Math.round(Number(module.passing_score||90))));const r=await trainingService.updateModule(module.id,{passing_score:n});setBusy(false);if(r.error)setError(r.error.message);else{setModule(r.data||{...module,passing_score:n});setMsg('Passing score saved.');}};
 const saveMission=async(m:Mission)=>{setBusy(true);setError('');const{error:e}=await supabase.from('confidentiality_training_missions').update({title:m.title.trim(),objective:m.objective.trim(),instructions:m.instructions.trim(),scenario_data:m.scenario_data,active:m.active,updated_at:new Date().toISOString()}).eq('id',m.id);setBusy(false);if(e)setError(e.message);else setMsg(`Mission ${m.sort_order} saved. Correct-decision keys remain server-controlled.`);};
 const saveQuestion=async(q:Question)=>{setBusy(true);setError('');const{error:e}=await supabase.from('training_assessment_questions').update({prompt:q.prompt.trim(),options:q.options,correct_index:q.correct_index,explanation:q.explanation.trim(),critical:q.critical,active:q.active,updated_at:new Date().toISOString()}).eq('id',q.id);setBusy(false);if(e)setError(e.message);else setMsg(`Scenario ${q.sort_order} saved.`);};
 const saveAck=async(a:Ack)=>{setBusy(true);setError('');const{error:e}=await supabase.from('training_acknowledgements').update({statement:a.statement.trim(),required:a.required,active:a.active,updated_at:new Date().toISOString()}).eq('id',a.id);setBusy(false);if(e)setError(e.message);else setMsg(`Acknowledgement ${a.sort_order} saved.`);};
 if(authLoading)return null;if(!isAdmin)return <Navigate to="/admin/workspace" replace/>;if(loading)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white px-6 py-5"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex gap-3"><button onClick={()=>navigate('/admin/app/recruitment?tab=onboarding')} className="rounded-xl border p-2"><ArrowLeft className="h-4 w-4"/></button><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Sales Academy · Module 19</div><h1 className="text-xl font-black">Confidentiality Training Controls</h1><p className="mt-1 text-xs text-slate-500">Maintain learner-facing wording and certification. Mission answer identifiers and secure validation remain server-controlled.</p></div></div><button onClick={()=>void load()} className="rounded-xl border p-2"><RefreshCw className="h-4 w-4"/></button></div></header><main className="mx-auto max-w-6xl space-y-6 p-6">{error&&<Notice danger>{error}</Notice>}{msg&&<Notice>{msg}</Notice>}<section className="rounded-3xl border bg-white p-5"><div className="grid gap-5 lg:grid-cols-[1fr_260px]"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#000080]"/><b>Module 19 · {module?.title}</b></div><p className="mt-2 text-xs text-slate-500">Lesson bodies remain editable in Curriculum & Module Editor.</p></div><div><label className="text-[10px] font-black uppercase text-slate-500">Passing score</label><div className="mt-2 flex gap-2"><input type="number" min={1} max={100} value={module?.passing_score??90} onChange={e=>setModule(m=>m?{...m,passing_score:Number(e.target.value)}:m)} className={input}/><button disabled={busy} onClick={()=>void saveScore()} className="rounded-xl bg-[#000080] p-3 text-white"><Save className="h-4 w-4"/></button></div></div></div></section><div className="grid grid-cols-3 gap-2 rounded-2xl border bg-white p-1">{(['missions','assessment','acks']as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-3 text-xs font-black ${tab===t?'bg-[#000080] text-white':'text-slate-600'}`}>{t==='missions'?'10 Missions':t==='assessment'?'20 Scenarios':'7 Acknowledgements'}</button>)}</div>
 {tab==='missions'&&<div className="space-y-4">{missions.map((m,i)=><section key={m.id} className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div className="text-[10px] font-black uppercase text-[#000080]">Mission {m.sort_order}</div><label className="text-xs"><input type="checkbox" checked={m.active} onChange={e=>setMissions(x=>x.map((v,j)=>j===i?{...v,active:e.target.checked}:v))}/> Active</label></div><input value={m.title} onChange={e=>setMissions(x=>x.map((v,j)=>j===i?{...v,title:e.target.value}:v))} className={`${input} mt-2 font-bold`}/><textarea value={m.objective} onChange={e=>setMissions(x=>x.map((v,j)=>j===i?{...v,objective:e.target.value}:v))} className={`${input} mt-2`}/><textarea value={m.instructions} onChange={e=>setMissions(x=>x.map((v,j)=>j===i?{...v,instructions:e.target.value}:v))} className={`${input} mt-2`}/><label className="mt-3 block text-[10px] font-black uppercase text-slate-500">Scenario facts</label><textarea value={m.scenario_data?.facts||''} onChange={e=>setMissions(x=>x.map((v,j)=>j===i?{...v,scenario_data:{...v.scenario_data,facts:e.target.value}}:v))} className={`${input} mt-1`}/><div className="mt-3 text-[10px] font-black uppercase text-slate-500">Learner answer labels <span className="font-medium normal-case">(server answer IDs are locked)</span></div>{(m.scenario_data?.options||[]).map((o,oi)=><div key={o.value} className="mt-2 grid gap-2 sm:grid-cols-[170px_1fr]"><div className="rounded-xl border bg-slate-50 px-3 py-2.5 text-[11px] font-mono text-slate-500">{o.value}</div><input value={o.label} onChange={e=>setMissions(x=>x.map((v,j)=>j===i?{...v,scenario_data:{...v.scenario_data,options:(v.scenario_data.options||[]).map((z,k)=>k===oi?{...z,label:e.target.value}:z)}}:v))} className={input}/></div>)}<div className="mt-3 flex justify-end"><button onClick={()=>void saveMission(missions[i])} className="rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white">Save Mission</button></div></section>)}</div>}
 {tab==='assessment'&&<div className="space-y-4">{questions.map((q,i)=><section key={q.id} className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div className="text-[10px] font-black uppercase text-[#000080]">Scenario {q.sort_order}</div><div className="flex gap-4"><label className="text-xs"><input type="checkbox" checked={q.critical} onChange={e=>setQuestions(x=>x.map((v,j)=>j===i?{...v,critical:e.target.checked}:v))}/> Critical</label><label className="text-xs"><input type="checkbox" checked={q.active} onChange={e=>setQuestions(x=>x.map((v,j)=>j===i?{...v,active:e.target.checked}:v))}/> Active</label></div></div><textarea value={q.prompt} onChange={e=>setQuestions(x=>x.map((v,j)=>j===i?{...v,prompt:e.target.value}:v))} className={`${input} mt-2`}/>{q.options.map((o,oi)=><div key={oi} className="mt-2 flex gap-2"><input type="radio" checked={q.correct_index===oi} onChange={()=>setQuestions(x=>x.map((v,j)=>j===i?{...v,correct_index:oi}:v))}/><input value={o} onChange={e=>setQuestions(x=>x.map((v,j)=>j===i?{...v,options:v.options.map((z,k)=>k===oi?e.target.value:z)}:v))} className={input}/></div>)}<textarea value={q.explanation} onChange={e=>setQuestions(x=>x.map((v,j)=>j===i?{...v,explanation:e.target.value}:v))} className={`${input} mt-2`} placeholder="Post-attempt coaching explanation"/><div className="mt-3 flex justify-end"><button onClick={()=>void saveQuestion(questions[i])} className="rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white">Save Scenario</button></div></section>)}</div>}
 {tab==='acks'&&<div className="space-y-4">{acks.map((a,i)=><section key={a.id} className="rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div className="text-[10px] font-black uppercase text-[#000080]">Acknowledgement {a.sort_order}</div><label className="text-xs"><input type="checkbox" checked={a.active} onChange={e=>setAcks(x=>x.map((v,j)=>j===i?{...v,active:e.target.checked}:v))}/> Active</label></div><textarea value={a.statement} onChange={e=>setAcks(x=>x.map((v,j)=>j===i?{...v,statement:e.target.value}:v))} className={`${input} mt-2`}/><div className="mt-3 flex justify-end"><button onClick={()=>void saveAck(acks[i])} className="rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white">Save Acknowledgement</button></div></section>)}</div>}</main></div>;
}
function Notice({children,danger=false}:any){return <div className={`rounded-2xl border p-4 text-sm ${danger?'border-rose-200 bg-rose-50 text-rose-900':'border-emerald-200 bg-emerald-50 text-emerald-900'}`}>{children}</div>}
