import React, { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, CircleDollarSign, Loader2, Plus, Save, SlidersHorizontal } from 'lucide-react';
import { contentDeliveryService, WorkerCompensationConfig, WorkerCompensationModel, WorkerRateCard } from '../../lib/contentDeliveryService';

const MODELS: WorkerCompensationModel[] = ['Fixed Project Fee','Fixed Deliverable Fee','Per Unit','Custom Project Amount','Package-Based Rate'];
const GATES = ['Independent Editorial Approval','Internal Editorial Approval','SEO / Conversion Approval','Client Approval','Ready for Implementation','Final Content Approval'];
const emptyCard: WorkerRateCard = { contentType:'',compensationModel:'Fixed Deliverable Fee',defaultFee:0,perUnitRate:null,currency:'USD',includedRevisions:2,qualityThreshold:90,defaultTimelineDays:2,approvalGate:'Independent Editorial Approval',active:true };
const num = (value: any) => Number(value || 0);

export default function ContentCompensationSettings() {
  const [config,setConfig]=useState<WorkerCompensationConfig|null>(null);
  const [cards,setCards]=useState<WorkerRateCard[]>([]);
  const [products,setProducts]=useState<any[]>([]);
  const [tiers,setTiers]=useState<any[]>([]);
  const [tier,setTier]=useState<any>({name:'',minimumCompletedProjects:0,minimumQuality:0,minimumOnTimePercent:0,minimumFirstPassPercent:0,maximumRevisionAverage:null,eligibleContentTypes:[],rateModifierPercent:0,manualApprovalRequired:true,sortOrder:0,active:true});
  const [draft,setDraft]=useState<WorkerRateCard>(emptyCard);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(''); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const data=await contentDeliveryService.getCompensationAdminSnapshot();setConfig(data.config);setCards(data.rateCards||[]);setProducts(data.salesProducts||[]);setTiers(data.tiers||[]);setDraft(current=>({...current,currency:data.config.defaultCurrency,includedRevisions:data.config.includedRevisions,qualityThreshold:data.config.qualityThreshold,approvalGate:data.config.earningTrigger}));}catch(e:any){setError(e?.message||'Unable to load compensation settings.');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const saveConfig=async()=>{if(!config)return;setSaving('config');setError('');setSuccess('');try{setConfig(await contentDeliveryService.saveCompensationConfig(config));setSuccess('Project compensation policy saved. Existing accepted assignments remain unchanged.');}catch(e:any){setError(e?.message||'Unable to save compensation policy.');}finally{setSaving('')}};
  const saveCard=async()=>{if(!draft.contentType?.trim()&&!draft.content_type?.trim()){setError('Content type is required.');return}setSaving('card');setError('');setSuccess('');try{await contentDeliveryService.saveRateCard(draft);setSuccess('Rate card saved. It will only affect future assignments.');setDraft({...emptyCard,currency:config?.defaultCurrency||'USD',includedRevisions:config?.includedRevisions||0,qualityThreshold:config?.qualityThreshold||90,approvalGate:config?.earningTrigger||GATES[0]});await load();}catch(e:any){setError(e?.message||'Unable to save rate card.');}finally{setSaving('')}};
  const saveTier=async()=>{if(!tier.name?.trim()){setError('Tier name is required.');return}setSaving('tier');setError('');try{await contentDeliveryService.savePerformanceTier(tier);setSuccess('Performance tier saved. Promotions remain subject to authorized review.');setTier({name:'',minimumCompletedProjects:0,minimumQuality:0,minimumOnTimePercent:0,minimumFirstPassPercent:0,maximumRevisionAverage:null,eligibleContentTypes:[],rateModifierPercent:0,manualApprovalRequired:true,sortOrder:0,active:true});await load();}catch(e:any){setError(e?.message||'Unable to save performance tier.');}finally{setSaving('')}};
  if(loading)return <div className="flex items-center justify-center rounded-3xl border border-slate-200 bg-white p-10"><Loader2 className="h-6 w-6 animate-spin text-[#000080]"/></div>;
  if(!config)return null;
  const update=(key:keyof WorkerCompensationConfig,value:any)=>setConfig({...config,[key]:value});
  return <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.16em] text-[#000080]"><CircleDollarSign className="h-4 w-4"/>Dynamic project compensation</div><h2 className="mt-1 text-lg font-black">Content Compensation Settings</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-500">Rates and payout rules are configurable. Accepted project assignments keep an immutable commercial snapshot.</p></div><button onClick={()=>void saveConfig()} disabled={saving!==''} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{saving==='config'?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Policy</button></div>
    {error&&<div className="mt-4 flex gap-2 rounded-2xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700"><AlertCircle className="h-4 w-4 shrink-0"/>{error}</div>}{success&&<div className="mt-4 flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4 shrink-0"/>{success}</div>}
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Select label="Default model" value={config.defaultModel} onChange={v=>update('defaultModel',v)} options={config.enabledModels}/><Input label="Default currency" value={config.defaultCurrency} onChange={v=>update('defaultCurrency',v.toUpperCase().slice(0,3))}/><Input type="number" label="Included revisions" value={config.includedRevisions} onChange={v=>update('includedRevisions',num(v))}/><Input type="number" label="Quality threshold" value={config.qualityThreshold} onChange={v=>update('qualityThreshold',num(v))}/><Select label="Earning trigger" value={config.earningTrigger} onChange={v=>update('earningTrigger',v)} options={GATES}/><Select label="Payout frequency" value={config.payoutFrequency} onChange={v=>update('payoutFrequency',v)} options={['Weekly','Twice Monthly','Monthly','Manual Batch','Custom schedule']}/><Input type="number" label="Payout hold days" value={config.payoutHoldDays} onChange={v=>update('payoutHoldDays',num(v))}/><Input type="number" label="Minimum payout" value={config.minimumPayout} onChange={v=>update('minimumPayout',num(v))}/><Input type="number" label="Manager override %" value={config.managerOverridePercent} onChange={v=>update('managerOverridePercent',num(v))}/><Input type="number" label="High-value approval" value={config.customApprovalThreshold} onChange={v=>update('customApprovalThreshold',num(v))}/><Input type="number" label="Due-soon days" value={config.deadlineRules?.dueSoonDays||0} onChange={v=>update('deadlineRules',{...config.deadlineRules,dueSoonDays:num(v)})}/><Input type="number" label="Late escalation hours" value={config.deadlineRules?.lateEscalationHours||0} onChange={v=>update('deadlineRules',{...config.deadlineRules,lateEscalationHours:num(v)})}/></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{MODELS.map(model=><label key={model} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-[10px] font-black"><span>{model}</span><input type="checkbox" checked={config.enabledModels.includes(model)} onChange={e=>{const next=e.target.checked?[...config.enabledModels,model]:config.enabledModels.filter(m=>m!==model);update('enabledModels',next)}}/></label>)}<Toggle label="Writer acceptance required" checked={config.acceptanceRequired} onChange={v=>update('acceptanceRequired',v)}/><Toggle label="Scope-change acceptance" checked={config.scopeChangeAcceptanceRequired} onChange={v=>update('scopeChangeAcceptanceRequired',v)}/><Toggle label="PM overrides allowed" checked={config.pmOverrideAllowed} onChange={v=>update('pmOverrideAllowed',v)}/><Toggle label="Exclude verified blocked time" checked={config.blockedTimeExcluded} onChange={v=>update('blockedTimeExcluded',v)}/></div>

    <div className="mt-8 border-t border-slate-100 pt-6"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-[#000080]"/><h3 className="text-sm font-black">Content Creator Rate Cards</h3></div><p className="mt-1 text-xs text-slate-500">Map a configurable content type to canonical Sales Catalog products where appropriate. Customer prices are never used as writer percentages.</p>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input label="Content type" value={draft.contentType||draft.content_type||''} onChange={v=>setDraft({...draft,contentType:v})}/><Select label="Compensation model" value={draft.compensationModel||draft.compensation_model||MODELS[1]} onChange={v=>setDraft({...draft,compensationModel:v as WorkerCompensationModel})} options={config.enabledModels}/><Input type="number" label="Default fee" value={draft.defaultFee??draft.default_fee??0} onChange={v=>setDraft({...draft,defaultFee:num(v)})}/><Input type="number" label="Per-unit rate" value={draft.perUnitRate??draft.per_unit_rate??''} onChange={v=>setDraft({...draft,perUnitRate:v===''?null:num(v)})}/><Input label="Currency" value={draft.currency} onChange={v=>setDraft({...draft,currency:v.toUpperCase().slice(0,3)})}/><Input type="number" label="Included revisions" value={draft.includedRevisions??draft.included_revisions??0} onChange={v=>setDraft({...draft,includedRevisions:num(v)})}/><Input type="number" label="Quality threshold" value={draft.qualityThreshold??draft.quality_threshold??0} onChange={v=>setDraft({...draft,qualityThreshold:num(v)})}/><Input type="number" label="Timeline (business days)" value={draft.defaultTimelineDays??draft.default_timeline_days??''} onChange={v=>setDraft({...draft,defaultTimelineDays:v===''?null:num(v)})}/><Select label="Approval gate" value={draft.approvalGate||draft.approval_gate||GATES[0]} onChange={v=>setDraft({...draft,approvalGate:v})} options={GATES}/><label className="text-[10px] font-black uppercase text-slate-500 sm:col-span-2"><span className="mb-1 block">Sales Catalog mapping (optional)</span><select value={draft.salesProductId??draft.sales_product_id??''} onChange={e=>setDraft({...draft,salesProductId:e.target.value||null})} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-bold normal-case"><option value="">No package mapping</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><Toggle label="Rate active" checked={draft.active} onChange={v=>setDraft({...draft,active:v})}/><button onClick={()=>void saveCard()} disabled={saving!==''} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-xs font-black text-white disabled:opacity-50"><Plus className="h-4 w-4"/>{draft.id?'Update Rate':'Add Rate'}</button></div>
      <div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr className="border-b border-slate-200 text-[9px] font-black uppercase tracking-wider text-slate-400"><th className="px-3 py-2">Content Type</th><th className="px-3 py-2">Model</th><th className="px-3 py-2">Rate</th><th className="px-3 py-2">Quality</th><th className="px-3 py-2">Revisions</th><th className="px-3 py-2">Status</th></tr></thead><tbody>{cards.length===0?<tr><td colSpan={6} className="px-3 py-8 text-center text-slate-400">No rates configured. Add the first real rate—no sample prices are created.</td></tr>:cards.map(card=><tr key={card.id} onClick={()=>setDraft(card)} className="cursor-pointer border-b border-slate-100 hover:bg-slate-50"><td className="px-3 py-3 font-black">{card.content_type}</td><td className="px-3 py-3">{card.compensation_model}</td><td className="px-3 py-3 font-black">{card.currency} {Number(card.default_fee||0).toFixed(2)}{card.per_unit_rate!=null?` · ${Number(card.per_unit_rate).toFixed(2)}/unit`:''}</td><td className="px-3 py-3">{card.quality_threshold}+</td><td className="px-3 py-3">{card.included_revisions}</td><td className="px-3 py-3">{card.active?'Active':'Inactive'}</td></tr>)}</tbody></table></div>
    </div>
    <div className="mt-8 border-t border-slate-100 pt-6"><h3 className="text-sm font-black">Performance Tiers</h3><p className="mt-1 text-xs text-slate-500">Configure opportunity eligibility signals without automatic deductions or silent contract changes.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input label="Tier name" value={tier.name} onChange={(v:string)=>setTier({...tier,name:v})}/><Input type="number" label="Completed projects" value={tier.minimumCompletedProjects} onChange={(v:string)=>setTier({...tier,minimumCompletedProjects:num(v)})}/><Input type="number" label="Minimum quality" value={tier.minimumQuality} onChange={(v:string)=>setTier({...tier,minimumQuality:num(v)})}/><Input type="number" label="Minimum on-time %" value={tier.minimumOnTimePercent} onChange={(v:string)=>setTier({...tier,minimumOnTimePercent:num(v)})}/><Input type="number" label="Minimum first-pass %" value={tier.minimumFirstPassPercent} onChange={(v:string)=>setTier({...tier,minimumFirstPassPercent:num(v)})}/><Input type="number" label="Maximum avg. revisions" value={tier.maximumRevisionAverage??''} onChange={(v:string)=>setTier({...tier,maximumRevisionAverage:v===''?null:num(v)})}/><Input type="number" label="Optional rate modifier %" value={tier.rateModifierPercent} onChange={(v:string)=>setTier({...tier,rateModifierPercent:num(v)})}/><Toggle label="Manual promotion approval" checked={tier.manualApprovalRequired} onChange={(v:boolean)=>setTier({...tier,manualApprovalRequired:v})}/><button onClick={()=>void saveTier()} disabled={saving!==''} className="rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{saving==='tier'?'Saving…':tier.id?'Update Tier':'Add Tier'}</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{tiers.length===0?<div className="text-xs text-slate-400">No tiers configured.</div>:tiers.map((item:any)=><button key={item.id} onClick={()=>setTier({id:item.id,name:item.name,minimumCompletedProjects:item.minimum_completed_projects,minimumQuality:item.minimum_quality,minimumOnTimePercent:item.minimum_on_time_percent,minimumFirstPassPercent:item.minimum_first_pass_percent,maximumRevisionAverage:item.maximum_revision_average,eligibleContentTypes:item.eligible_content_types||[],rateModifierPercent:item.rate_modifier_percent,manualApprovalRequired:item.manual_approval_required,sortOrder:item.sort_order,active:item.active})} className="rounded-xl border border-slate-200 p-3 text-left"><div className="text-xs font-black">{item.name}</div><div className="mt-1 text-[9px] text-slate-500">Quality {item.minimum_quality}+ · On-time {item.minimum_on_time_percent}% · First-pass {item.minimum_first_pass_percent}%</div></button>)}</div></div>
  </section>;
}

function Input({label,value,onChange,type='text'}:any){return <label className="text-[10px] font-black uppercase text-slate-500"><span className="mb-1 block">{label}</span><input type={type} min={type==='number'?0:undefined} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-bold normal-case outline-none focus:border-[#000080]"/></label>}
function Select({label,value,onChange,options}:any){return <label className="text-[10px] font-black uppercase text-slate-500"><span className="mb-1 block">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-bold normal-case">{options.map((o:string)=><option key={o}>{o}</option>)}</select></label>}
function Toggle({label,checked,onChange}:any){return <label className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-[10px] font-black"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
