import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,BookOpen,ChevronDown,ChevronUp,Database,Loader2,RefreshCw,Save,ShieldCheck}from'lucide-react';
import{Navigate,useNavigate}from'react-router-dom';
import{useAuth}from'../../lib/AuthContext';
import{supabase}from'../../lib/supabase';
import{trainingService,TrainingModule}from'../../lib/trainingService';

type Mission={id:string;module_id:string;mission_key:string;title:string;objective:string;instructions:string;scenario_data:Record<string,any>;sort_order:number;active:boolean};
type Question={id:string;module_id:string;prompt:string;options:string[];correct_index:number;explanation:string;sort_order:number;active:boolean;assessment_section?:string;case_key?:string;critical?:boolean};
type Ack={id:string;module_id:string;statement:string;sort_order:number;required:boolean;active:boolean};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const messageFrom=(e:any,fallback:string)=>e?.message||fallback;

export default function CrmTrainingAdmin(){
 const{isAdmin,loading:authLoading}=useAuth();const navigate=useNavigate();
 const[module,setModule]=useState<TrainingModule|null>(null);const[missions,setMissions]=useState<Mission[]>([]);const[questions,setQuestions]=useState<Question[]>([]);const[acks,setAcks]=useState<Ack[]>([]);const[expandedMission,setExpandedMission]=useState<string|null>(null);const[expandedQuestion,setExpandedQuestion]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const mods=await trainingService.getModules(true);if(mods.error)throw mods.error;const target=(mods.data||[]).find(m=>m.slug==='crm-training');if(!target)throw new Error('CRM Training module not found.');const[m,q,a]=await Promise.all([supabase.from('crm_training_missions').select('*').eq('module_id',target.id).order('sort_order'),supabase.from('training_assessment_questions').select('*').eq('module_id',target.id).order('sort_order'),supabase.from('training_acknowledgements').select('*').eq('module_id',target.id).order('sort_order')]);if(m.error)throw m.error;if(q.error)throw q.error;if(a.error)throw a.error;setModule(target);setMissions((m.data||[])as Mission[]);setQuestions((q.data||[])as Question[]);setAcks((a.data||[])as Ack[]);}catch(e:any){setError(messageFrom(e,'CRM Training controls could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{if(isAdmin)void load();},[isAdmin]);
 const criticalCount=useMemo(()=>questions.filter(q=>q.active&&q.critical).length,[questions]);
 const saveScore=async()=>{if(!module)return;const score=Math.max(1,Math.min(100,Math.round(Number(module.passing_score||85))));setBusy(true);setError('');const{data,error:e}=await trainingService.updateModule(module.id,{passing_score:score});if(e)setError(messageFrom(e,'Passing score could not be saved.'));else{setModule(data||{...module,passing_score:score});setMessage('Module 17 passing score saved.');}setBusy(false);};
 const patchMission=(id:string,patch:Partial<Mission>)=>setMissions(v=>v.map(m=>m.id===id?{...m,...patch}:m));
 const patchScenario=(m:Mission,key:string,raw:string)=>{const current=m.scenario_data[key];const next=typeof current==='number'?(raw.trim()===''?0:Number(raw)):raw;patchMission(m.id,{scenario_data:{...m.scenario_data,[key]:Number.isNaN(next as number)?current:next}});};
 const saveMission=async(m:Mission)=>{if(!m.title.trim()||!m.objective.trim()||!m.instructions.trim()){setError('Mission title, objective and instructions are required.');return;}setBusy(true);setError('');const{error:e}=await supabase.from('crm_training_missions').update({title:m.title.trim(),objective:m.objective.trim(),instructions:m.instructions.trim(),scenario_data:m.scenario_data,active:m.active,updated_at:new Date().toISOString()}).eq('id',m.id);if(e)setError(messageFrom(e,'Mission could not be saved.'));else setMessage(`Mission ${m.sort_order} saved.`);setBusy(false);};
 const patchQuestion=(id:string,patch:Partial<Question>)=>setQuestions(v=>v.map(q=>q.id===id?{...q,...patch}:q));
 const saveQuestion=async(q:Question)=>{const options=q.options.map(v=>v.trim());if(!q.prompt.trim()||options.length<2||options.some(v=>!v)){setError('Question prompt and every answer option are required.');return;}setBusy(true);setError('');const{error:e}=await supabase.from('training_assessment_questions').update({prompt:q.prompt.trim(),options,correct_index:q.correct_index,explanation:q.explanation.trim(),active:q.active,case_key:(q.case_key||'').trim(),critical:!!q.critical,updated_at:new Date().toISOString()}).eq('id',q.id);if(e)setError(messageFrom(e,'Scenario could not be saved.'));else setMessage(`Certification scenario ${q.sort_order} saved.`);setBusy(false);};
 const saveAck=async(a:Ack)=>{if(!a.statement.trim()){setError('Acknowledgement statement cannot be empty.');return;}setBusy(true);setError('');const{error:e}=await supabase.from('training_acknowledgements').update({statement:a.statement.trim(),required:a.required,active:a.active,updated_at:new Date().toISOString()}).eq('id',a.id);if(e)setError(messageFrom(e,'Acknowledgement could not be saved.'));else setMessage(`Acknowledgement ${a.sort_order} saved.`);setBusy(false);};
 if(authLoading)return null;if(!isAdmin)return <Navigate to="/admin/workspace" replace/>;if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-4 py-5 sm:px-8"><div className="mx-auto flex max-w-6xl items-start justify-between gap-4"><div className="flex gap-3"><button onClick={()=>navigate('/admin/app/recruitment?tab=onboarding')} className="mt-0.5 rounded-xl border border-slate-200 p-2 text-slate-600"><ArrowLeft className="h-4 w-4"/></button><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#000080]">Sales Academy · Module 17 Controls</div><h1 className="text-xl font-black">CRM Training Controls</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Maintain the CRM training missions, certification scenarios, acknowledgements and pass standard without editing code. Security-critical mission validation remains protected server logic.</p></div></div><button disabled={busy} onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2.5 text-slate-600"><RefreshCw className="h-4 w-4"/></button></div></header><main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8">{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}{module&&<section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-5 lg:grid-cols-[1fr_280px] lg:items-end"><div><div className="flex items-center gap-2 text-[#000080]"><ShieldCheck className="h-5 w-5"/><span className="text-sm font-black">Module 17 · {module.title}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{module.description}</p><button onClick={()=>navigate('/admin/app/recruitment?tab=onboarding')} className="mt-3 text-xs font-bold text-[#000080] hover:underline">Edit the 30 lesson bodies in Curriculum & Module Editor →</button></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">Passing score</div><div className="mt-2 flex gap-2"><input type="number" min={1} max={100} value={module.passing_score??85} onChange={e=>setModule({...module,passing_score:Number(e.target.value)})} className="w-24 rounded-xl border border-slate-200 px-3 py-2 font-black"/><span className="self-center font-black">%</span><button disabled={busy} onClick={()=>void saveScore()} className="ml-auto rounded-xl bg-[#000080] p-2.5 text-white"><Save className="h-4 w-4"/></button></div><div className="mt-2 text-[10px] font-bold text-slate-500">{missions.filter(m=>m.active).length} active missions · {questions.filter(q=>q.active).length} scenarios · {criticalCount} critical</div></div></div></section>}
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><div className="flex items-center gap-2"><Database className="h-5 w-5 text-[#000080]"/><h2 className="font-black">Synthetic CRM Mission Content</h2></div><p className="mt-1 text-xs text-slate-500">Mission keys/order are protected curriculum semantics. Admin may update scenario facts, instructions and availability; learner practice always remains sandbox-only.</p></div><div className="space-y-3">{missions.map(m=><div key={m.id} className="rounded-2xl border border-slate-200"><button onClick={()=>setExpandedMission(expandedMission===m.id?null:m.id)} className="flex w-full items-center justify-between gap-3 p-4 text-left"><div><div className="text-[10px] font-black uppercase text-slate-400">Mission {m.sort_order} · {m.mission_key}{!m.active?' · Inactive':''}</div><div className="mt-1 text-sm font-bold">{m.title}</div></div>{expandedMission===m.id?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{expandedMission===m.id&&<div className="space-y-4 border-t border-slate-100 p-4">{field('Title',m.title,v=>patchMission(m.id,{title:v}))}{area('Objective',m.objective,v=>patchMission(m.id,{objective:v}))}{area('Learner instructions',m.instructions,v=>patchMission(m.id,{instructions:v}))}<div><div className="mb-2 text-[10px] font-black uppercase tracking-wider text-slate-500">Synthetic scenario facts</div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(m.scenario_data||{}).map(([key,value])=><label key={key} className="block"><span className="mb-1 block text-[10px] font-bold text-slate-500">{key}</span><input type={typeof value==='number'?'number':'text'} value={String(value??'')} onChange={e=>patchScenario(m,key,e.target.value)} className={input}/></label>)}</div></div><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={m.active} onChange={e=>patchMission(m.id,{active:e.target.checked})}/>Active mission</label><div className="flex justify-end"><button disabled={busy} onClick={()=>void saveMission(m)} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white"><Save className="h-4 w-4"/>Save Mission</button></div></div>}</div>)}</div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><BookOpen className="h-5 w-5 text-[#000080]"/><div><h2 className="font-black">CRM Judgment Scenario Bank</h2><p className="text-xs text-slate-500">Correct answers and critical-failure flags remain Admin-only.</p></div></div><div className="space-y-3">{questions.map(q=><div key={q.id} className="rounded-2xl border border-slate-200"><button onClick={()=>setExpandedQuestion(expandedQuestion===q.id?null:q.id)} className="flex w-full items-center justify-between gap-3 p-4 text-left"><div><div className="text-[10px] font-black uppercase text-slate-400">Scenario {q.sort_order}{q.critical?' · Critical':''}</div><div className="mt-1 text-sm font-bold">{q.prompt}</div></div>{expandedQuestion===q.id?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{expandedQuestion===q.id&&<div className="space-y-4 border-t border-slate-100 p-4"><textarea rows={3} value={q.prompt} onChange={e=>patchQuestion(q.id,{prompt:e.target.value})} className={input}/><div className="grid gap-2">{q.options.map((o,i)=><div key={i} className="flex items-center gap-2"><input type="radio" checked={q.correct_index===i} onChange={()=>patchQuestion(q.id,{correct_index:i})}/><input value={o} onChange={e=>patchQuestion(q.id,{options:q.options.map((x,j)=>j===i?e.target.value:x)})} className={input}/></div>)}</div><textarea rows={2} value={q.explanation||''} onChange={e=>patchQuestion(q.id,{explanation:e.target.value})} placeholder="Coaching explanation" className={input}/><div className="grid gap-3 sm:grid-cols-2"><input value={q.case_key||''} onChange={e=>patchQuestion(q.id,{case_key:e.target.value})} placeholder="Case key" className={input}/><label className="flex items-center gap-2 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700"><input type="checkbox" checked={!!q.critical} onChange={e=>patchQuestion(q.id,{critical:e.target.checked})}/>Critical failure</label></div><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={q.active} onChange={e=>patchQuestion(q.id,{active:e.target.checked})}/>Active scenario</label><div className="flex justify-end"><button disabled={busy} onClick={()=>void saveQuestion(q)} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white"><Save className="h-4 w-4"/>Save Scenario</button></div></div>}</div>)}</div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Required Acknowledgements</h2><p className="mb-4 text-xs text-slate-500">Trainees must confirm every active required standard before server scoring.</p><div className="space-y-3">{acks.map(a=><div key={a.id} className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-[1fr_auto]"><textarea rows={2} value={a.statement} onChange={e=>setAcks(v=>v.map(x=>x.id===a.id?{...x,statement:e.target.value}:x))} className={input}/><div className="flex items-center gap-3"><label className="text-xs font-bold"><input type="checkbox" checked={a.required} onChange={e=>setAcks(v=>v.map(x=>x.id===a.id?{...x,required:e.target.checked}:x))}/> Required</label><label className="text-xs font-bold"><input type="checkbox" checked={a.active} onChange={e=>setAcks(v=>v.map(x=>x.id===a.id?{...x,active:e.target.checked}:x))}/> Active</label><button disabled={busy} onClick={()=>void saveAck(a)} className="rounded-xl bg-[#000080] p-2.5 text-white"><Save className="h-4 w-4"/></button></div></div>)}</div></section></main></div>;
}
function field(label:string,value:string,onChange:(v:string)=>void){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className={input}/></label>}
function area(label:string,value:string,onChange:(v:string)=>void){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} className={input}/></label>}
function Notice({children,danger=false}:{children:React.ReactNode;danger?:boolean}){return <div className={`rounded-2xl border p-4 text-sm ${danger?'border-red-200 bg-red-50 text-red-800':'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>}
