import React,{useEffect,useState}from'react';
import{ArrowLeft,Loader2,Mail,Power,RefreshCw,Save,ShieldCheck,UserRound}from'lucide-react';
import{Navigate,useNavigate}from'react-router-dom';
import{useAuth}from'../../lib/AuthContext';
import{supabase}from'../../lib/supabase';

type CommunicationSettings={
 customerEmailEnabled:boolean;
 humanSenderEnabled:boolean;
 defaultReplyTo:string;
 brandLine:string;
 websiteUrl:string;
 quotationExpiryReminderDays:number[];
 paymentDueReminderDays:number[];
 paymentOverdueReminderDays:number[];
 projectApprovalReminderDays:number[];
};

type SellerEmailControl={
 enabled:boolean;
 activeSellerCount:number;
 activeMailboxCount:number;
 provisioningMailboxCount:number;
 suspendedMailboxCount:number;
 connectedSenderCount:number;
};

const defaults:CommunicationSettings={customerEmailEnabled:true,humanSenderEnabled:true,defaultReplyTo:'contact@profoxwebdesigner.com',brandLine:'From site to system.',websiteUrl:'https://www.profoxwebdesigner.com',quotationExpiryReminderDays:[3,1],paymentDueReminderDays:[3,1,0],paymentOverdueReminderDays:[7,3,1],projectApprovalReminderDays:[2,1]};
const sellerEmailDefaults:SellerEmailControl={enabled:false,activeSellerCount:0,activeMailboxCount:0,provisioningMailboxCount:0,suspendedMailboxCount:0,connectedSenderCount:0};
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const parseList=(value:string)=>value.split(',').map(x=>Number(x.trim())).filter(Number.isFinite);

export default function CustomerCommunicationAdmin(){
 const navigate=useNavigate();const{isAdmin,loading:authLoading}=useAuth();
 const[settings,setSettings]=useState<CommunicationSettings>(defaults);
 const[sellerEmail,setSellerEmail]=useState<SellerEmailControl>(sellerEmailDefaults);
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[togglingSellerEmail,setTogglingSellerEmail]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
 const[quoteDays,setQuoteDays]=useState('3, 1');const[paymentDue,setPaymentDue]=useState('3, 1, 0');const[paymentOverdue,setPaymentOverdue]=useState('7, 3, 1');const[projectReview,setProjectReview]=useState('2, 1');
 const hydrate=(raw:any)=>{const next={...defaults,...(raw||{})}as CommunicationSettings;setSettings(next);setQuoteDays((next.quotationExpiryReminderDays||defaults.quotationExpiryReminderDays).join(', '));setPaymentDue((next.paymentDueReminderDays||defaults.paymentDueReminderDays).join(', '));setPaymentOverdue((next.paymentOverdueReminderDays||defaults.paymentOverdueReminderDays).join(', '));setProjectReview((next.projectApprovalReminderDays||defaults.projectApprovalReminderDays).join(', '));};
 const hydrateSellerEmail=(raw:any)=>setSellerEmail({...sellerEmailDefaults,...(raw||{})});
 const load=async()=>{setLoading(true);setError('');try{const[communicationResult,sellerResult]=await Promise.all([supabase.rpc('admin_get_communication_settings'),supabase.rpc('admin_get_seller_professional_email_control')]);if(communicationResult.error)throw communicationResult.error;if(sellerResult.error)throw sellerResult.error;hydrate(communicationResult.data);hydrateSellerEmail(sellerResult.data);}catch(e:any){setError(e?.message||'Customer communication settings could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{if(isAdmin)void load()},[isAdmin]);
 if(authLoading)return <div className="min-h-screen bg-slate-50"/>;if(!isAdmin)return <Navigate to="/admin/workspace" replace/>;
 const save=async()=>{setSaving(true);setError('');setSuccess('');try{const{data,error}=await supabase.rpc('admin_set_communication_settings',{p_customer_email_enabled:settings.customerEmailEnabled,p_human_sender_enabled:settings.humanSenderEnabled,p_default_reply_to:settings.defaultReplyTo,p_quotation_expiry_days:parseList(quoteDays),p_payment_due_days:parseList(paymentDue),p_payment_overdue_days:parseList(paymentOverdue),p_project_approval_days:parseList(projectReview)});if(error)throw error;hydrate(data);setSuccess('Customer communication policy saved.');}catch(e:any){setError(e?.message||'Customer communication policy could not be saved.')}finally{setSaving(false)}};
 const toggleSellerEmail=async(next:boolean)=>{if(togglingSellerEmail||next===sellerEmail.enabled)return;setTogglingSellerEmail(true);setError('');setSuccess('');try{const{data,error}=await supabase.rpc('admin_set_seller_professional_email_control',{p_enabled:next});if(error)throw error;hydrateSellerEmail(data);setSuccess(next?'Seller professional email is ON. Eligible seller mailboxes are being activated safely.':'Seller professional email is OFF. New seller email sends are blocked immediately and seller mailboxes are being suspended safely.');}catch(e:any){setError(e?.message||'Seller professional email setting could not be changed.')}finally{setTogglingSellerEmail(false)}};
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-4 py-5 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><div className="flex items-center gap-3"><button onClick={()=>navigate('/admin/app/settings?tab=configuration')} className="rounded-xl border border-slate-200 p-2 hover:bg-slate-50"><ArrowLeft className="h-4 w-4"/></button><div><h1 className="text-xl font-black">Customer Communication Policy</h1><p className="text-xs text-slate-500">Human sender rules, customer lifecycle timing and ProFox email standards.</p></div></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2 text-slate-500 hover:bg-slate-50"><RefreshCw className="h-4 w-4"/></button></div></header><main className="mx-auto max-w-6xl p-4 sm:p-8">{error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{success&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{success}</div>}{loading?<div className="flex min-h-72 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>:<div className="space-y-6">
 <section className="rounded-3xl border border-[#000080]/15 bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><div className="flex items-center gap-2"><Power className="h-5 w-5 text-[#000080]"/><h2 className="font-black">Seller Professional Email</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wider ${sellerEmail.enabled?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}`}>{sellerEmail.enabled?'On':'Off'}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">One global control for all eligible sellers. ON allows sellers to email customers they are authorized to access. OFF blocks new seller email sends immediately and securely suspends seller mailboxes without deleting their professional addresses.</p><p className="mt-2 text-xs leading-5 text-slate-500">Managers remain separate from this seller-only switch. Chat, CRM access and public quotation privacy are not changed.</p></div><label className={`flex min-w-[240px] cursor-pointer items-center justify-between gap-5 rounded-2xl border p-4 ${sellerEmail.enabled?'border-emerald-200 bg-emerald-50':'border-slate-200 bg-slate-50'}`}><span><span className="block text-sm font-black">Allow seller email</span><span className="mt-1 block text-xs text-slate-500">Applies to all eligible sellers</span></span><span className="relative inline-flex h-7 w-12 shrink-0 items-center"><input type="checkbox"className="peer sr-only"checked={sellerEmail.enabled}disabled={togglingSellerEmail}onChange={e=>void toggleSellerEmail(e.target.checked)}/><span className="absolute inset-0 rounded-full bg-slate-300 transition peer-checked:bg-[#000080] peer-disabled:opacity-50"/><span className="absolute left-1 h-5 w-5 rounded-full bg-white shadow transition-transform peer-checked:translate-x-5"/>{togglingSellerEmail&&<Loader2 className="absolute -right-7 h-4 w-4 animate-spin text-[#000080]"/>}</span></label></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Eligible active sellers" value={sellerEmail.activeSellerCount}/><Metric label="Active mailboxes" value={sellerEmail.activeMailboxCount}/><Metric label="Activating" value={sellerEmail.provisioningMailboxCount}/><Metric label="Suspended" value={sellerEmail.suspendedMailboxCount}/><Metric label="Zoho send connected" value={sellerEmail.connectedSenderCount}/></div>{sellerEmail.enabled&&sellerEmail.connectedSenderCount<sellerEmail.activeSellerCount&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs font-semibold leading-5 text-amber-800">A seller whose mailbox is active but whose Zoho send permission is not connected will be asked to authorize their own professional mailbox before sending from ProFox. This security step is intentionally not bypassed by the global switch.</div>}</section>
 <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Mail className="h-5 w-5 text-[#000080]"/><h2 className="font-black">Customer email</h2></div><label className="mt-5 flex items-start gap-3 rounded-2xl bg-slate-50 p-4"><input type="checkbox"checked={settings.customerEmailEnabled}onChange={e=>setSettings({...settings,customerEmailEnabled:e.target.checked})}className="mt-1"/><span><span className="block text-sm font-black">Enable customer lifecycle email</span><span className="mt-1 block text-xs leading-5 text-slate-500">Quotation, payment, project and client communications follow canonical business events. Disabling this does not disable internal Module 10 notifications.</span></span></label><label className="mt-3 flex items-start gap-3 rounded-2xl bg-slate-50 p-4"><input type="checkbox"checked={settings.humanSenderEnabled}onChange={e=>setSettings({...settings,humanSenderEnabled:e.target.checked})}className="mt-1"/><span><span className="block text-sm font-black">Use human sender context</span><span className="mt-1 block text-xs leading-5 text-slate-500">When a valid active ProFox owner exists, customers see the owner display name and can reply to that verified ProFox-domain address. The verified From address never changes.</span></span></label><div className="mt-4"><Field label="Default Reply-To"><input type="email"value={settings.defaultReplyTo}onChange={e=>setSettings({...settings,defaultReplyTo:e.target.value})}className={input}/></Field><p className="mt-2 text-[11px] leading-5 text-slate-400">For deliverability and identity protection, this must use the same verified domain as the configured ProFox sender.</p></div></div>
 <div className="rounded-3xl border border-[#000080]/15 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#000080]"/><h2 className="font-black">Brand and copy guard</h2></div><div className="mt-5 space-y-3 text-sm"><Rule title="Master line" value={settings.brandLine||'From site to system.'}/><Rule title="Voice" value="Calm, intelligent, concise, certain and human."/><Rule title="Email punctuation" value="No emojis. No em dashes."/><Rule title="Trust" value="No unverified claims, fake urgency or inflated language."/><Rule title="Human fallback" value="Missing names and ownership fall back to natural ProFox wording, never blank placeholders."/></div><button type="button"onClick={()=>navigate('/admin/automation-settings')}className="mt-5 text-xs font-black text-[#000080] hover:underline">Edit message templates in Notifications & Operational Automation</button></div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-[#000080]"/><h2 className="font-black">Customer lifecycle timing</h2></div><p className="mt-1 text-xs leading-5 text-slate-500">Milestones are deduplicated. Recovery sends the latest relevant reminder rather than flooding every missed step.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Quotation validity reminders, days before expiry"><input value={quoteDays}onChange={e=>setQuoteDays(e.target.value)}className={input}placeholder="3, 1"/></Field><Field label="Payment due reminders, days before"><input value={paymentDue}onChange={e=>setPaymentDue(e.target.value)}className={input}placeholder="3, 1, 0"/></Field><Field label="Payment overdue follow-ups, days overdue"><input value={paymentOverdue}onChange={e=>setPaymentOverdue(e.target.value)}className={input}placeholder="7, 3, 1"/></Field><Field label="Client review reminders, days waiting"><input value={projectReview}onChange={e=>setProjectReview(e.target.value)}className={input}placeholder="2, 1"/></Field></div><div className="mt-5 flex justify-end"><button disabled={saving}onClick={()=>void save()}className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save customer policy</button></div></section>
 </div>}</main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-black text-slate-600">{label}<div className="mt-2">{children}</div></label>}
function Rule({title,value}:{title:string;value:string}){return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-[#FF0E0E]">{title}</div><div className="mt-1 text-sm font-semibold text-slate-700">{value}</div></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="text-2xl font-black text-slate-900">{Number(value||0)}</div><div className="mt-1 text-[11px] font-bold leading-4 text-slate-500">{label}</div></div>}
