import React,{useEffect,useMemo,useState}from'react';
import{AlertCircle,ArrowLeft,CheckCircle2,Lock,Loader2,RefreshCw,Save,Settings2,ShieldCheck}from'lucide-react';
import{Navigate,useNavigate}from'react-router-dom';
import{useAuth}from'../../lib/AuthContext';
import{designDeliveryAdminService,type DesignDeliveryAdminConfig,type DesignDeliveryAdminSettingsPayload,type DesignDeliveryDepth}from'../../lib/designDeliveryAdminService';
import type{DesignEvidenceType}from'../../lib/designDeliveryService';

const field='w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const depths:DesignDeliveryDepth[]=['Launch','Growth','Scale','Custom','Unmapped'];
const evidenceLabel=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

export default function DesignDeliverySettingsAdmin(){
 const{isAdmin,loading:authLoading}=useAuth();const navigate=useNavigate();
 const[data,setData]=useState<DesignDeliveryAdminSettingsPayload|null>(null),[form,setForm]=useState<DesignDeliveryAdminConfig|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const result=await designDeliveryAdminService.getSettings();setData(result);setForm(JSON.parse(JSON.stringify(result.config)))}catch(e:any){setError(e?.message||'Design Delivery settings could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{if(isAdmin)void load()},[isAdmin]);
 const packageRows=useMemo(()=>{if(!data||!form)return[];const seen=new Set<string>();const rows=data.catalogPackages.map(p=>{seen.add(p.code);return p});Object.keys(form.packageDepthByProductCode||{}).filter(code=>!seen.has(code)).forEach(code=>rows.push({id:code,code,name:'Configured package',productType:'package',active:false}));return rows},[data,form]);
 const save=async()=>{if(!form)return;setBusy(true);setError('');setMessage('');try{const saved=await designDeliveryAdminService.updateSettings(form);setForm(saved);setMessage('PF-SOP-08 Design Delivery controls saved and audited. New workflow decisions now read these values.')}catch(e:any){setError(e?.message||'Settings could not be saved.')}finally{setBusy(false)}};
 const setNumber=(key:'wipLimit'|'minimumDesignQaScore'|'reviewSlaHours'|'clientReviewSlaHours',value:number)=>setForm(current=>current?{...current,[key]:value}:current);
 const setPackageDepth=(code:string,value:DesignDeliveryDepth)=>setForm(current=>current?{...current,packageDepthByProductCode:{...(current.packageDepthByProductCode||{}),[code]:value}}:current);
 const toggleEvidence=(depth:DesignDeliveryDepth,type:DesignEvidenceType)=>setForm(current=>{if(!current||!data)return current;const minimum=data.minimumEvidenceByDepth?.[depth]||[];if(minimum.includes(type))return current;const existing=current.requiredSubmissionEvidenceByDepth?.[depth]||[];const next=existing.includes(type)?existing.filter(v=>v!==type):[...existing,type];return{...current,requiredSubmissionEvidenceByDepth:{...current.requiredSubmissionEvidenceByDepth,[depth]:next}}});
 if(authLoading)return null;if(!isAdmin)return <Navigate to="/admin/workspace" replace/>;
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-4 py-5 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><button onClick={()=>navigate('/admin/app/settings?tab=configuration')} className="rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50" aria-label="Back to Settings"><ArrowLeft className="h-4 w-4"/></button><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">PF-SOP-08 · Controlled configuration</div><h1 className="mt-1 text-2xl font-black">Design Delivery Settings</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Tune operating capacity and package depth without code. Master quality gates and minimum package evidence stay protected.</p></div></div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading||busy} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-500"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><button onClick={()=>void save()} disabled={!form||busy} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Controls</button></div></div></header>
 <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-8">{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}{loading&&!form?<div className="flex justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>:form&&data?<>
  <section className="overflow-hidden rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-6 text-white shadow-xl sm:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl border border-white/20 bg-white/10 p-3"><Settings2 className="h-6 w-6"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/70">{form.sopCode||'PF-SOP-08'} · v{form.version||'1.1'}</div><h2 className="mt-1 text-2xl font-black">Executable design quality policy</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-white/80">These values drive server readiness, WIP, review assignment, quality thresholds and package evidence. Historical project/client approvals remain in their canonical records.</p></div></div></section>

  <div className="grid gap-5 lg:grid-cols-2"><Card title="Capacity & review SLA" text="Control throughput without overloading designers or allowing review queues to drift."><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Designer WIP limit" value={form.wipLimit} min={1} max={20} suffix="active design tasks" onChange={v=>setNumber('wipLimit',v)}/><NumberField label="Internal review SLA" value={form.reviewSlaHours} min={1} max={168} suffix="hours" onChange={v=>setNumber('reviewSlaHours',v)}/><NumberField label="Client review SLA" value={form.clientReviewSlaHours} min={1} max={336} suffix="hours" onChange={v=>setNumber('clientReviewSlaHours',v)}/><NumberField label="Independent Design QA pass" value={form.minimumDesignQaScore} min={90} max={100} suffix="/ 100" onChange={v=>setNumber('minimumDesignQaScore',v)}/></div></Card>
   <Card title="Protected PF-SOP-08 gates" text="These controls are visible for clarity but cannot be disabled through Admin settings."><div className="grid gap-2 sm:grid-cols-2">{['Independent Design QA','Accessibility review','Technical feasibility review','Business objective','Target audience','Primary conversion','Approved content reference','Brand assets reference'].map(label=><div key={label} className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><Lock className="h-3.5 w-3.5"/><span>{label}</span><CheckCircle2 className="ml-auto h-4 w-4"/></div>)}</div></Card></div>

  <Card title="Package → Design Delivery depth" text="Product codes come from the active Sales Catalog. Prices are never copied here; only the process depth is mapped."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{packageRows.map(p=><div key={p.code} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wide text-slate-400">{p.code}</div><div className="mt-1 min-h-10 text-sm font-black text-slate-900">{p.name}</div><select className={`${field} mt-3`} value={form.packageDepthByProductCode?.[p.code]||'Unmapped'} onChange={e=>setPackageDepth(p.code,e.target.value as DesignDeliveryDepth)}>{depths.map(d=><option key={d}>{d}</option>)}</select></div>)}{!packageRows.length&&<div className="text-sm text-slate-500">No active package/custom products are available in the Sales Catalog.</div>}</div></Card>

  <Card title="Required submission evidence by depth" text="Minimum PF-SOP-08 evidence is locked. You can add extra evidence when the delivery model becomes stricter."><div className="space-y-5">{depths.map(depth=><div key={depth} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-black text-[#000080]">{depth}</div><div className="mt-0.5 text-[10px] text-slate-400">Server-enforced before internal review submission</div></div><ShieldCheck className="h-5 w-5 text-[#000080]"/></div><div className="mt-4 flex flex-wrap gap-2">{data.allowedEvidenceTypes.map(type=>{const selected=(form.requiredSubmissionEvidenceByDepth?.[depth]||[]).includes(type);const mandatory=(data.minimumEvidenceByDepth?.[depth]||[]).includes(type);return <button key={type} type="button" onClick={()=>toggleEvidence(depth,type)} className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[10px] font-black transition ${selected?'border-[#000080]/20 bg-blue-50 text-[#000080]':'border-slate-200 bg-white text-slate-400'} ${mandatory?'cursor-not-allowed ring-1 ring-emerald-200':''}`}>{mandatory&&<Lock className="h-3 w-3"/>}{evidenceLabel(type)}{selected&&!mandatory&&<CheckCircle2 className="h-3 w-3"/>}</button>})}</div></div>)}</div></Card>

  <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-6 text-blue-900"><strong>Audit rule:</strong> every successful save writes old/new configuration snapshots into the existing Configuration Audit Log. Existing project scope, quotation/package snapshots, client approvals and design review evidence are not rewritten.</div>
 </>:null}</div></main>
}
function NumberField({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(v:number)=>void}){return <label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</span><input type="number" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className={field}/><span className="mt-1 block text-[10px] text-slate-400">{min}–{max} · {suffix}</span></label>}
function Card({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black text-slate-900">{title}</h2><p className="mt-1 mb-5 text-xs leading-5 text-slate-500">{text}</p>{children}</section>}
function Notice({danger=false,children}:{danger?:boolean;children:React.ReactNode}){return <div className={`flex items-start gap-2 rounded-xl border p-4 text-sm font-semibold ${danger?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{danger?<AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>:<CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/>}<span>{children}</span></div>}
