import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,BookOpenCheck,CheckCircle2,FileCode2,Loader2,Plus,RefreshCw,Save,ShieldCheck}from'lucide-react';
import{ArchitectureDecisionInput,DevelopmentTaskSpecInput,EngineeringEnvironment,ReleaseQualityScores,ReuseDecision,developmentSopService,type DevelopmentSopWorkspace}from'../../lib/developmentSopService';

const EMPTY_TICKET:DevelopmentTaskSpecInput={
 environment:'Development',requirementReference:'',designReference:'',acceptanceCriteria:'',dependencies:'None identified.',
 securityConsiderations:'Not applicable.',accessibilityConsiderations:'Not applicable.',seoImplications:'Not applicable.',analyticsRequirements:'Not applicable.',
 testingRequirements:'',definitionOfDone:'',reuseDecision:'REUSE',reuseInspectionNotes:'',duplicationReason:'',technicalRisks:'None identified.'
};
const EMPTY_ADR:ArchitectureDecisionInput={decisionId:'',problem:'',context:'',optionsConsidered:'',selectedOption:'',reason:'',tradeoffs:'',securityImplications:'Not applicable.',costImplications:'Not applicable.',reversalMigrationImplications:'Not applicable.'};
const EMPTY_SCORES:ReleaseQualityScores={functionalCorrectness:100,maintainability:100,security:100,accessibility:100,performance:100,responsiveBrowser:100,reliabilityErrorHandling:100,testing:100,seoAnalytics:100,documentationDeployability:100};

const label=(value:string)=>value.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());
const toInt=(value:string)=>Math.max(0,Math.min(100,Number(value||0)));

export default function DevelopmentSopPanel({taskId,workflowKey,onChanged}:{taskId:string;workflowKey?:string;onChanged?:()=>void|Promise<void>}){
 const[data,setData]=useState<DevelopmentSopWorkspace|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const[ticket,setTicket]=useState<DevelopmentTaskSpecInput>(EMPTY_TICKET);const[adr,setAdr]=useState<ArchitectureDecisionInput>(EMPTY_ADR);const[showAdr,setShowAdr]=useState(false);const[scores,setScores]=useState<ReleaseQualityScores>(EMPTY_SCORES);const[critical,setCritical]=useState(0);const[high,setHigh]=useState(0);const[scoreNotes,setScoreNotes]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const next=await developmentSopService.getWorkspace(taskId);setData(next);const t:any=next.ticket||{};if(Object.keys(t).length)setTicket({environment:(t.environment||'Development')as EngineeringEnvironment,requirementReference:t.requirement_reference||'',designReference:t.design_reference||'',acceptanceCriteria:t.acceptance_criteria||'',dependencies:t.dependencies||'',securityConsiderations:t.security_considerations||'',accessibilityConsiderations:t.accessibility_considerations||'',seoImplications:t.seo_implications||'',analyticsRequirements:t.analytics_requirements||'',testingRequirements:t.testing_requirements||'',definitionOfDone:t.definition_of_done||'',reuseDecision:(t.reuse_decision||'REUSE')as ReuseDecision,reuseInspectionNotes:t.reuse_inspection_notes||'',duplicationReason:t.duplication_reason||'',technicalRisks:t.technical_risks||''});const a:any=next.releaseQualityAssessment||{};if(a.category_scores)setScores({...EMPTY_SCORES,...a.category_scores});if(a.critical_defects!=null)setCritical(Number(a.critical_defects));if(a.high_defects!=null)setHigh(Number(a.high_defects));if(a.notes)setScoreNotes(a.notes);}catch(e:any){setError(e?.message||'Unable to load PF-SOP-09.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[taskId]);
 const run=async(key:string,fn:()=>Promise<any>,message:string)=>{setBusy(key);setError('');setNotice('');try{await fn();setNotice(message);await load();await onChanged?.()}catch(e:any){setError(e?.message||'Unable to complete this SOP action.')}finally{setBusy('')}};
 const readiness=data?.ticketReadiness;const tier=(data?.deliveryTier||'launch').toUpperCase();const majorTier=['growth','scale','custom'].includes(data?.deliveryTier||'');
 const weightedScore=useMemo(()=>{const weights=data?.sop?.qualityScoreWeights||{};return Math.round(Object.entries(scores).reduce((sum,[key,value])=>sum+(Number(value)||0)*(Number((weights as any)[key])||0)/100,0)*100)/100},[scores,data?.sop?.qualityScoreWeights]);
 const releasePass=critical===0&&high===0&&(!majorTier||weightedScore>=90);
 const saveTicket=()=>run('ticket',()=>developmentSopService.saveTaskSpec(taskId,ticket),'Engineering Ticket saved and readiness recalculated.');
 const saveAdr=()=>run('adr',async()=>{await developmentSopService.createArchitectureDecision(taskId,adr);setAdr(EMPTY_ADR);setShowAdr(false)},'Architecture Decision Record saved for independent review.');
 const saveScore=()=>run('score',()=>developmentSopService.submitReleaseQualityScore(taskId,scores,critical,high,scoreNotes),'Engineering Quality Score submitted.');
 if(loading&&!data)return <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-[#000080]"/><p className="mt-2 text-xs font-bold text-slate-500">Loading PF-SOP-09 controls...</p></div>;
 return <section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-[#000080]"><BookOpenCheck className="h-4 w-4"/>{data?.sop?.key||'PF-SOP-09'} · v{data?.sop?.version||'1.0'}</div><h3 className="mt-1 text-base font-black text-slate-900">Executable Engineering SOP</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Understand → inspect → plan → build → self-test → independent review → QA → release → verify → observe. The task cannot bypass required server gates.</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#000080]/10 px-3 py-1 text-[10px] font-black text-[#000080]">{tier}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black text-slate-600">{data?.supportDays||14}-day assurance</span><button onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2 text-slate-500"><RefreshCw className="h-4 w-4"/></button></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-700">{notice}</div>}
  <div className={`rounded-2xl border p-4 ${readiness?.ready?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex items-start gap-3">{readiness?.ready?<CheckCircle2 className="mt-0.5 h-5 w-5 text-emerald-700"/>:<AlertTriangle className="mt-0.5 h-5 w-5 text-amber-700"/>}<div><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">Gate 1 · Engineering Ready</div><div className="mt-1 text-sm font-black text-slate-900">{readiness?.status||'Checking'}</div>{!!readiness?.blockers?.length&&<ul className="mt-2 space-y-1 text-[11px] font-semibold text-amber-800">{readiness.blockers.map(x=><li key={x}>• {x}</li>)}</ul>}</div></div></div>
  <div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2"><FileCode2 className="h-4 w-4 text-[#000080]"/><div><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">Engineering Ticket</div><div className="text-xs font-bold text-slate-700">What must work, how we know it works, and what already exists.</div></div></div>
   <div className="mt-4 grid gap-3 md:grid-cols-2"><SelectField label="Environment" value={ticket.environment} onChange={v=>setTicket(x=>({...x,environment:v as EngineeringEnvironment}))} options={['Development','Preview/Test','Staging','Production','Multiple']}/><SelectField label="Inspect-before-build decision" value={ticket.reuseDecision} onChange={v=>setTicket(x=>({...x,reuseDecision:v as ReuseDecision}))} options={['REUSE','EXTEND','REFACTOR','BUILD NEW']}/><TextField label="Requirement / reference" value={ticket.requirementReference} onChange={v=>setTicket(x=>({...x,requirementReference:v}))}/><TextField label="Approved design reference" value={ticket.designReference} onChange={v=>setTicket(x=>({...x,designReference:v}))}/><Area label="Acceptance criteria" value={ticket.acceptanceCriteria} onChange={v=>setTicket(x=>({...x,acceptanceCriteria:v}))} placeholder="List observable conditions that prove the task works."/><Area label="Existing-system inspection" value={ticket.reuseInspectionNotes} onChange={v=>setTicket(x=>({...x,reuseInspectionNotes:v}))} placeholder="Components, utilities, services, APIs, hooks, tables/RPCs, auth, permissions, tokens, tests and conventions inspected."/><Area label="Dependencies" value={ticket.dependencies} onChange={v=>setTicket(x=>({...x,dependencies:v}))}/><Area label="Technical risks" value={ticket.technicalRisks||''} onChange={v=>setTicket(x=>({...x,technicalRisks:v}))}/><Area label="Security considerations" value={ticket.securityConsiderations} onChange={v=>setTicket(x=>({...x,securityConsiderations:v}))}/><Area label="Accessibility considerations" value={ticket.accessibilityConsiderations} onChange={v=>setTicket(x=>({...x,accessibilityConsiderations:v}))}/><Area label="SEO implications" value={ticket.seoImplications} onChange={v=>setTicket(x=>({...x,seoImplications:v}))}/><Area label="Analytics requirements" value={ticket.analyticsRequirements} onChange={v=>setTicket(x=>({...x,analyticsRequirements:v}))}/><Area label="Testing requirements" value={ticket.testingRequirements} onChange={v=>setTicket(x=>({...x,testingRequirements:v}))}/><Area label="Technical Definition of Done" value={ticket.definitionOfDone} onChange={v=>setTicket(x=>({...x,definitionOfDone:v}))}/>{ticket.reuseDecision==='BUILD NEW'&&<div className="md:col-span-2"><Area label="Why BUILD NEW is justified *" value={ticket.duplicationReason||''} onChange={v=>setTicket(x=>({...x,duplicationReason:v}))} placeholder="Why REUSE / EXTEND / REFACTOR is not appropriate. This is mandatory."/></div>}</div>
   <div className="mt-4 flex justify-end"><button disabled={busy==='ticket'} onClick={()=>void saveTicket()} className="flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white disabled:opacity-50">{busy==='ticket'?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save Engineering Ticket</button></div>
  </div>
  {(workflowKey==='technical_architecture'||data?.deliveryTier==='scale'||data?.deliveryTier==='custom')&&<div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">Architecture Decision Records</div><div className="mt-1 text-xs font-bold text-slate-700">Record significant choices so future engineers understand the decision, alternatives and trade-offs.</div></div><button onClick={()=>setShowAdr(v=>!v)} className="flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-[#000080]"><Plus className="h-4 w-4"/>ADR</button></div>{showAdr&&<div className="mt-4 grid gap-3 md:grid-cols-2"><TextField label="Decision ID" value={adr.decisionId} onChange={v=>setAdr(x=>({...x,decisionId:v}))} placeholder="ADR-001"/><TextField label="Selected option" value={adr.selectedOption} onChange={v=>setAdr(x=>({...x,selectedOption:v}))}/><Area label="Problem" value={adr.problem} onChange={v=>setAdr(x=>({...x,problem:v}))}/><Area label="Context" value={adr.context} onChange={v=>setAdr(x=>({...x,context:v}))}/><Area label="Options considered" value={adr.optionsConsidered} onChange={v=>setAdr(x=>({...x,optionsConsidered:v}))}/><Area label="Reason" value={adr.reason} onChange={v=>setAdr(x=>({...x,reason:v}))}/><Area label="Trade-offs" value={adr.tradeoffs} onChange={v=>setAdr(x=>({...x,tradeoffs:v}))}/><Area label="Security implications" value={adr.securityImplications} onChange={v=>setAdr(x=>({...x,securityImplications:v}))}/><Area label="Cost implications" value={adr.costImplications} onChange={v=>setAdr(x=>({...x,costImplications:v}))}/><Area label="Reversal / migration implications" value={adr.reversalMigrationImplications} onChange={v=>setAdr(x=>({...x,reversalMigrationImplications:v}))}/><div className="md:col-span-2 flex justify-end"><button disabled={busy==='adr'} onClick={()=>void saveAdr()} className="rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white disabled:opacity-50">{busy==='adr'?'Saving...':'Record ADR'}</button></div></div>}
   <div className="mt-4 space-y-2">{(data?.architectureDecisions||[]).map((item:any)=><details key={item.id} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-black text-slate-800">{item.decision_id} · {item.selected_option}</summary><div className="mt-3 grid gap-2 text-[11px] leading-5 text-slate-600 md:grid-cols-2"><Info title="Problem" value={item.problem}/><Info title="Reason" value={item.reason}/><Info title="Trade-offs" value={item.tradeoffs}/><Info title="Security" value={item.security_implications}/></div></details>)}{!data?.architectureDecisions?.length&&<div className="text-xs font-semibold text-slate-400">No ADR recorded yet.</div>}</div>
  </div>}
  {workflowKey==='development_release_readiness'&&<div className="rounded-2xl border border-blue-200 bg-blue-50/30 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-[#000080]"><ShieldCheck className="h-4 w-4"/>Gate 5 · Release Ready</div><h4 className="mt-1 text-sm font-black text-slate-900">ProFox Engineering Quality Score</h4><p className="mt-1 text-xs leading-5 text-slate-600">{majorTier?'Growth / Scale / Custom requires 90+ and zero critical/high defects.':'Launch uses the same quality categories proportionately; critical/high defects still block release.'}</p></div><div className={`rounded-xl px-3 py-2 text-center ${releasePass?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-800'}`}><div className="text-xl font-black">{weightedScore}</div><div className="text-[9px] font-black uppercase">Weighted score</div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.keys(scores).map(key=><label key={key} className="rounded-xl border border-slate-200 bg-white p-3"><span className="block min-h-8 text-[9px] font-black uppercase leading-4 text-slate-500">{label(key)} · {(data?.sop?.qualityScoreWeights as any)?.[key]||0}%</span><input type="number" min={0} max={100} value={(scores as any)[key]} onChange={e=>setScores(x=>({...x,[key]:toInt(e.target.value)}))} className="mt-2 w-full rounded-lg border border-slate-200 px-2 py-1.5 text-xs font-black"/></label>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="Critical defects (E0)" value={critical} onChange={setCritical}/><NumberField label="High defects (E1)" value={high} onChange={setHigh}/><div className="sm:col-span-2"><Area label="Assessment notes" value={scoreNotes} onChange={setScoreNotes} placeholder="Evidence, limitations and remediation context."/></div></div>{data?.releaseQualityAssessment&&Object.keys(data.releaseQualityAssessment).length>0&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-3 text-xs"><span className="font-black text-slate-700">Latest: </span><span className="font-black text-[#000080]">{data.releaseQualityAssessment.status}</span><span className="text-slate-500"> · {data.releaseQualityAssessment.total_score}/100 · E0 {data.releaseQualityAssessment.critical_defects} · E1 {data.releaseQualityAssessment.high_defects}</span></div>}<div className="mt-4 flex justify-end"><button disabled={busy==='score'} onClick={()=>void saveScore()} className="rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white disabled:opacity-50">{busy==='score'?'Submitting...':'Submit Quality Score'}</button></div></div>}
  <details className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer text-xs font-black text-slate-700">PF-SOP-09 quality gates & non-negotiables</summary><div className="mt-4 grid gap-4 md:grid-cols-2"><div><div className="text-[10px] font-black uppercase text-slate-400">Seven gates</div><ol className="mt-2 space-y-1 text-xs font-semibold text-slate-600">{(data?.sop?.qualityGates||[]).map((x,i)=><li key={x}>{i+1}. {x}</li>)}</ol></div><div><div className="text-[10px] font-black uppercase text-slate-400">Non-negotiables</div><ul className="mt-2 space-y-1 text-xs font-semibold text-slate-600">{(data?.sop?.nonNegotiables||[]).map(x=><li key={x}>• {x}</li>)}</ul></div></div></details>
 </section>
}
function TextField({label:caption,value,onChange,placeholder=''}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{caption}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs outline-none focus:border-[#000080]"/></label>}
function Area({label:caption,value,onChange,placeholder=''}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{caption}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs leading-5 outline-none focus:border-[#000080]"/></label>}
function SelectField({label:caption,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{caption}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold outline-none focus:border-[#000080]">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function NumberField({label:caption,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{caption}</span><input type="number" min={0} value={value} onChange={e=>onChange(Math.max(0,Math.trunc(Number(e.target.value||0))))} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-black"/></label>}
function Info({title,value}:{title:string;value:string}){return <div><span className="font-black text-slate-700">{title}: </span>{value}</div>}
