import React,{useEffect,useState}from'react';
import{CheckCircle2,Clock3,GitPullRequest,Loader2,RotateCcw}from'lucide-react';
import{DevelopmentReviewQueueItem,developmentDeliveryService}from'../../lib/developmentDeliveryService';
import{useAuth}from'../../lib/AuthContext';
import CRMSalesValidationQueue from './crm/CRMSalesValidationQueue';

export default function DevelopmentReviewQueue({onChanged}:{onChanged?:()=>void|Promise<void>}){
 const{role,isAdmin}=useAuth();
 const[items,setItems]=useState<DevelopmentReviewQueueItem[]>([]);const[loading,setLoading]=useState(true);const[selected,setSelected]=useState<DevelopmentReviewQueueItem|null>(null);const[notes,setNotes]=useState('');const[score,setScore]=useState('');const[running,setRunning]=useState(false);const[error,setError]=useState('');
 const canReviewSalesValidations=isAdmin||role==='developer';
 const load=async()=>{setLoading(true);try{setItems(await developmentDeliveryService.getMyReviews())}catch{setItems([])}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const decide=async(decision:'Pass'|'Changes Required')=>{if(!selected)return;setRunning(true);setError('');try{await developmentDeliveryService.submitReviewDecision(selected.reviewId,decision,score===''?null:Number(score),notes);setSelected(null);setNotes('');setScore('');await load();await onChanged?.()}catch(e:any){setError(e?.message||'Unable to submit review.')}finally{setRunning(false)}};
 if(loading&&!canReviewSalesValidations)return null;
 return <>
  {canReviewSalesValidations&&<CRMSalesValidationQueue/>}
  {!loading&&items.length>0&&<section className="rounded-3xl border border-violet-200 bg-violet-50/40 p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-violet-700"><GitPullRequest className="h-4 w-4"/> Independent Technical Review</div><h2 className="mt-1 text-base font-black text-slate-900">{items.length} review{items.length===1?'':'s'} need your attention</h2><p className="mt-1 text-xs leading-5 text-slate-600">Review another developer’s architecture/code evidence before the task can become Done.</p></div><button onClick={()=>void load()} className="rounded-xl border border-violet-200 bg-white p-2 text-violet-700"><RotateCcw className="h-4 w-4"/></button></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map(item=><button key={item.reviewId} onClick={()=>{setSelected(item);setNotes('');setScore('')}} className="rounded-2xl border border-violet-100 bg-white p-4 text-left transition hover:border-violet-300 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black text-slate-900">{item.taskTitle}</div><div className="mt-1 text-[10px] font-bold text-[#000080]">{item.projectNumber} · {item.projectName}</div><div className="mt-1 text-[10px] text-slate-500">Developer: {item.developerName||'Assigned developer'} · {item.clientName||'Client'}</div></div><span className={`rounded-full px-2 py-1 text-[9px] font-black ${item.slaStatus==='Breached'?'bg-red-100 text-red-700':item.slaStatus==='Due Soon'?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-700'}`}>{item.slaStatus}</span></div><div className="mt-3 flex items-center gap-2 text-[10px] font-bold text-slate-500"><Clock3 className="h-3.5 w-3.5"/>{item.ageHours}h waiting · {item.reviewType}</div></button>)}</div>
  {selected&&<div className="mt-4 rounded-2xl border border-violet-200 bg-white p-4"><div className="text-xs font-black text-slate-900">Review: {selected.taskTitle}</div><p className="mt-1 text-[11px] text-slate-500">Open the Development task/evidence from My Work if needed. Record a quality score and specific feedback for any returned work.</p>{error&&<div className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">{error}</div>}<div className="mt-3 grid gap-3 sm:grid-cols-[140px_1fr]"><label><span className="mb-1 block text-[10px] font-black uppercase text-slate-400">Quality score</span><input type="number" min="0" max="100" value={score} onChange={e=>setScore(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-xs" placeholder="0–100"/></label><label><span className="mb-1 block text-[10px] font-black uppercase text-slate-400">Review notes</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-xs" placeholder="What passed, or what exactly must change?"/></label></div><div className="mt-3 flex flex-wrap justify-end gap-2"><button disabled={running} onClick={()=>setSelected(null)} className="px-3 py-2 text-xs font-bold text-slate-500">Cancel</button><button disabled={running} onClick={()=>void decide('Changes Required')} className="flex items-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-2 text-xs font-black text-amber-800"><RotateCcw className="h-3.5 w-3.5"/> Changes Required</button><button disabled={running} onClick={()=>void decide('Pass')} className="flex items-center gap-1.5 rounded-xl bg-[#000080] px-4 py-2 text-xs font-black text-white">{running?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<CheckCircle2 className="h-3.5 w-3.5"/>} Pass Technical Review</button></div></div>}
  </section>}
 </>
}