import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,CheckCircle2,Code2,ExternalLink,FileCheck2,GitBranch,Loader2,Plus,RefreshCw,Send,ShieldCheck,X}from'lucide-react';
import ProductivityPlaybookChecklist from './ProductivityPlaybookChecklist';
import DevelopmentSopPanel from './DevelopmentSopPanel';
import{DevelopmentDeliveryWorkspace,DevelopmentEvidenceType,HandoverClientPackage,developmentDeliveryService}from'../../lib/developmentDeliveryService';

const EVIDENCE:Array<{type:DevelopmentEvidenceType;label:string}>=[
 {type:'architecture_notes',label:'Architecture / setup notes'},{type:'technical_discovery',label:'Technical discovery'},{type:'architecture_decision',label:'Architecture decision / ADR'},{type:'reuse_inspection',label:'Reuse inspection'},
 {type:'repository',label:'Repository'},{type:'branch',label:'Feature branch'},{type:'environment_check',label:'Environment / configuration check'},{type:'dependency_review',label:'Dependency / supply-chain review'},
 {type:'pull_request',label:'Pull request'},{type:'commit',label:'Release commit'},{type:'build_result',label:'Build / CI result'},{type:'test_result',label:'Test result'},{type:'acceptance_criteria',label:'Acceptance-criteria evidence'},
 {type:'staging_url',label:'Staging / preview URL'},{type:'implementation_notes',label:'Implementation notes'},{type:'browser_responsive_check',label:'Responsive / browser check'},
 {type:'accessibility_check',label:'Accessibility check'},{type:'performance_check',label:'Performance / Web Vitals check'},{type:'security_check',label:'Security check'},
 {type:'seo_check',label:'Technical SEO check'},{type:'analytics_check',label:'Analytics / tracking check'},{type:'qa_handoff',label:'QA / release readiness evidence'},
 {type:'backup_recovery',label:'Backup / recovery evidence'},{type:'rollback_plan',label:'Rollback plan'},{type:'release_notes',label:'Release notes'},{type:'documentation',label:'Technical / client documentation'},
 {type:'deployment_reference',label:'Deployment reference'},{type:'production_url',label:'Production URL'},{type:'smoke_test',label:'Production smoke test'},{type:'monitoring_check',label:'Monitoring / observability check'},
 {type:'handover_reference',label:'Handover reference'},{type:'incident_reference',label:'Incident reference'},{type:'root_cause_analysis',label:'Root-cause analysis'}
];
const EMPTY_HANDOVER:HandoverClientPackage={productionUrl:'',documentationReference:'',releaseEvidence:'',accessOwnership:'',supportBoundary:'',repositoryAccess:'',cmsInstructions:'',integrations:'',analyticsTracking:'',backupRecovery:'',trainingReference:''};
const evidenceName=(type:string)=>EVIDENCE.find(x=>x.type===type)?.label||type.replaceAll('_',' ');

export default function DevelopmentDeliveryTaskWorkspace({taskId,onClose,onChanged}:{taskId:string;onClose:()=>void;onChanged?:()=>void|Promise<void>}){
 const[workspace,setWorkspace]=useState<DevelopmentDeliveryWorkspace|null>(null);const[loading,setLoading]=useState(true);const[running,setRunning]=useState('');const[error,setError]=useState('');
 const[showEvidence,setShowEvidence]=useState(false);const[evidenceType,setEvidenceType]=useState<DevelopmentEvidenceType>('repository');const[evidenceLabel,setEvidenceLabel]=useState('');const[evidenceUrl,setEvidenceUrl]=useState('');const[evidenceNote,setEvidenceNote]=useState('');const[reviewNote,setReviewNote]=useState('');
 const[handover,setHandover]=useState<HandoverClientPackage>(EMPTY_HANDOVER);const[handoverNote,setHandoverNote]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setWorkspace(await developmentDeliveryService.getWorkspace(taskId));}catch(e:any){setError(e?.message||'Unable to load Development Delivery workspace.');}finally{setLoading(false)}};
 useEffect(()=>{void load()},[taskId]);
 const run=async(key:string,action:()=>Promise<any>)=>{setRunning(key);setError('');try{await action();await load();await onChanged?.()}catch(e:any){setError(e?.message||'Unable to complete this action.')}finally{setRunning('')}};
 const activeEvidence=useMemo(()=>(workspace?.evidence||[]).filter((x:any)=>x.active),[workspace?.evidence]);
 const activeTypes=useMemo(()=>new Set(activeEvidence.filter((x:any)=>['Provided','Verified'].includes(x.status)).map((x:any)=>x.evidence_type)),[activeEvidence]);
 if(loading&&!workspace)return <div className="flex min-h-[440px] items-center justify-center rounded-[28px] bg-white"><Loader2 className="h-7 w-7 animate-spin text-[#000080]"/></div>;
 const task=workspace?.task||{},project=workspace?.project||{},client=workspace?.client||{},ready=workspace?.readiness,required=workspace?.requiredEvidence||[];
 const isHandover=task.workflow_key==='development_handover_package';
 const status=task.status||'To Do';
 const saveEvidence=()=>run('evidence',async()=>{await developmentDeliveryService.addEvidence({taskId,type:evidenceType,label:evidenceLabel,referenceUrl:evidenceUrl,referenceNote:evidenceNote});setEvidenceLabel('');setEvidenceUrl('');setEvidenceNote('');setShowEvidence(false)});
 const setPackage=(key:keyof HandoverClientPackage,value:string)=>setHandover(current=>({...current,[key]:value}));
 return <div className="max-h-[92vh] overflow-y-auto rounded-[28px] bg-slate-50">
  <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur sm:px-7">
   <div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#000080]/10 px-2.5 py-1 text-[10px] font-black uppercase tracking-widest text-[#000080]">Development Delivery</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">{status}</span><span className="rounded-full bg-cyan-50 px-2.5 py-1 text-[10px] font-black text-cyan-700">{project.stage||'Project'}</span><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-black text-[#000080]">PF-SOP-09</span>{isHandover&&<span className="rounded-full bg-amber-100 px-2.5 py-1 text-[10px] font-black text-amber-800">Manager approval required</span>}</div><h2 className="mt-2 text-xl font-black text-slate-900">{task.title||'Development task'}</h2><p className="mt-1 text-xs font-semibold text-slate-500">{project.project_number||'Project'} · {project.project_name||''} · {client.company_name||'Client'}</p></div><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X className="h-5 w-5"/></button></div>
  </header>
  <div className="space-y-5 p-5 sm:p-7">
   {error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-bold text-red-700">{error}</div>}
   <section className={`rounded-3xl border p-5 ${ready?.ready?'border-emerald-200 bg-emerald-50/60':'border-amber-200 bg-amber-50/70'}`}>
    <div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${ready?.ready?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{ready?.ready?<CheckCircle2 className="h-5 w-5"/>:<AlertTriangle className="h-5 w-5"/>}</div><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Project Definition of Ready</div><h3 className="mt-1 text-base font-black text-slate-900">{ready?.status||'Checking readiness'}</h3><p className="mt-1 text-xs leading-5 text-slate-600">Server-enforced project checks connect scope, client approval, design handoff, developer assignment and technical sequencing. PF-SOP-09 Engineering Ready is enforced separately below.</p></div></div><button onClick={()=>void load()} className="rounded-xl border border-white bg-white p-2 text-slate-500" title="Recheck readiness"><RefreshCw className="h-4 w-4"/></button></div>
    {!!ready?.blockers?.length&&<div className="mt-4 grid gap-2 sm:grid-cols-2">{ready.blockers.map(x=><div key={x} className="rounded-xl bg-white/80 px-3 py-2 text-[11px] font-bold text-amber-800">• {x}</div>)}</div>}
   </section>

   <section className="grid gap-4 lg:grid-cols-3">
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><div className="flex items-center gap-2"><Code2 className="h-4 w-4 text-[#000080]"/><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Connected delivery brief</div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Package" value={project.package_snapshot||'Not recorded'}/><Info label="Project stage" value={project.stage||'Not recorded'}/><Info label="Due date" value={task.due_date||'No due date'}/><Info label="Workflow" value={task.workflow_key||'Development work'}/><Text label="Approved scope" value={project.scope_summary}/><Text label="Requirements" value={project.requirements_summary}/>{project.exclusions&&<Text label="Exclusions" value={project.exclusions}/>}<Text label="Task instructions" value={task.description}/></div></div>
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#000080]"/><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Quality chain</div></div><div className="mt-4 space-y-3 text-xs font-bold text-slate-700"><Flow ok>Developer self-QA</Flow><Flow>Independent technical review</Flow><Flow>QA engineer</Flow><Flow>UI/UX implementation QA</Flow><Flow>Client review / revisions</Flow><Flow>Engineering Release Readiness</Flow><Flow>Production smoke test / monitoring</Flow><Flow>Manager-approved final handover</Flow></div></div>
   </section>

   {!!workspace?.designHandoff?.length&&<section className="rounded-3xl border border-blue-200 bg-blue-50/40 p-5"><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-[#000080]"/><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Approved UI/UX → Development handoff</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{workspace.designHandoff.map((item:any)=><div key={item.id} className="rounded-2xl border border-blue-100 bg-white p-3"><div className="text-[10px] font-black uppercase text-slate-400">{String(item.type||'handoff').replaceAll('_',' ')}</div><div className="mt-1 text-xs font-bold text-slate-800">{item.label||item.version||'Approved reference'}</div>{item.note&&<p className="mt-1 line-clamp-3 text-[11px] leading-5 text-slate-600">{item.note}</p>}{item.url&&<a href={item.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[10px] font-black text-[#000080]">Open approved source <ExternalLink className="h-3 w-3"/></a>}</div>)}</div></section>}

   <DevelopmentSopPanel taskId={taskId} workflowKey={task.workflow_key} onChanged={async()=>{await load();await onChanged?.()}}/>

   {(status==='To Do'||status==='Changes Required'||status==='In Progress')&&<ProductivityPlaybookChecklist entityType="project_task" entityId={taskId}/>} 

   <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Engineering evidence</div><h3 className="mt-1 text-base font-black text-slate-900">One place for repository → release proof</h3><p className="mt-1 text-xs leading-5 text-slate-500">PF-SOP-09 evidence follows the real engineering lifecycle. Link source-of-truth proof; never paste passwords, tokens, API keys or private credentials.</p></div><button onClick={()=>setShowEvidence(v=>!v)} className="flex items-center gap-1.5 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-black text-[#000080]"><Plus className="h-3.5 w-3.5"/> Add evidence</button></div>
    {!!required.length&&<div className="mt-4"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Required before this task can leave Development</div><div className="mt-2 flex flex-wrap gap-2">{required.map(type=><span key={type} className={`rounded-full px-2.5 py-1 text-[10px] font-black ${activeTypes.has(type)?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-800'}`}>{activeTypes.has(type)?'✓ ':'○ '}{evidenceName(type)}</span>)}</div></div>}
    {showEvidence&&<div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="block"><Small>Evidence type</Small><select value={evidenceType} onChange={e=>setEvidenceType(e.target.value as DevelopmentEvidenceType)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold">{EVIDENCE.map(x=><option key={x.type} value={x.type}>{x.label}</option>)}</select></label><Field label="Label" value={evidenceLabel} onChange={setEvidenceLabel} placeholder="e.g. PR #124 · QA candidate"/><Field label="Source URL" value={evidenceUrl} onChange={setEvidenceUrl} placeholder="https://..."/><label className="block"><Small>Evidence note</Small><textarea rows={3} value={evidenceNote} onChange={e=>setEvidenceNote(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs" placeholder="Short verification context. Never include secrets."/></label></div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setShowEvidence(false)} className="px-3 py-2 text-xs font-bold text-slate-500">Cancel</button><button disabled={running==='evidence'} onClick={()=>void saveEvidence()} className="rounded-xl bg-[#000080] px-4 py-2 text-xs font-black text-white">{running==='evidence'?'Saving...':'Save evidence'}</button></div></div>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2">{activeEvidence.length?activeEvidence.map((item:any)=><div key={item.id} className="rounded-2xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">{evidenceName(item.evidence_type)}</div><div className="mt-1 text-xs font-bold text-slate-800">{item.label||item.status}</div>{item.reference_note&&<p className="mt-1 line-clamp-3 text-[11px] leading-5 text-slate-600">{item.reference_note}</p>}</div>{item.reference_url&&<a href={item.reference_url} target="_blank" rel="noreferrer" className="rounded-lg bg-slate-50 p-2 text-[#000080]"><ExternalLink className="h-4 w-4"/></a>}</div></div>):<div className="sm:col-span-2 rounded-2xl border border-dashed border-slate-200 p-6 text-center text-xs font-bold text-slate-400">No Development evidence recorded yet.</div>}</div>
   </section>

   {isHandover&&status==='In Progress'&&<section className="rounded-3xl border border-amber-200 bg-amber-50/50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-amber-700">Client-ready final handover</div><h3 className="mt-1 text-base font-black text-slate-900">Development prepares. Manager checks. Client receives only after approval.</h3><p className="mt-1 text-xs leading-5 text-slate-600">Before this stage, PF-SOP-09 requires production verification, documentation, backup/recovery and monitoring evidence. These client-facing fields must remain safe to share; secrets stay in approved credential systems.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Production URL *" value={handover.productionUrl} onChange={v=>setPackage('productionUrl',v)}/><Field label="Documentation reference *" value={handover.documentationReference} onChange={v=>setPackage('documentationReference',v)}/><Field label="Final QA / release evidence *" value={handover.releaseEvidence} onChange={v=>setPackage('releaseEvidence',v)}/><Field label="Access ownership / transfer *" value={handover.accessOwnership} onChange={v=>setPackage('accessOwnership',v)}/><Field label="Support / warranty boundary *" value={handover.supportBoundary} onChange={v=>setPackage('supportBoundary',v)}/><Field label="Repository/source access" value={handover.repositoryAccess||''} onChange={v=>setPackage('repositoryAccess',v)}/><Field label="CMS/admin instructions" value={handover.cmsInstructions||''} onChange={v=>setPackage('cmsInstructions',v)}/><Field label="Integrations" value={handover.integrations||''} onChange={v=>setPackage('integrations',v)}/><Field label="Analytics / tracking" value={handover.analyticsTracking||''} onChange={v=>setPackage('analyticsTracking',v)}/><Field label="Backup / recovery" value={handover.backupRecovery||''} onChange={v=>setPackage('backupRecovery',v)}/><Field label="Training reference" value={handover.trainingReference||''} onChange={v=>setPackage('trainingReference',v)}/><label className="block sm:col-span-2"><Small>Submission note</Small><textarea rows={3} value={handoverNote} onChange={e=>setHandoverNote(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs" placeholder="Anything the manager should verify before client release."/></label></div></section>}

   {!!workspace?.reviews?.length&&<section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Technical review history</div><div className="mt-3 space-y-2">{workspace.reviews.map((r:any)=><div key={r.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-black text-slate-800">{r.review_type} · Round {r.review_round}</div><span className={`rounded-full px-2 py-1 text-[9px] font-black ${r.status==='Pass'?'bg-emerald-100 text-emerald-700':r.status==='Changes Required'?'bg-amber-100 text-amber-800':'bg-violet-100 text-violet-700'}`}>{r.status}</span></div>{r.notes&&<p className="mt-2 whitespace-pre-wrap text-[11px] leading-5 text-slate-600">{r.notes}</p>}</div>)}</div></section>}

   <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex-1"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Next controlled action</div>{status==='In Progress'&&!isHandover&&<textarea rows={2} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs" placeholder="Optional note for the independent technical reviewer."/>}<p className="mt-2 text-xs leading-5 text-slate-500">PF-SOP-09 gates are server-authoritative. “Code written” is not DONE; review, QA, release verification and handover controls must pass.</p></div><div className="shrink-0">{(status==='To Do'||status==='Changes Required')&&<button disabled={!!running||!ready?.ready} onClick={()=>void run('start',()=>developmentDeliveryService.startTask(taskId))} className="flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><GitBranch className="h-4 w-4"/> Start Development</button>}{status==='In Progress'&&!isHandover&&<button disabled={!!running} onClick={()=>void run('review',()=>developmentDeliveryService.submitForReview(taskId,reviewNote))} className="flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white"><Send className="h-4 w-4"/> Submit for Technical Review</button>}{status==='In Progress'&&isHandover&&<button disabled={!!running} onClick={()=>void run('handover',()=>developmentDeliveryService.submitHandover(project.id,handover,handoverNote))} className="flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white"><Send className="h-4 w-4"/> Submit to Manager for Final Handover Review</button>}{status==='Review'&&<div className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-xs font-black text-violet-700">Waiting for {isHandover?'manager handover review':'independent technical review'}</div>}{status==='Done'&&<div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-black text-emerald-700"><CheckCircle2 className="h-4 w-4"/> Quality gate complete</div>}</div></div>
   </section>
  </div>
 </div>
}
function Info({label,value}:{label:string;value:any}){return <div><Small>{label}</Small><div className="mt-1 text-xs font-bold text-slate-800">{value||'Not recorded'}</div></div>}
function Text({label,value}:{label:string;value:any}){return <div className="sm:col-span-2"><Small>{label}</Small><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-slate-700">{value||'Not recorded'}</p></div>}
function Small({children}:{children:React.ReactNode}){return <span className="mb-1 block text-[10px] font-black uppercase tracking-wide text-slate-400">{children}</span>}
function Field({label,value,onChange,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block"><Small>{label}</Small><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs outline-none focus:border-[#000080]"/></label>}
function Flow({children,ok=false}:{children:React.ReactNode;ok?:boolean}){return <div className="flex items-center gap-2">{ok?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<ArrowRight className="h-4 w-4 text-slate-400"/>}{children}</div>}
