import React,{useEffect,useState}from'react';
import{AlertOctagon,CheckCircle2,ClipboardList,Flame,Loader2,Plus,RefreshCw,RotateCcw,ShieldAlert}from'lucide-react';
import{developmentQualityService,type FindingSeverity,type FindingSource,type FindingStatus,type QualityWorkspace}from'../../lib/developmentQualityService';

const SOURCES:FindingSource[]=['Developer Self-Test','Code Review','QA','Security','Accessibility','Performance','UI/UX Implementation QA','SEO','Analytics','UAT','Production Monitoring','Client'];
const SEVERITIES:FindingSeverity[]=['E0','E1','E2','E3'];
const severityText:Record<FindingSeverity,string>={E0:'Critical · release blocked',E1:'High · release blocked',E2:'Medium',E3:'Low'};

export default function DevelopmentQualityOperationsPanel({taskId,projectId,onChanged}:{taskId:string;projectId:string;onChanged?:()=>void|Promise<void>}){
 const[data,setData]=useState<QualityWorkspace|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');
 const[showFinding,setShowFinding]=useState(false);const[source,setSource]=useState<FindingSource>('Developer Self-Test');const[severity,setSeverity]=useState<FindingSeverity>('E2');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[evidence,setEvidence]=useState('');
 const[resolution,setResolution]=useState<Record<string,string>>({});const[regression,setRegression]=useState<Record<string,string>>({});
 const[showChange,setShowChange]=useState(false);const[change,setChange]=useState({summary:'',reason:'',effort:'',cost:'',timeline:'',architecture:'',security:'',qaRegression:'',designContentSeo:''});
 const[showIncident,setShowIncident]=useState(false);const[incidentSeverity,setIncidentSeverity]=useState<FindingSeverity>('E1');const[incidentTitle,setIncidentTitle]=useState('');const[incidentDescription,setIncidentDescription]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setData(await developmentQualityService.getWorkspace(taskId));}catch(e:any){setError(e?.message||'Unable to load PF-SOP-09 quality operations.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[taskId]);
 const run=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setError('');try{await fn();await load();await onChanged?.()}catch(e:any){setError(e?.message||'Unable to complete quality action.')}finally{setBusy('')}};
 const createFinding=()=>run('finding',async()=>{await developmentQualityService.createFinding({projectId,taskId,source,severity,title,description,evidenceUrl:evidence});setTitle('');setDescription('');setEvidence('');setShowFinding(false)});
 const updateFinding=(findingId:string,status:FindingStatus)=>run(findingId,()=>developmentQualityService.updateFinding(findingId,status,resolution[findingId]||'',regression[findingId]||''));
 const submitChange=()=>run('change',async()=>{await developmentQualityService.submitChangeRequest({projectId,taskId,...change});setChange({summary:'',reason:'',effort:'',cost:'',timeline:'',architecture:'',security:'',qaRegression:'',designContentSeo:''});setShowChange(false)});
 const createIncident=()=>run('incident',async()=>{await developmentQualityService.createIncident({projectId,severity:incidentSeverity,title:incidentTitle,description:incidentDescription});setIncidentTitle('');setIncidentDescription('');setShowIncident(false)});
 if(loading&&!data)return <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-[#000080]"/></div>;
 const blockers=data?.releaseBlockers||{e0:0,e1:0,e2:0,e3:0,releaseBlocking:false};
 return <section className="space-y-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-[#000080]"><ShieldAlert className="h-4 w-4"/>PF-SOP-09 quality operations</div><h3 className="mt-1 text-base font-black text-slate-900">Defects, scope change & production learning</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">QA findings remain traceable; material scope changes require approval; production incidents move through containment, recovery and root-cause improvement.</p></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2 text-slate-500"><RefreshCw className="h-4 w-4"/></button></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>}
  <div className={`grid gap-2 rounded-2xl border p-4 sm:grid-cols-4 ${blockers.releaseBlocking?'border-red-200 bg-red-50':'border-emerald-200 bg-emerald-50'}`}>{SEVERITIES.map(level=><div key={level}><div className="text-[9px] font-black uppercase text-slate-500">{severityText[level]}</div><div className={`mt-1 text-xl font-black ${level==='E0'||level==='E1'?'text-red-700':'text-slate-800'}`}>{(blockers as any)[level.toLowerCase()]||0}</div></div>)}</div>
  {blockers.releaseBlocking&&<div className="flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-black text-red-700"><AlertOctagon className="mt-0.5 h-4 w-4 shrink-0"/>Release is blocked until every current E0/E1 finding is resolved and independently verified or explicitly waived by authorized Management.</div>}
  <div className="flex flex-wrap gap-2"><button onClick={()=>setShowFinding(v=>!v)} className="flex items-center gap-1.5 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white"><Plus className="h-4 w-4"/>Quality Finding</button><button onClick={()=>setShowChange(v=>!v)} className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-black text-[#000080]"><ClipboardList className="h-4 w-4"/>Change Request</button><button onClick={()=>setShowIncident(v=>!v)} className="flex items-center gap-1.5 rounded-xl border border-red-200 px-4 py-2.5 text-xs font-black text-red-700"><Flame className="h-4 w-4"/>Production Incident</button></div>
  {showFinding&&<div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><Select label="Source" value={source} options={SOURCES} onChange={v=>setSource(v as FindingSource)}/><Select label="Severity" value={severity} options={SEVERITIES} onChange={v=>setSeverity(v as FindingSeverity)}/><Field label="Title" value={title} onChange={setTitle}/><Field label="Evidence URL" value={evidence} onChange={setEvidence}/><div className="sm:col-span-2"><Area label="Description / observed behavior" value={description} onChange={setDescription}/></div></div><div className="mt-3 flex justify-end"><button disabled={busy==='finding'||title.trim().length<3||description.trim().length<10} onClick={()=>void createFinding()} className="rounded-xl bg-[#000080] px-4 py-2 text-xs font-black text-white disabled:opacity-40">Record Finding</button></div></div>}
  {showChange&&<div className="rounded-2xl border border-amber-200 bg-amber-50/40 p-4"><p className="mb-3 text-xs font-bold text-amber-800">Material scope/design changes are not quietly absorbed. Record impact, then Project Management decides before implementation.</p><div className="grid gap-3 sm:grid-cols-2"><Field label="Requested change" value={change.summary} onChange={v=>setChange(x=>({...x,summary:v}))}/><Field label="Reason" value={change.reason} onChange={v=>setChange(x=>({...x,reason:v}))}/><Area label="Effort impact" value={change.effort} onChange={v=>setChange(x=>({...x,effort:v}))}/><Area label="Cost impact" value={change.cost} onChange={v=>setChange(x=>({...x,cost:v}))}/><Area label="Timeline impact" value={change.timeline} onChange={v=>setChange(x=>({...x,timeline:v}))}/><Area label="Architecture impact" value={change.architecture} onChange={v=>setChange(x=>({...x,architecture:v}))}/><Area label="Security impact" value={change.security} onChange={v=>setChange(x=>({...x,security:v}))}/><Area label="QA / regression impact" value={change.qaRegression} onChange={v=>setChange(x=>({...x,qaRegression:v}))}/><div className="sm:col-span-2"><Area label="Design / content / SEO impact" value={change.designContentSeo} onChange={v=>setChange(x=>({...x,designContentSeo:v}))}/></div></div><div className="mt-3 flex justify-end"><button disabled={busy==='change'} onClick={()=>void submitChange()} className="rounded-xl bg-[#000080] px-4 py-2 text-xs font-black text-white disabled:opacity-40">Submit for PM Review</button></div></div>}
  {showIncident&&<div className="rounded-2xl border border-red-200 bg-red-50/40 p-4"><div className="grid gap-3 sm:grid-cols-2"><Select label="Incident severity" value={incidentSeverity} options={SEVERITIES} onChange={v=>setIncidentSeverity(v as FindingSeverity)}/><Field label="Incident title" value={incidentTitle} onChange={setIncidentTitle}/><div className="sm:col-span-2"><Area label="What failed / customer impact" value={incidentDescription} onChange={setIncidentDescription}/></div></div><div className="mt-3 flex justify-end"><button disabled={busy==='incident'||incidentTitle.trim().length<3||incidentDescription.trim().length<10} onClick={()=>void createIncident()} className="rounded-xl bg-red-700 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Create Incident</button></div></div>}
  <div><div className="mb-2 text-[10px] font-black uppercase tracking-wider text-slate-400">Quality findings</div><div className="space-y-2">{(data?.findings||[]).map((f:any)=><div key={f.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className={`mr-2 rounded-full px-2 py-1 text-[9px] font-black ${f.severity==='E0'||f.severity==='E1'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-800'}`}>{f.severity}</span><span className="text-xs font-black text-slate-800">{f.title}</span><div className="mt-1 text-[10px] font-bold text-slate-400">{f.source} · {f.status}</div></div>{f.status==='Verified'?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:null}</div><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-slate-600">{f.description}</p>{!['Verified','Waived'].includes(f.status)&&<div className="mt-3 grid gap-2 sm:grid-cols-2"><Area label="Resolution / root-cause note" value={resolution[f.id]||''} onChange={v=>setResolution(x=>({...x,[f.id]:v}))}/><Area label="Regression evidence" value={regression[f.id]||''} onChange={v=>setRegression(x=>({...x,[f.id]:v}))}/><div className="sm:col-span-2 flex flex-wrap justify-end gap-2"><button disabled={busy===f.id} onClick={()=>void updateFinding(f.id,'In Progress')} className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-black text-slate-600">In Progress</button><button disabled={busy===f.id} onClick={()=>void updateFinding(f.id,'Resolved')} className="rounded-lg bg-amber-600 px-3 py-2 text-[10px] font-black text-white">Mark Resolved</button><button disabled={busy===f.id} onClick={()=>void updateFinding(f.id,'Verified')} className="rounded-lg bg-emerald-700 px-3 py-2 text-[10px] font-black text-white">Independent Verify</button></div></div>}</div>)}{!(data?.findings||[]).length&&<div className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-xs font-bold text-slate-400">No quality findings recorded for this task/project context.</div>}</div></div>
  {!!(data?.changeRequests||[]).length&&<details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-xs font-black text-slate-700">Change requests ({data?.changeRequests.length})</summary><div className="mt-3 space-y-2">{data?.changeRequests.map((c:any)=><div key={c.id} className="rounded-xl bg-slate-50 p-3 text-xs"><div className="font-black text-slate-800">{c.request_summary}</div><div className="mt-1 text-[10px] font-bold text-slate-500">{c.status}</div></div>)}</div></details>}
  {!!(data?.incidents||[]).length&&<details className="rounded-xl border border-red-100 p-3"><summary className="cursor-pointer text-xs font-black text-red-700">Production incidents ({data?.incidents.length})</summary><div className="mt-3 space-y-2">{data?.incidents.map((i:any)=><div key={i.id} className="rounded-xl bg-red-50 p-3 text-xs"><div className="font-black text-slate-800">{i.severity} · {i.title}</div><div className="mt-1 text-[10px] font-bold text-red-600">{i.status}</div>{i.root_cause&&<div className="mt-2 text-slate-600">Root cause: {i.root_cause}</div>}</div>)}</div></details>}
 </section>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs outline-none focus:border-[#000080]"/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{label}</span><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs leading-5 outline-none focus:border-[#000080]"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label><span className="mb-1 block text-[10px] font-black uppercase text-slate-500">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
