import React,{useEffect,useState}from'react';
import{AlertTriangle,CheckCircle2,Clock3,ExternalLink,Loader2,RotateCcw,ShieldCheck}from'lucide-react';
import{DevelopmentHandoverQueueItem,developmentHandoverManagerService}from'../../lib/developmentHandoverManagerService';

export default function DevelopmentHandoverManagerQueue({enabled,onChanged}:{enabled:boolean;onChanged?:()=>void|Promise<void>}){
 const[items,setItems]=useState<DevelopmentHandoverQueueItem[]>([]);const[selected,setSelected]=useState<DevelopmentHandoverQueueItem|null>(null);const[notes,setNotes]=useState('');const[loading,setLoading]=useState(false);const[running,setRunning]=useState(false);const[error,setError]=useState('');
 const load=async()=>{if(!enabled)return;setLoading(true);try{setItems(await developmentHandoverManagerService.getQueue())}catch{setItems([])}finally{setLoading(false)}};
 useEffect(()=>{void load()},[enabled]);
 const review=async(decision:'Approved'|'Changes Required')=>{if(!selected)return;setRunning(true);setError('');try{await developmentHandoverManagerService.review(selected.packageId,decision,notes);setSelected(null);setNotes('');await load();await onChanged?.()}catch(e:any){setError(e?.message||'Unable to review final handover.')}finally{setRunning(false)}};
 if(!enabled||loading||!items.length)return null;
 return <section className="rounded-3xl border border-amber-200 bg-amber-50/50 p-5 shadow-sm"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-amber-100 text-amber-800"><ShieldCheck className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-amber-700">Manager-controlled final handover</div><h2 className="mt-1 text-base font-black text-slate-900">{items.length} client handover package{items.length===1?'':'s'} waiting for Management review</h2><p className="mt-1 text-xs leading-5 text-slate-600">Nothing is released to the client from entering Handover alone. Review the client-safe package and either return specific changes or approve-and-release it.</p></div></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map(item=><button key={item.packageId} onClick={()=>{setSelected(item);setNotes('')}} className="rounded-2xl border border-amber-100 bg-white p-4 text-left transition hover:border-amber-300 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black text-slate-900">{item.projectNumber} · {item.projectName}</div><div className="mt-1 text-[10px] text-slate-500">Client: {item.clientName||'Client'} · Prepared by {item.developerName||'Developer'}</div></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black text-amber-800">v{item.version}</span></div><div className="mt-3 flex items-center gap-2 text-[10px] font-bold text-slate-500"><Clock3 className="h-3.5 w-3.5"/>{item.ageHours}h awaiting review</div></button>)}</div>
 {selected&&<div className="mt-4 rounded-2xl border border-amber-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-black text-slate-900">Final handover review · {selected.projectNumber}</div><div className="mt-1 text-[10px] text-slate-500">Prepared by {selected.developerName||'Developer'} · package v{selected.version}</div></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-black text-amber-800">CLIENT RELEASE GATE</span></div>{selected.submissionNote&&<div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><strong>Developer note:</strong> {selected.submissionNote}</div>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(selected.clientPackage||{}).filter(([,value])=>String(value||'').trim()).map(([key,value])=><div key={key} className="rounded-xl border border-slate-100 p-3"><div className="text-[9px] font-black uppercase tracking-wide text-slate-400">{key.replace(/([A-Z])/g,' $1')}</div>{/^https?:\/\//i.test(String(value))?<a href={String(value)} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 break-all text-xs font-bold text-[#000080]">Open reference <ExternalLink className="h-3 w-3"/></a>:<p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-slate-700">{String(value)}</p>}</div>)}</div><div className="mt-4 flex gap-3 rounded-xl border border-amber-100 bg-amber-50/60 p-3 text-[11px] leading-5 text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>Approve only after verifying the production result, documentation/access ownership, final QA/release evidence, support boundary and that no passwords, tokens or private credentials appear in the package.</div>{error&&<div className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">{error}</div>}<label className="mt-4 block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wide text-slate-400">Manager review notes</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs" placeholder="Required for changes; optional approval note."/></label><div className="mt-4 flex flex-wrap justify-end gap-2"><button disabled={running} onClick={()=>setSelected(null)} className="px-3 py-2 text-xs font-bold text-slate-500">Close</button><button disabled={running} onClick={()=>void review('Changes Required')} className="flex items-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-2 text-xs font-black text-amber-800"><RotateCcw className="h-3.5 w-3.5"/> Return Changes</button><button disabled={running} onClick={()=>void review('Approved')} className="flex items-center gap-1.5 rounded-xl bg-[#000080] px-4 py-2 text-xs font-black text-white">{running?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<CheckCircle2 className="h-3.5 w-3.5"/>} Approve & Release to Client</button></div></div>}
 </section>
}
