import React,{useEffect,useState} from 'react';
import { ArrowRight, CalendarPlus, CheckCircle2, Loader2, Target } from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {NextBestAction,productivityService} from '../../lib/productivityService';
import {useAuth} from '../../lib/AuthContext';
import {useConfirmContext} from './ConfirmContext';

function localDateTime(hours=24){const d=new Date(Date.now()+hours*60*60*1000);const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;}

export default function NextBestActionCard({entityType,entityId,onChanged,compact=false}:{entityType:string;entityId:string;onChanged?:()=>void;compact?:boolean}){
 const nav=useNavigate();const {profile}=useAuth();const {confirm}=useConfirmContext();const [action,setAction]=useState<NextBestAction|null>(null);const [loading,setLoading]=useState(true);const [running,setRunning]=useState(false);const [error,setError]=useState('');const [showInput,setShowInput]=useState(false);const [dueAt,setDueAt]=useState(localDateTime());const [subject,setSubject]=useState('Follow up');const [expectedValue,setExpectedValue]=useState('0');
 const load=async()=>{setLoading(true);setError('');try{let next=await productivityService.getNextAction(entityType,entityId);if(next.actionKey==='create_project_from_sale'&&!['admin','project_manager'].includes(profile?.role||'')){next={...next,label:'Delivery handoff queued',actionKey:'open',url:'/admin/app/crm?tab=pipeline',reason:'The verified sale is ready. ProFox has handed project launch to Admin/Project Management so Sales does not need to re-enter delivery data.',quick:false,requiresInput:false,requiresConfirmation:false};}setAction(next);}catch(e:any){setError(e?.message||'Unable to determine the next action.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[entityType,entityId,profile?.role]);
 const run=async()=>{if(!action)return;if(action.actionKey==='open'||(!action.quick&&!action.requiresInput)){nav(action.url);return;}if(action.requiresInput){setShowInput(true);return;}if(action.requiresConfirmation){const ok=await confirm(action.label,action.reason);if(!ok)return;}setRunning(true);setError('');try{await productivityService.executeAction(action.actionKey,entityType,entityId);await load();onChanged?.();}catch(e:any){setError(e?.message||'Action failed.');}finally{setRunning(false);}};
 const submitInput=async()=>{if(!action)return;if(action.requiresConfirmation){const ok=await confirm(action.label,action.reason);if(!ok)return;}setRunning(true);setError('');try{if(action.actionKey==='schedule_follow_up'){const iso=new Date(dueAt).toISOString();await productivityService.executeAction(action.actionKey,entityType,entityId,{dueAt:iso,subject});}else if(action.actionKey==='convert_lead'){await productivityService.executeAction(action.actionKey,entityType,entityId,{expectedValue:Number(expectedValue||0)});}else{throw new Error('This action requires an unsupported input.');}setShowInput(false);await load();onChanged?.();}catch(e:any){setError(e?.message||'Action failed.');}finally{setRunning(false);}};
 if(loading)return <div className={`rounded-2xl border border-slate-200 bg-white ${compact?'p-4':'p-5'}`}><Loader2 className="h-4 w-4 animate-spin text-[#000080]"/></div>;
 if(!action)return null;
 return <div className={`rounded-3xl border border-blue-200 bg-[linear-gradient(135deg,#f8fbff,#ffffff)] shadow-sm ${compact?'p-4':'p-5 sm:p-6'}`}>
   <div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-blue-50 text-[#000080]"><Target className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="text-[10px] font-black uppercase tracking-[0.16em] text-[#FF0E0E]">Next best action</div><h3 className="mt-1 text-base font-black text-slate-900">{action.label}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{action.reason}</p></div></div>
   {error&&<div className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">{error}</div>}
   {!showInput?<button onClick={()=>void run()} disabled={running} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{running?<Loader2 className="h-4 w-4 animate-spin"/>:action.quick?<CheckCircle2 className="h-4 w-4"/>:<ArrowRight className="h-4 w-4"/>}{action.label}</button>:<div className="mt-4 rounded-2xl border border-slate-200 bg-white p-4">
     {action.actionKey==='schedule_follow_up'?<div className="grid gap-3 sm:grid-cols-2"><label className="text-[11px] font-black text-slate-600">Follow-up date & time<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs outline-none focus:border-[#000080]"/></label><label className="text-[11px] font-black text-slate-600">Action<input value={subject} onChange={e=>setSubject(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs outline-none focus:border-[#000080]"/></label></div>:<label className="block text-[11px] font-black text-slate-600">Expected value<input type="number" min="0" step="1" value={expectedValue} onChange={e=>setExpectedValue(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs outline-none focus:border-[#000080]"/></label>}
     <div className="mt-3 flex justify-end gap-2"><button onClick={()=>setShowInput(false)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-slate-500">Cancel</button><button onClick={()=>void submitInput()} disabled={running} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-3 py-2 text-xs font-black text-white disabled:opacity-50">{running?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<CalendarPlus className="h-3.5 w-3.5"/>}Save action</button></div>
   </div>}
 </div>;
}
