import React,{useEffect,useMemo,useRef,useState} from 'react';
import { ArrowRight, Command, LayoutGrid, Loader2, Search, X } from 'lucide-react';
import {useLocation,useNavigate} from 'react-router-dom';
import {useAuth} from '../../lib/AuthContext';
import {getVisibleWorkspaceApps,getWorkspaceAppLaunchPath} from '../../lib/workspaceApps';
import {ProductivitySearchResult,productivityService} from '../../lib/productivityService';
import WorkspaceAppIcon from './workspace/WorkspaceAppIcon';

export default function ProductivityCommandPalette(){
 const location=useLocation();const nav=useNavigate();const {user,profile,role,status}=useAuth();
 const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [results,setResults]=useState<ProductivitySearchResult[]>([]);const [loading,setLoading]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
 const enabled=Boolean(user&&profile?.status==='active'&&!['customer','pending'].includes(profile.role)&&location.pathname.startsWith('/admin'));
 const apps=useMemo(()=>getVisibleWorkspaceApps(role,status),[role,status]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(!enabled)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v);}if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[enabled]);
 useEffect(()=>{if(open)setTimeout(()=>inputRef.current?.focus(),0);else{setQuery('');setResults([]);}},[open]);
 useEffect(()=>{if(!open||query.trim().length<2){setResults([]);return;}let live=true;const timer=setTimeout(async()=>{setLoading(true);try{const rows=await productivityService.search(query,20);if(live)setResults(rows);}catch{if(live)setResults([]);}finally{if(live)setLoading(false);}},220);return()=>{live=false;clearTimeout(timer);};},[query,open]);
 if(!enabled)return null;
 const go=(path:string)=>{setOpen(false);nav(path);};
 return <>{!open&&<button type="button" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-40 hidden items-center gap-2 rounded-2xl border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-black text-slate-600 shadow-xl transition hover:-translate-y-0.5 hover:text-[#000080] md:flex" title="Search or run a command"><Command className="h-4 w-4"/> <span>Ctrl K</span></button>}
 {open&&<div className="fixed inset-0 z-[200] flex items-start justify-center bg-slate-950/55 p-3 pt-[8vh] backdrop-blur-sm sm:p-6 sm:pt-[10vh]" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className="w-full max-w-2xl overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-2xl"><div className="flex items-center gap-3 border-b border-slate-100 px-4 py-3 sm:px-5"><Search className="h-5 w-5 text-slate-400"/><input ref={inputRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything or jump to an app…" className="min-w-0 flex-1 border-0 bg-transparent py-2 text-base font-semibold outline-none placeholder:font-normal placeholder:text-slate-400"/>{loading?<Loader2 className="h-4 w-4 animate-spin text-[#000080]"/>:<kbd className="hidden rounded-lg border border-slate-200 bg-slate-50 px-2 py-1 text-[10px] font-bold text-slate-400 sm:block">ESC</kbd>}<button onClick={()=>setOpen(false)} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4"/></button></div>
 <div className="max-h-[65vh] overflow-y-auto p-3">
  {query.trim().length<2?<><div className="px-2 pb-2 text-[10px] font-black uppercase tracking-widest text-slate-400">Work now</div><button onClick={()=>go('/admin/today')} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-blue-50"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-[#000080]"><Command className="h-5 w-5"/></div><div className="flex-1"><div className="text-sm font-black">Today's priorities</div><div className="text-xs text-slate-400">See the highest-value work across your role.</div></div><ArrowRight className="h-4 w-4 text-slate-300"/></button><button onClick={()=>go('/admin/workspace')} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-600"><LayoutGrid className="h-5 w-5"/></div><div className="flex-1"><div className="text-sm font-black">All apps</div><div className="text-xs text-slate-400">Open the complete ProFox workspace.</div></div><ArrowRight className="h-4 w-4 text-slate-300"/></button><div className="mt-4 px-2 pb-2 text-[10px] font-black uppercase tracking-widest text-slate-400">Jump to an app</div><div className="grid grid-cols-1 gap-1 sm:grid-cols-2">{apps.map(app=><button key={app.id} onClick={()=>go(getWorkspaceAppLaunchPath(app,role,status))} className="flex items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><div className={`flex h-9 w-9 items-center justify-center rounded-xl border ${app.iconBackgroundClass}`}><WorkspaceAppIcon name={app.icon} className={`h-4.5 w-4.5 ${app.iconClass}`}/></div><div className="min-w-0"><div className="truncate text-sm font-black">{app.shortLabel}</div><div className="truncate text-[11px] text-slate-400">{app.description}</div></div></button>)}</div></>:results.length>0?<><div className="px-2 pb-2 text-[10px] font-black uppercase tracking-widest text-slate-400">Connected records</div>{results.map(r=><button key={`${r.entityType}:${r.entityId}`} onClick={()=>go(`/admin/focus/${r.entityType}/${r.entityId}`)} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-blue-50"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-[10px] font-black uppercase text-slate-500">{r.entityType.slice(0,3)}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-black">{r.title}</div><div className="truncate text-xs text-slate-400">{r.subtitle}</div></div><ArrowRight className="h-4 w-4 text-slate-300"/></button>)}</>:!loading&&<div className="px-6 py-12 text-center"><Search className="mx-auto h-8 w-8 text-slate-200"/><div className="mt-3 text-sm font-black text-slate-600">No matching records</div><div className="mt-1 text-xs text-slate-400">Try a company, contact, project, quotation or candidate name.</div></div>}
 </div><div className="border-t border-slate-100 bg-slate-50 px-5 py-2.5 text-[10px] font-semibold text-slate-400">Search respects your existing role, ownership and RLS permissions.</div></div></div>}</>;
}
