import React, { useEffect, useState } from 'react';
import { CheckCircle2, Copy, Landmark, Loader2, RefreshCw, Save, XCircle } from 'lucide-react';
import { RazorpayXPayoutStatus, razorpayxPayoutService } from '../../lib/razorpayxPayoutService';
import WorkerPayoutVerificationAdmin from './WorkerPayoutVerificationAdmin';

const fieldClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL || '').replace(/\/$/, '');

export default function RazorpayXPayoutAdmin() {
  const [status, setStatus] = useState<RazorpayXPayoutStatus | null>(null);
  const [draft, setDraft] = useState({ enabled: false, mode: 'test' as 'test'|'live', keyId: '', apiSecret: '', accountNumber: '', webhookSecret: '', defaultBankMode: 'IMPS' as 'IMPS'|'NEFT'|'RTGS', queueIfLowBalance: true });
  const [busy, setBusy] = useState('load'); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const webhookUrl = `${SUPABASE_URL}/functions/v1/payout-webhook-razorpay`;
  const hydrate = (next: RazorpayXPayoutStatus) => { setStatus(next); setDraft(current => ({ ...current, enabled: !!next.enabled, mode: next.mode || 'test', keyId: next.keyId || '', apiSecret: '', accountNumber: '', webhookSecret: '', defaultBankMode: next.defaultBankMode || 'IMPS', queueIfLowBalance: next.queueIfLowBalance !== false })); };
  const load = async () => { setBusy('load'); setError(''); try { hydrate(await razorpayxPayoutService.getStatus()); } catch (e: any) { setError(e?.message || 'RazorpayX settings could not be loaded.'); } finally { setBusy(''); } };
  useEffect(() => { void load(); }, []);
  const save = async () => { setBusy('save'); setError(''); setMessage(''); try { hydrate(await razorpayxPayoutService.saveSettings(draft)); setMessage('RazorpayX payout settings saved securely. Secret values and the source account number were cleared from this screen.'); } catch (e: any) { setError(e?.message || 'RazorpayX settings could not be saved.'); } finally { setBusy(''); } };
  const test = async () => { setBusy('test'); setError(''); setMessage(''); try { const result = await razorpayxPayoutService.testConnection(); setMessage(result.message); await load(); } catch (e: any) { setError(e?.message || 'RazorpayX connection test failed.'); } finally { setBusy(''); } };
  const copy = async () => { try { await navigator.clipboard.writeText(webhookUrl); } catch { /* clipboard may be blocked */ } };
  return <>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-50 p-3 text-emerald-700"><Landmark className="h-5 w-5" /></div><div><h2 className="font-black">RazorpayX · Employee bulk payouts</h2><p className="mt-1 text-xs text-slate-500">Separate from client Checkout. Sends existing approved INR worker payout batches to verified bank or UPI destinations.</p><div className="mt-2 flex flex-wrap gap-2"><Badge ok={!!status?.configured}>API + source account</Badge><Badge ok={!!status?.webhookConfigured}>Payout webhook</Badge><Badge ok={!!status?.lastTestSuccess}>Connection test</Badge><Badge ok={!!status?.ready}>{status?.ready ? 'Ready to send' : 'Not ready'}</Badge></div></div></div>{status?.lastTestAt && <div className="text-right text-[10px] text-slate-500"><div className={status.lastTestSuccess ? 'font-bold text-emerald-600' : 'font-bold text-red-600'}>{status.lastTestSuccess ? 'Last test passed' : 'Last test failed'}</div><div>{new Date(status.lastTestAt).toLocaleString()}</div></div>}</div>
      {error && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}{message && <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">{message}</div>}
      {busy === 'load' && !status ? <div className="flex justify-center p-8"><Loader2 className="h-6 w-6 animate-spin" /></div> : <><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Mode"><select className={fieldClass} value={draft.mode} onChange={e => setDraft({ ...draft, mode: e.target.value as 'test'|'live', enabled: false, keyId: '' })}><option value="test">Test</option><option value="live">Live</option></select></Field><Field label="Key ID"><input className={fieldClass} value={draft.keyId} onChange={e => setDraft({ ...draft, keyId: e.target.value })} placeholder={`rzp_${draft.mode}_...`} /></Field><Field label="API Secret · write only"><input type="password" autoComplete="new-password" className={fieldClass} value={draft.apiSecret} onChange={e => setDraft({ ...draft, apiSecret: e.target.value })} placeholder={status?.configured ? 'Stored — enter only to replace' : 'Enter RazorpayX API Secret'} /></Field><Field label="Source account number · write only"><input className={fieldClass} inputMode="numeric" autoComplete="off" value={draft.accountNumber} onChange={e => setDraft({ ...draft, accountNumber: e.target.value.replace(/\D/g, '') })} placeholder={status?.accountNumberLast4 ? `Stored ending ${status.accountNumberLast4}` : 'RazorpayX account number'} /></Field><Field label="Payout webhook secret · write only"><input type="password" autoComplete="new-password" className={fieldClass} value={draft.webhookSecret} onChange={e => setDraft({ ...draft, webhookSecret: e.target.value })} placeholder={status?.webhookConfigured ? 'Stored — enter only to replace' : 'Enter payout webhook secret'} /></Field><Field label="Default bank rail"><select className={fieldClass} value={draft.defaultBankMode} onChange={e => setDraft({ ...draft, defaultBankMode: e.target.value as 'IMPS'|'NEFT'|'RTGS' })}><option>IMPS</option><option>NEFT</option><option>RTGS</option></select></Field></div>
      <div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">RazorpayX payout webhook URL</div><div className="mt-2 flex items-center gap-2"><code className="min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap text-xs">{webhookUrl}</code><button onClick={() => void copy()} className="rounded-lg border border-slate-200 bg-white p-2"><Copy className="h-4 w-4" /></button></div><p className="mt-2 text-[10px] text-slate-500">Subscribe to payout.processed, payout.failed and payout.reversed. Use the same secret entered above.</p></div>
      <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="space-y-2"><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={draft.queueIfLowBalance} onChange={e => setDraft({ ...draft, queueIfLowBalance: e.target.checked })} />Queue when balance is low</label><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={draft.enabled} disabled={!status?.configured || !status?.webhookConfigured} onChange={e => setDraft({ ...draft, enabled: e.target.checked })} />Enable employee payouts</label></div><div className="flex gap-2"><button onClick={() => void test()} disabled={!!busy || !status?.configured} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-black disabled:opacity-40">{busy === 'test' ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}Test Connection</button><button onClick={() => void save()} disabled={!!busy} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{busy === 'save' ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save Payout Settings</button></div></div></>}
    </section>
    <WorkerPayoutVerificationAdmin />
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span>{children}</label>; }
function Badge({ ok, children }: { ok: boolean; children: React.ReactNode }) { return <span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[10px] font-black ${ok ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-slate-50 text-slate-500'}`}>{ok ? <CheckCircle2 className="h-3 w-3" /> : <XCircle className="h-3 w-3" />}{children}</span>; }
