import { useEffect, useState } from 'react';
import { CheckCircle2, Eye, EyeOff, Landmark, Loader2, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type ProfileRow = {
  id:string; partnerUserId:string; partnerCode:string; partnerName:string; partnerEmail:string;
  payoutMethod:string; preferredCurrency:string; countryCode?:string; status:string; detailsVersion:number;
  maskedDetails:Record<string,string>; verificationMode:string; verificationReference?:string;
  submittedAt?:string; verifiedAt?:string; rejectedAt?:string; rejectionReason?:string; approvedUnpaidRewards:number;
};

export default function TalentPartnerPayoutVerification(){
  const[rows,setRows]=useState<ProfileRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[message,setMessage]=useState('');
  const[reasons,setReasons]=useState<Record<string,string>>({});const[references,setReferences]=useState<Record<string,string>>({});
  const[revealed,setRevealed]=useState<Record<string,any>>({});const[busy,setBusy]=useState<Record<string,boolean>>({});

  const load=async()=>{setLoading(true);setError('');const{data,error:rpcError}=await supabase.rpc('admin_list_talent_partner_payout_profiles');if(rpcError)setError(rpcError.message||'Could not load payout verification queue.');else setRows((data||[]) as ProfileRow[]);setLoading(false)};
  useEffect(()=>{void load()},[]);
  const run=async(id:string,action:()=>Promise<void>,success:string)=>{setBusy(v=>({...v,[id]:true}));setError('');setMessage('');try{await action();setMessage(success);await load()}catch(err:any){setError(err?.message||'Action failed.')}finally{setBusy(v=>({...v,[id]:false}))}};

  const reveal=(row:ProfileRow)=>run(row.id,async()=>{const reason=(reasons[row.id]||'').trim();if(reason.length<10)throw new Error('Enter a clear access reason of at least 10 characters.');const{data,error:rpcError}=await supabase.rpc('admin_reveal_talent_partner_payout_profile',{p_profile_id:row.id,p_reason:reason});if(rpcError)throw rpcError;setRevealed(v=>({...v,[row.id]:data}))},'Sensitive payout details revealed for this review session. The access was audited.');
  const review=(row:ProfileRow,decision:'Verified'|'Rejected')=>run(row.id,async()=>{const reason=(reasons[row.id]||'').trim();const reference=(references[row.id]||'').trim();if(decision==='Verified'&&!revealed[row.id])throw new Error('Reveal and review the current payout details first.');const{error:rpcError}=await supabase.rpc('admin_review_talent_partner_payout_profile',{p_profile_id:row.id,p_decision:decision,p_reason:decision==='Rejected'?reason:null,p_verification_reference:decision==='Verified'?reference:null});if(rpcError)throw rpcError;setRevealed(v=>{const n={...v};delete n[row.id];return n})},decision==='Verified'?'Payout profile verified.':'Payout profile rejected and returned to the partner.');

  if(loading&&!rows.length)return <div className="flex min-h-[45vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
  const pending=rows.filter(r=>r.status==='Verification Pending').length;
  return <div className="min-h-screen bg-[#f5f7fb] p-4 text-slate-900 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1400px]">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#FF0E0E]">Talent Partners · Finance control</div><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Payout verification</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Review encrypted payout profiles only after partners have approved rewards. Revealing details is audited; verification requires a recent reveal plus a verification reference.</p></div><button onClick={load} className="btn-light"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-3"><Kpi label="Profiles" value={rows.length}/><Kpi label="Pending verification" value={pending}/><Kpi label="Verified" value={rows.filter(r=>r.status==='Verified').length}/></div>
    {error&&<Alert tone="error">{error}</Alert>}{message&&<Alert tone="success">{message}</Alert>}
    <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-800"><strong>PayPal India:</strong> standard PayPal Payouts API outbound/bulk sends are not enabled for an India merchant under PayPal's country-support matrix. PayPal profiles here are therefore manually verified and manually settled; this screen does not claim automatic PayPal transfer or automatic provider verification.</div>
    <div className="mt-6 space-y-4">{rows.map(row=>{const open=revealed[row.id];const masked=row.maskedDetails||{};return <article key={row.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">{row.partnerName||'Talent Partner'}</h2><span className="text-xs font-black text-[#000080]">{row.partnerCode}</span><Status value={row.status}/></div><div className="mt-1 text-xs text-slate-500">{row.partnerEmail} · {row.payoutMethod} · {row.preferredCurrency}{row.countryCode?` · ${row.countryCode}`:''} · version {row.detailsVersion}</div><div className="mt-1 text-xs text-slate-500">{row.approvedUnpaidRewards||0} approved unpaid reward entries</div></div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[#000080]"/><span className="text-[10px] font-black uppercase text-slate-400">Encrypted at rest</span></div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(masked).filter(([,v])=>Boolean(v)).map(([k,v])=><Mini key={k} label={labelFor(k)} value={String(v)}/>)}</div>
      {row.rejectionReason&&<Alert tone="error"><strong>Previous rejection:</strong> {row.rejectionReason}</Alert>}
      <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto]"><input className="input" value={reasons[row.id]||''} onChange={e=>setReasons(v=>({...v,[row.id]:e.target.value}))} placeholder="Access/rejection reason — required to reveal or reject"/><button disabled={busy[row.id]} onClick={()=>open?setRevealed(v=>{const n={...v};delete n[row.id];return n}):reveal(row)} className="btn-light">{open?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}{open?'Hide sensitive details':'Reveal for review'}</button></div>
      {open&&<div className="mt-4 rounded-2xl border border-red-100 bg-red-50/40 p-4"><div className="flex items-center gap-2 text-xs font-black text-red-700"><Landmark className="h-4 w-4"/>Sensitive financial details — do not copy into notes or chat</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(open.details||{}).map(([k,v])=><div key={k} className="rounded-xl bg-white p-3"><div className="text-[9px] font-black uppercase text-slate-400">{labelFor(k)}</div><div className="mt-1 break-all text-sm font-bold text-slate-800">{String(v||'—')}</div></div>)}</div></div>}
      <div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto_auto]"><input className="input" value={references[row.id]||''} onChange={e=>setReferences(v=>({...v,[row.id]:e.target.value}))} placeholder="Verification reference / review evidence (required to verify)"/><button disabled={busy[row.id]||!open||!(references[row.id]||'').trim()} onClick={()=>review(row,'Verified')} className="btn-primary"><CheckCircle2 className="h-4 w-4"/>Verify</button><button disabled={busy[row.id]||!(reasons[row.id]||'').trim()} onClick={()=>review(row,'Rejected')} className="btn-danger"><XCircle className="h-4 w-4"/>Reject</button></div>
    </article>})}{!rows.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No Talent Partner payout profiles have been submitted yet.</div>}</div>
  </div></div>;
}

function Kpi({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-[10px] font-black uppercase text-slate-400">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] font-black uppercase text-slate-400">{label}</div><div className="mt-1 break-all text-xs font-bold">{value}</div></div>}
function Status({value}:{value:string}){const l=value.toLowerCase();const c=l==='verified'?'border-emerald-200 bg-emerald-50 text-emerald-700':l==='rejected'?'border-red-200 bg-red-50 text-red-700':'border-amber-200 bg-amber-50 text-amber-800';return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-black ${c}`}>{value}</span>}
function Alert({tone,children}:{tone:'error'|'success';children:any}){const c=tone==='error'?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700';return <div className={`mt-4 rounded-xl border p-4 text-sm ${c}`}>{children}</div>}
function labelFor(key:string){return ({accountHolderName:'Account holder',paypalEmail:'PayPal email',wiseEmail:'Wise email',bankName:'Bank',accountNumber:'Account / IBAN',routingType:'Routing type',routingCode:'Routing code',accountType:'Account type',paymentInstructions:'Instructions'} as Record<string,string>)[key]||key.replace(/([A-Z])/g,' $1')}
