import React,{useEffect,useMemo,useState}from'react';
import{Navigate}from'react-router-dom';
import{AlertCircle,ArrowRight,BriefcaseBusiness,CalendarClock,CheckCircle2,Clock3,ExternalLink,FileText,Loader2,RefreshCw,ShieldCheck,UserCheck,XCircle}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{uiuxPeopleService,type UIUXApplicant,type UIUXStagePolicy}from'../../lib/uiuxPeopleService';

const field='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const fmt=(v?:string)=>v?new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'Not recorded';

export default function UIUXRecruitmentWorkspace(){
 const{isAdmin,user,loading:authLoading}=useAuth();
 const[applicants,setApplicants]=useState<UIUXApplicant[]>([]),[policies,setPolicies]=useState<UIUXStagePolicy[]>([]),[job,setJob]=useState<any>(null);
 const[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showClosed,setShowClosed]=useState(false);
 const load=async(preferred?:string)=>{setLoading(true);setError('');try{const j=await uiuxPeopleService.getJob();setJob(j);if(!j?.id){setApplicants([]);setPolicies([]);return}const[a,p]=await Promise.all([uiuxPeopleService.getApplicants(),uiuxPeopleService.getPolicies(j.id)]);setApplicants(a);setPolicies(p);const visible=a.filter(x=>showClosed||!x.refusalReason);const id=preferred&&a.some(x=>x.id===preferred)?preferred:selectedId&&a.some(x=>x.id===selectedId)?selectedId:visible[0]?.id||'';setSelectedId(id)}catch(e:any){setError(e?.message||'UI/UX recruitment could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{if(isAdmin)void load()},[isAdmin]);
 const visible=useMemo(()=>applicants.filter(a=>showClosed||!a.refusalReason),[applicants,showClosed]);
 const selected=applicants.find(a=>a.id===selectedId)||null;
 if(authLoading)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#000080]"/></div>;
 if(!isAdmin)return <Navigate to="/admin/workspace" replace/>;
 return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-5"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">People · UI/UX Design</div><h1 className="mt-1 text-2xl font-black">UI/UX Designer Hiring & Activation</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">One canonical candidate record from application and portfolio evidence through assessment, interview, agreement, Design Academy, Final Approval and production activation.</p></div><div className="flex gap-2"><a href="/careers/ui-ux-designer" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-[#000080]">Job page <ExternalLink className="h-4 w-4"/></a><button onClick={()=>void load()} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-500"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div></header>
 <div className="mx-auto max-w-7xl p-4 sm:p-7">{error&&<div className="mb-4 flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle className="h-4 w-4"/>{error}</div>}
 <div className="mb-5 grid gap-3 sm:grid-cols-4"><Metric label="Applications" value={applicants.length}/><Metric label="In hiring" value={applicants.filter(a=>!a.refusalReason&&a.stage!=='Activated').length}/><Metric label="Design Academy" value={applicants.filter(a=>a.stage==='Design Academy'&&!a.refusalReason).length}/><Metric label="Activated" value={applicants.filter(a=>a.stage==='Activated').length} success/></div>
 <label className="mb-4 inline-flex items-center gap-2 text-xs font-bold text-slate-500"><input type="checkbox" checked={showClosed} onChange={e=>setShowClosed(e.target.checked)} className="accent-[#000080]"/>Show closed candidates</label>
 {loading&&!applicants.length?<div className="flex justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>:<div className="grid gap-5 xl:grid-cols-[330px_1fr]">
   <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-3 shadow-sm xl:sticky xl:top-4"><div className="px-3 py-2 text-[10px] font-black uppercase tracking-[.15em] text-slate-400">Candidates</div><div className="max-h-[75vh] space-y-2 overflow-y-auto">{visible.map(a=><button key={a.id} onClick={()=>setSelectedId(a.id)} className={`w-full rounded-2xl border p-4 text-left transition ${a.id===selectedId?'border-blue-200 bg-blue-50':'border-transparent hover:bg-slate-50'}`}><div className="flex justify-between gap-2"><div className="min-w-0"><div className="truncate text-sm font-black">{a.fullName}</div><div className="mt-0.5 truncate text-[10px] text-slate-400">{a.applicationReference}</div></div>{a.stage==='Activated'?<UserCheck className="h-4 w-4 text-emerald-600"/>:null}</div><div className="mt-3 rounded-lg bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{a.stage}</div>{a.refusalReason&&<div className="mt-2 text-[10px] font-bold text-red-600">Closed · {a.refusalReason}</div>}</button>)}{!visible.length&&<div className="py-10 text-center text-xs text-slate-400">No candidates yet.</div>}</div></aside>
   <section>{selected?<CandidatePanel applicant={selected} policies={policies} adminId={user?.id||''} onChanged={()=>load(selected.id)}/>:<div className="rounded-3xl border border-dashed border-slate-300 bg-white py-24 text-center"><BriefcaseBusiness className="mx-auto h-9 w-9 text-slate-300"/><p className="mt-3 text-sm font-bold text-slate-500">Select a candidate to review the complete hiring record.</p></div>}</section>
 </div>}</div></main>
}

function CandidatePanel({applicant,policies,adminId,onChanged}:{applicant:UIUXApplicant;policies:UIUXStagePolicy[];adminId:string;onChanged:()=>Promise<void>}){
 const[snapshot,setSnapshot]=useState<any>(null),[assessments,setAssessments]=useState<any[]>([]),[interviews,setInterviews]=useState<any[]>([]),[timeline,setTimeline]=useState<any[]>([]),[meta,setMeta]=useState<any>({}),[cvUrl,setCvUrl]=useState('');
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[status,setStatus]=useState<'Passed'|'Failed'|'Retry Required'>('Passed'),[scores,setScores]=useState<Record<string,number>>({}),[evidence,setEvidence]=useState(''),[evidenceUrl,setEvidenceUrl]=useState(''),[notes,setNotes]=useState(''),[critical,setCritical]=useState('');
 const[interviewAt,setInterviewAt]=useState(''),[interviewMinutes,setInterviewMinutes]=useState(45),[meetingUrl,setMeetingUrl]=useState(''),[closeReason,setCloseReason]=useState(''),[closeNotes,setCloseNotes]=useState('');
 const policy=policies.find(p=>p.stage===applicant.stage); const next=policies.filter(p=>p.sortOrder>(policy?.sortOrder||0)).sort((a,b)=>a.sortOrder-b.sortOrder)[0]?.stage;
 const currentAssessments=assessments.filter(a=>a.stage===applicant.stage);const latest=currentAssessments[0];
 const currentInterviews=interviews.filter(i=>i.stage===applicant.stage);const interviewDone=currentInterviews.some(i=>i.status==='Completed');
 const rubricMax=(policy?.rubric||[]).reduce((s,r)=>s+r.maxPoints,0),rubricPoints=(policy?.rubric||[]).reduce((s,r)=>s+Math.max(0,Number(scores[r.key]||0)),0),score=rubricMax?Math.round(rubricPoints/rubricMax*100):0;
 const stageHours=meta.stageEnteredAt?Math.max(0,(Date.now()-new Date(meta.stageEnteredAt).getTime())/3600000):0,overdue=Boolean(policy?.slaHours&&stageHours>=policy.slaHours);
 const load=async()=>{setError('');try{const[s,a,i,t,m,cv]=await Promise.all([uiuxPeopleService.getSnapshot(applicant.id),uiuxPeopleService.getAssessments(applicant.id),uiuxPeopleService.getInterviews(applicant.id),uiuxPeopleService.getTimeline(applicant.id),uiuxPeopleService.getWorkflowMeta(applicant.id),uiuxPeopleService.getSecureCv(applicant.cvStoragePath).catch(()=>applicant.cvUrl||'')]);setSnapshot(s);setAssessments(a);setInterviews(i);setTimeline(t);setMeta(m);setCvUrl(cv||applicant.cvUrl||'')}catch(e:any){setError(e?.message||'Candidate details could not be loaded.')}};
 useEffect(()=>{void load()},[applicant.id,applicant.stage]);
 const run=async(fn:()=>Promise<any>,message:string)=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);await onChanged();await load()}catch(e:any){setError(e?.message||'Action failed.')}finally{setBusy(false)}};
 const record=()=>run(()=>uiuxPeopleService.recordAssessment({applicantId:applicant.id,stage:applicant.stage,status,score,rubricScores:scores,criticalFailures:critical.split('\n').map(x=>x.trim()).filter(Boolean),evidence,evidenceUrl,notes}),'Structured assessment recorded.');
 const schedule=()=>{if(!interviewAt)return;const start=new Date(interviewAt),end=new Date(start.getTime()+Math.max(15,interviewMinutes)*60000);return run(()=>uiuxPeopleService.scheduleInterview({applicantId:applicant.id,startAt:start.toISOString(),endAt:end.toISOString(),timezone:applicant.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,meetingUrl,interviewerId:adminId||null}),'Design interview scheduled.')};
 const completeInterview=(i:any)=>run(()=>uiuxPeopleService.updateInterview({interviewId:i.id,status:'Completed',outcomeNotes:notes||'Structured interview completed.',meetingUrl:i.meetingUrl||i.meeting_url||meetingUrl||null}),'Interview marked completed.');
 const assessmentPassed=!policy?.assessmentRequired||latest?.status==='Passed',interviewPassed=!policy?.interviewRequired||interviewDone;
 return <div className="space-y-4">
  <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#FF0E0E]">{applicant.applicationReference||'Candidate'}</div><h2 className="mt-1 text-2xl font-black">{applicant.fullName}</h2><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-bold"><Tag>{applicant.stage}</Tag><Tag>{applicant.country||'Country not set'}</Tag><Tag>{applicant.timezone||'Timezone not set'}</Tag><Tag>{applicant.availableHoursPerWeek||0}h/week</Tag></div></div><div className={`h-fit rounded-xl border px-3 py-2 text-xs font-black ${overdue?'border-red-200 bg-red-50 text-red-700':'border-slate-200 bg-slate-50 text-slate-500'}`}><Clock3 className="mr-1 inline h-4 w-4"/>Stage {Math.round(stageHours)}h · SLA {policy?.slaHours||0}h</div></div>
   {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}{notice&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700">{notice}</div>}
  </div>

  <div className="grid gap-4 lg:grid-cols-2"><Card title="Application & portfolio"><Key label="Email" value={applicant.email}/><Key label="LinkedIn" value={applicant.linkedinUrl} link/><Key label="Portfolio" value={applicant.portfolioUrl} link/><Key label="CV / resume" value={cvUrl} link/><Key label="Submitted" value={fmt(applicant.applicationSubmittedAt||applicant.createdAt)}/>{Object.entries(applicant.applicationAnswers||{}).filter(([,v])=>String(v||'').trim()).map(([k,v])=><div key={k} className="border-t border-slate-100 py-2"><div className="text-[9px] font-black uppercase tracking-wide text-slate-400">{human(k)}</div><div className="mt-1 whitespace-pre-wrap text-xs leading-5 text-slate-700">{String(v)}</div></div>)}</Card>
   <Card title="Application readiness">{snapshot?.checks?.map((c:any)=><div key={c.key} className="flex items-start gap-2 border-b border-slate-100 py-2 last:border-0">{c.passed?<CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/>:<XCircle className="mt-0.5 h-4 w-4 shrink-0 text-red-500"/>}<div><div className="text-xs font-bold text-slate-700">{c.label}</div>{c.detail&&<div className="text-[10px] text-slate-400">{c.detail}</div>}</div></div>)}<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs font-black text-[#000080]">Completeness {Number(snapshot?.completenessPercent||0)}%</div></Card></div>

  {policy?.assessmentRequired&&<Card title={`${applicant.stage} · structured assessment`}><div className="grid gap-3 sm:grid-cols-2">{policy.rubric.map(r=><label key={r.key}><span className="mb-1 block text-[10px] font-black text-slate-500">{r.label} · /{r.maxPoints}</span><input type="number" min={0} max={r.maxPoints} className={field} value={scores[r.key]??''} onChange={e=>setScores({...scores,[r.key]:Math.min(r.maxPoints,Math.max(0,Number(e.target.value||0)))})}/></label>)}</div><div className="mt-4 flex items-center justify-between rounded-xl bg-blue-50 p-3 text-xs"><span className="font-bold text-slate-600">Calculated score</span><strong className="text-lg text-[#000080]">{score}%</strong></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><select className={field} value={status} onChange={e=>setStatus(e.target.value as any)}><option>Passed</option><option>Retry Required</option><option>Failed</option></select><input className={field} placeholder="Evidence URL (Figma/case study if applicable)" value={evidenceUrl} onChange={e=>setEvidenceUrl(e.target.value)}/></div><textarea className={`${field} mt-3`} rows={2} placeholder="Evidence reviewed" value={evidence} onChange={e=>setEvidence(e.target.value)}/><textarea className={`${field} mt-3`} rows={2} placeholder="Critical failures, one per line (if any)" value={critical} onChange={e=>setCritical(e.target.value)}/><textarea className={`${field} mt-3`} rows={2} placeholder="Evaluator notes" value={notes} onChange={e=>setNotes(e.target.value)}/><button disabled={busy||rubricMax===0} onClick={()=>void record()} className="mt-4 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-40">Record assessment</button>{latest&&<div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs"><strong>Latest:</strong> {latest.status} · {Number(latest.score||0)}%</div>}</Card>}

  {policy?.interviewRequired&&<Card title="Structured Design Interview">{currentInterviews.length?<div className="space-y-2">{currentInterviews.map((i:any)=><div key={i.id} className="rounded-xl border border-slate-200 p-3 text-xs"><div className="font-black">{i.status} · {fmt(i.startAt||i.start_at)}</div>{(i.meetingUrl||i.meeting_url)&&<a className="mt-1 inline-block font-bold text-[#000080]" target="_blank" rel="noreferrer" href={i.meetingUrl||i.meeting_url}>Open meeting</a>}{i.status!=='Completed'&&<button onClick={()=>void completeInterview(i)} disabled={busy} className="ml-3 font-black text-emerald-700">Mark completed</button>}</div>)}</div>:null}<div className="mt-4 grid gap-3 sm:grid-cols-3"><input type="datetime-local" className={field} value={interviewAt} onChange={e=>setInterviewAt(e.target.value)}/><input type="number" min={15} step={15} className={field} value={interviewMinutes} onChange={e=>setInterviewMinutes(Number(e.target.value||45))}/><input className={field} placeholder="Meeting URL" value={meetingUrl} onChange={e=>setMeetingUrl(e.target.value)}/></div><button disabled={busy||!interviewAt} onClick={()=>void schedule()} className="mt-3 inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-[#000080] disabled:opacity-40"><CalendarClock className="h-4 w-4"/>Schedule interview</button></Card>}

  <Card title="Protected next action"><div className="flex flex-wrap items-center gap-2">
   {applicant.stage==='Selected'&&<Action onClick={()=>run(()=>uiuxPeopleService.issueAgreement(applicant.id),'UI/UX Designer agreement issued.')}>Issue Designer Agreement</Action>}
   {applicant.stage==='Agreement Pending'&&applicant.agreementStatus==='signed'&&<Action onClick={()=>run(()=>uiuxPeopleService.sendAcademyAccess(applicant.id),'Design Academy account invitation sent.')}>Send Design Academy Access</Action>}
   {applicant.stage==='Agreement Pending'&&applicant.agreementStatus!=='signed'&&<a href="/admin/agreements" className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-xs font-black text-[#000080]">Open Agreement Review</a>}
   {applicant.stage==='Final Approval'&&<Action onClick={()=>run(()=>uiuxPeopleService.finalApprove(applicant.id),'Final Approval granted. Candidate is ready for system activation.')}>Grant Final Approval</Action>}
   {applicant.stage==='Ready for System Access'&&applicant.linkedUserId&&<Action onClick={()=>run(()=>uiuxPeopleService.activate(applicant.linkedUserId as string),'UI/UX Designer activated.')}>Activate Designer Account</Action>}
   {!['Selected','Agreement Pending','Design Academy','Final Approval','Ready for System Access','Activated'].includes(applicant.stage)&&next&&<Action disabled={!assessmentPassed||!interviewPassed} onClick={()=>run(()=>uiuxPeopleService.advance(applicant.id),`Candidate advanced to ${next}.`)}>Advance to {next} <ArrowRight className="h-3.5 w-3.5"/></Action>}
   {applicant.stage==='Design Academy'&&<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-2.5 text-xs font-bold text-amber-800">Waiting for the candidate to complete Design Academy and request Final Approval.</div>}
   {applicant.stage==='Activated'&&<div className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-black text-emerald-700"><UserCheck className="h-4 w-4"/>Active UI/UX Designer · production My Work unlocked</div>}
  </div>{(!assessmentPassed||!interviewPassed)&&<p className="mt-3 text-[10px] font-bold text-amber-700">Progression stays locked until the current required assessment/interview gate passes.</p>}</Card>

  {!applicant.refusalReason&&applicant.stage!=='Activated'&&<Card title="Close candidate"><div className="grid gap-3 sm:grid-cols-[1fr_2fr_auto]"><input className={field} placeholder="Reason" value={closeReason} onChange={e=>setCloseReason(e.target.value)}/><input className={field} placeholder="Internal closure notes" value={closeNotes} onChange={e=>setCloseNotes(e.target.value)}/><button disabled={busy||closeReason.trim().length<3} onClick={()=>void run(()=>uiuxPeopleService.close(applicant.id,closeReason,closeNotes),'Candidate closed and pending onboarding access/communications handled.')} className="rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-xs font-black text-red-700 disabled:opacity-40">Close</button></div></Card>}

  <Card title="Audit timeline"><div className="max-h-72 space-y-2 overflow-y-auto">{timeline.slice(0,40).map((e:any)=><div key={e.id} className="border-l-2 border-slate-200 pl-3"><div className="text-xs font-black text-slate-700">{e.title}</div><div className="text-[10px] text-slate-400">{fmt(e.occurredAt||e.occurred_at)} · {e.actor||e.actorType||'System'}</div>{e.detail&&<div className="mt-1 text-[10px] leading-4 text-slate-500">{e.detail}</div>}</div>)}{!timeline.length&&<div className="text-xs text-slate-400">No timeline events yet.</div>}</div></Card>
 </div>
}

function Metric({label,value,success}:{label:string;value:number;success?:boolean}){return <div className={`rounded-2xl border p-4 ${success?'border-emerald-200 bg-emerald-50':'border-slate-200 bg-white'}`}><div className="text-[9px] font-black uppercase tracking-[.14em] text-slate-400">{label}</div><div className={`mt-1 text-2xl font-black ${success?'text-emerald-700':'text-slate-900'}`}>{value}</div></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 border-b border-slate-100 pb-3"><ShieldCheck className="h-4 w-4 text-[#000080]"/><h3 className="text-sm font-black">{title}</h3></div>{children}</section>}
function Tag({children}:{children:React.ReactNode}){return <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-slate-600">{children}</span>}
function Key({label,value,link}:{label:string;value?:string;link?:boolean}){return <div className="flex items-start justify-between gap-3 border-b border-slate-100 py-2 text-xs"><span className="font-bold text-slate-400">{label}</span>{value?(link?<a href={value} target="_blank" rel="noreferrer" className="max-w-[65%] truncate font-black text-[#000080]">Open <ExternalLink className="inline h-3 w-3"/></a>:<span className="max-w-[65%] text-right font-bold text-slate-700">{value}</span>):<span className="text-slate-300">—</span>}</div>}
function Action({children,onClick,disabled}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{children}</button>}
function human(v:string){return v.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}
