import React from'react';

type Agreement={agreementNumber?:string;templateVersion?:number;status?:string;agreementType?:string;targetRole?:string;targetDepartment?:string;partner?:any;company?:any;commercial?:any;training?:any;hiring?:any;template?:any;documentHash?:string;partnerSignedAt?:string;companySignerName?:string;companySignerTitle?:string;companySignedAt?:string;verifiedAt?:string};
const money=(value:any,currency='USD')=>{const n=Number(value);if(!Number.isFinite(n))return String(value||'');return new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:0}).format(n)};
const rate=(v:any)=>`${Number(v||0)}%`;
const labelFor=(agreement:Agreement)=>{const role=agreement.targetRole||agreement.hiring?.systemRole||agreement.agreementType||'sales';if(['developer','web_developer','developer_designer','web_developer_contractor'].includes(role))return'Web Developer';if(['uiux_designer','uiux_designer_contractor'].includes(role))return'UI/UX Designer';return'Sales Partner'};
const academyFor=(track:string,roleLabel:string)=>track==='web_development'?'Developer Academy':track==='uiux_design'?'Design Academy':track==='sales'?'Sales Academy':`${roleLabel} Academy`;

export default function SalesPartnerAgreementDocument({agreement}:{agreement:Agreement}){
 const t=agreement.template||{},partner=agreement.partner||{},company=agreement.company||{},commercial=agreement.commercial||{},settings=commercial.settings||{},products=Array.isArray(commercial.products)?commercial.products:[],training=agreement.training||{},hiring=agreement.hiring||{};
 const roleLabel=labelFor(agreement);const role=agreement.targetRole||hiring.systemRole||'sales';const isSales=['sales','sales_rep','sales_team'].includes(role)||agreement.agreementType==='sales_partner';const track=String(training.track||'sales');
 const selfBonus=Number(settings.self_generated_bonus_percent||0),perfBonus=Number(settings.performance_bonus_percent||0),threshold=Number(settings.performance_threshold||0);
 return <article className="mx-auto max-w-4xl bg-white text-slate-800">
  <header className="border-b border-slate-200 pb-8"><div className="text-xs font-black uppercase tracking-[.18em] text-[#FF0E0E]">PROFOX · AGREEMENT</div><h1 className="mt-3 text-3xl font-black tracking-tight text-[#000080] sm:text-4xl">{t.title||`Independent ${roleLabel} Agreement`}</h1><p className="mt-2 text-sm font-semibold text-slate-500">{t.subtitle}</p><p className="mt-5 max-w-3xl text-sm leading-7 text-slate-600">{t.introduction}</p></header>
  <section className="grid gap-3 border-b border-slate-200 py-7 sm:grid-cols-2"><Fact label="Agreement ID" value={agreement.agreementNumber||'Preview'}/><Fact label="Agreement version" value={agreement.templateVersion?`Version ${agreement.templateVersion}.0`:'Current draft'}/><Fact label="Company" value={`${company.legalEntity||'ProFox Digital Solution'} · ${company.businessName||'ProFox Web Designer'}`}/><Fact label={roleLabel} value={`${partner.fullName||`Preview ${roleLabel}`} · ${partner.email||''}`}/><Fact label="Department" value={agreement.targetDepartment||hiring.department||(isSales?'Sales':'Not recorded')}/><Fact label="Document status" value={agreement.status||'Preview'}/></section>
  {(t.sections||[]).map((s:any,i:number)=>{const heading=s.title||s.heading||`Section ${i+1}`;return <section key={s.key||heading||i} className="border-b border-slate-100 py-7"><h2 className="text-lg font-black text-[#000080]">{heading}</h2><div className="mt-4 space-y-3 text-sm leading-7 text-slate-650">{String(s.body||'').split(/\n\s*\n/).filter(Boolean).map((p:string,j:number)=><p key={j}>{p}</p>)}</div></section>})}
  {isSales&&<section className="border-b border-slate-200 py-8"><div className="text-xs font-black uppercase tracking-[.18em] text-[#FF0E0E]">DYNAMIC COMMERCIAL SCHEDULE</div><h2 className="mt-2 text-2xl font-black text-[#000080]">Commercial terms captured for this agreement</h2><p className="mt-3 text-sm leading-6 text-slate-600">These values were pulled from the current ProFox Admin configuration when this agreement was issued. They are frozen for this agreement and later Admin changes apply only to future agreements.</p>
   <div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Offer</th><th className="px-4 py-3">Current price</th><th className="px-4 py-3">Base commission</th><th className="px-4 py-3">Self-sourced + closed</th></tr></thead><tbody className="divide-y divide-slate-100">{products.map((p:any)=><tr key={p.productCode}><td className="px-4 py-4 font-bold text-slate-900">{p.productName}</td><td className="px-4 py-4">{p.priceMode==='fixed'&&Number(p.basePrice)>0?money(p.basePrice,p.currency):p.priceMode==='starting_at'&&Number(p.basePrice)>0?`${money(p.basePrice,p.currency)}+`:'Approved quotation'}</td><td className="px-4 py-4">{p.requiresAdminRate?`${rate(p.minRatePercent)}–${rate(p.maxRatePercent)} approved per quotation`:rate(p.baseRatePercent)}</td><td className="px-4 py-4">{p.requiresAdminRate?`Approved base + ${selfBonus} percentage points`:rate(Number(p.baseRatePercent)+selfBonus)}</td></tr>)}</tbody></table></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2"><Policy title="Self-sourced bonus" text={`+${selfBonus} percentage points when the same representative qualifies as the recorded self-sourced originator and closes the eligible sale.`}/><Policy title="Performance bonus" text={perfBonus>0?`+${perfBonus} percentage points when the commission engine's current monthly sale-rank rule is met (after threshold ${threshold}).`:'No performance bonus is currently enabled.'}/><Policy title="Payout schedule" text={settings.payout_schedule||'As shown in the current Admin commission policy.'}/><Policy title="Payout trigger" text="Eligible client funds must be received and verified by ProFox before commission is generated."/></div>
  </section>}
  {!isSales&&<section className="border-b border-slate-200 py-8"><div className="text-xs font-black uppercase tracking-[.18em] text-[#FF0E0E]">ROLE & ONBOARDING CONTEXT</div><h2 className="mt-2 text-2xl font-black text-[#000080]">{roleLabel} onboarding controls</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><Policy title="Engagement" text={String(commercial.engagementType||'Contract')}/><Policy title="Department" text={String(agreement.targetDepartment||hiring.department||'Delivery')}/><Policy title="Training track" text={academyFor(track,roleLabel)}/><Policy title="Production access" text={String(training.productionAccess||'Locked until final approval and activation')}/></div>{commercial.note&&<p className="mt-4 text-sm leading-6 text-slate-600">{commercial.note}</p>}</section>}
  <section className="border-b border-slate-200 py-8"><div className="text-xs font-black uppercase tracking-[.18em] text-[#FF0E0E]">ONBOARDING REQUIREMENT</div><h2 className="mt-2 text-xl font-black text-[#000080]">{academyFor(track,roleLabel)} & Final Approval</h2><p className="mt-3 text-sm leading-7 text-slate-600">Required onboarding and certification are controlled through the assigned <strong>{academyFor(track,roleLabel)}</strong>. Production/client-project access remains locked until the applicable training gates, final review and authorized activation are complete.</p></section>
  {(agreement.partnerSignedAt||agreement.companySignedAt)&&<section className="py-8"><h2 className="text-xl font-black text-[#000080]">Signature record</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{agreement.partnerSignedAt&&<Policy title={roleLabel} text={`Signed ${new Date(agreement.partnerSignedAt).toLocaleString()}`}/>} {agreement.companySignedAt&&<Policy title="For ProFox" text={`${agreement.companySignerName||''}${agreement.companySignerTitle?` · ${agreement.companySignerTitle}`:''} · Signed ${new Date(agreement.companySignedAt).toLocaleString()}`}/>}</div></section>}
  <footer className="mt-4 border-t border-slate-200 py-6 text-[11px] leading-5 text-slate-400">Agreement hash: {agreement.documentHash||'Generated when issued'} · From site to system.</footer>
 </article>
}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-sm font-bold text-slate-800">{value}</div></div>}
function Policy({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-slate-200 p-4"><div className="text-xs font-black text-[#000080]">{title}</div><p className="mt-2 text-xs leading-5 text-slate-600">{text}</p></div>}