import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-profox-zoho-calendar-cron-token","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}});
const validEmail=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const accountsHost=(dc:string)=>({com:"https://accounts.zoho.com",in:"https://accounts.zoho.in",eu:"https://accounts.zoho.eu","com.au":"https://accounts.zoho.com.au",jp:"https://accounts.zoho.jp",ca:"https://accounts.zohocloud.ca",sa:"https://accounts.zoho.sa"} as Record<string,string>)[dc]||"";
const calendarHost=(dc:string)=>({com:"https://calendar.zoho.com",in:"https://calendar.zoho.in",eu:"https://calendar.zoho.eu","com.au":"https://calendar.zoho.com.au",jp:"https://calendar.zoho.jp",ca:"https://calendar.zohocloud.ca",sa:"https://calendar.zoho.sa"} as Record<string,string>)[dc]||"";
const toBasicUtc=(value:string|Date)=>{const d=value instanceof Date?value:new Date(value);const p=(n:number)=>String(n).padStart(2,"0");return `${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}T${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}Z`;};
const meetingLink=(event:any)=>String(event?.conference_data?.meetingdata?.meeting_link||event?.conference_data?.meetingdata?.meeting_url||"");
const eventFrom=(payload:any)=>Array.isArray(payload?.events)?payload.events[0]:null;
const zohoError=(payload:any,status:number)=>String(payload?.error?.[0]?.description||payload?.error?.[0]?.message||payload?.status?.description||payload?.data?.errorCode||payload?.message||payload?.error_description||payload?.error||`Zoho API request failed (${status})`).slice(0,1800);
const retryable=(status:number)=>status===429||status>=500;
const reconnectRequired=(status:number,payload:any)=>status===401||status===403||/INVALID_OAUTHTOKEN|INVALID_TOKEN|invalid oauth|scope|permission/i.test(zohoError(payload,status));
function retryDelay(attempts:number){const base=Math.min(30*Math.pow(2,Math.max(attempts-1,0)),21600);return Math.max(5,Math.round(base+Math.random()*Math.min(base*.25,60)));}

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")||"",anonKey=Deno.env.get("SUPABASE_ANON_KEY")||"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
 if(!supabaseUrl||!anonKey||!serviceKey)return json({error:"Server configuration unavailable"},500);
 const service=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
 let body:any={};try{body=await req.json();}catch{body={};}
 const cronHeader=req.headers.get("x-profox-zoho-calendar-cron-token")||"";const {data:cronSecret}=await service.rpc("service_get_zoho_calendar_cron_secret");
 let manualUserId="";
 if(!cronSecret||cronHeader!==String(cronSecret)){
  const authHeader=req.headers.get("Authorization")||"";if(!authHeader.startsWith("Bearer "))return json({error:"Authentication required"},401);
  const userClient=createClient(supabaseUrl,anonKey,{global:{headers:{Authorization:authHeader}},auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await userClient.auth.getUser();if(userError||!userData.user)return json({error:"Authentication required"},401);
  manualUserId=userData.user.id;if(String(body?.action||"")!=="sync_now")return json({error:"Unsupported manual action"},400);
  const {error:queueError}=await userClient.rpc("request_zoho_calendar_sync_now");if(queueError)return json({error:queueError.message},400);
 }
 await service.rpc("service_queue_due_zoho_busy_refreshes");
 const {data:jobs,error:claimError}=await service.rpc("service_claim_zoho_sync_jobs",{p_limit:25});if(claimError)return json({error:claimError.message},500);
 const results:any[]=[];const maxAttempts=8,lookaheadDays=90;
 async function finish(job:any,status:string,message="",retrySeconds?:number){await service.rpc("service_finish_zoho_sync_job",{p_job_id:job.id,p_status:status,p_error:message||null,p_retry_seconds:retrySeconds??null});}
 async function mark(job:any,status:string,message:string,success=false){await service.rpc("service_mark_zoho_connection_state",{p_user_id:job.user_id,p_status:status,p_error:message||null,p_success:success});}
 async function reconnect(job:any,message:string){await mark(job,"reconnect_required",message,false);await finish(job,"reconnect_required",message);}
 async function fail(job:any,message:string,status:number|null=null){if(status!==null&&retryable(status)&&Number(job.attempts)<maxAttempts){const d=retryDelay(Number(job.attempts));await finish(job,"retry",message,d);}else await finish(job,"failed",message);}
 async function tokenFor(job:any,connection:any){
  const {data:provider,error:providerError}=await service.rpc("service_get_zoho_provider_credentials");if(providerError||!provider?.clientId||!provider?.clientSecret)throw Object.assign(new Error("Zoho OAuth provider credentials are not configured."),{kind:"configuration"});
  const {data:refresh,error:refreshError}=await service.rpc("service_get_zoho_calendar_refresh_token",{p_user_id:job.user_id});if(refreshError||!refresh)throw Object.assign(new Error("Zoho Calendar refresh token is unavailable. Reconnect the Zoho account."),{kind:"reconnect"});
  const base=accountsHost(String(connection.data_center||""));if(!base)throw Object.assign(new Error("Unsupported Zoho data center."),{kind:"configuration"});
  let response:Response;try{response=await fetch(`${base}/oauth/v2/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({refresh_token:String(refresh),client_id:String(provider.clientId),client_secret:String(provider.clientSecret),grant_type:"refresh_token"})});}catch(e){throw Object.assign(new Error(e instanceof Error?e.message:"Zoho token endpoint unavailable"),{kind:"retry"});}
  const payload:any=await response.json().catch(()=>({}));if(!response.ok){const msg=zohoError(payload,response.status);if(reconnectRequired(response.status,payload)||/invalid_code|invalid_client/i.test(msg))throw Object.assign(new Error(msg),{kind:"reconnect",status:response.status});if(retryable(response.status))throw Object.assign(new Error(msg),{kind:"retry",status:response.status});throw Object.assign(new Error(msg),{kind:"configuration",status:response.status});}
  const token=String(payload?.access_token||"");if(!token)throw Object.assign(new Error("Zoho token refresh returned no access token."),{kind:"reconnect"});return token;
 }
 async function zfetch(connection:any,token:string,path:string,init:RequestInit={}){const base=calendarHost(String(connection.data_center||""));if(!base)throw Object.assign(new Error("Unsupported Zoho Calendar data center."),{kind:"configuration"});let response:Response;try{response=await fetch(`${base}${path}`,{...init,headers:{Accept:"application/json",...(init.headers||{}),Authorization:`Zoho-oauthtoken ${token}`}});}catch(e){throw Object.assign(new Error(e instanceof Error?e.message:"Zoho Calendar network error"),{kind:"retry"});}const text=await response.text();let payload:any={};try{payload=text?JSON.parse(text):{};}catch{payload={raw:text};}return{response,payload};}
 async function connectionFor(job:any){const {data,error}=await service.from("zoho_connections").select("*").eq("user_id",job.user_id).maybeSingle();if(error||!data||data.status!=="connected")throw Object.assign(new Error(error?.message||"Zoho Calendar is not connected."),{kind:"reconnect"});return data;}
 async function loadMeeting(job:any){const {data,error}=await service.from("sales_meetings").select("*").eq("id",job.meeting_id).eq("salesperson_id",job.user_id).maybeSingle();if(error||!data)throw Object.assign(new Error(error?.message||"Meeting no longer exists."),{kind:"failed"});return data;}
 async function loadLink(job:any){const {data}=await service.from("zoho_calendar_event_links").select("*").eq("meeting_id",job.meeting_id).maybeSingle();return data||null;}
 async function meetingRequested(job:any,connection:any){const {data:cfgRow}=await service.from("system_configuration").select("config_value").eq("config_key","professional_integrations").maybeSingle();const cfg=cfgRow?.config_value||{};const {data:provider}=await service.rpc("service_effective_meeting_provider",{p_user_id:job.user_id});return String(provider)==="zoho_meeting"&&Boolean(cfg?.zohoMeetingEnabled)&&Boolean(connection.meeting_ready);}
 function eventData(meeting:any,requestMeeting:boolean,etag?:unknown,eventUid?:string){const data:any={title:String(meeting.title||"ProFox Meeting"),dateandtime:{start:toBasicUtc(meeting.start_at),end:toBasicUtc(meeting.end_at),timezone:String(meeting.timezone||"UTC")},isallday:false,isprivate:false,description:`${String(meeting.description||"").trim()}${meeting.description?"\n\n":""}ProFox Meeting ID: ${meeting.id}`,transparency:0,conference:requestMeeting?"zmeeting":"none",notifyType:1,allowForwarding:true};if(validEmail(String(meeting.attendee_email||"")))data.attendees=[{email:String(meeting.attendee_email).toLowerCase(),status:"NEEDS-ACTION",attendance:1}];if(etag!==undefined&&etag!==null&&String(etag)!=="")data.etag=etag;if(eventUid)data.uid=eventUid;return data;}
 async function persist(job:any,connection:any,event:any,operation:string){const uid=String(event?.uid||"");if(!uid)throw Object.assign(new Error("Zoho Calendar returned no event UID."),{kind:"retry"});const url=meetingLink(event);const {error}=await service.rpc("service_upsert_zoho_event_link",{p_meeting_id:job.meeting_id,p_user_id:job.user_id,p_calendar_id:String(connection.calendar_id||"primary"),p_event_id:uid,p_etag:String(event?.etag||""),p_meeting_url:url,p_operation:operation});if(error)throw Object.assign(new Error(error.message),{kind:"retry"});return url;}
 async function refreshBusy(job:any,token:string,connection:any){
  const start=new Date(Date.now()-60*60*1000),end=new Date(Date.now()+lookaheadDays*86400000);const params=new URLSearchParams({uemail:String(connection.account_email||""),sdate:toBasicUtc(start).replace(/Z$/,"") ,edate:toBasicUtc(end).replace(/Z$/,"") ,ftype:"eventbased"});
  const {response,payload}=await zfetch(connection,token,`/api/v1/calendars/freebusy?${params.toString()}`);if(!response.ok){const msg=zohoError(payload,response.status);if(reconnectRequired(response.status,payload))return reconnect(job,msg);return fail(job,msg,response.status);}
  const busy=(Array.isArray(payload?.freebusy)?payload.freebusy:[]).map((x:any)=>({start:String(x?.startTime||""),end:String(x?.endTime||"")})).filter((x:any)=>x.start&&x.end);
  const {error}=await service.rpc("service_replace_zoho_busy_blocks",{p_user_id:job.user_id,p_calendar_id:String(connection.calendar_id||"primary"),p_window_start:start.toISOString(),p_window_end:end.toISOString(),p_busy:busy});if(error)return fail(job,error.message,null);
  await finish(job,"succeeded");await mark(job,"connected","",true);return true;
 }
 async function getEvent(job:any,token:string,connection:any,eventUid:string){return zfetch(connection,token,`/api/v1/calendars/${encodeURIComponent(String(connection.calendar_id||"primary"))}/events/${encodeURIComponent(eventUid)}`,{method:"GET"});}
 async function deleteEvent(job:any,token:string,connection:any){const link=await loadLink(job);if(!link?.external_event_id){await service.rpc("service_delete_zoho_event_link",{p_meeting_id:job.meeting_id,p_user_id:job.user_id});await finish(job,"succeeded");return true;}const current=await getEvent(job,token,connection,String(link.external_event_id));if(current.response.status===404){await service.rpc("service_delete_zoho_event_link",{p_meeting_id:job.meeting_id,p_user_id:job.user_id});await finish(job,"succeeded");return true;}if(!current.response.ok){const msg=zohoError(current.payload,current.response.status);if(reconnectRequired(current.response.status,current.payload))return reconnect(job,msg);return fail(job,msg,current.response.status);}const ev=eventFrom(current.payload);const etag=String(ev?.etag||link.etag||"");const {response,payload}=await zfetch(connection,token,`/api/v1/calendars/${encodeURIComponent(String(connection.calendar_id||"primary"))}/events/${encodeURIComponent(String(link.external_event_id))}`,{method:"DELETE",headers:etag?{etag}:{}});if(!response.ok&&response.status!==404){const msg=zohoError(payload,response.status);if(reconnectRequired(response.status,payload))return reconnect(job,msg);return fail(job,msg,response.status);}await service.rpc("service_delete_zoho_event_link",{p_meeting_id:job.meeting_id,p_user_id:job.user_id});await finish(job,"succeeded");await mark(job,"connected","",true);return true;}
 async function upsert(job:any,token:string,connection:any){
  const meeting=await loadMeeting(job);if(meeting.status==="Cancelled")return deleteEvent(job,token,connection);const link=await loadLink(job);const requestMeeting=await meetingRequested(job,connection);const cal=encodeURIComponent(String(connection.calendar_id||"primary"));
  if(link?.external_event_id){
   const current=await getEvent(job,token,connection,String(link.external_event_id));
   if(current.response.ok){const existing=eventFrom(current.payload);if(job.job_type==="reconcile_event"){const url=await persist(job,connection,existing,"reconcile");if(requestMeeting&&!url&&Number(job.attempts)<maxAttempts){await finish(job,"retry","Zoho Meeting link is still pending.",retryDelay(Number(job.attempts)));return;}await finish(job,"succeeded");await mark(job,"connected","",true);return true;}const data=eventData(meeting,requestMeeting,existing?.etag||link.etag,String(link.external_event_id));const params=new URLSearchParams({eventdata:JSON.stringify(data)});const write=await zfetch(connection,token,`/api/v1/calendars/${cal}/events/${encodeURIComponent(String(link.external_event_id))}?${params.toString()}`,{method:"PUT"});if(!write.response.ok){const msg=zohoError(write.payload,write.response.status);if(reconnectRequired(write.response.status,write.payload))return reconnect(job,msg);return fail(job,msg,write.response.status);}const saved=eventFrom(write.payload);const url=await persist(job,connection,saved,"update");await finish(job,"succeeded");await mark(job,"connected","",true);if(requestMeeting&&!url)await service.rpc("queue_zoho_calendar_sync",{p_user_id:job.user_id,p_job_type:"reconcile_event",p_meeting_id:job.meeting_id,p_force:true});return true;}
   if(current.response.status!==404){const msg=zohoError(current.payload,current.response.status);if(reconnectRequired(current.response.status,current.payload))return reconnect(job,msg);return fail(job,msg,current.response.status);}
  }
  const data=eventData(meeting,requestMeeting);const params=new URLSearchParams({eventdata:JSON.stringify(data)});const write=await zfetch(connection,token,`/api/v1/calendars/${cal}/events?${params.toString()}`,{method:"POST"});if(!write.response.ok){let msg=zohoError(write.payload,write.response.status);if(requestMeeting&&write.response.status===400)msg=`${msg} Zoho rejected Calendar + Meeting creation; verify the free-plan/API entitlement and ZohoMeeting.meeting.ALL permission.`;if(reconnectRequired(write.response.status,write.payload))return reconnect(job,msg);return fail(job,msg,write.response.status);}const saved=eventFrom(write.payload);const url=await persist(job,connection,saved,"create");await finish(job,"succeeded");await mark(job,"connected","",true);if(requestMeeting&&!url)await service.rpc("queue_zoho_calendar_sync",{p_user_id:job.user_id,p_job_type:"reconcile_event",p_meeting_id:job.meeting_id,p_force:true});return true;
 }
 for(const job of jobs||[]){if(manualUserId&&job.user_id!==manualUserId)continue;try{const connection=await connectionFor(job);const token=await tokenFor(job,connection);if(job.job_type==="refresh_busy")await refreshBusy(job,token,connection);else if(job.job_type==="delete_event")await deleteEvent(job,token,connection);else await upsert(job,token,connection);results.push({jobId:job.id,status:"processed"});}catch(e:any){const msg=e instanceof Error?e.message:"Zoho Calendar synchronization failed.";if(e?.kind==="reconnect")await reconnect(job,msg);else if(e?.kind==="retry"&&Number(job.attempts)<maxAttempts)await finish(job,"retry",msg,retryDelay(Number(job.attempts)));else await fail(job,msg,e?.status??null);results.push({jobId:job.id,status:"error",message:msg.slice(0,240)});}}
 return json({processed:results.length,results});
});
