import { FormEvent, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowLeft,
  ArrowRight,
  Brain,
  BriefcaseBusiness,
  CheckCircle2,
  ChevronDown,
  Clock3,
  DollarSign,
  FileText,
  LayoutTemplate,
  Loader2,
  PenLine,
  Search,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  UploadCloud,
  Video,
} from 'lucide-react';
import type { CareerJob } from '../lib/careerService';
import { applicantService } from '../lib/applicantService';
import { talentPartnerService } from '../lib/talentPartnerService';
import { supabase } from '../lib/supabase';

interface Props { job: CareerJob }

type FormState = {
  fullName:string;email:string;phone:string;country:string;linkedinUrl:string;currentRole:string;
  contentExperience:string;researchApproach:string;qualityProcess:string;skills:string;
  availableHoursPerWeek:string;weeklyAvailability:string;earliestStartDate:string;motivation:string;
  hasLaptopInternet:boolean;consentAccurate:boolean;consentPrivacy:boolean;
};

type Acknowledgements = {
  contractor:boolean;projectPayment:boolean;earningPotential:boolean;earningVariables:boolean;salaryPath:boolean;
};

const initial:FormState={
  fullName:'',email:'',phone:'',country:'',linkedinUrl:'',currentRole:'',contentExperience:'',researchApproach:'',qualityProcess:'',skills:'',
  availableHoursPerWeek:'20',weeklyAvailability:'',earliestStartDate:'',motivation:'',hasLaptopInternet:false,consentAccurate:false,consentPrivacy:false
};

const initialAcknowledgements:Acknowledgements={contractor:false,projectPayment:false,earningPotential:false,earningVariables:false,salaryPath:false};

const selectionSteps=[
  ['Application','Submit your details, current CV/resume and a short professional introduction video.'],
  ['Initial Review','We review relevant experience, communication, availability, reliability and overall role fit.'],
  ['Portfolio Review','Shortlisted applicants receive a secure request to submit three structured case studies showing their experience and contribution.'],
  ['Content Assessment','Complete a role-specific assessment covering clarity, structure, content judgment and commercial thinking.'],
  ['Conditional Selection & Agreement','Successful applicants review and accept the approved project-based Content Writer contractor agreement.'],
  ['Content Academy','Complete the required ProFox Content training and learn our delivery and quality standards.'],
  ['Practical Certification','Complete production-style work that is independently reviewed. A minimum 90% score is required.'],
  ['Production Approval','Complete the required approval and system-access process before becoming eligible for ProFox client projects.'],
] as const;

const faq=[
  ['How much can I earn?','The project-based opportunity is designed to provide the potential to earn approximately $1,000–$1,500+ per month. Actual earnings depend on available projects, accepted project fees, capacity, performance and successful delivery. This amount is not guaranteed.'],
  ['How am I paid?','You are initially paid according to the agreed compensation terms for each accepted project rather than through a fixed monthly salary.'],
  ['How can I earn more?','Writers who maintain strong quality, reliable delivery and sufficient capacity may be able to accept additional suitable projects when available. More projects can increase earnings, but quality always comes first.'],
  ['Are projects guaranteed?','No. Project availability depends on client demand, project requirements, role fit, performance and available capacity.'],
  ['Is this initially a salaried position?','No. You begin as a project-based independent Content Writer.'],
  ['Can I become salaried?','Yes. After at least six months with ProFox, consistently strong content quality, dependable service, professional communication and project performance can earn you the opportunity to transition into a salaried role.'],
  ['What salary would I receive after six months?','There is no predetermined salary promised at the application stage. If you qualify for a salaried opportunity, compensation, responsibilities, working arrangements and applicable employment terms are discussed at that time.'],
  ['Does staying six months automatically guarantee a salary?','No. Six months is the minimum performance period, not an automatic entitlement. The opportunity depends on consistently meeting the required quality, reliability, service and performance standards.'],
  ['What kind of content will I write?','The primary focus is website and conversion content, including page messaging, service content, headlines, calls to action, supporting sections and other website copy required by an approved project.'],
  ['Can I use AI tools?','AI and other tools may support appropriate parts of your workflow, but you remain responsible for research, originality, accuracy, evidence, brand fit and final quality. Raw AI-generated content should never be submitted as finished client work.'],
  ['Do I need to submit my full portfolio now?','No. Start with your CV/resume and introduction video. Shortlisted applicants receive a secure Portfolio Review request for three structured case studies.'],
  ['What if important client information is missing?','Do not guess. Raise missing facts, evidence or project information through the project workflow so the appropriate person can resolve it before unsupported claims enter the content.'],
  ['What happens after my content is approved?','Approved content is organized and handed to the UI/UX team for implementation with the hierarchy, calls to action, evidence and project context connected to the work.'],
] as const;

export default function ContentWriterJobView({job}:Props){
  const [form,setForm]=useState<FormState>(initial);
  const [acks,setAcks]=useState<Acknowledgements>(initialAcknowledgements);
  const [cv,setCv]=useState<File|null>(null);
  const [video,setVideo]=useState<File|null>(null);
  const [progress,setProgress]=useState(0);
  const [uploadLabel,setUploadLabel]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [reference,setReference]=useState('');
  const minHours=Number(job.roleDetails?.applicationForm?.minimumWeeklyHours||20);
  const set=(key:keyof FormState,value:any)=>setForm(current=>({...current,[key]:value}));
  const setAck=(key:keyof Acknowledgements,value:boolean)=>setAcks(current=>({...current,[key]:value}));

  const submit=async(event:FormEvent)=>{
    event.preventDefault();setError('');
    if(!cv){setError('Please upload your CV or resume.');return;}
    if(!video){setError('Please upload your short introduction video.');return;}
    if(Number(form.availableHoursPerWeek)<minHours){setError(`This role currently requires at least ${minHours} available hours per week.`);return;}
    if(!Object.values(acks).every(Boolean)){setError('Please confirm the project-based earnings and career-path terms before submitting.');return;}
    setBusy(true);
    try{
      setUploadLabel('Uploading CV / resume');setProgress(0);
      const uploadedCv=await applicantService.uploadPublicApplicationFile(form.email.trim().toLowerCase(),'cv',cv,setProgress);
      setUploadLabel('Uploading introduction video');setProgress(0);
      const uploadedVideo=await applicantService.uploadPublicApplicationFile(form.email.trim().toLowerCase(),'video',video,setProgress);
      setUploadLabel('Submitting application');
      const params=new URLSearchParams(window.location.search);
      const result=await supabase.rpc('submit_public_content_writer_application',{p_application:{
        ...form,
        fullName:form.fullName.trim(),email:form.email.trim().toLowerCase(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',
        availableHoursPerWeek:Number(form.availableHoursPerWeek),cvStoragePath:uploadedCv.path,videoStoragePath:uploadedVideo.path,
        utmSource:params.get('utm_source')||'',utmMedium:params.get('utm_medium')||'',utmCampaign:params.get('utm_campaign')||'',
        utmContent:params.get('utm_content')||'',utmTerm:params.get('utm_term')||'',landingPage:window.location.pathname,referrerUrl:document.referrer||''
      }});
      if(result.error)throw result.error;
      if(!result.data?.success)throw new Error(result.data?.error||'Your application could not be submitted.');
      if(result.data.reference)await talentPartnerService.claimApplication(result.data.reference,form.email);
      setReference(result.data.reference||'Submitted');window.scrollTo({top:0,behavior:'smooth'});
    }catch(err:any){setError(err?.message||'Your application could not be submitted. Please try again.');}
    finally{setBusy(false);setUploadLabel('');}
  };

  if(reference)return <div className="min-h-screen bg-white px-6 pb-24 pt-36"><div className="mx-auto max-w-2xl rounded-[2rem] border border-emerald-200 bg-emerald-50 p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="mt-5 text-3xl font-black text-slate-900">Application received</h1><p className="mt-3 text-sm leading-7 text-slate-600">Your Content Writer application, resume and introduction video are now in the ProFox recruitment workflow. Please do not send portfolio material yet. If you pass the initial review, we will email you a secure Portfolio Review link with the required three-case-study format.</p><div className="mx-auto mt-5 w-fit rounded-xl bg-white px-4 py-2 text-xs font-black text-slate-700">Reference: {reference}</div><Link to="/careers" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-sm font-black text-white transition hover:-translate-y-0.5 hover:shadow-lg"><ArrowLeft className="h-4 w-4"/>Back to Careers</Link></div></div>;

  return <div className="min-h-screen bg-white text-slate-900">
    <section className="relative overflow-hidden border-b border-slate-200 bg-[#fbfcff] pt-24 lg:h-[100svh] lg:min-h-[720px] lg:max-h-[940px]">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(0,0,128,.06),transparent_34%),radial-gradient(circle_at_90%_25%,rgba(255,14,14,.04),transparent_28%)]"/>
      <div className="relative mx-auto grid h-full max-w-7xl gap-8 px-6 pb-10 pt-6 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:gap-12 lg:pb-8 lg:pt-4">
        <div className="py-4 lg:py-0">
          <Link to="/careers" className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3.5 py-1.5 text-xs font-bold text-slate-500 transition hover:border-blue-200 hover:text-[#000080]"><ArrowLeft className="h-3.5 w-3.5"/>Back to Careers</Link>
          <div className="mt-7 text-[11px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">Remote Content Writer Opportunity · Project-Based</div>
          <h1 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.045em] text-[#071126] sm:text-5xl lg:text-[3.7rem] lg:leading-[1.02]">Content Writer — Website &amp; Conversion Copy</h1>
          <h2 className="mt-5 max-w-2xl text-xl font-black leading-8 text-slate-800 sm:text-2xl">Write website content. Get paid per project. Build a long-term career with ProFox.</h2>
          <p className="mt-4 max-w-2xl text-base leading-7 text-slate-600">Turn research, customer insight and real business information into website copy people can understand, trust and act on.</p>
          <div className="mt-6 flex flex-wrap items-end gap-x-4 gap-y-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 sm:w-fit">
            <div><div className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-700">Monthly earning opportunity*</div><div className="mt-1 text-3xl font-black tracking-tight text-[#071126]">$1,000–$1,500+</div></div>
            <div className="pb-1 text-xs font-bold text-slate-500">Project-based · performance dependent</div>
          </div>
          <div className="mt-5 flex flex-wrap gap-2">{['Remote','Independent Contractor','Paid Per Project','6-Month Salaried Career Path'].map(item=><span key={item} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-[11px] font-black text-slate-600">{item}</span>)}</div>
          <div className="mt-6 flex flex-wrap items-center gap-4"><a href="#apply" className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3.5 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg">Apply for Content Writer <ArrowRight className="h-4 w-4"/></a><a href="#earnings" className="text-sm font-black text-[#000080] hover:underline">See how project earnings work</a></div>
          <p className="mt-4 max-w-2xl text-[11px] leading-5 text-slate-500">*$1,000–$1,500+ per month is a potential project-based earning opportunity, not guaranteed income. Actual earnings depend on available projects, accepted project fees, capacity, performance and successful delivery.</p>
        </div>
        <div className="min-h-[360px] overflow-hidden rounded-[2rem] border border-blue-100 bg-[#071126] shadow-2xl shadow-blue-950/10 sm:min-h-[480px] lg:h-[calc(100svh-9rem)] lg:min-h-[560px] lg:max-h-[760px]">
          <CareerVisual file="content-writer-hero.svg" alt="ProFox Content Writer researching and preparing website content" eager/>
        </div>
      </div>
    </section>

    <section className="border-b border-slate-100 bg-white py-16 sm:py-20">
      <Container><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow>More than another freelance writing gig</Eyebrow><H2>Get Paid For Quality Work—Then Earn The Chance To Build Something Long-Term.</H2><p className="mt-5 text-base leading-8 text-slate-600">You begin with ProFox as a <strong className="text-slate-900">project-based independent Content Writer</strong>. Each accepted assignment has a defined scope, timeline, quality standard and agreed project fee.</p><p className="mt-4 text-base leading-8 text-slate-600">As you prove your ability to deliver high-quality work consistently, you can take on suitable additional projects based on capacity—creating a potential monthly earning opportunity of <strong className="text-slate-900">$1,000–$1,500+</strong>.</p><div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><div className="text-xs font-black uppercase tracking-[.14em] text-[#000080]">Long-term opportunity</div><p className="mt-2 text-sm leading-7 text-slate-600">After at least <strong className="text-slate-900">six months</strong> of consistently strong quality, reliability and service, qualifying writers can be offered the opportunity to transition into a salaried ProFox role. Salary and applicable terms are discussed at that time.</p></div></div><VisualFrame><CareerVisual file="content-writer-earnings.svg" alt="Project-based Content Writer earnings and payment flow"/></VisualFrame></div></Container>
    </section>

    <section className="bg-[#fbfcff] py-16 sm:py-20">
      <Container><div className="mx-auto max-w-3xl text-center"><Eyebrow>This isn't about filling pages with words</Eyebrow><H2>You Own The Message Before Design Begins.</H2><p className="mt-5 text-base leading-8 text-slate-600">Understand the client's business, customer, offer, objectives and evidence first. Then turn that information into clear website messaging the customer can understand—and the UI/UX Designer can confidently build from.</p></div><div className="mt-10"><VisualFrame><CareerVisual file="content-workflow.svg" alt="ProFox Content workflow from client truth through UI UX handoff"/></VisualFrame></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MiniCard title="Research" text="Understand the business, audience, offer, objections and market." icon={<Search/>}/><MiniCard title="Structure" text="Decide what the page communicates, in what order and why." icon={<LayoutTemplate/>}/><MiniCard title="Write" text="Turn research into clear website and conversion-focused copy." icon={<PenLine/>}/><MiniCard title="Verify" text="Protect the accuracy behind facts, proof and important claims." icon={<ShieldCheck/>}/><MiniCard title="Handoff" text="Give UI/UX organized, approved content ready to implement." icon={<ArrowRight/>}/></div></Container>
    </section>

    <section id="earnings" className="scroll-mt-24 bg-white py-16 sm:py-20">
      <Container><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Clear projects. Clear payment.</Eyebrow><H2>Your Income Grows With The Projects You Can Successfully Handle.</H2><p className="mt-5 text-base leading-8 text-slate-600">This opportunity begins on a project-based independent contractor model. There is no fixed monthly salary during this stage. Compensation is agreed for the individual project.</p><div className="mt-7 rounded-3xl bg-[#071126] p-6 text-white"><div className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Monthly earning opportunity*</div><div className="mt-2 text-4xl font-black">$1,000–$1,500+</div><p className="mt-3 text-sm leading-6 text-slate-300">More suitable projects can increase total project earnings when your capacity and performance support them. Quality always comes first.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><ProcessCard n="01" title="Review the project" text="Understand required pages, deliverables, timeline and responsibilities."/><ProcessCard n="02" title="Know the project fee" text="The agreed project compensation and applicable payment terms are provided for the assignment."/><ProcessCard n="03" title="Accept the work" text="Take suitable projects that match your availability and capacity."/><ProcessCard n="04" title="Deliver to standard" text="Research, write, revise and complete the required quality process."/><ProcessCard n="05" title="Get paid per project" text="Payment follows the agreed terms for successfully delivered work."/><div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><TrendingUp className="h-6 w-6 text-emerald-700"/><h3 className="mt-3 text-lg font-black text-slate-900">What affects earnings?</h3><p className="mt-2 text-sm leading-6 text-slate-600">Project availability, project size and fee, accepted workload, capacity, quality, reliability, performance and revision discipline.</p></div></div></div><p className="mt-7 text-xs leading-6 text-slate-500">*The $1,000–$1,500+ figure is an earning opportunity rather than guaranteed income. Project availability and actual earnings may vary.</p></Container>
    </section>

    <section className="bg-[#071126] py-16 text-white sm:py-20">
      <Container><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="text-[11px] font-black uppercase tracking-[.18em] text-emerald-300">Performance should create opportunity</div><h2 className="mt-3 text-3xl font-black tracking-[-.035em] sm:text-4xl">Prove Yourself For Six Months. Open The Door To A Salaried Role.</h2><p className="mt-5 text-base leading-8 text-slate-300">We don't want our strongest Content Writers to remain project-based forever. After at least six months, consistently strong work can earn a qualifying writer the opportunity to transition into a salaried ProFox role.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{['Content quality','Research & accuracy','Reliability','Project delivery','Feedback & revisions','Team collaboration','Client-service quality'].map(item=><div key={item} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm font-bold text-slate-200"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-300"/>{item}</div>)}</div><div className="mt-7 rounded-2xl border border-white/10 bg-white/5 p-5"><div className="text-sm font-black text-white">Don't just complete six months.</div><p className="mt-1 text-sm leading-6 text-slate-300">Build six months of work that makes us want to keep you. Six months alone does not guarantee a salaried offer. Salary, responsibilities and employment terms are discussed only if you qualify.</p></div></div><VisualFrame dark><CareerVisual file="content-writer-growth.svg" alt="Six month Content Writer performance path toward a salaried role opportunity"/></VisualFrame></div></Container>
    </section>

    <section className="bg-white py-16 sm:py-20">
      <Container><div className="mx-auto max-w-3xl text-center"><Eyebrow>Your responsibility</Eyebrow><H2>Research Deeply. Write Clearly. Never Invent The Proof.</H2><p className="mt-4 text-base leading-8 text-slate-600">Good website copy starts long before the first headline.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><InfoCard title="Research the client" text="Understand the business, services, customers, offer, competitors and project objectives."/><InfoCard title="Understand the customer" text="Identify what customers need to understand, what may stop them and what helps them make an informed decision."/><InfoCard title="Structure the message" text="Turn scattered information into a logical page hierarchy and customer journey."/><InfoCard title="Write conversion copy" text="Create headlines, service sections, proof positioning, calls to action and project-specific website copy."/><InfoCard title="Verify important claims" text="Never invent statistics, credentials, guarantees, testimonials, comparisons or results."/><InfoCard title="Review your work" text="Check accuracy, clarity, structure, grammar, tone, consistency and conversion logic before submitting."/><InfoCard title="Handle feedback" text="Improve the work based on editorial, fact-checking, SEO/conversion, client and project feedback."/><InfoCard title="Prepare the handoff" text="Give UI/UX approved, structured content they can implement without guessing."/></div></Container>
    </section>

    <section className="border-y border-slate-100 bg-[#fbfcff] py-16 sm:py-20">
      <Container><div className="grid gap-12 lg:grid-cols-2"><div><Eyebrow>Good writing is the starting point</Eyebrow><H2>We Need Writers Who Can Think Before They Write.</H2><div className="mt-7 space-y-3"><Requirement title="Strong written English" text="Make complicated ideas clear, natural and professional."/><Requirement title="Website & commercial writing experience" text="Show relevant website, landing-page, service-page, conversion or UX content work."/><Requirement title="Research discipline" text="Know what is verified, what is assumed and what still needs clarification."/><Requirement title="Information structure" text="Turn messy inputs into a clear message hierarchy."/><Requirement title="Commercial thinking" text="Help the right customer understand the offer and confidently decide what to do next."/><Requirement title="Feedback discipline" text="Receive professional criticism, revise and improve the work."/><Requirement title="Ownership" text="Flag missing information and never invent unsupported proof."/></div></div><div><div className="rounded-[2rem] border border-red-100 bg-red-50/60 p-7"><div className="text-[11px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">This probably isn't for you if…</div><div className="mt-5 space-y-3">{['You copy competitors instead of understanding the client.','You submit raw AI-generated writing as finished work.','You fabricate proof, claims, statistics or credentials.','You treat research and revisions as optional.','You repeatedly miss commitments or accept more work than you can deliver properly.'].map(item=><div key={item} className="flex gap-3 text-sm leading-6 text-slate-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#FF0E0E]"/>{item}</div>)}</div></div><div className="mt-5 rounded-[2rem] border border-blue-100 bg-white p-7 shadow-sm"><Sparkles className="h-7 w-7 text-[#000080]"/><h3 className="mt-4 text-xl font-black">Know what quality looks like.</h3><p className="mt-3 text-sm leading-7 text-slate-600">ProFox gives writers clearer project context, defined deliverables, quality standards, independent review, structured feedback and a reliable UI/UX handoff.</p><p className="mt-4 text-sm font-black leading-7 text-[#071126]">We don't want writers who produce more words. We want writers who become more valuable with every project.</p></div></div></div></Container>
    </section>

    <section className="bg-white py-16 sm:py-20">
      <Container><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><Eyebrow>Tools can help. Judgment cannot be outsourced.</Eyebrow><H2>Use The Tools. Own The Work.</H2><p className="mt-5 text-base leading-8 text-slate-600">AI and other tools may support appropriate parts of research, organization, ideation or editing. But you remain responsible for everything submitted under your name.</p><div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50/60 p-5 text-sm font-black leading-7 text-[#071126]">Your value isn't how fast AI can generate words. Your value is the judgment you add before those words reach the client.</div></div><div className="grid gap-3 sm:grid-cols-2"><Standard icon={<Brain/>} title="Human judgment" text="Be able to explain the thinking behind your content."/><Standard icon={<ShieldCheck/>} title="Evidence first" text="Never fabricate information, testimonials, statistics, credentials or results."/><Standard icon={<Search/>} title="Verify important facts" text="Check important claims against appropriate project evidence."/><Standard icon={<PenLine/>} title="Own the final copy" text="Make sure the work is original, relevant, accurate and appropriate for the client."/></div></div></Container>
    </section>

    <section className="bg-[#fbfcff] py-16 sm:py-20">
      <Container><div className="mx-auto max-w-3xl text-center"><Eyebrow>How you join</Eyebrow><H2>We Don't Activate Content Writers From A CV Alone.</H2><p className="mt-4 text-base leading-8 text-slate-600">The selection process is designed to understand how you communicate, research, write, think and respond to professional standards.</p></div><div className="relative mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{selectionSteps.map(([title,text],index)=><div key={title} className="group rounded-3xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><div className="text-xs font-black text-[#FF0E0E]">{String(index+1).padStart(2,'0')}</div><h3 className="mt-3 text-base font-black text-[#071126]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div><div className="mx-auto mt-6 max-w-3xl rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-center text-xs font-semibold leading-6 text-amber-900">Passing an individual stage does not guarantee final activation. All applicable recruitment, agreement, training, certification and approval requirements must be completed.</div></Container>
    </section>

    <section className="bg-white py-16 sm:py-20">
      <Container><div className="grid gap-8 rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm lg:grid-cols-[1fr_360px] lg:items-center lg:p-10"><div><Eyebrow>Flexible doesn't mean unreliable</Eyebrow><H2>Take The Projects You Can Properly Deliver.</H2><p className="mt-4 max-w-3xl text-base leading-8 text-slate-600">Applicants should normally have approximately <strong className="text-slate-900">{minHours} hours per week of available project capacity</strong> while actively accepting ProFox projects. This represents capacity—not guaranteed paid hours. Compensation remains based on the agreed project fee.</p><p className="mt-4 text-sm font-bold leading-7 text-slate-700">More capacity + strong performance can create access to more suitable projects and higher project-based earnings—but never at the expense of quality.</p></div><div className="rounded-3xl bg-[#071126] p-6 text-white"><Clock3 className="h-7 w-7 text-emerald-300"/><div className="mt-4 text-3xl font-black">{minHours}+ hrs</div><div className="mt-1 text-sm font-bold text-slate-300">Available project capacity / week</div><div className="my-5 h-px bg-white/10"/><div className="text-2xl font-black">$1,000–$1,500+*</div><div className="mt-1 text-xs text-slate-400">Potential monthly project-based earnings</div></div></div></Container>
    </section>

    <section id="apply" className="scroll-mt-24 border-t border-slate-200 bg-slate-50 py-16 sm:py-20">
      <form onSubmit={submit} className="mx-auto max-w-4xl space-y-7 px-6"><div className="text-center"><Eyebrow>Ready to apply?</Eyebrow><h2 className="mt-3 text-3xl font-black tracking-[-.035em] text-[#071126] sm:text-4xl">Show Us How You Think—Not Just Where You've Worked.</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-slate-600">Start with your details, CV/resume and a short professional introduction video. Your full three-case-study portfolio is collected later only if you pass the initial review.</p><p className="mt-2 text-xs font-bold text-[#000080]">Keep written answers focused. 3–6 thoughtful sentences is usually enough.</p></div>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
        <Card title="Your details"><Grid><Field label="Full name *"><input required value={form.fullName} onChange={e=>set('fullName',e.target.value)}/></Field><Field label="Email address *"><input required type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Phone"><input value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Country *"><input required value={form.country} onChange={e=>set('country',e.target.value)}/></Field><Field label="Current role"><input value={form.currentRole} onChange={e=>set('currentRole',e.target.value)}/></Field><Field label="LinkedIn profile"><input type="url" value={form.linkedinUrl} onChange={e=>set('linkedinUrl',e.target.value)}/></Field></Grid></Card>
        <Card title="Required application material"><Grid><Field label="CV / Resume *"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs font-bold text-slate-600 transition hover:border-[#000080]"><UploadCloud className="h-4 w-4 text-[#000080]"/>{cv?cv.name:'Upload PDF, DOC or DOCX'}<input className="hidden" type="file" required accept=".pdf,.doc,.docx" onChange={e=>setCv(e.target.files?.[0]||null)}/></label></Field><Field label="Introduction video *"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs font-bold text-slate-600 transition hover:border-[#000080]"><Video className="h-4 w-4 text-[#000080]"/>{video?video.name:'Upload MP4, WebM or MOV'}<input className="hidden" type="file" required accept="video/mp4,video/webm,video/quicktime,.mp4,.webm,.mov" onChange={e=>setVideo(e.target.files?.[0]||null)}/></label></Field></Grid><div className="rounded-2xl border border-blue-100 bg-blue-50 p-4 text-xs leading-6 text-slate-600"><strong className="text-slate-900">Video guidance:</strong> briefly explain who you are, your relevant content experience, how you approach research and how you protect quality before submitting work. Keep it concise and professional.</div>{busy&&progress>0&&<div><div className="mb-2 flex justify-between text-[11px] font-bold text-slate-500"><span>{uploadLabel}</span><span>{progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#000080] transition-all" style={{width:`${progress}%`}}/></div></div>}</Card>
        <Card title="How you work"><Long label="Describe your relevant website or commercial content-writing experience *" value={form.contentExperience} onChange={v=>set('contentExperience',v)}/><Long label="How do you research a business, its customers and its market before writing? *" value={form.researchApproach} onChange={v=>set('researchApproach',v)}/><Long label="How do you check accuracy, clarity, structure and quality before submitting content? *" value={form.qualityProcess} onChange={v=>set('qualityProcess',v)}/><Long label="Which writing, research, SEO, AI, collaboration or productivity tools do you use?" value={form.skills} onChange={v=>set('skills',v)}/></Card>
        <Card title="Project availability"><Grid><Field label={`Available project capacity per week * (minimum ${minHours})`}><input required type="number" min={minHours} max={80} value={form.availableHoursPerWeek} onChange={e=>set('availableHoursPerWeek',e.target.value)}/></Field><Field label="Earliest available start date"><input type="date" value={form.earliestStartDate} onChange={e=>set('earliestStartDate',e.target.value)}/></Field></Grid><p className="rounded-xl bg-slate-50 px-4 py-3 text-xs leading-6 text-slate-500">This is your available capacity while actively accepting projects. It is not a guarantee of {minHours} paid hours. Payment is based on the agreed project fee.</p><Long label="Typical weekly availability" value={form.weeklyAvailability} onChange={v=>set('weeklyAvailability',v)}/><Long label="Why do you want to work with the ProFox Content team?" value={form.motivation} onChange={v=>set('motivation',v)}/></Card>
        <Card title="Confirmations"><Check checked={form.hasLaptopInternet} onChange={v=>set('hasLaptopInternet',v)}>I have access to a reliable laptop and internet connection.</Check><Check checked={form.consentAccurate} onChange={v=>set('consentAccurate',v)}>The information and materials I submit accurately represent my experience and work.</Check><Check checked={acks.contractor} onChange={v=>setAck('contractor',v)}>I understand that I am initially applying for project-based independent contractor work rather than an immediate salaried position.</Check><Check checked={acks.projectPayment} onChange={v=>setAck('projectPayment',v)}>I understand that payment during the project-based stage is agreed per project.</Check><Check checked={acks.earningPotential} onChange={v=>setAck('earningPotential',v)}>I understand that $1,000–$1,500+ per month is a potential earning opportunity and not guaranteed income.</Check><Check checked={acks.earningVariables} onChange={v=>setAck('earningVariables',v)}>I understand that actual earnings depend on available projects, project fees, my capacity, performance and successful delivery.</Check><Check checked={acks.salaryPath} onChange={v=>setAck('salaryPath',v)}>I understand that strong performance for at least six months can create an opportunity to transition into a salaried ProFox role, with salary and applicable terms discussed at that time.</Check><Check checked={form.consentPrivacy} onChange={v=>set('consentPrivacy',v)}>I agree that ProFox may process this information for recruitment and assessment purposes.</Check></Card>
        <button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#000080] px-6 py-4 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg disabled:translate-y-0 disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileText className="h-4 w-4"/>}{busy?(uploadLabel||'Submitting securely...'):'Submit Content Writer Application'}</button><p className="text-center text-xs leading-6 text-slate-500">No full portfolio required yet. Shortlisted applicants receive the next step securely.</p>
      </form>
    </section>

    <section className="bg-white py-16 sm:py-20"><Container><div className="mx-auto max-w-3xl text-center"><Eyebrow>Know before you apply</Eyebrow><H2>Clear Answers. No Hidden Expectations.</H2></div><div className="mx-auto mt-8 max-w-4xl divide-y divide-slate-200 rounded-[2rem] border border-slate-200 bg-white px-6 shadow-sm">{faq.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-left font-black text-[#071126]"><span>{q}</span><ChevronDown className="h-5 w-5 shrink-0 text-slate-400 transition group-open:rotate-180"/></summary><p className="max-w-3xl pt-3 text-sm leading-7 text-slate-600">{a}</p></details>)}</div></Container></section>

    <section className="bg-[#071126] py-16 text-white sm:py-20"><Container><div className="mx-auto max-w-4xl text-center"><div className="text-[11px] font-black uppercase tracking-[.18em] text-emerald-300">Your next project could be the start of something bigger</div><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-5xl">Start Project-Based. Grow Your Earnings. Earn Your Place On The Team.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-8 text-slate-300">If you research before you write, protect the truth behind your copy, meet commitments, handle feedback professionally and consistently produce work the next team can trust—we want to see what you can do.</p><div className="mx-auto mt-7 grid max-w-2xl gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><DollarSign className="mx-auto h-6 w-6 text-emerald-300"/><div className="mt-3 text-2xl font-black">$1,000–$1,500+*</div><div className="mt-1 text-xs font-bold text-slate-400">Monthly project-based earning potential</div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><BriefcaseBusiness className="mx-auto h-6 w-6 text-blue-300"/><div className="mt-3 text-2xl font-black">6+ Months</div><div className="mt-1 text-xs font-bold text-slate-400">Performance-based salaried role opportunity</div></div></div><a href="#apply" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-black text-[#000080] transition hover:-translate-y-0.5 hover:shadow-xl">Apply for Content Writer <ArrowRight className="h-4 w-4"/></a><p className="mx-auto mt-5 max-w-2xl text-[11px] leading-5 text-slate-500">*Actual earnings are not guaranteed and depend on project availability, project fees, capacity, performance and successful delivery.</p></div></Container></section>
  </div>;
}

function CareerVisual({file,alt,eager=false}:{file:string;alt:string;eager?:boolean}){const fallback=`/images/careers/${file}`;return <img src={`/api/r2-media/careers/${file}`} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} onError={event=>{if(!event.currentTarget.src.endsWith(fallback))event.currentTarget.src=fallback}} className="h-full w-full object-cover object-center"/>}
function Container({children}:{children:any}){return <div className="mx-auto max-w-7xl px-6">{children}</div>}
function Eyebrow({children}:{children:string}){return <div className="text-[11px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">{children}</div>}
function H2({children}:{children:any}){return <h2 className="mt-3 text-3xl font-black tracking-[-.035em] text-[#071126] sm:text-4xl">{children}</h2>}
function VisualFrame({children,dark=false}:{children:any;dark?:boolean}){return <div className={`overflow-hidden rounded-[2rem] border shadow-xl ${dark?'border-white/10 bg-white/5 shadow-black/20':'border-slate-200 bg-white shadow-slate-900/5'}`}>{children}</div>}
function MiniCard({title,text,icon}:{title:string;text:string;icon:any}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-md"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-[#000080] [&_svg]:h-4 [&_svg]:w-4">{icon}</div><h3 className="mt-3 text-sm font-black text-[#071126]">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-600">{text}</p></div>}
function ProcessCard({n,title,text}:{n:string;title:string;text:string}){return <div className="rounded-3xl border border-slate-200 bg-[#fbfcff] p-6"><div className="text-xs font-black text-[#FF0E0E]">{n}</div><h3 className="mt-2 text-lg font-black text-[#071126]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>}
function InfoCard({title,text}:{title:string;text:string}){return <div className="rounded-3xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><CheckCircle2 className="h-5 w-5 text-emerald-600"/><h3 className="mt-4 text-base font-black text-[#071126]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>}
function Requirement({title,text}:{title:string;text:string}){return <div className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/><div><div className="text-sm font-black text-[#071126]">{title}</div><p className="mt-1 text-xs leading-5 text-slate-600">{text}</p></div></div>}
function Standard({icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-3xl border border-slate-200 bg-[#fbfcff] p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-[#000080] [&_svg]:h-5 [&_svg]:w-5">{icon}</div><h3 className="mt-4 text-base font-black text-[#071126]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>}
function Card({title,children}:{title:string;children:any}){return <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><h3 className="mb-5 text-sm font-black text-slate-900">{title}</h3><div className="space-y-5">{children}</div></section>}
function Grid({children}:{children:any}){return <div className="grid gap-5 sm:grid-cols-2">{children}</div>}
function Field({label,children}:{label:string;children:any}){return <div className="block text-xs font-bold text-slate-700"><span className="mb-2 block">{label}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-200 [&_input]:bg-slate-50 [&_input]:px-3 [&_input]:py-3 [&_input]:text-sm [&_input]:font-normal [&_input]:outline-none focus-within:[&_input]:border-[#000080]">{children}</div></div>}
function Long({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="block text-xs font-bold text-slate-700"><span className="mb-2 block">{label}</span><textarea required={label.includes('*')} rows={4} value={value} onChange={e=>onChange(e.target.value)} className="w-full resize-y rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-normal outline-none transition focus:border-[#000080]"/></label>}
function Check({checked,onChange,children}:{checked:boolean;onChange:(value:boolean)=>void;children:any}){return <label className="flex cursor-pointer items-start gap-3 text-sm leading-6 text-slate-600"><input required type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-[#000080]"/><span>{children}</span></label>}
