import React,{useEffect,useMemo,useState}from'react';
import{Award,BookOpen,CheckCircle2,ChevronRight,Clock3,Loader2,Lock,ShieldCheck}from'lucide-react';
import ReactMarkdown from'react-markdown';
import{Navigate}from'react-router-dom';
import{useAuth}from'../lib/AuthContext';
import{trainingService,type TrainingLesson,type TrainingModule,type UserProgress}from'../lib/trainingService';
import UIUXFinalCertificationView from'../components/onboarding/UIUXFinalCertificationView';

export default function DesignAcademyPage(){
 const{user,profile,loading:authLoading}=useAuth();
 const[modules,setModules]=useState<TrainingModule[]>([]),[progress,setProgress]=useState<UserProgress[]>([]),[selected,setSelected]=useState<TrainingModule|null>(null),[lessons,setLessons]=useState<TrainingLesson[]>([]),[submission,setSubmission]=useState<any>(null);
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ack,setAck]=useState(false);
 const load=async()=>{if(!user)return;setLoading(true);setError('');try{const[m,p]=await Promise.all([trainingService.getModules(),trainingService.getUserProgress(user.id)]);setModules((m.data||[]).filter(x=>x.training_track==='uiux_design'||x.slug.startsWith('uiux-')||['welcome','confidentiality-data-protection'].includes(x.slug)));setProgress(p.data||[])}catch(e:any){setError(e?.message||'Design Academy could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{if(user)void load()},[user]);
 const item=(id:string)=>progress.find(p=>p.module_id===id);
 const isPassed=(id:string)=>['Passed','Completed'].includes(item(id)?.status||'');
 const locked=(m:TrainingModule)=>{const index=modules.findIndex(x=>x.id===m.id);if(index<=0)return false;return !isPassed(modules[index-1].id)};
 const overall=modules.length?Math.round(modules.filter(m=>isPassed(m.id)).length/modules.length*100):0;
 const open=async(m:TrainingModule)=>{if(!user||locked(m))return;setBusy(true);setError('');try{let p=item(m.id);if(!p){const started=await trainingService.startModule(user.id,m.id);if(started.error||!started.data)throw started.error||new Error('Unable to start module.');p=started.data}const[l,a]=await Promise.all([trainingService.getLessons(m.id),trainingService.getLatestAssignment(user.id,m.id)]);setLessons(l.data||[]);setSubmission(a.data||null);setSelected(m);setAck(false);await load()}catch(e:any){setError(e?.message||'Module could not be opened.')}finally{setBusy(false)}};
 const complete=async()=>{if(!user||!selected)return;const p=item(selected.id);if(!p)return;setBusy(true);try{if(selected.slug==='confidentiality-data-protection'&&!ack)throw new Error('Confirm the confidentiality and data-protection acknowledgement before completing this module.');const evidence={type:selected.slug==='confidentiality-data-protection'?'confidentiality_ack':'uiux_academy_module_complete',slug:selected.slug,acknowledged:true,completedAt:new Date().toISOString()};const saved=await trainingService.saveEvidence(user.id,selected.id,p.id,evidence);if(saved.error)throw saved.error;const done=await trainingService.updateProgress(p.id,{status:'Completed',progress_percent:100,completed_at:new Date().toISOString()});if(done.error)throw done.error;setSelected(null);await load()}catch(e:any){setError(e?.message||'Module could not be completed.')}finally{setBusy(false)}};
 const submitFinal=async(data:any)=>{if(!user||!selected)return;const p=item(selected.id);if(!p)return;setBusy(true);try{const res=await trainingService.submitAssignment(user.id,selected.id,p.id,data);if(res.error)throw res.error;setSubmission(data);await load()}catch(e:any){setError(e?.message||'Certification could not be submitted.')}finally{setBusy(false)}};
 const requestApproval=async()=>{setBusy(true);try{const r=await trainingService.requestFinalApproval();if(r.error)throw r.error;await load();alert('Final Approval request submitted to Management.')}catch(e:any){setError(e?.message||'Final Approval could not be requested.')}finally{setBusy(false)}};
 const completed=useMemo(()=>modules.filter(m=>isPassed(m.id)).length,[modules,progress]);
 if(authLoading)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(!user)return <Navigate to="/admin" replace/>;
 if(profile?.role!=='uiux_designer')return <Navigate to="/admin" replace/>;
 return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <section className="overflow-hidden rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-white/75">ProFox Design Certification</div><h1 className="mt-2 text-3xl font-black">UI/UX Design Onboarding & Academy</h1><p className="mt-3 max-w-2xl text-xs leading-6 text-white/80">Learn the exact PF-SOP-08 operating standard, then prove development-ready delivery through a reviewed final certification. Production My Work remains locked until Management Final Approval and activation.</p></div><div className="min-w-[190px] rounded-2xl border border-white/20 bg-white/10 p-5 text-center backdrop-blur"><div className="text-4xl font-black">{overall}%</div><div className="mt-1 text-[10px] font-black uppercase tracking-widest text-white/70">Certification progress</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full bg-white" style={{width:`${overall}%`}}/></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><HeroMetric icon={<CheckCircle2 className="h-5 w-5 text-emerald-300"/>} value={`${completed}/${modules.length}`} label="Completed"/><HeroMetric icon={<Clock3 className="h-5 w-5 text-amber-300"/>} value={String(progress.filter(p=>p.status==='Submitted').length)} label="Under review"/><HeroMetric icon={<ShieldCheck className="h-5 w-5"/>} value={profile?.status==='active'?'Active':'Onboarding'} label="Account state"/></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {loading&&!modules.length?<div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>:selected?(
   selected.slug==='uiux-final-certification'?<UIUXFinalCertificationView progress={item(selected.id)} latestSubmission={submission} isSubmitting={busy} onSubmit={submitFinal} onRequestFinalApproval={requestApproval} userStatus={profile?.status}/>:<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><button onClick={()=>setSelected(null)} className="mb-5 text-xs font-black text-[#000080]">← Back to curriculum</button><div className="border-b border-slate-100 pb-5"><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#FF0E0E]">Module {selected.sort_order}</div><h2 className="mt-1 text-2xl font-black">{selected.title}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{selected.description}</p></div><div className="mt-6 space-y-5">{lessons.map(l=><article key={l.id} className="prose prose-slate max-w-none rounded-2xl border border-slate-200 bg-slate-50 p-6 text-sm"><ReactMarkdown>{l.content}</ReactMarkdown></article>)}{!lessons.length&&<p className="text-sm text-slate-500">The training content for this module is not available.</p>}</div>{selected.slug==='confidentiality-data-protection'&&<label className="mt-6 flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-900"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} className="mt-0.5 h-4 w-4 accent-[#000080]"/><span>I understand and accept the confidentiality, client-data, approved-tool and data-protection requirements for ProFox UI/UX work.</span></label>}{!isPassed(selected.id)&&<button onClick={()=>void complete()} disabled={busy||!lessons.length||(selected.slug==='confidentiality-data-protection'&&!ack)} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-sm font-black text-white disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}Complete Module</button>}</section>
  ):(<section><div className="mb-4 flex items-end justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#000080]">PF-SOP-08 onboarding path</div><h2 className="mt-1 text-xl font-black">Design Academy Curriculum</h2></div><BookOpen className="h-6 w-6 text-slate-300"/></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map((m,index)=>{const p=item(m.id),isLocked=locked(m),passed=isPassed(m.id),submitted=p?.status==='Submitted',retry=p?.status==='Retry Required';return <button key={m.id} disabled={isLocked} onClick={()=>void open(m)} className={`flex min-h-[190px] flex-col justify-between rounded-3xl border p-5 text-left transition ${isLocked?'cursor-not-allowed border-slate-200 bg-slate-100 opacity-55':'border-slate-200 bg-white hover:border-[#000080]/40 hover:shadow-lg'}`}><div><div className="flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#000080]/10 text-xs font-black text-[#000080]">{index+1}</span>{isLocked?<Lock className="h-4 w-4 text-slate-400"/>:passed?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:submitted?<Clock3 className="h-5 w-5 text-amber-600"/>:retry?<Award className="h-5 w-5 text-red-500"/>:null}</div><h3 className="mt-4 text-sm font-black">{m.title}</h3><p className="mt-2 line-clamp-3 text-xs leading-5 text-slate-500">{m.description}</p></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-[10px] font-black text-[#000080]"><span>{isLocked?'Complete previous module':passed?'Review module':submitted?'Under Management review':retry?'Retry required':p?'Continue':'Start module'}</span><ChevronRight className="h-4 w-4"/></div></button>})}</div></section>)}
 </div></main>
}
function HeroMetric({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/10 p-3"><div>{icon}</div><div><div className="text-base font-black">{value}</div><div className="text-[9px] font-black uppercase tracking-wide text-white/65">{label}</div></div></div>}
