import React, { useEffect, useState } from 'react';
import { CheckCircle2, Clock, CreditCard, FileText, Loader2, ShieldCheck, XCircle } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';

type ClientExpectations = {
  clientResponsibilities?: string[];
  deliveryAssumptions?: string[];
  reviewAndApproval?: string[];
  handoverAndSupport?: string[];
};
type TimelineImpact = 'base' | 'additive' | 'parallel' | 'assessment_required';
type QuoteItem = {
  id:string; productCode:string; productName:string; description?:string; quantity:number; unitPrice:number; lineTotal:number; itemType:string; clientExpectations?:ClientExpectations;
  durationMin?:number|null; durationMax?:number|null; durationUnit?:string; timelineImpact?:TimelineImpact; durationNote?:string|null;
};
type PublicQuote = {
  id:string; quotationNumber:string; customerName:string; contactName?:string; currency:string; status:string; validUntil?:string; paymentTerms?:string; scopeSummary?:string; exclusions?:string; customerNotes?:string; subtotal:number; total:number; sentAt?:string; acceptedAt?:string; firstViewedAt?:string; items:QuoteItem[];
  estimatedDurationMin?:number|null; estimatedDurationMax?:number|null; durationUnit?:string; durationSnapshotText?:string|null; durationSource?:string;
};
type PaymentCta = { paymentId?:string; paymentReference?:string; paymentUrl?:string; paymentType?:string; milestoneLabel?:string; amountDue?:number; currency?:string; status?:string; dueDate?:string };

function money(value:number,currency='USD'){try{return new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(value||0));}catch{return `${currency} ${Number(value||0).toFixed(2)}`;}}
function date(value?:string){if(!value)return '—';const d=new Date(String(value).length===10?`${value}T00:00:00`:value);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});}
function cleanList(value?:string[]){return Array.isArray(value)?value.map(item=>String(item||'').trim()).filter(Boolean):[];}
function hasExpectations(value?:ClientExpectations){if(!value)return false;return cleanList(value.clientResponsibilities).length+cleanList(value.deliveryAssumptions).length+cleanList(value.reviewAndApproval).length+cleanList(value.handoverAndSupport).length>0;}
function durationRange(min?:number|null,max?:number|null){if(min==null||max==null)return '';return min===max?`${min} business days`:`${min}–${max} business days`;}
function itemTimeline(item:QuoteItem){
 if(item.itemType==='care_plan'&&item.timelineImpact==='parallel'&&item.durationMin==null)return 'Ongoing care · no project delivery extension';
 if(item.timelineImpact==='assessment_required')return 'Timeline confirmed in the overall quotation estimate';
 const range=durationRange(item.durationMin,item.durationMax);if(!range)return '';
 if(item.timelineImpact==='additive')return `Adds ${range}${item.quantity>1?` × ${item.quantity}`:''}`;
 if(item.timelineImpact==='parallel')return `${range} · runs in parallel`;
 if(item.timelineImpact==='base')return `Base delivery window · ${range}`;
 return range;
}

export default function PublicQuotationReview(){
 const {token=''}=useParams<{token:string}>();
 const [quote,setQuote]=useState<PublicQuote|null>(null);const[payment,setPayment]=useState<PaymentCta|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[note,setNote]=useState('');const[message,setMessage]=useState('');
 useEffect(()=>{void (async()=>{setLoading(true);setError('');try{const{data,error}=await supabase.rpc('open_public_quotation',{p_token:token});if(error)throw error;const opened=data as PublicQuote;setQuote(opened);if(opened?.status==='Accepted'){const{data:accepted,error:acceptedError}=await supabase.rpc('respond_public_quotation',{p_token:token,p_response:'accept',p_note:''});if(acceptedError)throw acceptedError;if(accepted?.payment)setPayment(accepted.payment as PaymentCta);}}catch(err:any){setError(err?.message||'This quotation could not be opened.');}finally{setLoading(false);}})();},[token]);
 const respond=async(response:'accept'|'reject')=>{if(!quote)return;if(response==='reject'&&!window.confirm('Decline this quotation?'))return;setSaving(true);setError('');setMessage('');try{const{data,error}=await supabase.rpc('respond_public_quotation',{p_token:token,p_response:response,p_note:note.trim()});if(error)throw error;setQuote(current=>current?{...current,status:String(data?.status||current.status),acceptedAt:data?.acceptedAt||current.acceptedAt}:current);if(response==='accept'&&data?.payment)setPayment(data.payment as PaymentCta);setMessage(response==='accept'?'Thank you. Your quotation has been accepted and your approved payment plan is ready.':'Your response has been recorded. ProFox will follow up if needed.');}catch(err:any){setError(err?.message||'Your response could not be recorded.');}finally{setSaving(false);}};
 const expectationItems=(quote?.items||[]).filter(item=>hasExpectations(item.clientExpectations));
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(error&&!quote)return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="max-w-lg rounded-3xl border border-red-200 bg-white p-8 text-center shadow-sm"><XCircle className="mx-auto h-10 w-10 text-red-600"/><h1 className="mt-4 text-xl font-black">Quotation unavailable</h1><p className="mt-2 text-sm leading-6 text-slate-500">{error}</p></div></div>;
 return <div className="min-h-screen bg-slate-50 text-slate-900"><main className="mx-auto max-w-5xl p-4 sm:p-8">{quote&&<div className="space-y-5">
   <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div><div className="inline-flex items-center gap-2 text-[#000080]"><FileText className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-wider">ProFox Quotation</span></div><h1 className="mt-3 text-3xl font-black">{quote.quotationNumber}</h1><p className="mt-2 text-sm text-slate-500">Prepared for {quote.customerName}</p></div><div className="sm:text-right"><div className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-black uppercase text-slate-600">{quote.status}</div><div className="mt-3 text-xs text-slate-500">Valid until {date(quote.validUntil)}</div></div></div></section>
   {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{message}</div>}
   <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-black">Scope & Investment</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50 text-left text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Item</th><th className="px-4 py-3 text-center">Qty</th><th className="px-4 py-3 text-right">Unit Price</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-100">{(quote.items||[]).map(item=><tr key={item.id}><td className="px-5 py-4"><div className="font-black">{item.productName}</div>{item.description&&<div className="mt-1 text-xs leading-5 text-slate-500">{item.description}</div>}{itemTimeline(item)&&<div className="mt-2 inline-flex items-center gap-1 rounded-lg bg-blue-50 px-2 py-1 text-[10px] font-bold text-[#000080]"><Clock className="h-3 w-3"/>{itemTimeline(item)}</div>}</td><td className="px-4 py-4 text-center">{item.quantity}</td><td className="px-4 py-4 text-right">{money(item.unitPrice,quote.currency)}</td><td className="px-5 py-4 text-right font-black">{money(item.lineTotal,quote.currency)}</td></tr>)}</tbody></table></div><div className="border-t border-slate-100 p-5"><div className="ml-auto max-w-sm space-y-2"><div className="flex justify-between text-sm text-slate-500"><span>Subtotal</span><span>{money(quote.subtotal,quote.currency)}</span></div><div className="flex justify-between text-xl font-black"><span>Total</span><span className="text-[#000080]">{money(quote.total,quote.currency)}</span></div></div></div></section>
   {quote.durationSnapshotText&&<section className="rounded-3xl border border-blue-100 bg-blue-50/60 p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-white text-[#000080] shadow-sm"><Clock className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-wider text-[#000080]">Estimated Project Timeline</div><h2 className="mt-2 text-xl font-black">{quote.estimatedDurationMin!=null&&quote.estimatedDurationMax!=null?durationRange(quote.estimatedDurationMin,quote.estimatedDurationMax):'Delivery timing'}</h2><p className="mt-2 max-w-3xl text-sm font-semibold leading-6 text-slate-700">{quote.durationSnapshotText}</p><p className="mt-2 text-xs leading-5 text-slate-500">This estimate is part of this quotation snapshot. It is based on the selected package, add-ons, parallel work, quantities and any Admin-confirmed custom-scope assessment.</p></div></div></section>}
   {(quote.scopeSummary||quote.paymentTerms||quote.exclusions)&&<section className="grid gap-4 md:grid-cols-2"><Info title="Scope Summary" text={quote.scopeSummary||'See quotation items above.'}/><Info title="Payment Terms" text={quote.paymentTerms||'Your approved payment schedule is generated from this quotation after acceptance.'}/>{quote.exclusions&&<div className="md:col-span-2"><Info title="Exclusions" text={quote.exclusions}/></div>}</section>}
   {expectationItems.length>0&&<section className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm sm:p-8"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 text-[#000080]"><ShieldCheck className="h-5 w-5"/><span className="text-[10px] font-black uppercase tracking-wider">Clear delivery expectations</span></div><h2 className="mt-2 text-xl font-black">What you can expect — and what we need from you</h2><p className="mt-2 text-xs leading-5 text-slate-500">These expectations are part of this quotation snapshot. Future Sales Catalog edits do not change the version shown here.</p></div><div className="mt-6 space-y-5">{expectationItems.map(item=><ExpectationCard key={item.id} item={item}/>)}</div></section>}
   {quote.status==='Accepted'&&payment?.paymentUrl&&<section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-emerald-800"><ShieldCheck className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-wider">Approved payment plan generated</span></div><h2 className="mt-2 text-xl font-black text-emerald-950">{payment.milestoneLabel||payment.paymentType||'First payment'}</h2><p className="mt-1 text-sm text-emerald-800">{money(Number(payment.amountDue||0),payment.currency||quote.currency)} · {payment.paymentReference}</p></div><a href={payment.paymentUrl} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-sm font-black text-white"><CreditCard className="h-4 w-4"/>Pay Now</a></div><p className="mt-4 text-xs leading-5 text-emerald-800">The amount above comes directly from the accepted quotation and its snapshotted Sales Catalog payment schedule. It cannot be changed on checkout.</p></section>}
   <section className="rounded-3xl border border-blue-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-black">Your response</h2><p className="mt-2 text-xs leading-5 text-slate-500">Acceptance confirms the scope, exclusions, payment terms, estimated project delivery timeline, and client expectations shown in this quotation. Payment milestones are generated automatically, and the sale becomes Won only after a protected verified Advance/Full payment.</p>{quote.status==='Sent'?<><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="Optional note or question for ProFox..." className="mt-5 min-h-28 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm outline-none focus:border-[#000080]"/><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void respond('accept')} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}Accept Quotation</button><button onClick={()=>void respond('reject')} disabled={saving} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-xs font-black text-slate-700 disabled:opacity-50"><XCircle className="h-4 w-4"/>Decline</button></div></>:<div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm font-semibold text-slate-700">This quotation is currently <strong>{quote.status}</strong>.{quote.status==='Accepted'&&payment?.paymentUrl?' Your payment action is shown above.':' Contact ProFox if you need an updated quotation.'}</div>}</section>
 </div>}</main></div>;
}

function ExpectationCard({item}:{item:QuoteItem}){
 const value=item.clientExpectations||{};
 const groups=[['Your responsibilities',cleanList(value.clientResponsibilities)],['Delivery assumptions',cleanList(value.deliveryAssumptions)],['Review & approval',cleanList(value.reviewAndApproval)],['Handover & support',cleanList(value.handoverAndSupport)]] as Array<[string,string[]]>;
 return <div className="rounded-2xl border border-slate-200 bg-slate-50/60 p-5"><div className="font-black text-slate-900">{item.productName}</div><div className="mt-4 grid gap-4 md:grid-cols-2">{groups.filter(([,items])=>items.length>0).map(([title,items])=><div key={title} className="rounded-xl border border-slate-100 bg-white p-4"><div className="text-[10px] font-black uppercase tracking-wider text-[#000080]">{title}</div><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-600">{items.map((text,index)=><li key={`${title}-${index}`} className="flex gap-2"><span className="mt-0.5 font-black text-[#000080]">•</span><span>{text}</span></li>)}</ul></div>)}</div></div>;
}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="text-[10px] font-black uppercase tracking-wider text-[#000080]">{title}</div><div className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{text}</div></div>}
