import React,{useEffect,useMemo,useState}from'react';
import{CheckCircle2,Loader2,PenLine,ShieldCheck,XCircle}from'lucide-react';
import{useParams}from'react-router-dom';
import{agreementService}from'../lib/agreementService';
import SalesPartnerAgreementDocument from'../components/agreements/SalesPartnerAgreementDocument';
import SignaturePad from'../components/agreements/SignaturePad';

export default function SalesPartnerAgreementSign(){
 const{token=''}=useParams<{token:string}>();const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[name,setName]=useState('');const[signature,setSignature]=useState('');const[acks,setAcks]=useState<Record<string,boolean>>({});const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);const[decline,setDecline]=useState(false);const[reason,setReason]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await agreementService.getPublicAgreement(token);if(!r?.success)throw new Error(r?.error||'Agreement not found.');setData(r.agreement);setName(r.agreement?.partner?.fullName||'');if(r.agreement?.status==='Partner Signed'||r.agreement?.status==='Verified')setDone(true)}catch(e:any){setError(e?.message||'Agreement could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[token]);
 const required=useMemo(()=>data?.template?.acknowledgements||[],[data]);const allAccepted=required.length>0&&required.every((a:any)=>acks[a.key]===true);
 const sign=async()=>{if(!signature||!allAccepted)return;setBusy(true);setError('');try{await agreementService.signPublicAgreement(token,name,signature,acks);setDone(true);await load()}catch(e:any){setError(e?.message||'Agreement could not be signed.')}finally{setBusy(false)}};
 const declineAgreement=async()=>{setBusy(true);setError('');try{await agreementService.declinePublicAgreement(token,reason);setDone(true);setData((d:any)=>({...d,status:'Declined'}))}catch(e:any){setError(e?.message||'Agreement could not be declined.')}finally{setBusy(false)}};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(error&&!data)return <State title="Agreement unavailable" text={error} danger/>;
 if(data?.status==='Declined')return <State title="Agreement declined" text="Your response has been recorded. ProFox will not continue onboarding under this agreement." danger/>;
 if(done)return <State title={data?.status==='Verified'?'Agreement complete':'Signature received'} text={data?.status==='Verified'?'This agreement has been signed and verified by ProFox. The agreement gate is complete.':'Your signature has been securely recorded. ProFox will review and countersign the agreement before onboarding access is unlocked.'}/>;
 return <div className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><div><div className="text-sm font-black text-[#000080]">ProFox</div><div className="text-xs text-slate-500">Secure agreement review & signature</div></div><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><ShieldCheck className="h-4 w-4 text-[#000080]"/>Agreement {data?.agreementNumber}</div></div></header>
  <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><SalesPartnerAgreementDocument agreement={data}/></div>
   <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-3"><PenLine className="mt-1 h-5 w-5 text-[#000080]"/><div><h2 className="text-xl font-black text-[#000080]">Review and sign</h2><p className="mt-1 text-sm leading-6 text-slate-600">Confirm each statement below. Your typed name must match the Agreement Record.</p></div></div>
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mt-6 space-y-3">{required.map((a:any)=><label key={a.key} className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" checked={!!acks[a.key]} onChange={e=>setAcks(v=>({...v,[a.key]:e.target.checked}))} className="mt-1"/><span className="text-sm leading-6 text-slate-700">{a.text||a.label||a.key}</span></label>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><label className="block text-xs font-black text-slate-600">Full legal name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-[#000080]"/></label><SignaturePad onChange={setSignature}/></div>
    <div className="mt-7 flex flex-col gap-3 sm:flex-row"><button type="button" disabled={busy||!signature||!allAccepted||name.trim().toLowerCase()!==String(data?.partner?.fullName||'').trim().toLowerCase()} onClick={()=>void sign()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3.5 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}Sign agreement</button><button type="button" onClick={()=>setDecline(true)} className="rounded-xl border border-slate-300 px-5 py-3.5 text-sm font-bold text-slate-600">Decline</button></div>
    {decline&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5"><label className="text-xs font-black text-red-700">Reason (optional)<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-red-200 bg-white p-3 text-sm text-slate-700"/></label><div className="mt-3 flex gap-2"><button type="button" disabled={busy} onClick={()=>void declineAgreement()} className="rounded-lg bg-red-600 px-4 py-2 text-xs font-bold text-white">Confirm decline</button><button type="button" onClick={()=>setDecline(false)} className="rounded-lg bg-white px-4 py-2 text-xs font-bold text-slate-600">Cancel</button></div></div>}
   </section></main></div>
}
function State({title,text,danger=false}:{title:string;text:string;danger?:boolean}){return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-5"><div className="w-full max-w-xl rounded-3xl border border-slate-200 bg-white p-10 text-center shadow-sm">{danger?<XCircle className="mx-auto h-10 w-10 text-red-500"/>:<CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600"/>}<h1 className="mt-5 text-2xl font-black text-[#000080]">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><div className="mt-7 text-xs font-black text-[#FF0E0E]">From site to system.</div></div></div>}