import React,{useEffect,useMemo,useState}from'react';
import{Navigate,useParams}from'react-router-dom';
import{CheckCircle2,ExternalLink,Loader2,ShieldCheck,XCircle}from'lucide-react';
import{useAuth}from'../lib/AuthContext';
import{uiuxPeopleService,type UIUXApplicant}from'../lib/uiuxPeopleService';

export default function UIUXAcademyReviewPage(){
 const{userId=''}=useParams<{userId:string}>();const{isAdmin,loading:authLoading}=useAuth();
 const[data,setData]=useState<any>(null),[candidate,setCandidate]=useState<UIUXApplicant|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[score,setScore]=useState(90),[feedback,setFeedback]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const[d,a]=await Promise.all([uiuxPeopleService.getAcademyStatus(userId),uiuxPeopleService.getApplicants()]);setData(d);setCandidate(a.find(x=>x.linkedUserId===userId)||null)}catch(e:any){setError(e?.message||'Design Academy review could not be loaded.')}finally{setLoading(false)}};
 useEffect(()=>{if(isAdmin&&userId)void load()},[isAdmin,userId]);
 const modules=Array.isArray(data?.modules)?data.modules:[];const final=useMemo(()=>modules.find((m:any)=>m.slug==='uiux-final-certification'),[modules]);
 const review=async(status:'Passed'|'Retry Required')=>{if(!final?.progressId)return;setBusy(true);setError('');try{if(feedback.trim().length<12)throw new Error('Add specific Management feedback of at least 12 characters.');await uiuxPeopleService.reviewTraining(final.progressId,status,feedback,score);await load()}catch(e:any){setError(e?.message||'Certification review could not be recorded.')}finally{setBusy(false)}};
 if(authLoading)return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;if(!isAdmin)return <Navigate to="/admin/workspace" replace/>;
 return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">People · UI/UX Design</div><h1 className="mt-1 text-2xl font-black">Design Academy Certification Review</h1><p className="mt-2 text-xs leading-5 text-slate-500">Independent Management review of the same canonical training submission required before UI/UX production activation.</p>{candidate&&<div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="font-black">{candidate.fullName}</div><div className="mt-1 text-xs text-slate-500">{candidate.applicationReference} · {candidate.stage} · {candidate.email}</div></div>}</header>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {loading?<div className="flex justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>:<><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{modules.map((m:any)=><div key={m.moduleId} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-2"><div className="text-xs font-black">{m.sortOrder}. {m.title}</div>{['Passed','Completed'].includes(m.status)?<CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600"/>:<span className="text-[9px] font-black text-slate-400">{m.status}</span>}</div>{m.score!=null&&<div className="mt-2 text-xs font-bold text-[#000080]">Score {m.score}%</div>}</div>)}</section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-5"><div><div className="text-[10px] font-black uppercase tracking-[.15em] text-[#000080]">Required reviewed capstone</div><h2 className="mt-1 text-xl font-black">UI/UX Final Certification</h2></div>{final?.status==='Passed'?<span className="rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-black text-emerald-700">Passed</span>:final?.status==='Submitted'?<span className="rounded-full bg-amber-100 px-3 py-1 text-[10px] font-black text-amber-700">Awaiting review</span>:<span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black text-slate-500">{final?.status||'Not started'}</span>}</div>
 {!final?.latestSubmission?<p className="mt-6 text-sm text-slate-500">No certification submission is available yet.</p>:<div className="mt-6 space-y-4"><Evidence label="Figma / design file" value={final.latestSubmission.figmaUrl} link/><Evidence label="UX / business rationale" value={final.latestSubmission.rationale}/><Evidence label="Responsive & states" value={final.latestSubmission.responsive}/><Evidence label="Design system / tokens" value={final.latestSubmission.designSystem}/><Evidence label="Accessibility" value={final.latestSubmission.accessibility}/><Evidence label="Developer handoff" value={final.latestSubmission.handoff}/></div>}
 {final?.progressId&&final?.status==='Submitted'&&<div className="mt-7 border-t border-slate-100 pt-6"><div className="grid gap-4 sm:grid-cols-[160px_1fr]"><label><span className="mb-1.5 block text-[10px] font-black uppercase text-slate-500">Score / 100</span><input type="number" min={0} max={100} value={score} onChange={e=>setScore(Number(e.target.value||0))} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label><span className="mb-1.5 block text-[10px] font-black uppercase text-slate-500">Management feedback *</span><textarea rows={3} value={feedback} onChange={e=>setFeedback(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="What passed, what must change, or why the evidence meets the PF-SOP-08 production-readiness standard."/></label></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||score<90} onClick={()=>void review('Passed')} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-40"><ShieldCheck className="h-4 w-4"/>Pass Certification</button><button disabled={busy} onClick={()=>void review('Retry Required')} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-xs font-black text-red-700"><XCircle className="h-4 w-4"/>Retry Required</button></div></div>}
 {final?.latestReview&&<div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5"><strong>Latest Management review:</strong> {final.latestReview.status} · {final.latestReview.score}%<br/>{final.latestReview.feedback}</div>}
 </section></>}</div></main>
}
function Evidence({label,value,link}:{label:string;value?:string;link?:boolean}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-[9px] font-black uppercase tracking-wide text-slate-400">{label}</div>{link&&value?<a href={value} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-sm font-black text-[#000080]">Open evidence <ExternalLink className="h-4 w-4"/></a>:<div className="mt-2 whitespace-pre-wrap text-xs leading-6 text-slate-700">{value||'Not provided'}</div>}</div>}
