import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const accountsHost=(dc:string)=>({com:"https://accounts.zoho.com",in:"https://accounts.zoho.in",eu:"https://accounts.zoho.eu","com.au":"https://accounts.zoho.com.au",jp:"https://accounts.zoho.jp",ca:"https://accounts.zohocloud.ca",sa:"https://accounts.zoho.sa"} as Record<string,string>)[dc]||"";
const mailHost=(dc:string)=>({com:"https://mail.zoho.com",in:"https://mail.zoho.in",eu:"https://mail.zoho.eu","com.au":"https://mail.zoho.com.au",jp:"https://mail.zoho.jp",ca:"https://mail.zohocloud.ca",sa:"https://mail.zoho.sa"} as Record<string,string>)[dc]||"";
function retryDelay(attempts:number){const base=30;const exp=Math.min(base*Math.pow(2,Math.max(attempts-1,0)),21600);return Math.max(10,Math.round(exp+Math.random()*Math.min(exp*.25,60)));}
function safeError(payload:any,status:number){const parts=[payload?.data?.errorCode,payload?.data?.moreInfo,payload?.status?.description,payload?.error_description,payload?.error,payload?.message].map((v)=>String(v||"").trim()).filter(Boolean);return ([...new Set(parts)].join(" | ")||`Zoho API request failed (${status})`).slice(0,1600);}
function normalizePart(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,".").replace(/^\.+|\.+$/g,"").replace(/\.{2,}/g,".");}
function nameParts(fullName:string,fallbackEmail:string,userId:string){const words=String(fullName||"").trim().split(/\s+/).map(normalizePart).filter(Boolean);if(words.length>=2)return {first:words[0],last:words[words.length-1],base:`${words[0]}.${words[words.length-1]}`.slice(0,48)};if(words.length===1)return {first:words[0],last:"",base:words[0].slice(0,48)};const emailBase=normalizePart(String(fallbackEmail||"").split("@")[0]||"");const base=(emailBase||`employee.${userId.replaceAll("-","").slice(0,8)}`).slice(0,48);return {first:base.split(".")[0]||"employee",last:"",base};}
function tempPassword(){const bytes=new Uint8Array(14);crypto.getRandomValues(bytes);const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";let body="";for(const b of bytes)body+=alphabet[b%alphabet.length];return `Qz@${body}7m`;}
function accountRows(payload:any){const d=payload?.data;return Array.isArray(d)?d:(Array.isArray(d?.accounts)?d.accounts:[]);}
function accountDomains(rows:any[]){const domains=new Set<string>();for(const row of rows){for(const raw of [row?.primaryEmailAddress,row?.mailboxAddress,row?.incomingUserName]){const email=String(raw||"").toLowerCase();const domain=email.includes("@")?email.split("@").pop()||"":"";if(domain)domains.add(domain);}for(const item of Array.isArray(row?.emailAddress)?row.emailAddress:[]){const email=String(item?.mailId||"").toLowerCase();const domain=email.includes("@")?email.split("@").pop()||"":"";if(domain)domains.add(domain);}}return [...domains].sort();}
function isLicenseCapacityError(message:string){return /maximum user license limit reached|purchase\s*\/\s*upgrade license|purchase.*license.*add more user|license limit.*mailbox/i.test(message);}

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")||"";const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!supabaseUrl||!serviceKey)return json({error:"Server configuration unavailable"},500);
 const service=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
 const cronHeader=req.headers.get("x-profox-mailbox-cron-token")||"";const authHeader=req.headers.get("Authorization")||"";const {data:cronSecret}=await service.rpc("service_get_professional_mailbox_cron_secret");const internalAuth=authHeader===`Bearer ${serviceKey}`;if(!internalAuth&&(!cronSecret||cronHeader!==String(cronSecret)))return json({error:"Unauthorized"},401);
 const {data:runtime,error:runtimeError}=await service.rpc("service_get_zoho_org_mail_runtime");if(runtimeError)return json({error:"Zoho Mail runtime configuration could not be loaded."},500);if(String(runtime?.status||"")!=="connected")return json({ok:true,claimed:0,reason:"zoho_mail_not_connected"});
 const dc=String(runtime?.dataCenter||"");const orgId=String(runtime?.organizationId||"");const clientId=String(runtime?.clientId||"");const clientSecret=String(runtime?.clientSecret||"");const refreshToken=String(runtime?.refreshToken||"");const accountBase=accountsHost(dc);const mailBase=mailHost(dc);if(!accountBase||!mailBase||!orgId||!clientId||!clientSecret||!refreshToken)return json({error:"Verified Zoho Mail runtime configuration is incomplete."},503);
 const {data:jobs,error:claimError}=await service.rpc("service_claim_professional_mailbox_jobs",{p_limit:10});if(claimError)return json({error:claimError.message},500);if(!jobs?.length)return json({ok:true,claimed:0,results:[]});
 let token="";try{const tr=await fetch(`${accountBase}/oauth/v2/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret,grant_type:"refresh_token"})});const p:any=await tr.json().catch(()=>({}));if(!tr.ok||!p?.access_token){const m=safeError(p,tr.status);for(const job of jobs)await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:Number(job.attempts)>=8?"dead_letter":"retry",p_error:m,p_retry_seconds:retryDelay(Number(job.attempts))});return json({ok:false,claimed:jobs.length,error:"Zoho token refresh failed."},tr.status>=500?503:400);}token=String(p.access_token);}catch(error){const m=error instanceof Error?error.message:"Zoho token endpoint unavailable.";for(const job of jobs)await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:Number(job.attempts)>=8?"dead_letter":"retry",p_error:m,p_retry_seconds:retryDelay(Number(job.attempts))});return json({ok:false,claimed:jobs.length,error:"Zoho token endpoint unavailable."},503);}
 const results:any[]=[];const headers={Authorization:`Zoho-oauthtoken ${token}`,Accept:"application/json","Content-Type":"application/json"};
 async function getRemote(email:string){const r=await fetch(`${mailBase}/api/organization/${encodeURIComponent(orgId)}/accounts/${encodeURIComponent(email)}`,{headers});const p:any=await r.json().catch(()=>({}));if(r.ok)return {exists:true,payload:p};if(r.status===404)return {exists:false,payload:p};const detail=safeError(p,r.status).toLowerCase();const syntacticallyValid=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);if(r.status===400&&syntacticallyValid&&(detail.includes("invalid input")||detail.includes("input passed is invalid")))return {exists:false,payload:p};if(detail.includes("not found")||detail.includes("no account"))return {exists:false,payload:p};throw Object.assign(new Error(safeError(p,r.status)),{status:r.status});}
 for(const job of jobs){try{
  const {data:profile,error:profileError}=await service.from("user_profiles").select("id,full_name,email,timezone,status,onboarding_status,role").eq("id",job.user_id).maybeSingle();if(profileError||!profile){await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"skipped",p_error:"Employee profile no longer exists."});continue;}
  const {data:eligible,error:eligibilityError}=await service.rpc("service_professional_mailbox_eligible",{p_user_id:job.user_id});if(eligibilityError||eligible!==true){await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"skipped",p_error:"Staff role/status is no longer eligible for Professional Email."});results.push({id:job.id,status:"ineligible_skipped"});continue;}
  const {data:cfgRow}=await service.from("system_configuration").select("config_value").eq("config_key","notification_settings").maybeSingle();const fromEmail=String(cfgRow?.config_value?.fromEmail||"contact@profoxwebdesigner.com").toLowerCase();const domain=fromEmail.split("@")[1]||"profoxwebdesigner.com";const parts=nameParts(String(profile.full_name||""),String(profile.email||""),String(profile.id));
  const listResponse=await fetch(`${mailBase}/api/organization/${encodeURIComponent(orgId)}/accounts?start=0&limit=200`,{headers});const listPayload:any=await listResponse.json().catch(()=>({}));if(!listResponse.ok)throw Object.assign(new Error(`Zoho organization account preflight failed: ${safeError(listPayload,listResponse.status)}`),{status:listResponse.status});const rows=accountRows(listPayload);const domains=accountDomains(rows);if(domains.length>0&&!domains.includes(domain))throw Object.assign(new Error(`Configured professional email domain ${domain} is not present in the connected Zoho Mail organization. Hosted domains observed: ${domains.join(", ")}.`),{terminal:true});const planTypes=[...new Set(rows.map((row:any)=>String(row?.planType??"")).filter(Boolean))];const orgContext=`hostedDomain=${domains.includes(domain)}, existingAccounts=${rows.length}${planTypes.length?`, planTypes=${planTypes.join(",")}`:""}`;
  const {data:localAccount}=await service.from("staff_professional_accounts").select("work_email,mailbox_status,provider_user_id,provider_account_id").eq("user_id",job.user_id).maybeSingle();if(localAccount?.mailbox_status==="active"&&localAccount?.work_email){await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"succeeded",p_work_email:localAccount.work_email,p_provider_user_id:localAccount.provider_user_id||null,p_provider_account_id:localAccount.provider_account_id||null});results.push({id:job.id,status:"already_active"});continue;}
  let chosen="";let remote:any=null;for(let suffix=1;suffix<=100;suffix++){const local=suffix===1?parts.base:`${parts.base}.${suffix}`;const candidate=`${local.slice(0,48)}@${domain}`;const {data:localCollision}=await service.from("staff_professional_accounts").select("user_id").eq("work_email",candidate).neq("user_id",job.user_id).maybeSingle();if(localCollision)continue;const found=await getRemote(candidate);if(!found.exists){chosen=candidate;break;}const rd=found.payload?.data||found.payload;const existingLocalOwner=await service.from("staff_professional_accounts").select("user_id").eq("work_email",candidate).maybeSingle();if(existingLocalOwner.data?.user_id===job.user_id){chosen=candidate;remote={userId:String(rd?.zuid||rd?.userId||""),accountId:String(rd?.accountId||"")};break;}}
  if(!chosen)throw Object.assign(new Error("No collision-safe professional email address was available after 100 attempts."),{terminal:true});if(remote){await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"succeeded",p_work_email:chosen,p_provider_user_id:remote.userId||null,p_provider_account_id:remote.accountId||null,p_initial_password:null});results.push({id:job.id,status:"existing_remote_account_linked",workEmail:chosen});continue;}
  const password=tempPassword();const createBody:Record<string,unknown>={primaryEmailAddress:chosen,password,firstName:parts.first||"employee",displayName:String(profile.full_name||parts.first||"ProFox Employee").slice(0,100),role:"member",timeZone:String(profile.timezone||"Asia/Kolkata"),oneTimePassword:true};if(parts.last)createBody.lastName=parts.last;
  const cr=await fetch(`${mailBase}/api/organization/${encodeURIComponent(orgId)}/accounts`,{method:"POST",headers,body:JSON.stringify(createBody)});const cp:any=await cr.json().catch(()=>({}));if(!cr.ok){let m=safeError(cp,cr.status);if(isLicenseCapacityError(m)){const capacityMessage="Zoho Mail user license capacity is full. Purchase/upgrade a Zoho Mail user license or free an existing license, then rerun this mailbox canary.";await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"dead_letter",p_error:capacityMessage});results.push({id:job.id,status:"license_capacity"});continue;}if(cr.status===400)m=`${m} | Zoho account-create preflight: ${orgContext}. Check Zoho user/license capacity, account-creation restrictions, or whether this address is already attached to another Zoho identity.`;if(cr.status===409||/exist|duplicate/i.test(m)){await sleep(200);const found=await getRemote(chosen);if(found.exists){const d=found.payload?.data||found.payload;await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"succeeded",p_work_email:chosen,p_provider_user_id:String(d?.zuid||d?.userId||"")||null,p_provider_account_id:String(d?.accountId||"")||null,p_initial_password:null});results.push({id:job.id,status:"race_reconciled",workEmail:chosen});continue;}}if(cr.status===401||cr.status===403){await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"skipped",p_error:"Zoho Mail reconnect is required."});results.push({id:job.id,status:"reconnect_required"});continue;}const retry=cr.status===429||cr.status>=500;await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:retry&&Number(job.attempts)<8?"retry":"dead_letter",p_error:m,p_retry_seconds:retryDelay(Number(job.attempts))});results.push({id:job.id,status:retry?"retry":"dead_letter"});continue;}
  const d=cp?.data||{};await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:"succeeded",p_work_email:chosen,p_provider_user_id:String(d?.zuid||d?.userId||"")||null,p_provider_account_id:String(d?.accountId||"")||null,p_initial_password:password});results.push({id:job.id,status:"created",workEmail:chosen});
 }catch(error:any){const m=error instanceof Error?error.message:"Professional mailbox provisioning failed.";const terminal=Boolean(error?.terminal);const retryable=!terminal&&(Number(error?.status||0)===429||Number(error?.status||0)>=500||!error?.status);await service.rpc("service_finish_professional_mailbox_job",{p_job_id:job.id,p_status:retryable&&Number(job.attempts)<8?"retry":"dead_letter",p_error:m,p_retry_seconds:retryDelay(Number(job.attempts))});results.push({id:job.id,status:retryable?"retry":"dead_letter"});}}
 await service.rpc("service_mark_zoho_org_mail_connection_error",{p_status:"connected",p_error:null});return json({ok:true,claimed:jobs.length,results});
});
