import React,{useEffect,useState}from'react';
import{CalendarClock,CheckCircle2,Clock3,ExternalLink,Loader2,RefreshCw,ShieldCheck,UserRound,Users,XCircle}from'lucide-react';
import{TrainingModule,UserProgress}from'../../lib/trainingService';
import{mockCallTrainingService,TraineeMockCall}from'../../lib/mockCallTrainingService';

type Props={module:TrainingModule;progress?:UserProgress;onRefresh:()=>Promise<void>};
const nice=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());
const fmt=(value?:string|null,tz?:string)=>{if(!value)return 'Not scheduled yet';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'full',timeStyle:'short',timeZone:tz||undefined}).format(new Date(value))+(tz?` · ${tz}`:'')}catch{return new Date(value).toLocaleString()}};

export default function AutomatedMockSalesCall({module,progress,onRefresh}:Props){
 const[data,setData]=useState<TraineeMockCall|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=async(show=true)=>{if(show)setLoading(true);setError('');const{data:d,error:e}=await mockCallTrainingService.getMyMockCall(module.id);if(e)setError(e.message||'Mock call details could not be loaded.');else setData(d);if(show)setLoading(false);};
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(false),60000);return()=>window.clearInterval(id)},[module.id,progress?.status]);
 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(error)return <Notice danger>{error}</Notice>;
 if(!data?.hasSession)return <Notice><strong>Your live mock call has not been created yet.</strong><br/>Complete Module 10 — Call Practice, including all drills, rehearsals and assessment availability. The system will then create Module 11 automatically.</Notice>;
 const status=data.status||'pending_assignment';const passed=status==='passed'||progress?.status==='Passed';const retry=status==='retry_required'||progress?.status==='Retry Required';const scheduled=status==='scheduled';
 return <div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 11 · Live Human Certification</div><h2 className="mt-2 text-2xl font-black">Mock Sales Call Test</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Treat this exactly like a real cold-outreach discovery meeting. You know the lead context; your evaluator knows the hidden business situation. Your job is to discover it.</p><div className="mt-5 flex flex-wrap gap-3"><Badge>Attempt {data.attemptNo}</Badge><Badge>{data.scenarioName||'Scenario assigned'}</Badge><Badge>Pass standard {data.passingScore}/100</Badge></div></section>

  {passed&&<section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex gap-4"><CheckCircle2 className="h-8 w-8 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-widest text-emerald-700">Certification passed</div><h3 className="mt-1 text-xl font-black text-emerald-950">Live Mock Sales Call Passed · {data.score}/100</h3><p className="mt-2 text-sm leading-6 text-emerald-900">Your evaluator confirmed that you demonstrated the required live discovery skill. The next Academy module is now available.</p>{data.feedback&&<div className="mt-4 rounded-2xl bg-white p-4 text-sm leading-6 text-emerald-950"><strong>Evaluator coaching:</strong><br/>{data.feedback}</div>}</div></div></section>}
  {retry&&!scheduled&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-4"><XCircle className="h-7 w-7 text-amber-600"/><div><h3 className="font-black text-amber-950">Targeted coaching + retry</h3><p className="mt-1 text-sm leading-6 text-amber-900">Review the feedback below. A fresh scenario and new live retry are created automatically; you do not need Admin to assign one manually.</p>{data.feedback&&<div className="mt-3 rounded-xl bg-white p-3 text-sm">{data.feedback}</div>}</div></div></section>}

  {!passed&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Automation status</div><h3 className="mt-1 text-lg font-black">{scheduled?'Your live call is scheduled':status==='needs_admin_attention'?'Scheduling exception is being reviewed':'Finding the right evaluator and mutual time'}</h3></div><button onClick={()=>void load()} className="rounded-xl border border-slate-200 p-2.5 text-slate-600"><RefreshCw className="h-4 w-4"/></button></div>{scheduled?<div className="mt-5 grid gap-3 sm:grid-cols-3"><Info icon={<CalendarClock className="h-4 w-4"/>} label="Date & time" value={fmt(data.scheduledStartAt,data.timezone)}/><Info icon={<UserRound className="h-4 w-4"/>} label="Evaluator" value={data.evaluatorName||'Assigned evaluator'}/><Info icon={<Clock3 className="h-4 w-4"/>} label="Duration" value={data.scheduledStartAt&&data.scheduledEndAt?`${Math.round((new Date(data.scheduledEndAt).getTime()-new Date(data.scheduledStartAt).getTime())/60000)} minutes`:'Configured automatically'}/></div>:<p className="mt-3 text-sm leading-6 text-slate-500">ProFox is checking evaluator eligibility, tenure, workload, both calendars, time-off, existing meetings and your assessment availability. You do not need to coordinate this manually.</p>}{scheduled&&data.meetingUrl&&<a href={data.meetingUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white">Open Meeting Link<ExternalLink className="h-4 w-4"/></a>}{scheduled&&!data.meetingUrl&&<Notice><strong>Meeting link pending.</strong> Your assigned evaluator can add the approved call link from their evaluator workspace. The schedule remains reserved.</Notice>}</section>}

  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-3"><Users className="h-6 w-6 text-[#000080]"/><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Your simulated cold-outreach lead</div><h3 className="mt-1 text-lg font-black">Seller Brief</h3><p className="mt-1 text-xs leading-5 text-slate-500">This is intentionally all you receive before the call. Hidden pain, budget, decision dynamics and objections stay with the evaluator unless you discover them naturally.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(data.sellerBrief||{}).map(([key,value])=><Brief key={key} label={nice(key)} value={value}/>)}</div></section>

  <section className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm leading-6 text-red-900"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-red-600"/><div><strong>Assessment integrity:</strong> do not ask the evaluator for the hidden scenario before the call. They are instructed to remain in prospect role and reveal private facts only when your discovery earns them.</div></div></section>

  {!!data.history?.length&&<section className="rounded-3xl border border-slate-200 bg-white p-6"><h3 className="font-black">Attempt & coaching history</h3><div className="mt-4 space-y-3">{data.history.map(h=><div key={h.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-sm font-black">Attempt {h.attemptNo} · {h.scenarioName}</div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase">{h.status.replaceAll('_',' ')}</span></div><div className="mt-1 text-xs text-slate-500">{h.scheduledStartAt?fmt(h.scheduledStartAt):'Not scheduled'}{h.score!=null?` · ${h.score}/100`:''}</div>{h.feedback&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm leading-6"><strong>Coaching:</strong> {h.feedback}</div>}</div>)}</div></section>}
 </div>;
}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-black">{children}</span>}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-slate-500">{icon}<span className="text-[10px] font-black uppercase tracking-wider">{label}</span></div><div className="mt-2 text-sm font-black text-slate-900">{value}</div></div>}
function Brief({label,value}:{label:string;value:any}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div>{Array.isArray(value)?<ul className="mt-2 list-disc space-y-1 pl-4 text-sm leading-6 text-slate-800">{value.map((v,i)=><li key={i}>{String(v)}</li>)}</ul>:<div className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-800">{typeof value==='object'?JSON.stringify(value,null,2):String(value??'')}</div>}</div>}
function Notice({danger=false,children}:{danger?:boolean;children:React.ReactNode}){return <div className={`my-4 rounded-2xl border p-4 text-sm leading-6 ${danger?'border-red-200 bg-red-50 text-red-700':'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>}
