import React,{useEffect,useMemo,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CalendarDays,CheckCircle2,Clock3,FlaskConical,Loader2,ShieldCheck,Target}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{trainingService,TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{CalendarTrainingAssessmentResult,CalendarTrainingConfig,CalendarTrainingMission,calendarMeetingTrainingService}from'../../lib/calendarMeetingTrainingService';
import{useAcademyResumeSync}from'../../hooks/useAcademyResumeCheckpoint';

type Props={onCertified?:()=>Promise<void>|void};
type View='learn'|'missions'|'assessment'|'result';
const errorText=(error:any,fallback:string)=>error?.message||fallback;
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const phases=[
 {start:1,end:4,title:'Control Your Capacity'},
 {start:5,end:8,title:'Book Without Friction'},
 {start:9,end:12,title:'Make the Meeting Worth Attending'},
 {start:13,end:16,title:'Run Meetings That Advance the Deal'},
 {start:17,end:20,title:'Capture, Recover & Multiply Time'}
];

export default function CalendarMeetingTraining({onCertified}:Props){
 const{user}=useAuth();
 const[module,setModule]=useState<TrainingModule|null>(null);const[lessons,setLessons]=useState<TrainingLesson[]>([]);const[progress,setProgress]=useState<UserProgress|null>(null);const[config,setConfig]=useState<CalendarTrainingConfig|null>(null);
 const[view,setView]=useState<View>('learn');const[lessonIndex,setLessonIndex]=useState(0);const[missionIndex,setMissionIndex]=useState(0);const[missionPayload,setMissionPayload]=useState<Record<string,any>>({});const[questionIndex,setQuestionIndex]=useState(0);const[confirmStage,setConfirmStage]=useState(false);const[answers,setAnswers]=useState<number[]>([]);const[acks,setAcks]=useState<Record<string,boolean>>({});const[result,setResult]=useState<CalendarTrainingAssessmentResult|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');

 const load=async()=>{if(!user)return;setLoading(true);setError('');try{const[modulesRes,progressRes]=await Promise.all([trainingService.getModules(),trainingService.getUserProgress(user.id)]);if(modulesRes.error)throw modulesRes.error;if(progressRes.error)throw progressRes.error;const target=(modulesRes.data||[]).find(item=>item.slug==='calendar-setup');if(!target)throw new Error('Calendar / Meeting Setup module is unavailable.');setModule(target);let p=(progressRes.data||[]).find(item=>item.module_id===target.id)||null;if(!p){const started=await trainingService.startModule(user.id,target.id);if(started.error)throw started.error;const refreshed=await trainingService.getUserProgress(user.id);p=(refreshed.data||[]).find(item=>item.module_id===target.id)||null;}setProgress(p);const[lessonRes,configRes]=await Promise.all([trainingService.getLessons(target.id),calendarMeetingTrainingService.getConfig(target.id)]);if(lessonRes.error)throw lessonRes.error;if(configRes.error||!configRes.data)throw configRes.error||new Error('Calendar training configuration is unavailable.');const lessonData=lessonRes.data||[];const c=configRes.data;setLessons(lessonData);setConfig(c);setLessonIndex(Math.min(Number(c.lessonsCompleted||0),Math.max(lessonData.length-1,0)));setMissionIndex(Math.min(Number(c.missionsCompleted||0),Math.max(c.missions.length-1,0)));setMissionPayload({});setAnswers(old=>old.length===c.questions.length?old:Array(c.questions.length).fill(-1));setAcks(old=>Object.keys(old).length?old:Object.fromEntries(c.acknowledgements.map(item=>[item.id,false])));if(p?.status==='Passed'||p?.status==='Completed'||c.latestAttempt?.passed)setView('result');else if(c.lessonsCompleted>=lessonData.length&&lessonData.length>0&&c.missionsCompleted<c.missionCount)setView(current=>current==='learn'?'missions':current);else if(c.missionCount>0&&c.missionsCompleted>=c.missionCount)setView(current=>current==='learn'||current==='missions'?'assessment':current);}catch(e:any){setError(errorText(e,'Module 18 could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[user?.id]);

 const certified=progress?.status==='Passed'||progress?.status==='Completed'||result?.passed===true||config?.latestAttempt?.passed===true;
 const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;
 const missionsDone=!!config&&config.missionCount>0&&config.missionsCompleted>=config.missionCount;
 const requiredAcks=useMemo(()=>config?.acknowledgements.filter(item=>item.required)||[],[config]);
 const allAcks=requiredAcks.every(item=>acks[item.id]);
 const allAnswered=!!config&&config.questions.length>0&&answers.length===config.questions.length&&answers.every(v=>Number.isInteger(v)&&v>=0);
 const currentQuestion=config?.questions[questionIndex];const currentMission=config?.missions[missionIndex];const latest=config?.latestAttempt;const phase=phases.find(item=>lessonIndex+1>=item.start&&lessonIndex+1<=item.end)||phases[phases.length-1];

 useAcademyResumeSync(
  loading?null:module?.id,
  !loading&&!certified&&view!=='result',
  {view,lessonIndex,missionKey:currentMission?.missionKey||'',missionPayload,questionIndex,confirmStage,answers,acknowledgements:acks},
  checkpoint=>{
   if(certified)return;
   const savedLesson=Number(checkpoint?.lessonIndex);if(Number.isInteger(savedLesson))setLessonIndex(Math.max(0,Math.min(savedLesson,Math.max(lessons.length-1,0))));
   if(!lessonsDone){setView('learn');return;}
   if(!missionsDone){setView('missions');if(checkpoint?.missionKey===currentMission?.missionKey&&checkpoint?.missionPayload&&typeof checkpoint.missionPayload==='object')setMissionPayload(checkpoint.missionPayload);return;}
   setView('assessment');
   if(progress?.status==='Retry Required'){setQuestionIndex(0);setConfirmStage(false);setAnswers(Array(config?.questions.length||0).fill(-1));setAcks({});return;}
   const savedQuestion=Number(checkpoint?.questionIndex);if(Number.isInteger(savedQuestion))setQuestionIndex(Math.max(0,Math.min(savedQuestion,Math.max((config?.questions.length||1)-1,0))));
   if(Array.isArray(checkpoint?.answers)&&checkpoint.answers.length===(config?.questions.length||0))setAnswers(checkpoint.answers.map((v:any)=>Number.isInteger(v)?v:-1));
   if(checkpoint?.acknowledgements&&typeof checkpoint.acknowledgements==='object')setAcks(checkpoint.acknowledgements);
   setConfirmStage(Boolean(checkpoint?.confirmStage));
  },450
 );

 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');setMessage('');const{data,error:e}=await calendarMeetingTrainingService.completeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(errorText(e,'Lesson progress could not be saved.'));else{const done=Number((data as any)?.lessonsCompleted||0);setConfig(c=>c?{...c,lessonsCompleted:done}:c);if(done>=lessons.length){setView('missions');setMissionIndex(0);setMissionPayload({});setMessage('All calendar lessons are complete. Your isolated scheduling missions are unlocked.');}else setLessonIndex(done);}setBusy(false);};
 const submitMission=async()=>{if(!progress||!currentMission||!config)return;setBusy(true);setError('');setMessage('');const{data,error:e}=await calendarMeetingTrainingService.submitMission(progress.id,currentMission.id,missionPayload);if(e)setError(errorText(e,'Calendar practice mission could not be verified.'));else if(data){setConfig(c=>c?{...c,missionsCompleted:data.missionsCompleted,sandboxSnapshot:data.sandboxSnapshot}:c);setMissionPayload({});if(data.complete){setView('assessment');setQuestionIndex(0);setConfirmStage(false);setMessage('All 10 synthetic calendar missions are verified. The final judgment certification is unlocked.');}else{setMissionIndex(data.missionsCompleted);setMessage(`Mission ${data.missionsCompleted} verified. Continue to the next scheduling task.`);}}setBusy(false);};
 const submitAssessment=async()=>{if(!progress||!config)return;if(!allAnswered){setError('Answer every calendar scenario before submitting.');return;}if(!allAcks){setError('Confirm every required ProFox calendar standard before submitting.');return;}setBusy(true);setError('');const ids=requiredAcks.filter(item=>acks[item.id]).map(item=>item.id);const{data,error:e}=await calendarMeetingTrainingService.submitAssessment(progress.id,answers,ids);if(e)setError(errorText(e,'Calendar certification could not be scored.'));else if(data){setResult(data);setView('result');await load();}setBusy(false);};
 const retake=()=>{if(!config)return;setAnswers(Array(config.questions.length).fill(-1));setAcks(Object.fromEntries(config.acknowledgements.map(item=>[item.id,false])));setQuestionIndex(0);setConfirmStage(false);setResult(null);setError('');setMessage('');setView('assessment');};

 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(!config||!module)return <Notice danger>{error||'Module 18 is unavailable.'}</Notice>;
 if(certified&&view==='result'){const score=result?.score??progress?.score??latest?.score??100;return <div className="space-y-5"><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><div className="flex items-start gap-4"><CheckCircle2 className="h-8 w-8 shrink-0 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Module 18 Certified</div><h2 className="mt-1 text-2xl font-black text-emerald-950">Calendar / Meeting Setup Passed</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-900">You completed the 20-lesson operating standard, all 10 isolated calendar missions and the final scheduling judgment certification. Training never created or changed a live customer meeting.</p><div className="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-black text-emerald-800">Certification score: {score}/100</div>{onCertified&&<button onClick={()=>void onCertified()} className="ml-3 mt-4 rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white">Finish Module & Return</button>}</div></div></section><Framework value={config.framework}/></div>}

 return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 18 · Calendar & Meeting Operating System</div><h2 className="mt-2 text-2xl font-black">Own Your Time. Make Every Meeting Move Revenue Forward.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Protect selling capacity, book internationally without friction, prepare properly, run focused meetings, and turn every legitimate conversation into a clear next action.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<BookOpen className="h-4 w-4"/>} value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat icon={<FlaskConical className="h-4 w-4"/>} value={`${config.missionsCompleted}/${config.missionCount}`} label="Sandbox Missions"/><Stat icon={<Target className="h-4 w-4"/>} value={`${config.passingScore}/100`} label="Pass Standard"/><Stat icon={<ShieldCheck className="h-4 w-4"/>} value="0" label="Critical Misses"/></div></section><Framework value={config.framework}/><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">High-performance meeting standard</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Mini label="Capacity" value={config.operatingStandard?.capacity||''}/><Mini label="Timezone" value={config.operatingStandard?.timezone||''}/><Mini label="Preparation" value={config.operatingStandard?.preparation||''}/><Mini label="Training isolation" value={config.operatingStandard?.trainingIsolation||''}/></div></section>{latest&&!latest.passed&&<Notice><strong>Previous certification:</strong> {latest.score??0}/100 with {latest.criticalMisses??0} critical miss(es). Your lessons and verified missions remain complete; review the coaching and retry only the scenarios.</Notice>}{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 <div className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-1 md:grid-cols-3"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn the System</Tab><Tab active={view==='missions'} disabled={!lessonsDone} onClick={()=>setView('missions')}>2. Synthetic Calendar Missions</Tab><Tab active={view==='assessment'} disabled={!missionsDone} onClick={()=>{setView('assessment');setConfirmStage(false)}}>3. Meeting Judgment Certification</Tab></div>

 {view==='learn'&&lessons[lessonIndex]&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">{phase.title} · Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black text-slate-950">{lessons[lessonIndex].title}</h3></div><BookOpen className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm leading-7"><ReactMarkdown>{lessons[lessonIndex].content||''}</ReactMarkdown></div><div className="mt-5 flex items-center justify-between gap-3"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy||!progress} onClick={()=>void completeLesson()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">I Reviewed the Lesson & Practice Prompt<ArrowRight className="h-4 w-4"/></button>}</div></section>}

 {view==='missions'&&currentMission&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Synthetic mission {missionIndex+1} of {config.missionCount} · Draft saved</div><h3 className="mt-1 text-xl font-black">{currentMission.title}</h3><p className="mt-2 text-sm text-slate-600">{currentMission.objective}</p></div><CalendarDays className="h-7 w-7 shrink-0 text-[#000080]"/></div><div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><strong>Training-only sandbox:</strong> {currentMission.instructions} Nothing submitted here creates, reschedules, cancels or completes a production customer meeting.</div><ScenarioData mission={currentMission}/><div className="mt-5"><MissionForm mission={currentMission} value={missionPayload} onChange={setMissionPayload}/></div><div className="mt-6 flex items-center justify-between gap-3 border-t border-slate-100 pt-5"><div className="text-xs text-slate-500">The server validates this decision before the next mission unlocks.</div><button disabled={busy||!progress} onClick={()=>void submitMission()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><Clock3 className="h-4 w-4"/>{busy?'Verifying...':'Verify Mission & Continue'}</button></div></section>}

 {view==='assessment'&&!confirmStage&&currentQuestion&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Meeting situation {questionIndex+1} of {config.questions.length} · Progress saved</div><h3 className="mt-2 max-w-4xl text-base font-black leading-6 text-slate-950">{currentQuestion.prompt}</h3></div><Target className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="mt-5 grid gap-3">{currentQuestion.options.map((option,index)=><button key={index} type="button" onClick={()=>setAnswers(previous=>previous.map((v,i)=>i===questionIndex?index:v))} className={`rounded-2xl border p-4 text-left text-sm leading-6 transition ${answers[questionIndex]===index?'border-[#000080] bg-blue-50 text-blue-950 ring-2 ring-blue-100':'border-slate-200 bg-white text-slate-700 hover:border-slate-300'}`}><span className="mr-2 font-black">{String.fromCharCode(65+index)}.</span>{option}</button>)}</div><div className="mt-6 flex justify-between"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{questionIndex<config.questions.length-1?<button disabled={answers[questionIndex]<0} onClick={()=>setQuestionIndex(i=>Math.min(config.questions.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-30">Next Scenario<ArrowRight className="h-4 w-4"/></button>:<button disabled={!allAnswered} onClick={()=>setConfirmStage(true)} className="rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white disabled:opacity-30">Review Standards & Submit</button>}</div></section>}

 {view==='assessment'&&confirmStage&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black">Final calendar standards · Progress saved</h3><p className="mt-2 text-sm text-slate-600">Confirm every required standard. Certification requires {config.passingScore}/100 and zero critical failures.</p><div className="mt-5 space-y-3">{config.acknowledgements.map(item=><label key={item.id} className="flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 p-4 text-sm"><input type="checkbox" checked={!!acks[item.id]} onChange={e=>setAcks(v=>({...v,[item.id]:e.target.checked}))} className="mt-1"/><span>{item.statement}</span></label>)}</div><div className="mt-6 flex justify-between"><button onClick={()=>setConfirmStage(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold">Back to Scenarios</button><button disabled={busy||!allAcks||!allAnswered} onClick={()=>void submitAssessment()} className="rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-30">{busy?'Scoring...':'Submit Certification'}</button></div></section>}

 {view==='result'&&!certified&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><div className="text-[10px] font-black uppercase tracking-widest text-amber-700">Retry Required</div><h3 className="mt-1 text-xl font-black text-amber-950">Review the coaching, then retry the judgment scenarios.</h3><p className="mt-2 text-sm text-amber-900">Score: {result?.score??latest?.score??0}/100 · Critical misses: {result?.criticalMisses??latest?.criticalMisses??0}. Your 20 lessons and 10 verified calendar missions remain complete.</p><button onClick={retake} className="mt-5 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white">Retry Certification</button></section>}
 </div>;
}

function ScenarioData({mission}:{mission:CalendarTrainingMission}){const entries=Object.entries(mission.scenarioData||{});if(!entries.length)return null;return <div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-widest text-slate-500">Synthetic scenario facts</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{entries.map(([k,v])=><div key={k} className="rounded-xl bg-white px-3 py-2"><div className="text-[9px] font-black uppercase text-slate-400">{pretty(k)}</div><div className="mt-1 text-xs font-semibold text-slate-700">{Array.isArray(v)?v.join(', '):String(v)}</div></div>)}</div></div>}
function MissionForm({mission,value,onChange}:{mission:CalendarTrainingMission;value:Record<string,any>;onChange:(v:Record<string,any>)=>void}){const set=(k:string,v:any)=>onChange({...value,[k]:v});const text=(k:string,label:string,placeholder='')=><Field label={label}><input value={value[k]||''} onChange={e=>set(k,e.target.value)} placeholder={placeholder} className={input}/></Field>;const area=(k:string,label:string)=><Field label={label}><textarea rows={3} value={value[k]||''} onChange={e=>set(k,e.target.value)} className={input}/></Field>;const dt=(k:string,label:string)=><Field label={label}><input type="datetime-local" value={value[k]||''} onChange={e=>set(k,e.target.value)} className={input}/></Field>;
 switch(mission.missionKey){
  case'configure_availability':return <Grid>{text('timezone','Primary timezone','Asia/Kolkata')}{text('workingDays','Working days','1,2,3,4,5')}{text('workStart','Work start','09:00')}{text('workEnd','Work end','17:00')}<Field label="Availability active"><select value={value.active??''} onChange={e=>set('active',e.target.value)} className={input}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></Field></Grid>;
  case'build_high_performance_day':return <Grid>{text('prospectingBlock','Protected prospecting block')}{text('followUpBlock','Follow-up block')}{text('meetingWindow','Customer meeting window')}{text('crmBlock','CRM/admin block')}{area('priorityRule','Priority rule')}</Grid>;
  case'configure_capacity':return <Grid>{text('defaultDurationMinutes','Default duration (minutes)','30')}{text('bufferBeforeMinutes','Buffer before (minutes)','0')}{text('bufferAfterMinutes','Buffer after (minutes)','15')}{text('maxBackToBack','Maximum back-to-back meetings','2')}</Grid>;
  case'international_discovery':return <Grid>{text('meetingType','Meeting type','Discovery Meeting')}{text('buyerTimezone','Buyer timezone','America/New_York')}{dt('startAt','Meeting start')}{dt('endAt','Meeting end')}{text('confirmedBuyerTime','Buyer-facing confirmed time')}</Grid>;
  case'complete_invite':return <Grid>{text('title','Meeting title')}{text('attendeeName','Attendee name')}{text('attendeeEmail','Attendee email')}{text('meetingType','Meeting type')}{text('platform','Platform')}{area('purpose','Purpose / agenda')}</Grid>;
  case'prepare_meeting_brief':return <Grid>{area('accountContext','Account context')}{area('objective','Meeting objective')}{area('knownFacts','Known facts')}{area('unknowns','Important unknowns')}{area('desiredOutcome','Desired meeting outcome')}</Grid>;
  case'mutual_next_step':return <Grid>{area('action','Action')}{text('owner','Owner')}{dt('dueAt','Due date/time')}{area('expectedOutcome','Expected outcome')}</Grid>;
  case'reschedule_existing':return <Grid><Field label="Action"><select value={value.decision||''} onChange={e=>set('decision',e.target.value)} className={input}><option value="">Select</option><option value="reschedule_existing">Reschedule existing meeting</option><option value="create_duplicate">Create duplicate meeting</option></select></Field>{dt('newStartAt','New start')}{dt('newEndAt','New end')}{area('buyerConfirmation','Buyer confirmation')}</Grid>;
  case'no_show_recovery':return <Grid><Field label="Meeting outcome"><select value={value.outcome||''} onChange={e=>set('outcome',e.target.value)} className={input}><option value="">Select</option><option value="No-Show">No-Show</option><option value="Completed">Completed</option></select></Field><Field label="Recovery action"><select value={value.action||''} onChange={e=>set('action',e.target.value)} className={input}><option value="">Select</option><option value="send_reschedule_once">Send one professional reschedule option</option><option value="mark_attended">Mark attended</option></select></Field>{area('message','Recovery message')}</Grid>;
  case'weekly_calendar_audit':return <Grid>{area('protectedBlocks','Protected selling blocks')}{area('capacityRisk','Capacity / fragmentation risk')}{area('meetingQualityRisk','Meeting-quality risk')}{area('nextWeekImprovement','Next-week improvement')}</Grid>;
  default:return <Grid>{area('response','Your response')}</Grid>;
 }
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span>{children}</label>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 md:grid-cols-2">{children}</div>}
function Framework({value}:{value:string}){return <section className="rounded-3xl border border-blue-200 bg-blue-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Operating framework</div><div className="mt-2 text-sm font-black tracking-wide text-blue-950">{value}</div></section>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</div><p className="mt-1 text-xs leading-5 text-slate-700">{value}</p></div>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-2xl border border-white/15 bg-white/10 p-3"><div className="flex items-center gap-2 text-white/80">{icon}<span className="text-lg font-black text-white">{value}</span></div><div className="mt-1 text-[9px] font-black uppercase tracking-wider text-white/70">{label}</div></div>}
function Tab({active,disabled=false,onClick,children}:{active:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button disabled={disabled} onClick={onClick} className={`rounded-xl px-4 py-3 text-xs font-black transition disabled:cursor-not-allowed disabled:opacity-35 ${active?'bg-[#000080] text-white':'text-slate-600 hover:bg-slate-50'}`}>{children}</button>}
function Notice({children,danger=false}:{children:React.ReactNode;danger?:boolean}){return <div className={`rounded-2xl border p-4 text-sm ${danger?'border-red-200 bg-red-50 text-red-800':'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>}
function pretty(value:string){return value.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,c=>c.toUpperCase())}
