import React,{useEffect,useMemo,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,Clock3,Loader2,Mic2,ShieldCheck,Target,Users}from'lucide-react';
import{TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{CallPracticeConfig,mockCallTrainingService}from'../../lib/mockCallTrainingService';
import{useAcademyResumeSync}from'../../hooks/useAcademyResumeCheckpoint';

type Props={module:TrainingModule;lessons:TrainingLesson[];progress?:UserProgress;onRefresh:()=>Promise<void>};
type View='learn'|'drills'|'rehearse'|'ready';
const criteria=['preparation','openingAgenda','listening','questionQuality','rootCause','businessImpact','outcomePriority','commercialDecision','summary','nextStep'];
const criteriaLabels=['Preparation','Opening & agenda','Listening','Question quality','Root cause','Business impact','Outcome & priority','Commercial & decision context','Summary','Next step'];
const msg=(e:any,f:string)=>e?.message||f;

export default function CallPracticeTraining({module,lessons,progress,onRefresh}:Props){
 const[config,setConfig]=useState<CallPracticeConfig|null>(null);const[view,setView]=useState<View>('learn');
 const[lessonIndex,setLessonIndex]=useState(0);const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);
 const[error,setError]=useState('');const[message,setMessage]=useState('');const[reflections,setReflections]=useState<Record<string,string>>({});
 const[rehearsalNo,setRehearsalNo]=useState(1);const[scores,setScores]=useState<Record<string,number>>(Object.fromEntries(criteria.map(k=>[k,1])));
 const[rehearsalReflection,setRehearsalReflection]=useState('');
 const[timezone,setTimezone]=useState(()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Kolkata');
 const[days,setDays]=useState<number[]>([1,2,3,4,5]);const[workStart,setWorkStart]=useState('09:00');const[workEnd,setWorkEnd]=useState('17:00');
 const[readinessChecked,setReadinessChecked]=useState(false);const[scheduleResult,setScheduleResult]=useState<any>(null);

 const load=async()=>{if(!progress){setLoading(false);return;}setLoading(true);setError('');const{data,error:e}=await mockCallTrainingService.getPracticeConfig(module.id);if(e||!data)setError(msg(e,'Call Practice could not be loaded.'));else{setConfig(data);const done=Number(data.lessonsCompleted||0);setLessonIndex(Math.min(done,Math.max(lessons.length-1,0)));setReflections(Object.fromEntries(data.drills.map(d=>[d.id,d.reflection||''])));const next=Math.min(data.rehearsalsRequired,(data.rehearsals?.length||0)+1);setRehearsalNo(Math.max(1,next));if(data.availability?.timezone)setTimezone(data.availability.timezone);if(Array.isArray(data.availability?.workingDays))setDays(data.availability.workingDays);if(data.availability?.workStart)setWorkStart(data.availability.workStart);if(data.availability?.workEnd)setWorkEnd(data.availability.workEnd);if(data.completed)setView('ready');else if((data.rehearsals?.length||0)>=data.rehearsalsRequired)setView('ready');else if(data.drillsCompleted>=data.requiredDrills)setView('rehearse');else if(done>=lessons.length&&lessons.length)setView('drills');}setLoading(false);};
 useEffect(()=>{void load();},[module.id,progress?.id,progress?.status,lessons.length]);

 const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;
 const drillsDone=!!config&&config.drillsCompleted>=config.requiredDrills;
 const rehearsalsDone=!!config&&(config.rehearsals?.length||0)>=config.rehearsalsRequired;
 const completed=!!config?.completed||progress?.status==='Completed'||progress?.status==='Passed';
 const selfScore=useMemo(()=>Object.values(scores).reduce((a,b)=>a+b,0),[scores]);

 useAcademyResumeSync(
  loading?null:module.id,
  !loading&&!completed,
  {view,lessonIndex,reflections,rehearsalNo,selfRatings:scores,rehearsalReflection,timezone,days,workStart,workEnd,readinessChecked},
  checkpoint=>{
   if(!checkpoint||completed)return;
   const savedReflections=checkpoint.reflections&&typeof checkpoint.reflections==='object'?checkpoint.reflections:{};
   if(config)setReflections(Object.fromEntries(config.drills.map(d=>[d.id,d.completed?(d.reflection||''):(savedReflections[d.id]||d.reflection||'')])));
   if(checkpoint.selfRatings&&typeof checkpoint.selfRatings==='object')setScores({...Object.fromEntries(criteria.map(k=>[k,1])),...checkpoint.selfRatings});
   if(typeof checkpoint.rehearsalReflection==='string')setRehearsalReflection(checkpoint.rehearsalReflection);
   if(typeof checkpoint.timezone==='string'&&checkpoint.timezone)setTimezone(checkpoint.timezone);
   if(Array.isArray(checkpoint.days))setDays(checkpoint.days.filter((v:any)=>Number.isInteger(v)&&v>=0&&v<=6));
   if(typeof checkpoint.workStart==='string')setWorkStart(checkpoint.workStart);
   if(typeof checkpoint.workEnd==='string')setWorkEnd(checkpoint.workEnd);
   setReadinessChecked(Boolean(checkpoint.readinessChecked));
   const savedLesson=Number(checkpoint.lessonIndex);if(Number.isInteger(savedLesson))setLessonIndex(Math.max(0,Math.min(savedLesson,Math.max(lessons.length-1,0))));
   // Server milestones decide the furthest allowed practice phase.
   if(rehearsalsDone)setView('ready');
   else if(drillsDone)setView(checkpoint.view==='ready'?'rehearse':checkpoint.view==='rehearse'?'rehearse':'rehearse');
   else if(lessonsDone)setView(checkpoint.view==='drills'?'drills':'drills');
   else setView('learn');
  },500
 );

 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');const{error:e}=await mockCallTrainingService.completePracticeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(msg(e,'Lesson progress could not be saved.'));else{await onRefresh();await load();}setBusy(false);};
 const completeDrill=async(id:string)=>{if(!progress)return;const reflection=(reflections[id]||'').trim();if(reflection.length<10){setError('Add a short reflection about what you learned from this drill.');return;}setBusy(true);setError('');const{error:e}=await mockCallTrainingService.completePracticeDrill(progress.id,id,reflection);if(e)setError(msg(e,'Practice drill could not be recorded.'));else{setMessage('Practice recorded. Continue to the next skill.');await onRefresh();await load();}setBusy(false);};
 const submitRehearsal=async()=>{if(!progress)return;if(rehearsalReflection.trim().length<20){setError('Add an honest coaching reflection before saving this rehearsal.');return;}setBusy(true);setError('');const{error:e}=await mockCallTrainingService.submitRehearsal(progress.id,rehearsalNo,scores,rehearsalReflection.trim());if(e)setError(msg(e,'Rehearsal could not be saved.'));else{setMessage(`Rehearsal ${rehearsalNo} recorded at ${selfScore}/20. This score is coaching only.`);setRehearsalReflection('');setScores(Object.fromEntries(criteria.map(k=>[k,1])));await onRefresh();await load();}setBusy(false);};
 const finish=async()=>{if(!progress)return;if(!readinessChecked){setError('Confirm the readiness acknowledgement before scheduling your live mock call.');return;}if(!days.length){setError('Choose at least one day when you can attend the live mock call.');return;}setBusy(true);setError('');const{data,error:e}=await mockCallTrainingService.completePracticeAndSchedule(progress.id,{timezone,workingDays:days,workStart,workEnd});if(e)setError(msg(e,'Call Practice could not be completed.'));else{setScheduleResult(data);setMessage('Module 10 is complete. The Module 11 live mock call is now being handled automatically.');await onRefresh();await load();}setBusy(false);};

 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(!progress)return <Notice danger>Training progress is still being prepared. Return to the module list and open Call Practice again.</Notice>;
 if(!config)return <Notice danger>{error||'Call Practice is unavailable.'}</Notice>;

 return <div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl">
   <div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 10 · Deliberate Practice Lab</div><h2 className="mt-2 text-2xl font-black">Call Practice</h2>
   <p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Turn discovery knowledge into calm, adaptive conversation skill before a live human evaluator tests you in Module 11.</p>
   <div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<BookOpen className="h-4 w-4"/>} value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat icon={<Target className="h-4 w-4"/>} value={`${config.drillsCompleted}/${config.requiredDrills}`} label="Required Drills"/><Stat icon={<Mic2 className="h-4 w-4"/>} value={`${config.rehearsals.length}/${config.rehearsalsRequired}`} label="Full Rehearsals"/><Stat icon={<Users className="h-4 w-4"/>} value="Live" label="Next Assessment"/></div>
  </section>
  <section className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-950"><strong>{config.framework}</strong><br/><span className="text-xs">Your self-score is a coaching signal only. Module 11 is the formal live human evaluation. Unsubmitted practice reflections and readiness settings are saved automatically.</span></section>
  {error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}
  <div className="grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 bg-white p-2 sm:grid-cols-4"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn</Tab><Tab active={view==='drills'} disabled={!lessonsDone} onClick={()=>setView('drills')}>2. Skill Drills</Tab><Tab active={view==='rehearse'} disabled={!drillsDone} onClick={()=>setView('rehearse')}>3. Rehearse</Tab><Tab active={view==='ready'} disabled={!rehearsalsDone} onClick={()=>setView('ready')}>4. Ready</Tab></div>

  {view==='learn'&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black">{lessons[lessonIndex]?.title}</h3></div><BookOpen className="h-6 w-6 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm leading-7"><ReactMarkdown>{lessons[lessonIndex]?.content||''}</ReactMarkdown></div><div className="mt-5 flex justify-between"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy} onClick={()=>void completeLesson()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">Mark Learned & Continue<ArrowRight className="h-4 w-4"/></button>}</div></section>}

  {view==='drills'&&<div className="space-y-4"><section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Practice rule:</strong> complete the action out loud or with a practice partner first. Then write what you noticed. Draft reflections auto-save until you submit each drill.</section>{config.drills.map((d,i)=><section key={d.id} className={`rounded-3xl border p-5 shadow-sm ${d.completed?'border-emerald-200 bg-emerald-50':'border-slate-200 bg-white'}`}><div className="flex gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-[#000080]/10 text-xs font-black text-[#000080]">{i+1}</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{d.title}</h3><span className="rounded-full border px-2 py-0.5 text-[10px] font-bold">{d.category}</span>{d.completed&&<CheckCircle2 className="h-4 w-4 text-emerald-600"/>}</div><p className="mt-2 text-sm leading-6 text-slate-600">{d.instructions}</p><label className="mt-4 block text-xs font-black text-slate-600">{d.completionPrompt}<textarea value={reflections[d.id]||''} onChange={e=>setReflections(r=>({...r,[d.id]:e.target.value}))} rows={2} disabled={d.completed} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm font-normal outline-none focus:border-[#000080] disabled:bg-slate-100"/></label>{!d.completed&&<button disabled={busy} onClick={()=>void completeDrill(d.id)} className="mt-3 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-40">I completed this drill</button>}</div></div></section>)}</div>}

  {view==='rehearse'&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Full discovery rehearsal {rehearsalNo} of {config.rehearsalsRequired} · Draft saved</div><h3 className="mt-1 text-lg font-black">Run the conversation before you score it</h3><p className="mt-2 text-sm leading-6 text-slate-500">Use a practice partner or realistic role-play. Score yourself only after the rehearsal. 0 = missed, 1 = partial, 2 = strong.</p></div><Mic2 className="h-6 w-6 text-[#000080]"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{criteria.map((key,i)=><div key={key} className="rounded-2xl border border-slate-200 p-4"><div className="mb-3 text-xs font-black">{criteriaLabels[i]}</div><div className="grid grid-cols-3 gap-2">{[0,1,2].map(v=><button key={v} onClick={()=>setScores(s=>({...s,[key]:v}))} className={`rounded-xl border px-3 py-2 text-xs font-black ${scores[key]===v?'border-[#000080] bg-blue-50 text-[#000080]':'border-slate-200'}`}>{v}</button>)}</div></div>)}</div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="text-sm font-black">Self-coaching score: {selfScore}/20</div><div className="mt-1 text-xs text-slate-500">Suggested readiness reference: {config.readinessBenchmark}/20. This does not pass or fail Module 10.</div></div><textarea rows={4} value={rehearsalReflection} onChange={e=>setRehearsalReflection(e.target.value)} placeholder="What worked? Where did you lose the thread? What will you deliberately improve next time?" className="mt-4 w-full rounded-2xl border border-slate-200 p-4 text-sm outline-none focus:border-[#000080]"/><button disabled={busy} onClick={()=>void submitRehearsal()} className="mt-4 w-full rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">Save Rehearsal & Coaching Review</button>{config.rehearsals.length>0&&<div className="mt-5 flex flex-wrap gap-2">{config.rehearsals.map(r=><span key={r.rehearsalNo} className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">Rehearsal {r.rehearsalNo}: {r.score}/20</span>)}</div>}</section>}

  {view==='ready'&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">{config.completed?<div className="flex gap-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><CheckCircle2 className="h-7 w-7 shrink-0 text-emerald-600"/><div><h3 className="font-black text-emerald-950">Call Practice completed</h3><p className="mt-1 text-sm leading-6 text-emerald-900">The Module 11 live mock-call workflow is automated. Open Module 11 to see your simulated lead, evaluator assignment and schedule status.</p>{scheduleResult?.mockCall?.status&&<p className="mt-2 text-xs font-bold">Automation status: {scheduleResult.mockCall.status}</p>}</div></div>:<><div className="flex items-start gap-3"><Clock3 className="h-6 w-6 text-[#000080]"/><div><h3 className="text-lg font-black">Set your live assessment availability</h3><p className="mt-1 text-sm leading-6 text-slate-500">After you confirm this, ProFox automatically chooses an unseen fake lead, finds an eligible senior evaluator, finds a mutual slot, reserves both calendars and sends the private briefs. These settings auto-save until final submission.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><Field label="Timezone"><input value={timezone} onChange={e=>setTimezone(e.target.value)} className="w-full rounded-xl border p-3 text-sm"/></Field><Field label="Available from"><input type="time" value={workStart} onChange={e=>setWorkStart(e.target.value)} className="w-full rounded-xl border p-3 text-sm"/></Field><Field label="Available until"><input type="time" value={workEnd} onChange={e=>setWorkEnd(e.target.value)} className="w-full rounded-xl border p-3 text-sm"/></Field></div><div className="mt-4"><div className="text-xs font-black text-slate-600">Days you can attend</div><div className="mt-2 flex flex-wrap gap-2">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((label,i)=><button key={label} onClick={()=>setDays(d=>d.includes(i)?d.filter(x=>x!==i):[...d,i].sort())} className={`rounded-xl border px-3 py-2 text-xs font-bold ${days.includes(i)?'border-[#000080] bg-blue-50 text-[#000080]':'border-slate-200'}`}>{label}</button>)}</div></div><label className="mt-5 flex items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6"><input type="checkbox" checked={readinessChecked} onChange={e=>setReadinessChecked(e.target.checked)} className="mt-1"/><span>I completed the practice honestly and understand that Module 11 is a live human assessment. My evaluator receives a private scenario that I must discover naturally during the call.</span></label><button disabled={busy||!readinessChecked} onClick={()=>void finish()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><ShieldCheck className="h-4 w-4"/>{busy?'Scheduling securely...':'Complete Module 10 & Schedule Mock Call'}</button></>}</section>}
 </div>;
}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-2xl border border-white/20 bg-white/10 p-3"><div className="flex items-center gap-2 text-white/80">{icon}<span className="text-[10px] font-bold uppercase tracking-wider">{label}</span></div><div className="mt-1 text-lg font-black">{value}</div></div>}
function Tab({active,disabled,onClick,children}:{active:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button disabled={disabled} onClick={onClick} className={`rounded-xl px-3 py-2.5 text-xs font-black transition disabled:cursor-not-allowed disabled:opacity-35 ${active?'bg-[#000080] text-white':'text-slate-500 hover:bg-slate-50'}`}>{children}</button>}
function Notice({danger=false,children}:{danger?:boolean;children:React.ReactNode}){return <div className={`rounded-2xl border p-4 text-sm ${danger?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-black text-slate-600">{label}<div className="mt-2">{children}</div></label>}
