import React,{useEffect,useMemo,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,FlaskConical,Loader2,ShieldAlert,ShieldCheck,Target}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{trainingService,TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{ConfidentialityTrainingAssessmentResult,ConfidentialityTrainingConfig,ConfidentialityTrainingMission,confidentialityTrainingService}from'../../lib/confidentialityTrainingService';
import{useAcademyResumeSync}from'../../hooks/useAcademyResumeCheckpoint';

type Props={onCertified?:()=>Promise<void>|void};
type View='learn'|'missions'|'assessment'|'result';
const errorText=(e:any,f:string)=>e?.message||f;
const phases=[{start:1,end:4,title:'Protect the Right Information'},{start:5,end:8,title:'Access & Account Security'},{start:9,end:12,title:'Phishing, Communication & Sharing'},{start:13,end:16,title:'Sell Without Leaking Information'},{start:17,end:20,title:'AI, Incidents & Professional Trust'}];

export default function ConfidentialityDataTraining({onCertified}:Props){
 const{user}=useAuth();
 const[module,setModule]=useState<TrainingModule|null>(null);const[lessons,setLessons]=useState<TrainingLesson[]>([]);const[progress,setProgress]=useState<UserProgress|null>(null);const[config,setConfig]=useState<ConfidentialityTrainingConfig|null>(null);
 const[view,setView]=useState<View>('learn');const[lessonIndex,setLessonIndex]=useState(0);const[missionIndex,setMissionIndex]=useState(0);const[decision,setDecision]=useState('');const[notes,setNotes]=useState('');const[questionIndex,setQuestionIndex]=useState(0);const[confirmStage,setConfirmStage]=useState(false);const[answers,setAnswers]=useState<number[]>([]);const[acks,setAcks]=useState<Record<string,boolean>>({});const[result,setResult]=useState<ConfidentialityTrainingAssessmentResult|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=async()=>{if(!user)return;setLoading(true);setError('');try{const[modulesRes,progressRes]=await Promise.all([trainingService.getModules(),trainingService.getUserProgress(user.id)]);if(modulesRes.error)throw modulesRes.error;if(progressRes.error)throw progressRes.error;const target=(modulesRes.data||[]).find(m=>m.slug==='confidentiality-data-protection');if(!target)throw new Error('Confidentiality & Data Protection module is unavailable.');setModule(target);let p=(progressRes.data||[]).find(x=>x.module_id===target.id)||null;if(!p){const started=await trainingService.startModule(user.id,target.id);if(started.error)throw started.error;const refreshed=await trainingService.getUserProgress(user.id);p=(refreshed.data||[]).find(x=>x.module_id===target.id)||null;}setProgress(p);const[lessonRes,configRes]=await Promise.all([trainingService.getLessons(target.id),confidentialityTrainingService.getConfig(target.id)]);if(lessonRes.error)throw lessonRes.error;if(configRes.error||!configRes.data)throw configRes.error||new Error('Confidentiality training configuration is unavailable.');const ls=lessonRes.data||[];const c=configRes.data;setLessons(ls);setConfig(c);setLessonIndex(Math.min(Number(c.lessonsCompleted||0),Math.max(ls.length-1,0)));setMissionIndex(Math.min(Number(c.missionsCompleted||0),Math.max(c.missions.length-1,0)));setDecision('');setNotes('');setAnswers(a=>a.length===c.questions.length?a:Array(c.questions.length).fill(-1));setAcks(a=>Object.keys(a).length?a:Object.fromEntries(c.acknowledgements.map(x=>[x.id,false])));if(p?.status==='Passed'||p?.status==='Completed'||c.latestAttempt?.passed)setView('result');else if(c.lessonsCompleted>=ls.length&&ls.length>0&&c.missionsCompleted<c.missionCount)setView('missions');else if(c.missionCount>0&&c.missionsCompleted>=c.missionCount)setView('assessment');}catch(e:any){setError(errorText(e,'Module 19 could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[user?.id]);
 const certified=progress?.status==='Passed'||progress?.status==='Completed'||result?.passed===true||config?.latestAttempt?.passed===true;const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;const missionsDone=!!config&&config.missionCount>0&&config.missionsCompleted>=config.missionCount;const requiredAcks=useMemo(()=>config?.acknowledgements.filter(x=>x.required)||[],[config]);const allAcks=requiredAcks.every(x=>acks[x.id]);const allAnswered=!!config&&answers.length===config.questions.length&&answers.every(v=>Number.isInteger(v)&&v>=0);const currentMission=config?.missions[missionIndex];const currentQuestion=config?.questions[questionIndex];const latest=config?.latestAttempt;const phase=phases.find(p=>lessonIndex+1>=p.start&&lessonIndex+1<=p.end)||phases[4];

 useAcademyResumeSync(
  loading?null:module?.id,
  !loading&&!certified&&view!=='result',
  {view,lessonIndex,missionKey:currentMission?.missionKey||'',decision,notes,questionIndex,confirmStage,answers,acknowledgements:acks},
  checkpoint=>{
   if(certified)return;
   const savedLesson=Number(checkpoint?.lessonIndex);if(Number.isInteger(savedLesson))setLessonIndex(Math.max(0,Math.min(savedLesson,Math.max(lessons.length-1,0))));
   if(!lessonsDone){setView('learn');return;}
   if(!missionsDone){
    setView('missions');
    if(checkpoint?.missionKey===currentMission?.missionKey){if(typeof checkpoint?.decision==='string')setDecision(checkpoint.decision);if(typeof checkpoint?.notes==='string')setNotes(checkpoint.notes);}
    return;
   }
   setView('assessment');
   if(progress?.status==='Retry Required'){setQuestionIndex(0);setConfirmStage(false);setAnswers(Array(config?.questions.length||0).fill(-1));setAcks({});return;}
   const savedQuestion=Number(checkpoint?.questionIndex);if(Number.isInteger(savedQuestion))setQuestionIndex(Math.max(0,Math.min(savedQuestion,Math.max((config?.questions.length||1)-1,0))));
   if(Array.isArray(checkpoint?.answers)&&checkpoint.answers.length===(config?.questions.length||0))setAnswers(checkpoint.answers.map((v:any)=>Number.isInteger(v)?v:-1));
   if(checkpoint?.acknowledgements&&typeof checkpoint.acknowledgements==='object')setAcks(checkpoint.acknowledgements);
   setConfirmStage(Boolean(checkpoint?.confirmStage));
  },450
 );

 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');const{data,error:e}=await confidentialityTrainingService.completeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(errorText(e,'Lesson progress could not be saved.'));else{const done=Number((data as any)?.lessonsCompleted||0);setConfig(c=>c?{...c,lessonsCompleted:done}:c);if(done>=lessons.length){setView('missions');setMissionIndex(0);setDecision('');setNotes('');setMessage('All confidentiality lessons are complete. Your synthetic security missions are unlocked.');}else setLessonIndex(done);}setBusy(false);};
 const submitMission=async()=>{if(!progress||!currentMission||!decision.trim())return setError('Choose the safest action before submitting.');setBusy(true);setError('');const{data,error:e}=await confidentialityTrainingService.submitMission(progress.id,currentMission.id,{decision,notes});if(e)setError(errorText(e,'Security mission could not be verified.'));else if(data){setConfig(c=>c?{...c,missionsCompleted:data.missionsCompleted,sandboxSnapshot:data.sandboxSnapshot}:c);setDecision('');setNotes('');if(data.complete){setView('assessment');setQuestionIndex(0);setMessage('All 10 synthetic security missions are verified. Final judgment certification is unlocked.');}else{setMissionIndex(data.missionsCompleted);setMessage(`Mission ${data.missionsCompleted} verified. Continue to the next security decision.`);}}setBusy(false);};
 const submitAssessment=async()=>{if(!progress||!config)return;if(!allAnswered)return setError('Answer every scenario before submitting.');if(!allAcks)return setError('Confirm every required confidentiality standard before submitting.');setBusy(true);setError('');const ids=requiredAcks.filter(x=>acks[x.id]).map(x=>x.id);const{data,error:e}=await confidentialityTrainingService.submitAssessment(progress.id,answers,ids);if(e)setError(errorText(e,'Certification could not be scored.'));else if(data){setResult(data);setView('result');await load();}setBusy(false);};
 const retake=()=>{if(!config)return;setAnswers(Array(config.questions.length).fill(-1));setAcks(Object.fromEntries(config.acknowledgements.map(x=>[x.id,false])));setQuestionIndex(0);setConfirmStage(false);setResult(null);setView('assessment');setError('');setMessage('');};
 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;if(!config||!module)return <Notice danger>{error||'Module 19 is unavailable.'}</Notice>;
 if(certified&&view==='result'){const score=result?.score??progress?.score??latest?.score??100;return <div className="space-y-5"><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><div className="flex gap-4"><CheckCircle2 className="h-8 w-8 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-widest text-emerald-700">Module 19 Certified</div><h2 className="mt-1 text-2xl font-black text-emerald-950">Confidentiality & Data Protection Passed</h2><p className="mt-2 text-sm leading-6 text-emerald-900">You completed all lessons, all synthetic security missions and the final judgment certification without using real customer data or credentials.</p><div className="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-black text-emerald-800">Certification score: {score}/100</div>{onCertified&&<button onClick={()=>void onCertified()} className="ml-3 mt-4 rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white">Finish Module & Return</button>}</div></div></section><Framework value={config.framework}/></div>}
 return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 19 · Confidentiality & Data Protection</div><h2 className="mt-2 text-2xl font-black">Protect Trust. Move Fast Safely.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Build fast security judgment: minimize data, protect access, verify unusual requests, share only where authorized, and report incidents immediately.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<BookOpen className="h-4 w-4"/>} value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat icon={<FlaskConical className="h-4 w-4"/>} value={`${config.missionsCompleted}/${config.missionCount}`} label="Synthetic Missions"/><Stat icon={<Target className="h-4 w-4"/>} value={`${config.passingScore}/100`} label="Pass Standard"/><Stat icon={<ShieldCheck className="h-4 w-4"/>} value="0" label="Critical Misses"/></div></section><Framework value={config.framework}/><section className="rounded-3xl border bg-white p-5"><h3 className="font-black">High-performance confidentiality standard</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Mini label="Minimize" value={config.operatingStandard?.minimize||''}/><Mini label="Access" value={config.operatingStandard?.access||''}/><Mini label="Sharing" value={config.operatingStandard?.sharing||''}/><Mini label="Incident response" value={config.operatingStandard?.incident||''}/></div></section>{latest&&!latest.passed&&<Notice><strong>Previous certification:</strong> {latest.score??0}/100 with {latest.criticalMisses??0} critical miss(es). Lessons and missions remain complete; use the coaching and retry only certification.</Notice>}{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}<div className="grid gap-2 rounded-2xl border bg-white p-1 md:grid-cols-3"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn</Tab><Tab active={view==='missions'} disabled={!lessonsDone} onClick={()=>setView('missions')}>2. Security Missions</Tab><Tab active={view==='assessment'} disabled={!missionsDone} onClick={()=>{setView('assessment');setConfirmStage(false)}}>3. Judgment Certification</Tab></div>
 {view==='learn'&&lessons[lessonIndex]&&<section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-5 flex justify-between"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">{phase.title} · Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black">{lessons[lessonIndex].title}</h3></div><BookOpen className="h-6 w-6 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm leading-7"><ReactMarkdown>{lessons[lessonIndex].content||''}</ReactMarkdown></div><div className="mt-5 flex justify-between"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="mr-2 inline h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="rounded-xl border px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="ml-2 inline h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy} onClick={()=>void completeLesson()} className="rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white">I Reviewed & Practised<ArrowRight className="ml-2 inline h-4 w-4"/></button>}</div></section>}
 {view==='missions'&&currentMission&&<section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Synthetic mission {missionIndex+1} of {config.missionCount} · Draft saved</div><h3 className="mt-1 text-xl font-black">{currentMission.title}</h3><p className="mt-2 text-sm text-slate-600">{currentMission.objective}</p></div><ShieldAlert className="h-7 w-7 text-[#000080]"/></div><div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5"><strong>Training-only:</strong> {currentMission.instructions} No real customer data, credentials, exports or incidents are used.</div><ScenarioData mission={currentMission}/><div className="mt-5 grid gap-3">{((currentMission.scenarioData?.options||[])as any[]).map((o:any)=><button key={o.value} onClick={()=>setDecision(o.value)} className={`rounded-2xl border p-4 text-left text-sm ${decision===o.value?'border-[#000080] bg-blue-50 ring-2 ring-blue-100':'border-slate-200'}`}>{o.label}</button>)}<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Briefly explain why this is the safest business action." className="min-h-24 rounded-xl border p-3 text-sm"/></div><div className="mt-6 flex justify-end"><button disabled={busy||!decision} onClick={()=>void submitMission()} className="rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">Verify Mission & Continue</button></div></section>}
 {view==='assessment'&&!confirmStage&&currentQuestion&&<section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Security situation {questionIndex+1} of {config.questions.length} · Progress saved</div><h3 className="mt-2 text-base font-black leading-6">{currentQuestion.prompt}</h3><div className="mt-5 grid gap-3">{currentQuestion.options.map((o,i)=><button key={i} onClick={()=>setAnswers(a=>a.map((v,j)=>j===questionIndex?i:v))} className={`rounded-2xl border p-4 text-left text-sm ${answers[questionIndex]===i?'border-[#000080] bg-blue-50 ring-2 ring-blue-100':'border-slate-200'}`}><b className="mr-2">{String.fromCharCode(65+i)}.</b>{o}</button>)}</div><div className="mt-6 flex justify-between"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>Math.max(0,i-1))} className="rounded-xl border px-4 py-2.5 text-xs font-bold">Previous</button><button onClick={()=>questionIndex<config.questions.length-1?setQuestionIndex(i=>i+1):setConfirmStage(true)} disabled={answers[questionIndex]<0} className="rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">{questionIndex<config.questions.length-1?'Next Scenario':'Review & Certify'}</button></div></section>}
 {view==='assessment'&&confirmStage&&<section className="rounded-3xl border bg-white p-6"><h3 className="text-xl font-black">Required confidentiality acknowledgements · Progress saved</h3><p className="mt-2 text-sm text-slate-600">Confirm each operating standard before certification.</p><div className="mt-5 space-y-3">{config.acknowledgements.map(a=><label key={a.id} className="flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={!!acks[a.id]} onChange={e=>setAcks(x=>({...x,[a.id]:e.target.checked}))}/><span>{a.statement}</span></label>)}</div><div className="mt-6 flex justify-between"><button onClick={()=>setConfirmStage(false)} className="rounded-xl border px-4 py-2.5 text-xs font-bold">Back</button><button disabled={busy||!allAcks||!allAnswered} onClick={()=>void submitAssessment()} className="rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">Submit Secure Certification</button></div></section>}
 {view==='result'&&!certified&&<section className="rounded-3xl border border-rose-200 bg-rose-50 p-7"><h3 className="text-xl font-black text-rose-950">Retry Required</h3><p className="mt-2 text-sm text-rose-900">Score: {result?.score??latest?.score??0}/100 · Critical misses: {result?.criticalMisses??latest?.criticalMisses??0}. Your completed lessons and missions are preserved.</p><button onClick={retake} className="mt-5 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white">Review Coaching & Retry Certification</button></section>}</div>;
}

function Tab({children,active,disabled,onClick}:any){return <button disabled={disabled} onClick={onClick} className={`rounded-xl px-4 py-3 text-xs font-black disabled:opacity-30 ${active?'bg-[#000080] text-white':'text-slate-600'}`}>{children}</button>}
function Stat({icon,value,label}:any){return <div className="rounded-2xl border border-white/20 bg-white/10 p-3"><div className="flex items-center gap-2">{icon}<b>{value}</b></div><div className="mt-1 text-[10px] uppercase tracking-wider text-white/70">{label}</div></div>}
function Framework({value}:{value:string}){return <section className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-center text-sm font-black text-blue-950">{value}</section>}
function Mini({label,value}:any){return <div className="rounded-2xl border bg-slate-50 p-4"><div className="text-[10px] font-black uppercase text-slate-500">{label}</div><div className="mt-1 text-xs leading-5 text-slate-700">{value}</div></div>}
function Notice({children,danger=false}:any){return <div className={`rounded-2xl border p-4 text-sm ${danger?'border-rose-200 bg-rose-50 text-rose-900':'border-amber-200 bg-amber-50 text-amber-900'}`}>{children}</div>}
function ScenarioData({mission}:{mission:ConfidentialityTrainingMission}){const data=mission.scenarioData||{};return <div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">Scenario facts</div><div className="mt-2 grid gap-2 text-xs text-slate-700">{Object.entries(data).filter(([k])=>k!=='options').map(([k,v])=><div key={k}><b>{k.replace(/([A-Z])/g,' $1')}: </b>{Array.isArray(v)?v.join(', '):String(v)}</div>)}</div></div>}
