import React,{useEffect,useMemo,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,Database,FlaskConical,Loader2,RefreshCw,ShieldCheck,Target}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{trainingService,TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{CrmTrainingAssessmentResult,CrmTrainingConfig,CrmTrainingMission,crmTrainingService}from'../../lib/crmTrainingService';
import{useAcademyResumeSync}from'../../hooks/useAcademyResumeCheckpoint';

type Props={onComplete?:()=>void};
type View='learn'|'missions'|'assessment'|'result';
const errorText=(error:any,fallback:string)=>error?.message||fallback;
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';
const phases=[
 {start:1,end:10,title:'CRM Foundations & Activity Discipline'},
 {start:11,end:20,title:'Qualification, Opportunities & Meetings'},
 {start:21,end:30,title:'Commercial Truth, Protection & Handoff'}
];

export default function CrmTraining({onComplete}:Props){
 const{user}=useAuth();
 const[module,setModule]=useState<TrainingModule|null>(null);const[lessons,setLessons]=useState<TrainingLesson[]>([]);const[progress,setProgress]=useState<UserProgress|null>(null);const[config,setConfig]=useState<CrmTrainingConfig|null>(null);
 const[view,setView]=useState<View>('learn');const[lessonIndex,setLessonIndex]=useState(0);const[missionIndex,setMissionIndex]=useState(0);const[missionPayload,setMissionPayload]=useState<Record<string,any>>({});const[questionIndex,setQuestionIndex]=useState(0);const[confirmStage,setConfirmStage]=useState(false);const[answers,setAnswers]=useState<number[]>([]);const[acks,setAcks]=useState<Record<string,boolean>>({});const[result,setResult]=useState<CrmTrainingAssessmentResult|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');

 const load=async()=>{if(!user)return;setLoading(true);setError('');try{const[modulesRes,progressRes]=await Promise.all([trainingService.getModules(),trainingService.getUserProgress(user.id)]);if(modulesRes.error)throw modulesRes.error;if(progressRes.error)throw progressRes.error;const target=(modulesRes.data||[]).find(item=>item.slug==='crm-training');if(!target)throw new Error('CRM Training module is unavailable.');setModule(target);let p=(progressRes.data||[]).find(item=>item.module_id===target.id)||null;if(!p){const started=await trainingService.startModule(user.id,target.id);if(started.error)throw started.error;const refreshed=await trainingService.getUserProgress(user.id);p=(refreshed.data||[]).find(item=>item.module_id===target.id)||null;}setProgress(p);const[lessonRes,configRes]=await Promise.all([trainingService.getLessons(target.id),crmTrainingService.getConfig(target.id)]);if(lessonRes.error)throw lessonRes.error;if(configRes.error||!configRes.data)throw configRes.error||new Error('CRM Training configuration is unavailable.');const lessonData=lessonRes.data||[];const c=configRes.data;setLessons(lessonData);setConfig(c);setLessonIndex(Math.min(Number(c.lessonsCompleted||0),Math.max(lessonData.length-1,0)));setMissionIndex(Math.min(Number(c.missionsCompleted||0),Math.max(c.missions.length-1,0)));setMissionPayload({});setAnswers(old=>old.length===c.questions.length?old:Array(c.questions.length).fill(-1));setAcks(old=>Object.keys(old).length?old:Object.fromEntries(c.acknowledgements.map(item=>[item.id,false])));if(p?.status==='Passed'||p?.status==='Completed'||c.latestAttempt?.passed)setView('result');else if(c.lessonsCompleted>=lessonData.length&&lessonData.length>0&&c.missionsCompleted<c.missionCount)setView(current=>current==='learn'?'missions':current);else if(c.missionCount>0&&c.missionsCompleted>=c.missionCount)setView(current=>current==='learn'||current==='missions'?'assessment':current);}catch(e:any){setError(errorText(e,'Module 17 could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[user?.id]);

 const certified=progress?.status==='Passed'||progress?.status==='Completed'||result?.passed===true||config?.latestAttempt?.passed===true;
 const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;
 const missionsDone=!!config&&config.missionCount>0&&config.missionsCompleted>=config.missionCount;
 const requiredAcks=useMemo(()=>config?.acknowledgements.filter(item=>item.required)||[],[config]);
 const allAcks=requiredAcks.every(item=>acks[item.id]);
 const allAnswered=!!config&&config.questions.length>0&&answers.length===config.questions.length&&answers.every(v=>Number.isInteger(v)&&v>=0);
 const currentQuestion=config?.questions[questionIndex];const currentMission=config?.missions[missionIndex];const latest=config?.latestAttempt;const phase=phases.find(item=>lessonIndex+1>=item.start&&lessonIndex+1<=item.end)||phases[phases.length-1];

 useAcademyResumeSync(
  loading?null:module?.id,
  !loading&&!certified&&view!=='result',
  {view,lessonIndex,missionKey:currentMission?.missionKey||'',missionPayload,questionIndex,confirmStage,answers,acknowledgements:acks},
  checkpoint=>{
   if(certified)return;
   const savedLesson=Number(checkpoint?.lessonIndex);if(Number.isInteger(savedLesson))setLessonIndex(Math.max(0,Math.min(savedLesson,Math.max(lessons.length-1,0))));
   if(!lessonsDone){setView('learn');return;}
   if(!missionsDone){
    setView('missions');
    if(checkpoint?.missionKey===currentMission?.missionKey&&checkpoint?.missionPayload&&typeof checkpoint.missionPayload==='object')setMissionPayload(checkpoint.missionPayload);
    return;
   }
   setView('assessment');
   if(progress?.status==='Retry Required'){setQuestionIndex(0);setConfirmStage(false);setAnswers(Array(config?.questions.length||0).fill(-1));setAcks({});return;}
   const savedQuestion=Number(checkpoint?.questionIndex);if(Number.isInteger(savedQuestion))setQuestionIndex(Math.max(0,Math.min(savedQuestion,Math.max((config?.questions.length||1)-1,0))));
   if(Array.isArray(checkpoint?.answers)&&checkpoint.answers.length===(config?.questions.length||0))setAnswers(checkpoint.answers.map((v:any)=>Number.isInteger(v)?v:-1));
   if(checkpoint?.acknowledgements&&typeof checkpoint.acknowledgements==='object')setAcks(checkpoint.acknowledgements);
   setConfirmStage(Boolean(checkpoint?.confirmStage));
  },450
 );

 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');setMessage('');const{data,error:e}=await crmTrainingService.completeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(errorText(e,'Lesson progress could not be saved.'));else{const done=Number((data as any)?.lessonsCompleted||0);setConfig(c=>c?{...c,lessonsCompleted:done}:c);if(done>=lessons.length){setView('missions');setMissionIndex(0);setMissionPayload({});setMessage('All CRM lessons are complete. Your isolated practice sandbox is unlocked.');}else setLessonIndex(done);}setBusy(false);};
 const submitMission=async()=>{if(!progress||!currentMission||!config)return;setBusy(true);setError('');setMessage('');const{data,error:e}=await crmTrainingService.submitMission(progress.id,currentMission.id,missionPayload);if(e)setError(errorText(e,'CRM practice mission could not be verified.'));else if(data){setConfig(c=>c?{...c,missionsCompleted:data.missionsCompleted,sandboxSnapshot:data.sandboxSnapshot}:c);setMissionPayload({});if(data.complete){setView('assessment');setQuestionIndex(0);setConfirmStage(false);setMessage('All 12 synthetic CRM missions are verified. The final CRM judgment certification is unlocked.');}else{setMissionIndex(data.missionsCompleted);setMessage(`Mission ${data.missionsCompleted} verified. Continue to the next synthetic CRM task.`);}}setBusy(false);};
 const submitAssessment=async()=>{if(!progress||!config)return;if(!allAnswered){setError('Answer every CRM scenario before submitting.');return;}if(!allAcks){setError('Confirm every required ProFox CRM standard before submitting.');return;}setBusy(true);setError('');const ids=requiredAcks.filter(item=>acks[item.id]).map(item=>item.id);const{data,error:e}=await crmTrainingService.submitAssessment(progress.id,answers,ids);if(e)setError(errorText(e,'CRM certification could not be scored.'));else if(data){setResult(data);setView('result');await load();}setBusy(false);};
 const retake=()=>{if(!config)return;setAnswers(Array(config.questions.length).fill(-1));setAcks(Object.fromEntries(config.acknowledgements.map(item=>[item.id,false])));setQuestionIndex(0);setConfirmStage(false);setResult(null);setError('');setMessage('');setView('assessment');};

 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(!config||!module)return <Notice danger>{error||'Module 17 is unavailable.'}</Notice>;
 if(certified&&view==='result'){const score=result?.score??progress?.score??latest?.score??100;return <div className="space-y-5"><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><div className="flex items-start gap-4"><CheckCircle2 className="h-8 w-8 shrink-0 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Module 17 Certified</div><h2 className="mt-1 text-2xl font-black text-emerald-950">CRM Training Passed</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-900">You completed the 30-lesson operating standard, all 12 isolated CRM missions and the final judgment certification. Your practice never touched live customer CRM records.</p><div className="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-black text-emerald-800">Certification score: {score}/100</div>{onComplete&&progress?.status!=='Completed'&&<button onClick={onComplete} className="ml-3 mt-4 rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white">Finish Module & Return</button>}</div></div></section><Framework value={config.framework}/></div>}

 return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 17 · CRM Operational Mastery</div><h2 className="mt-2 text-2xl font-black">CRM Training</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Learn the real ProFox CRM rules, practise the full lifecycle with synthetic records, then prove your judgment before production access.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<BookOpen className="h-4 w-4"/>} value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat icon={<FlaskConical className="h-4 w-4"/>} value={`${config.missionsCompleted}/${config.missionCount}`} label="Sandbox Missions"/><Stat icon={<Target className="h-4 w-4"/>} value={`${config.passingScore}/100`} label="Pass Standard"/><Stat icon={<ShieldCheck className="h-4 w-4"/>} value="0" label="Critical Misses"/></div></section><Framework value={config.framework}/><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">CRM operating standard</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Mini label="Source of truth" value={config.operatingStandard?.sourceOfTruth||''}/><Mini label="Training isolation" value={config.operatingStandard?.trainingIsolation||''}/><Mini label="Stage rule" value={config.operatingStandard?.stageRule||''}/><Mini label="Protected Won" value={config.operatingStandard?.wonRule||''}/></div></section>{latest&&!latest.passed&&<Notice><strong>Previous certification:</strong> {latest.score??0}/100 with {latest.criticalMisses??0} critical miss(es). Your lessons and verified sandbox missions remain complete; review the coaching and retry only the scenarios.</Notice>}{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 <div className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-1 md:grid-cols-3"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn the CRM</Tab><Tab active={view==='missions'} disabled={!lessonsDone} onClick={()=>setView('missions')}>2. Synthetic CRM Missions</Tab><Tab active={view==='assessment'} disabled={!missionsDone} onClick={()=>{setView('assessment');setConfirmStage(false)}}>3. CRM Judgment Certification</Tab></div>

 {view==='learn'&&lessons[lessonIndex]&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">{phase.title} · Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black text-slate-950">{lessons[lessonIndex].title}</h3></div><BookOpen className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm leading-7"><ReactMarkdown>{lessons[lessonIndex].content||''}</ReactMarkdown></div><div className="mt-5 flex items-center justify-between gap-3"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy||!progress} onClick={()=>void completeLesson()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">I Reviewed the Lesson & Practice Prompt<ArrowRight className="h-4 w-4"/></button>}</div></section>}

 {view==='missions'&&currentMission&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Synthetic mission {missionIndex+1} of {config.missionCount} · Draft saved</div><h3 className="mt-1 text-xl font-black">{currentMission.title}</h3><p className="mt-2 text-sm text-slate-600">{currentMission.objective}</p></div><FlaskConical className="h-7 w-7 shrink-0 text-[#000080]"/></div><div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><strong>Training-only sandbox:</strong> {currentMission.instructions} Nothing submitted here creates or edits a production CRM customer record.</div><ScenarioData mission={currentMission}/><div className="mt-5"><MissionForm mission={currentMission} value={missionPayload} onChange={setMissionPayload}/></div><div className="mt-6 flex items-center justify-between gap-3 border-t border-slate-100 pt-5"><div className="text-xs text-slate-500">Server verifies this mission before the next one unlocks.</div><button disabled={busy||!progress} onClick={()=>void submitMission()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><Database className="h-4 w-4"/>{busy?'Verifying...':'Verify Mission & Continue'}</button></div></section>}

 {view==='assessment'&&!confirmStage&&currentQuestion&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">CRM situation {questionIndex+1} of {config.questions.length} · Progress saved</div><h3 className="mt-2 max-w-4xl text-base font-black leading-6 text-slate-950">{currentQuestion.prompt}</h3></div><Target className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="mt-5 grid gap-3">{currentQuestion.options.map((option,index)=><button key={index} type="button" onClick={()=>setAnswers(previous=>previous.map((v,i)=>i===questionIndex?index:v))} className={`rounded-2xl border p-4 text-left text-sm leading-6 transition ${answers[questionIndex]===index?'border-[#000080] bg-blue-50 text-blue-950 ring-2 ring-blue-100':'border-slate-200 bg-white text-slate-700 hover:border-slate-300'}`}><span className="mr-2 font-black">{String.fromCharCode(65+index)}.</span>{option}</button>)}</div><div className="mt-6 flex justify-between"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button><button disabled={answers[questionIndex]<0} onClick={()=>{if(questionIndex>=config.questions.length-1)setConfirmStage(true);else setQuestionIndex(i=>i+1)}} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">{questionIndex>=config.questions.length-1?'Review Standards':'Next Situation'}<ArrowRight className="h-4 w-4"/></button></div></section>}

 {view==='assessment'&&confirmStage&&<section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Final certification check · Progress saved</div><h3 className="mt-1 text-lg font-black">Confirm the ProFox CRM operating standards</h3><p className="mt-1 text-xs leading-5 text-slate-500">Every required acknowledgement must be confirmed before the server scores your CRM scenarios.</p></div><div className="grid gap-3">{config.acknowledgements.map(item=><label key={item.id} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6"><input type="checkbox" checked={!!acks[item.id]} onChange={e=>setAcks(previous=>({...previous,[item.id]:e.target.checked}))} className="mt-1"/><span>{item.statement}{item.required&&<strong className="ml-1 text-red-600">*</strong>}</span></label>)}</div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><strong>Scoring rule:</strong> At least {config.passingScore}/100 and zero critical misses. Falsified source, activity, commercial, payment, Won, data-protection or reporting decisions are automatic retry conditions.</div><div className="flex flex-col gap-3 sm:flex-row"><button onClick={()=>{setConfirmStage(false);setQuestionIndex(config.questions.length-1)}} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-xs font-black"><ArrowLeft className="h-4 w-4"/>Review Answers</button><button disabled={busy||!allAnswered||!allAcks} onClick={()=>void submitAssessment()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><ShieldCheck className="h-4 w-4"/>{busy?'Scoring securely...':'Submit CRM Certification'}</button></div></section>}
 {view==='result'&&!certified&&<FailedResult result={result||latest as any} passingScore={config.passingScore} onRetake={retake}/>}</div>;
}

function ScenarioData({mission}:{mission:CrmTrainingMission}){const entries=Object.entries(mission.scenarioData||{}).filter(([key])=>!['minimumNoteLength','expectedDecision','expectedStage'].includes(key));return <section className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-widest text-slate-500">Synthetic scenario facts</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{entries.map(([key,value])=><div key={key} className="rounded-xl border border-slate-200 bg-white p-3"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{humanize(key)}</div><div className="mt-1 text-xs font-semibold leading-5 text-slate-800">{String(value)}</div></div>)}</div></section>}

function MissionForm({mission,value,onChange}:{mission:CrmTrainingMission;value:Record<string,any>;onChange:(v:Record<string,any>)=>void}){const set=(key:string,v:any)=>onChange({...value,[key]:v});const field=(key:string,label:string,placeholder='',type='text')=><label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span><input type={type} value={value[key]??''} onChange={e=>set(key,e.target.value)} placeholder={placeholder} className={input}/></label>;const area=(key:string,label:string,placeholder='')=><label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span><textarea rows={3} value={value[key]??''} onChange={e=>set(key,e.target.value)} placeholder={placeholder} className={input}/></label>;const select=(key:string,label:string,items:string[])=><label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span><select value={value[key]??''} onChange={e=>set(key,e.target.value)} className={input}><option value="">Select…</option>{items.map(x=><option key={x} value={x}>{x}</option>)}</select></label>;
 switch(mission.missionKey){
  case'create_lead':return <div className="grid gap-4 sm:grid-cols-2">{field('companyName','Company')}{field('contactName','Contact')}{field('email','Business email','','email')}{field('country','Country')}{field('source','Lead source')}{field('serviceInterest','Service interest')}</div>;
  case'record_research':return <div className="grid gap-4 sm:grid-cols-2">{field('industry','Industry')}{field('observedProblem','Observed problem')}<div className="sm:col-span-2">{area('unknowns','Still unknown')}</div><div className="sm:col-span-2">{area('researchNote','Factual research note')}</div></div>;
  case'log_outreach':return <div className="grid gap-4 sm:grid-cols-2">{select('channel','Channel',['Email','LinkedIn','Phone','WhatsApp'])}{select('activityType','Activity type',['Cold Email','Cold Call','LinkedIn / Social Outreach','Loom Outreach'])}{field('subject','Subject / purpose')}<div className="sm:col-span-2">{area('notes','Activity note')}</div></div>;
  case'schedule_follow_up':return <div className="grid gap-4 sm:grid-cols-2">{field('dueAt','Due date & time','','datetime-local')}{select('leadStatus','Lead status',['Follow-Up','Interested','Qualified'])}<div className="sm:col-span-2">{area('purpose','Follow-up purpose')}</div></div>;
  case'qualify_convert':return <div className="grid gap-4"><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold"><input type="checkbox" checked={!!value.qualified} onChange={e=>set('qualified',e.target.checked)}/>Qualification threshold is met from the supplied buyer update</label>{field('opportunityName','Opportunity name')}{area('qualificationReason','Qualification evidence')}</div>;
  case'record_discovery':return <div className="grid gap-4 sm:grid-cols-2">{area('problem','Problem / gap')}{area('desiredOutcome','Desired outcome')}{area('requirements','Confirmed requirements')}{area('decisionMakers','Decision-makers')}{area('timeline','Timeline')}<div className="sm:col-span-2">{area('nextStep','Agreed next step')}</div></div>;
  case'schedule_meeting':return <div className="grid gap-4 sm:grid-cols-2">{field('meetingType','Meeting type')}{field('timezone','Timezone')}{field('attendeeName','Attendee name')}{field('attendeeEmail','Attendee email','','email')}{field('startAt','Start','','datetime-local')}{field('endAt','End','','datetime-local')}</div>;
  case'advance_pipeline':return <div className="grid gap-4">{select('stage','Evidence-supported stage',['Qualified','Meeting Scheduled','Requirements Confirmed','Quotation Sent','Negotiation / Decision Pending','Awaiting Advance Payment','Won'])}{area('nextAction','Next action')}</div>;
  case'record_objection':return <div className="grid gap-4">{area('concern','Buyer concern')}{area('responseBoundary','Approved response boundary')}{area('nextStep','Exact next step')}</div>;
  case'record_quotation':return <div className="grid gap-4 sm:grid-cols-2">{field('quotationReference','Quotation reference')}{select('stage','Opportunity stage',['Requirements Confirmed','Quotation Sent','Negotiation / Decision Pending','Awaiting Advance Payment','Won'])}<div className="sm:col-span-2">{area('followUpPurpose','Quotation follow-up purpose')}</div></div>;
  case'handle_payment_claim':return <div className="grid gap-4">{select('decision','CRM action',['record_pending_verification','mark_verified','mark_won'])}{select('stage','Opportunity stage',['Quotation Sent','Negotiation / Decision Pending','Awaiting Advance Payment','Won'])}</div>;
  case'verified_handoff':return <div className="grid gap-4">{select('decision','Action after protected verification',['advance_after_verified_payment','keep_pending','mark_won_without_verification'])}</div>;
  default:return <Notice danger>This mission form is not configured.</Notice>;
 }
}

function FailedResult({result,passingScore,onRetake}:{result:any;passingScore:number;onRetake:()=>void}){const feedback=Array.isArray(result?.feedback)?result.feedback.filter((item:any)=>!item.correct):[];return <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-start gap-3"><RefreshCw className="mt-1 h-6 w-6 shrink-0 text-amber-700"/><div className="w-full"><div className="text-[10px] font-black uppercase tracking-widest text-amber-700">Retry Required</div><h3 className="mt-1 text-xl font-black text-amber-950">CRM certification needs another attempt</h3><p className="mt-2 text-sm text-amber-900">Score: {result?.score??0}/100 · Pass: {passingScore}/100 · Critical misses: {result?.criticalMisses??0}. Your 30 lessons and 12 verified sandbox missions stay complete.</p>{feedback.length>0&&<div className="mt-4 space-y-2">{feedback.map((item:any)=><div key={item.questionId||item.sortOrder} className="rounded-xl bg-white/80 p-3 text-xs leading-5 text-amber-950"><strong>Situation {item.sortOrder}{item.criticalMiss?' · Critical':''}:</strong> {item.explanation}</div>)}</div>}<button onClick={onRetake} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white"><RefreshCw className="h-4 w-4"/>Retry CRM Scenarios</button></div></div></section>}
function Framework({value}:{value:string}){return <section className="rounded-3xl border border-blue-200 bg-blue-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Permanent CRM framework</div><div className="mt-2 text-sm font-black leading-6 text-blue-950">{value}</div></section>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-2xl border border-white/15 bg-white/10 p-3"><div className="flex items-center gap-2 text-white/80">{icon}<span className="text-[9px] font-black uppercase tracking-wider">{label}</span></div><div className="mt-1 text-lg font-black">{value}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-xs font-semibold leading-5 text-slate-700">{value}</div></div>}
function Tab({active,disabled,onClick,children}:{active:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button disabled={disabled} onClick={onClick} className={`rounded-xl px-4 py-3 text-xs font-black transition ${active?'bg-[#000080] text-white':'text-slate-600 hover:bg-slate-50'} disabled:cursor-not-allowed disabled:opacity-35`}>{children}</button>}
function Notice({children,danger=false}:{children:React.ReactNode;danger?:boolean}){return <div className={`rounded-2xl border p-4 text-sm leading-6 ${danger?'border-red-200 bg-red-50 text-red-800':'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>}
function humanize(value:string){return value.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
