import React,{useEffect,useMemo,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,Loader2,MessageCircleMore,RefreshCw,ShieldCheck,Target}from'lucide-react';
import{TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{ObjectionAssessmentResult,ObjectionTrainingConfig,objectionHandlingTrainingService}from'../../lib/objectionHandlingTrainingService';
import{useStandardAssessmentResume}from'../../hooks/useStandardAssessmentResume';

type Props={module:TrainingModule;lessons:TrainingLesson[];progress?:UserProgress;onRefresh:()=>Promise<void>};
type View='learn'|'assessment'|'result';
const errorText=(error:any,fallback:string)=>error?.message||fallback;

export default function ObjectionHandlingTraining({module,lessons,progress,onRefresh}:Props){
 const[config,setConfig]=useState<ObjectionTrainingConfig|null>(null);const[view,setView]=useState<View>('learn');
 const[lessonIndex,setLessonIndex]=useState(0);const[questionIndex,setQuestionIndex]=useState(0);const[confirmStage,setConfirmStage]=useState(false);
 const[answers,setAnswers]=useState<number[]>([]);const[acks,setAcks]=useState<Record<string,boolean>>({});const[result,setResult]=useState<ObjectionAssessmentResult|null>(null);
 const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');

 const load=async()=>{setLoading(true);setError('');try{const{data,error:e}=await objectionHandlingTrainingService.getConfig(module.id);if(e||!data)throw e||new Error('Objection Handling configuration is unavailable.');setConfig(data);const done=Number(data.lessonsCompleted||0);setLessonIndex(Math.min(done,Math.max(lessons.length-1,0)));setAnswers(old=>old.length===data.questions.length?old:Array(data.questions.length).fill(-1));setAcks(old=>Object.keys(old).length?old:Object.fromEntries(data.acknowledgements.map(item=>[item.id,false])));if(progress?.status==='Passed'||progress?.status==='Completed'||data.latestAttempt?.passed)setView('result');else if(done>=lessons.length&&lessons.length>0)setView(current=>current==='learn'?'assessment':current);}catch(e:any){setError(errorText(e,'Module 13 could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[module.id,progress?.status,lessons.length]);

 const certified=progress?.status==='Passed'||progress?.status==='Completed'||result?.passed===true||config?.latestAttempt?.passed===true;
 const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;
 const requiredAcks=useMemo(()=>config?.acknowledgements.filter(item=>item.required)||[],[config]);
 const allAcks=requiredAcks.every(item=>acks[item.id]);const allAnswered=!!config&&config.questions.length>0&&answers.length===config.questions.length&&answers.every(v=>Number.isInteger(v)&&v>=0);
 const currentQuestion=config?.questions[questionIndex];const latest=config?.latestAttempt;

 useStandardAssessmentResume({moduleId:module.id,loading,terminal:certified,retryRequired:progress?.status==='Retry Required',lessonsDone,lessonCount:lessons.length,questionCount:config?.questions.length||0,view,lessonIndex,questionIndex,confirmStage,answers,acknowledgements:acks,setView,setLessonIndex,setQuestionIndex,setConfirmStage,setAnswers,setAcknowledgements:setAcks});

 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');setMessage('');const{data,error:e}=await objectionHandlingTrainingService.completeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(errorText(e,'Lesson progress could not be saved.'));else{const done=Number((data as any)?.lessonsCompleted||0);setConfig(c=>c?{...c,lessonsCompleted:done}:c);await onRefresh();if(done>=lessons.length){setView('assessment');setQuestionIndex(0);setConfirmStage(false);setMessage('All Objection Handling lessons are complete. Your buyer-resistance certification is unlocked.');}else setLessonIndex(done);}setBusy(false);};
 const submit=async()=>{if(!progress||!config)return;if(!allAnswered){setError('Answer every objection scenario before submitting.');return;}if(!allAcks){setError('Confirm every required ProFox objection-handling standard before submitting.');return;}setBusy(true);setError('');const ids=requiredAcks.filter(item=>acks[item.id]).map(item=>item.id);const{data,error:e}=await objectionHandlingTrainingService.submitAssessment(progress.id,answers,ids);if(e)setError(errorText(e,'Objection Handling certification could not be scored.'));else if(data){setResult(data);setView('result');await onRefresh();await load();}setBusy(false);};
 const retake=()=>{if(!config)return;setAnswers(Array(config.questions.length).fill(-1));setAcks(Object.fromEntries(config.acknowledgements.map(item=>[item.id,false])));setQuestionIndex(0);setConfirmStage(false);setResult(null);setError('');setMessage('');setView('assessment');};

 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(!config)return <Notice danger>{error||'Module 13 is unavailable.'}</Notice>;

 if(certified&&view==='result'){
  const score=result?.score??progress?.score??latest?.score??100;
  return <div className="space-y-5"><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><div className="flex items-start gap-4"><CheckCircle2 className="h-8 w-8 shrink-0 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Module 13 Certified</div><h2 className="mt-1 text-2xl font-black text-emerald-950">Objection Handling Passed</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-900">You demonstrated the ProFox standard: diagnose resistance before responding, use evidence instead of pressure, protect commercial authority and trust, respect genuine rejection, and advance only when the concern is actually resolved.</p><div className="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-black text-emerald-800">Certification score: {score}/100</div></div></div></section><Framework value={config.framework}/></div>;
 }

 return <div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 13 · Buyer Resistance & Trust</div><h2 className="mt-2 text-2xl font-black">Objection Handling</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Do not fight the objection. Find what is really stopping the buyer, determine whether ProFox can responsibly resolve it, and move forward without pressure or manipulation.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<BookOpen className="h-4 w-4"/>} value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat icon={<Target className="h-4 w-4"/>} value={`${config.passingScore}/100`} label="Pass Standard"/><Stat icon={<ShieldCheck className="h-4 w-4"/>} value="0" label="Critical Misses"/><Stat icon={<MessageCircleMore className="h-4 w-4"/>} value="Module 14" label="Closing Next"/></div></section>

  <Framework value={config.framework}/>
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Objection operating standard</h3><p className="mt-1 text-xs leading-5 text-slate-500">The goal is clarity, not winning an argument. A truthful “not now” or “not a fit” is better than a manipulated yes.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Mini label="Diagnose first" value={config.operatingStandard?.diagnoseFirst||'Question before answer'}/><Mini label="Response" value={config.operatingStandard?.responseRule||'Truth + relevant evidence'}/><Mini label="Escalation" value={config.operatingStandard?.escalationRule||'Verify unknowns before promise'}/><Mini label="Stop rule" value={config.operatingStandard?.stopRule||'Respect rejection & no-contact'}/></div></section>

  {latest&&!latest.passed&&<Notice><strong>Previous attempt:</strong> {latest.score??0}/100 with {latest.criticalMisses??0} critical miss(es). Review the coaching explanations, then retry the buyer scenarios.</Notice>}
  {error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}
  <div className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-1"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn Objection Handling</Tab><Tab active={view==='assessment'} disabled={!lessonsDone} onClick={()=>{setView('assessment');setConfirmStage(false)}}>2. Buyer Scenario Certification</Tab></div>

  {view==='learn'&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black text-slate-950">{lessons[lessonIndex]?.title}</h3></div><BookOpen className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm leading-7"><ReactMarkdown>{lessons[lessonIndex]?.content||''}</ReactMarkdown></div><div className="mt-5 flex items-center justify-between gap-3"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy||!progress} onClick={()=>void completeLesson()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">Mark Learned & Continue<ArrowRight className="h-4 w-4"/></button>}</div></section>}

  {view==='assessment'&&!confirmStage&&currentQuestion&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Buyer objection {questionIndex+1} of {config.questions.length} · Progress saved</div><h3 className="mt-2 max-w-4xl text-base font-black leading-6 text-slate-950">{currentQuestion.prompt}</h3></div><Target className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="mt-5 grid gap-3">{currentQuestion.options.map((option,index)=><button key={index} type="button" onClick={()=>setAnswers(previous=>previous.map((v,i)=>i===questionIndex?index:v))} className={`rounded-2xl border p-4 text-left text-sm leading-6 transition ${answers[questionIndex]===index?'border-[#000080] bg-blue-50 text-blue-950 ring-2 ring-blue-100':'border-slate-200 bg-white text-slate-700 hover:border-slate-300'}`}><span className="mr-2 font-black">{String.fromCharCode(65+index)}.</span>{option}</button>)}</div><div className="mt-6 flex justify-between"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button><button disabled={answers[questionIndex]<0} onClick={()=>{if(questionIndex>=config.questions.length-1)setConfirmStage(true);else setQuestionIndex(i=>i+1)}} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">{questionIndex>=config.questions.length-1?'Review Standards':'Next Situation'}<ArrowRight className="h-4 w-4"/></button></div></section>}

  {view==='assessment'&&confirmStage&&<section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Final certification check · Progress saved</div><h3 className="mt-1 text-lg font-black">Confirm the ProFox objection-handling standards</h3><p className="mt-1 text-xs leading-5 text-slate-500">Every required acknowledgement must be confirmed before the server scores your buyer scenarios.</p></div><div className="grid gap-3">{config.acknowledgements.map(item=><label key={item.id} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6"><input type="checkbox" checked={!!acks[item.id]} onChange={e=>setAcks(previous=>({...previous,[item.id]:e.target.checked}))} className="mt-1"/><span>{item.statement}{item.required&&<strong className="ml-1 text-red-600">*</strong>}</span></label>)}</div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><strong>Scoring rule:</strong> At least {config.passingScore}/100 and zero critical misses. Objection Handling resolves resistance; Module 14 teaches decision/closing discipline after major concerns are addressed.</div><div className="flex flex-col gap-3 sm:flex-row"><button onClick={()=>{setConfirmStage(false);setQuestionIndex(config.questions.length-1)}} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-xs font-black"><ArrowLeft className="h-4 w-4"/>Review Answers</button><button disabled={busy||!allAnswered||!allAcks} onClick={()=>void submit()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><ShieldCheck className="h-4 w-4"/>{busy?'Scoring securely...':'Submit Objection Certification'}</button></div></section>}

  {view==='result'&&!certified&&<FailedResult result={result||latest as any} passingScore={config.passingScore} onRetake={retake}/>} 
 </div>;
}

function FailedResult({result,passingScore,onRetake}:{result:any;passingScore:number;onRetake:()=>void}){const feedback=Array.isArray(result?.feedback)?result.feedback.filter((item:any)=>!item.correct):[];return <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><RefreshCw className="h-6 w-6 shrink-0 text-amber-700"/><div className="flex-1"><div className="text-[10px] font-black uppercase tracking-widest text-amber-700">Retry Required</div><h3 className="mt-1 text-xl font-black text-amber-950">Score {result?.score??0}/100 · {result?.criticalMisses??0} critical miss(es)</h3><p className="mt-2 text-sm leading-6 text-amber-900">You need at least {passingScore}/100 and zero critical misses. Your completed lessons stay complete; review the coaching and retry only the scenarios.</p>{feedback.length>0&&<div className="mt-4 space-y-2">{feedback.slice(0,10).map((item:any)=><div key={item.questionId} className="rounded-xl bg-white p-3 text-xs leading-5 text-amber-950"><strong>Scenario {item.sortOrder}{item.criticalMiss?' · Critical':''}:</strong> {item.explanation}</div>)}</div>}<button onClick={onRetake} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white"><RefreshCw className="h-4 w-4"/>Retry Buyer Scenarios</button></div></div></section>}
function Framework({value}:{value:string}){return <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-blue-700">ProFox objection framework</div><div className="mt-2 text-sm font-black leading-6 text-blue-950">{value}</div></section>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-2xl border border-white/15 bg-white/10 p-3"><div className="flex items-center gap-2 text-white/80">{icon}<span className="text-[10px] font-black uppercase tracking-wider">{label}</span></div><div className="mt-1 text-sm font-black">{value}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-xs font-black leading-5 text-slate-800">{value}</div></div>}
function Tab({active,disabled=false,onClick,children}:{active:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" disabled={disabled} onClick={onClick} className={`flex-1 rounded-xl px-4 py-3 text-xs font-black transition ${active?'bg-[#000080] text-white':'text-slate-500 hover:bg-slate-50'} disabled:cursor-not-allowed disabled:opacity-35`}>{children}</button>}
function Notice({danger=false,children}:{danger?:boolean;children:React.ReactNode}){return <div className={`rounded-2xl border px-4 py-3 text-sm font-medium ${danger?'border-red-200 bg-red-50 text-red-700':'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>}
