import React,{useEffect,useMemo,useRef,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,Copy,Loader2,Save,Send,ShieldCheck}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{trainingService,TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{CompliancePreset,OutreachMessagingConfig,outreachMessagingTrainingService}from'../../lib/outreachMessagingTrainingService';

const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs outline-none focus:border-[#000080]';
const checks=['individualized','buyerFirst','oneIdea','oneCta','evidenceBacked','noFabrication','noGuarantees','noUnauthorizedCommitment','complianceChecked','crmPlanReady','certificationNotSentBeforeApproval'] as const;
type CheckKey=typeof checks[number];
type FormState={companyName:string;prospectUrl:string;targetContact:string;targetRole:string;marketCode:string;researchReference:string;evidenceUrl:string;businessSignal:string;verifiedObservation:string;carefulRelevance:string;valueOffer:string;subject:string;firstEmail:string;linkedinConnection:string;linkedinFollowup:string;loomCompanion:string;followups:Record<string,string>;cadence:any[];replyHandling:Record<string,string>;selfChecks:Record<CheckKey,boolean>};
const blank=(cfg?:OutreachMessagingConfig|null):FormState=>({companyName:'',prospectUrl:'',targetContact:'',targetRole:'',marketCode:'US',researchReference:'',evidenceUrl:'',businessSignal:'',verifiedObservation:'',carefulRelevance:'',valueOffer:'',subject:'',firstEmail:'',linkedinConnection:'',linkedinFollowup:'',loomCompanion:'',followups:{bump:'',newObservation:'',value:'',alternate:'',proofOrValue:'',closeLoop:''},cadence:cfg?.defaultCadence||[],replyHandling:Object.fromEntries((cfg?.requiredReplyScenarios||[]).map(x=>[x.key,''])),selfChecks:Object.fromEntries(checks.map(k=>[k,false])) as Record<CheckKey,boolean>});
const countWords=(s:string)=>s.trim()?s.trim().split(/\s+/).length:0;
const msg=(e:any,f:string)=>e?.message||f;

export default function OutreachMessagingTraining(){
 const{user}=useAuth();const[module,setModule]=useState<TrainingModule|null>(null);const[progress,setProgress]=useState<UserProgress>();const[lessons,setLessons]=useState<TrainingLesson[]>([]);const[config,setConfig]=useState<OutreachMessagingConfig|null>(null);const[form,setForm]=useState<FormState>(blank());const[lessonIndex,setLessonIndex]=useState(0);const[view,setView]=useState<'learn'|'assignment'|'playbooks'>('learn');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const hydratedRef=useRef(false);
 const load=async()=>{if(!user)return;setLoading(true);setError('');hydratedRef.current=false;try{const[mr,pr]=await Promise.all([trainingService.getModules(),trainingService.getUserProgress(user.id)]);const m=(mr.data||[]).find(x=>x.slug==='outreach-cadence');if(!m)throw new Error('Module 7 Outreach Messages & Follow-Up was not found.');let p=(pr.data||[]).find(x=>x.module_id===m.id);if(!p){const started=await trainingService.startModule(user.id,m.id);if(started.error||!started.data)throw started.error||new Error('Module 7 could not be started.');p=started.data;}const[lr,cr]=await Promise.all([trainingService.getLessons(m.id),outreachMessagingTrainingService.getConfig(m.id)]);if(cr.error||!cr.data)throw cr.error||new Error('Module 7 configuration is unavailable.');setModule(m);setProgress(p);setLessons(lr.data||[]);setConfig(cr.data);const base=blank(cr.data);const source=cr.data.draftData&&Object.keys(cr.data.draftData).length?cr.data.draftData:(cr.data.latestSubmission&&p?.status!=='Passed'?cr.data.latestSubmission:null);setForm(source?{...base,...source,followups:{...base.followups,...(source.followups||{})},replyHandling:{...base.replyHandling,...(source.replyHandling||{})},selfChecks:{...base.selfChecks,...(source.selfChecks||{})},cadence:source.cadence||base.cadence}:base);const done=Number(cr.data.lessonsCompleted||0);setLessonIndex(Math.min(done,Math.max((lr.data||[]).length-1,0)));if((lr.data||[]).length&&done>=(lr.data||[]).length)setView('assignment');Promise.resolve().then(()=>{hydratedRef.current=true;});}catch(e:any){setError(msg(e,'Module 7 could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{if(user)void load();},[user?.id]);
 const certified=progress?.status==='Passed'||progress?.status==='Completed',underReview=progress?.status==='Submitted';const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;const emailWords=countWords(form.firstEmail),subjectWords=countWords(form.subject);const emailValid=!!config&&emailWords>=config.acceptedMessageMinWords&&emailWords<=config.acceptedMessageMaxWords;const subjectValid=!!config&&subjectWords>=config.subjectMinWords&&subjectWords<=config.subjectMaxWords;const allReplies=!!config&&config.requiredReplyScenarios.every(x=>form.replyHandling[x.key]?.trim());const allChecks=checks.every(k=>form.selfChecks[k]);const compliance:CompliancePreset|undefined=config?.compliancePresets.find(x=>x.channel==='Email'&&x.marketCode===form.marketCode)||config?.compliancePresets.find(x=>x.channel==='Email'&&x.marketCode==='GLOBAL');const complianceBlocked=compliance?.status==='do_not_send';const requiredText=[form.companyName,form.prospectUrl,form.targetContact,form.targetRole,form.marketCode,form.researchReference,form.evidenceUrl,form.businessSignal,form.verifiedObservation,form.carefulRelevance,form.valueOffer,form.subject,form.firstEmail,form.linkedinConnection,form.linkedinFollowup,form.loomCompanion,...Object.values(form.followups)];const canSubmit=lessonsDone&&requiredText.every(x=>x.trim().length>=2)&&/^https?:\/\//i.test(form.prospectUrl)&&/^https?:\/\//i.test(form.evidenceUrl)&&emailValid&&subjectValid&&allReplies&&allChecks&&!complianceBlocked&&!underReview&&!certified&&!!config&&form.cadence.length>=config.defaultCadence.length;
 const patch=(x:Partial<FormState>)=>setForm(p=>({...p,...x}));
 useEffect(()=>{if(!hydratedRef.current||!progress||view!=='assignment'||underReview||certified)return;const timer=window.setTimeout(()=>{void outreachMessagingTrainingService.saveDraft(progress.id,form).then(({error:e})=>{if(e)console.error('Outreach certification auto-save failed:',e);});},900);return()=>window.clearTimeout(timer);},[progress?.id,view,underReview,certified,form]);
 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');const{data,error:e}=await outreachMessagingTrainingService.completeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(msg(e,'Lesson progress could not be saved.'));else{const done=Number((data as any)?.lessonsCompleted||0);setConfig(p=>p?{...p,lessonsCompleted:done}:p);if(done>=lessons.length){setView('assignment');setMessage('Training complete. Build your one-time messaging certification sequence.');}else setLessonIndex(done);}setBusy(false);};
 const save=async()=>{if(!progress)return;setBusy(true);setError('');const{error:e}=await outreachMessagingTrainingService.saveDraft(progress.id,form);if(e)setError(msg(e,'Draft could not be saved.'));else setMessage('Messaging certification draft saved.');setBusy(false);};
 const submit=async()=>{if(!progress||!canSubmit){setError('Complete every required field, message standard, reply scenario, cadence step, compliance check, and integrity acknowledgement before submitting.');return;}setBusy(true);setError('');setMessage('');const{error:e}=await outreachMessagingTrainingService.submit(progress.id,{type:'outreach_messaging_v1',...form});if(e)setError(msg(e,'Messaging certification could not be submitted.'));else{setMessage('Messaging certification submitted for Admin review. Do not send this training sequence to the prospect while review is pending.');await load();}setBusy(false);};
 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 if(!module||!config)return <Notice danger>{error||'Module 7 is unavailable.'}</Notice>;
 if(certified)return <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><div className="flex gap-3"><CheckCircle2 className="h-7 w-7 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-widest text-emerald-700">Module 7 Certified</div><h2 className="mt-1 text-xl font-black text-emerald-950">Outreach Messages & Follow-Up Passed</h2><p className="mt-2 max-w-3xl text-sm text-emerald-900">Your one-time onboarding messaging test is approved. After onboarding, normal prospecting messages do <strong>not</strong> require per-message Admin approval. Use the approved playbooks, CRM discipline, current market rules, and this quality standard independently.</p>{config.latestReview?.totalScore!==undefined&&<p className="mt-3 text-xs font-bold">Certification score: {config.latestReview.totalScore}/100</p>}</div></div></div>;
 return <div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 7 · One-Time Onboarding Certification</div><h2 className="mt-2 text-2xl font-black">Outreach Messages & Follow-Up</h2><p className="mt-2 max-w-3xl text-sm text-white/85">Research → relevance → concise message → purposeful follow-up → professional reply handling. Learn every step before creating your certification sequence.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat value={`${config.targetMessageMinWords}–${config.targetMessageMaxWords} words`} label="Email Target"/><Stat value={`${module.passing_score||80}/100`} label="Pass Standard"/><Stat value="One Time" label="Approval Scope"/></div></section>
  <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><strong>Important:</strong> Admin reviews this certification sequence once during onboarding. After certification, your normal outreach is not sent to Admin for message-by-message approval.</div>
  {config.latestReview?.status==='Retry Required'&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Retry Required · {config.latestReview.totalScore||0}/100.</strong> Use the Admin feedback, improve the complete sequence, and resubmit. Your completed lessons remain complete.{config.latestReview.feedback&&<p className="mt-2 rounded-xl bg-white/70 p-3 text-xs">{config.latestReview.feedback}</p>}</div>}
  {error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}
  <div className="flex gap-2 rounded-2xl border bg-white p-1"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn the SOP</Tab><Tab active={view==='playbooks'} onClick={()=>setView('playbooks')}>2. Approved Playbooks</Tab><Tab active={view==='assignment'} disabled={!lessonsDone} onClick={()=>setView('assignment')}>3. Certification</Tab></div>
  {view==='learn'&&<section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black">{lessons[lessonIndex]?.title}</h3></div><BookOpen className="h-6 w-6 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm"><ReactMarkdown>{lessons[lessonIndex]?.content||''}</ReactMarkdown></div><div className="mt-5 flex justify-between"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy} onClick={()=>void completeLesson()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white">Mark Learned & Continue<ArrowRight className="h-4 w-4"/></button>}</div></section>}
  {view==='playbooks'&&<section className="rounded-3xl border bg-white p-6"><div className="mb-5"><h3 className="text-lg font-black">Admin-Approved Message Playbooks</h3><p className="mt-1 text-xs text-slate-500">Use these as structures. Replace variables with real research; never copy a generic template and pretend it is personalized.</p></div><div className="grid gap-4 md:grid-cols-2">{config.playbooks.map(p=><div key={p.id} className="rounded-2xl border bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><div className="text-[9px] font-black uppercase tracking-widest text-[#000080]">{p.channel} · {p.category}</div><h4 className="mt-1 text-sm font-black">{p.title}</h4></div><button onClick={()=>navigator.clipboard.writeText(`${p.subjectTemplate?`Subject: ${p.subjectTemplate}\n\n`:''}${p.bodyTemplate}`)} className="rounded-lg border bg-white p-2"><Copy className="h-3.5 w-3.5"/></button></div>{p.subjectTemplate&&<div className="mt-3 rounded-lg bg-white p-2 text-xs"><strong>Subject:</strong> {p.subjectTemplate}</div>}<pre className="mt-2 whitespace-pre-wrap rounded-lg bg-white p-3 text-xs font-sans">{p.bodyTemplate}</pre><p className="mt-2 text-[11px] text-slate-500"><strong>Coach:</strong> {p.coachingNote}</p></div>)}</div></section>}
  {view==='assignment'&&<div className="space-y-5">{!underReview&&<div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-xs font-bold text-[#000080]">Draft auto-save is active. You can leave this page and continue your certification sequence later.</div>}{underReview&&<Notice>Certification is under Admin review. Do not send this training sequence to the real prospect.</Notice>}<Section title="1. Prospect & research" subtitle="Use one genuinely qualified prospect from your Module 5 discipline."><Grid><Field label="Company"><input className={input} value={form.companyName} onChange={e=>patch({companyName:e.target.value})}/></Field><Field label="Prospect website / public URL"><input className={input} value={form.prospectUrl} onChange={e=>patch({prospectUrl:e.target.value})}/></Field><Field label="Target contact"><input className={input} value={form.targetContact} onChange={e=>patch({targetContact:e.target.value})}/></Field><Field label="Role / title"><input className={input} value={form.targetRole} onChange={e=>patch({targetRole:e.target.value})}/></Field><Field label="Market"><select className={input} value={form.marketCode} onChange={e=>patch({marketCode:e.target.value})}><option value="US">United States</option><option value="UK">United Kingdom</option><option value="CA">Canada</option><option value="AU">Australia</option><option value="GLOBAL">Other / Global</option></select></Field><Field label="Module 5 / CRM / research reference"><input className={input} value={form.researchReference} onChange={e=>patch({researchReference:e.target.value})}/></Field></Grid><Field label="Evidence URL"><input className={input} value={form.evidenceUrl} onChange={e=>patch({evidenceUrl:e.target.value})}/></Field><Text label="Business signal — why this company / why now?" value={form.businessSignal} onChange={v=>patch({businessSignal:v})}/><Text label="Verified observation" value={form.verifiedObservation} onChange={v=>patch({verifiedObservation:v})}/><Text label="Careful relevance — why may it matter?" value={form.carefulRelevance} onChange={v=>patch({carefulRelevance:v})}/><Text label="Useful value / idea" value={form.valueOffer} onChange={v=>patch({valueOffer:v})}/></Section>
   <Section title="2. First outreach" subtitle="SIGNAL → OBSERVATION → RELEVANCE → VALUE → INVITATION"><Field label={`Subject · ${subjectWords} words · allowed ${config.subjectMinWords}–${config.subjectMaxWords}`}><input className={`${input} ${subjectValid?'':'border-amber-300'}`} value={form.subject} onChange={e=>patch({subject:e.target.value})}/></Field><Text rows={7} label={`First email · ${emailWords} words · target ${config.targetMessageMinWords}–${config.targetMessageMaxWords} · accepted ${config.acceptedMessageMinWords}–${config.acceptedMessageMaxWords}`} value={form.firstEmail} onChange={v=>patch({firstEmail:v})}/></Section>
   <Section title="3. Channel adaptation" subtitle="Do not paste the same message into every channel."><Text label="LinkedIn connection request" value={form.linkedinConnection} onChange={v=>patch({linkedinConnection:v})}/><Text label="LinkedIn after-accept / follow-up message" value={form.linkedinFollowup} onChange={v=>patch({linkedinFollowup:v})}/><Text label="Loom companion message" value={form.loomCompanion} onChange={v=>patch({loomCompanion:v})}/></Section>
   <Section title="4. Follow-up ladder" subtitle="Each touch must add a purpose — not another ‘just following up.’">{[['bump','Bump'],['newObservation','New observation'],['value','Useful value'],['alternate','Loom / alternate channel'],['proofOrValue','Approved proof OR new value'],['closeLoop','Close the loop']].map(([k,l])=><Text key={k} label={l} value={form.followups[k]||''} onChange={v=>patch({followups:{...form.followups,[k]:v}})}/>)}</Section>
   <Section title="5. Cadence plan" subtitle="Current Admin-controlled starting framework. Review every important high-value touch before sending."><div className="grid gap-2">{config.defaultCadence.map((c,i)=><div key={i} className="rounded-xl border bg-slate-50 p-3 text-xs"><strong>Day {c.day} · {c.channel} — {c.label}</strong><div className="mt-1 text-slate-500">{c.purpose}</div></div>)}</div></Section>
   <Section title="6. Reply handling" subtitle="Once a prospect replies, stop the cold cadence and respond to the real conversation.">{config.requiredReplyScenarios.map(s=><Text key={s.key} label={s.label} value={form.replyHandling[s.key]||''} onChange={v=>patch({replyHandling:{...form.replyHandling,[s.key]:v}})}/>)}</Section>
   <Section title="7. Market & channel check" subtitle="Use the live Admin preset; training guidance is not a substitute for current legal/compliance review.">{compliance?<div className={`rounded-2xl border p-4 text-sm ${compliance.status==='do_not_send'?'border-red-200 bg-red-50 text-red-900':compliance.status==='admin_review_required'?'border-amber-200 bg-amber-50 text-amber-950':'border-emerald-200 bg-emerald-50 text-emerald-950'}`}><div className="font-black">{compliance.marketLabel} · Email · {compliance.status.replaceAll('_',' ')}</div><p className="mt-1 text-xs">{compliance.summary}</p><ul className="mt-2 list-disc pl-5 text-xs">{compliance.rules.map((r,i)=><li key={i}>{r}</li>)}</ul></div>:<Notice danger>No active compliance preset is available. Ask Admin before sending.</Notice>}</Section>
   <Section title="8. Five-second quality & integrity check" subtitle="A high-performing message that damages trust is a failed message."><div className="grid gap-2 md:grid-cols-2">{([['individualized','Could not be sent to 100 companies unchanged'],['buyerFirst','First sentence starts in the buyer’s world'],['oneIdea','One central idea only'],['oneCta','One easy CTA only'],['evidenceBacked','Claims and observations are evidence-backed'],['noFabrication','No fabricated facts, proof, metrics, or personalization'],['noGuarantees','No guaranteed results'],['noUnauthorizedCommitment','No unauthorized price, scope, timeline, discount, or free-work promise'],['complianceChecked','I checked the live market/channel rule'],['crmPlanReady','I will log meaningful outreach/replies in CRM'],['certificationNotSentBeforeApproval','I have not sent this certification sequence to the real prospect before approval']] as Array<[CheckKey,string]>).map(([k,l])=><label key={k} className="flex items-start gap-3 rounded-xl border bg-slate-50 p-3 text-xs"><input type="checkbox" checked={form.selfChecks[k]} onChange={e=>patch({selfChecks:{...form.selfChecks,[k]:e.target.checked}})}/><span>{l}</span></label>)}</div></Section>
   {!underReview&&<div className="flex flex-col gap-3 sm:flex-row"><button disabled={busy} onClick={()=>void save()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border px-5 py-3 text-xs font-black"><Save className="h-4 w-4"/>Save Now</button><button disabled={busy||!canSubmit} onClick={()=>void submit()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><Send className="h-4 w-4"/>Submit One-Time Certification</button></div>}
  </div>}
 </div>;
}
function Stat({value,label}:{value:string;label:string}){return <div className="rounded-xl border border-white/20 bg-white/10 p-3"><div className="text-sm font-black">{value}</div><div className="mt-1 text-[9px] font-bold uppercase tracking-widest text-white/70">{label}</div></div>}
function Tab({active,disabled,onClick,children}:{active:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button disabled={disabled} onClick={onClick} className={`flex-1 rounded-xl px-3 py-3 text-xs font-black ${active?'bg-[#000080] text-white':'text-slate-600'} disabled:opacity-35`}>{children}</button>}
function Section({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="space-y-4 rounded-3xl border bg-white p-6"><div><h3 className="font-black">{title}</h3><p className="mt-1 text-xs text-slate-500">{subtitle}</p></div>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-3 md:grid-cols-2">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-black">{label}</span>{children}</label>}
function Text({label,value,onChange,rows=4}:{label:string;value:string;onChange:(v:string)=>void;rows?:number}){return <Field label={label}><textarea rows={rows} className={input} value={value} onChange={e=>onChange(e.target.value)}/></Field>}
function Notice({children,danger=false}:{children:React.ReactNode;danger?:boolean}){return <div className={`rounded-2xl border p-4 text-sm ${danger?'border-red-200 bg-red-50 text-red-900':'border-blue-200 bg-blue-50 text-blue-950'}`}>{children}</div>}
