import React,{useEffect,useMemo,useState}from'react';
import ReactMarkdown from'react-markdown';
import{ArrowLeft,ArrowRight,BookOpen,CheckCircle2,CreditCard,Loader2,RefreshCw,ShieldCheck,Target}from'lucide-react';
import{useAuth}from'../../lib/AuthContext';
import{trainingService,TrainingLesson,TrainingModule,UserProgress}from'../../lib/trainingService';
import{PaymentProcessAssessmentResult,PaymentProcessConfig,paymentProcessTrainingService}from'../../lib/paymentProcessTrainingService';
import{useStandardAssessmentResume}from'../../hooks/useStandardAssessmentResume';

type Props={onComplete?:()=>void};type View='learn'|'assessment'|'result';
const errorText=(error:any,fallback:string)=>error?.message||fallback;
const phases=[
 {start:1,end:5,title:'Payment Readiness'},
 {start:6,end:10,title:'Build the Right Payment Request'},
 {start:11,end:15,title:'Send & Follow Up Professionally'},
 {start:16,end:20,title:'Understand Payment Status'},
 {start:21,end:25,title:'Verification, Exceptions & Control'},
 {start:26,end:30,title:'Collection, Handoff & Judgment'}
];

export default function PaymentProcessTraining({onComplete}:Props){
 const{user}=useAuth();const[module,setModule]=useState<TrainingModule|null>(null);const[lessons,setLessons]=useState<TrainingLesson[]>([]);const[progress,setProgress]=useState<UserProgress|null>(null);const[config,setConfig]=useState<PaymentProcessConfig|null>(null);
 const[view,setView]=useState<View>('learn');const[lessonIndex,setLessonIndex]=useState(0);const[questionIndex,setQuestionIndex]=useState(0);const[confirmStage,setConfirmStage]=useState(false);const[answers,setAnswers]=useState<number[]>([]);const[acks,setAcks]=useState<Record<string,boolean>>({});const[result,setResult]=useState<PaymentProcessAssessmentResult|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const load=async()=>{if(!user)return;setLoading(true);setError('');try{const[modulesRes,progressRes]=await Promise.all([trainingService.getModules(),trainingService.getUserProgress(user.id)]);if(modulesRes.error)throw modulesRes.error;if(progressRes.error)throw progressRes.error;const target=(modulesRes.data||[]).find(item=>item.slug==='payment-process');if(!target)throw new Error('Payment Process module is unavailable.');setModule(target);let p=(progressRes.data||[]).find(item=>item.module_id===target.id)||null;if(!p){const started=await trainingService.startModule(user.id,target.id);if(started.error)throw started.error;const refreshed=await trainingService.getUserProgress(user.id);p=(refreshed.data||[]).find(item=>item.module_id===target.id)||null;}setProgress(p);const[lessonRes,configRes]=await Promise.all([trainingService.getLessons(target.id),paymentProcessTrainingService.getConfig(target.id)]);if(lessonRes.error)throw lessonRes.error;if(configRes.error||!configRes.data)throw configRes.error||new Error('Payment Process configuration is unavailable.');const lessonData=lessonRes.data||[];setLessons(lessonData);setConfig(configRes.data);const done=Number(configRes.data.lessonsCompleted||0);setLessonIndex(Math.min(done,Math.max(lessonData.length-1,0)));setAnswers(old=>old.length===configRes.data!.questions.length?old:Array(configRes.data!.questions.length).fill(-1));setAcks(old=>Object.keys(old).length?old:Object.fromEntries(configRes.data!.acknowledgements.map(item=>[item.id,false])));if(p?.status==='Passed'||p?.status==='Completed'||configRes.data.latestAttempt?.passed)setView('result');else if(done>=lessonData.length&&lessonData.length>0)setView(current=>current==='learn'?'assessment':current);}catch(e:any){setError(errorText(e,'Module 16 could not be loaded.'));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[user?.id]);
 const certified=progress?.status==='Passed'||progress?.status==='Completed'||result?.passed===true||config?.latestAttempt?.passed===true;const lessonsDone=!!config&&lessons.length>0&&config.lessonsCompleted>=lessons.length;const requiredAcks=useMemo(()=>config?.acknowledgements.filter(item=>item.required)||[],[config]);const allAcks=requiredAcks.every(item=>acks[item.id]);const allAnswered=!!config&&config.questions.length>0&&answers.length===config.questions.length&&answers.every(v=>Number.isInteger(v)&&v>=0);const currentQuestion=config?.questions[questionIndex];const latest=config?.latestAttempt;const phase=phases.find(item=>lessonIndex+1>=item.start&&lessonIndex+1<=item.end)||phases[phases.length-1];

 useStandardAssessmentResume({moduleId:module?.id,loading,terminal:certified,retryRequired:progress?.status==='Retry Required',lessonsDone,lessonCount:lessons.length,questionCount:config?.questions.length||0,view,lessonIndex,questionIndex,confirmStage,answers,acknowledgements:acks,setView,setLessonIndex,setQuestionIndex,setConfirmStage,setAnswers,setAcknowledgements:setAcks});

 const completeLesson=async()=>{if(!progress||!lessons[lessonIndex])return;setBusy(true);setError('');setMessage('');const{data,error:e}=await paymentProcessTrainingService.completeLesson(progress.id,lessons[lessonIndex].id);if(e)setError(errorText(e,'Lesson progress could not be saved.'));else{const done=Number((data as any)?.lessonsCompleted||0);setConfig(c=>c?{...c,lessonsCompleted:done}:c);if(done>=lessons.length){setView('assessment');setQuestionIndex(0);setConfirmStage(false);setMessage('All Payment Process lessons are complete. Your payment-integrity certification is unlocked.');}else setLessonIndex(done);}setBusy(false);};
 const submit=async()=>{if(!progress||!config)return;if(!allAnswered){setError('Answer every payment scenario before submitting.');return;}if(!allAcks){setError('Confirm every required ProFox payment standard before submitting.');return;}setBusy(true);setError('');const ids=requiredAcks.filter(item=>acks[item.id]).map(item=>item.id);const{data,error:e}=await paymentProcessTrainingService.submitAssessment(progress.id,answers,ids);if(e)setError(errorText(e,'Payment Process certification could not be scored.'));else if(data){setResult(data);setView('result');await load();}setBusy(false);};
 const retake=()=>{if(!config)return;setAnswers(Array(config.questions.length).fill(-1));setAcks(Object.fromEntries(config.acknowledgements.map(item=>[item.id,false])));setQuestionIndex(0);setConfirmStage(false);setResult(null);setError('');setMessage('');setView('assessment');};
 if(loading)return <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;if(!config||!module)return <Notice danger>{error||'Module 16 is unavailable.'}</Notice>;
 if(certified&&view==='result'){const score=result?.score??progress?.score??latest?.score??100;return <div className="space-y-5"><section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><div className="flex items-start gap-4"><CheckCircle2 className="h-8 w-8 shrink-0 text-emerald-600"/><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700">Module 16 Certified</div><h2 className="mt-1 text-2xl font-black text-emerald-950">Payment Process Passed</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-900">You demonstrated the ProFox payment standard: request from the accepted commercial truth, use approved channels, protect customer credentials, follow up professionally, never self-verify money, and allow only the protected verification workflow to advance the opportunity.</p><div className="mt-4 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-black text-emerald-800">Certification score: {score}/100</div>{onComplete&&progress?.status!=='Completed'&&<button onClick={onComplete} className="ml-3 mt-4 rounded-xl bg-[#000080] px-5 py-2.5 text-xs font-black text-white">Finish Module & Return</button>}</div></div></section><Framework value={config.framework}/></div>}
 return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-7 text-white shadow-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-white/75">Module 16 · Payment Integrity & Customer Confidence</div><h2 className="mt-2 text-2xl font-black">Payment Process</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/85">Make payment easy for the customer and exact for ProFox. Sales requests and follows up; the protected verification workflow decides financial truth.</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<BookOpen className="h-4 w-4"/>} value={`${config.lessonsCompleted}/${lessons.length}`} label="Lessons"/><Stat icon={<Target className="h-4 w-4"/>} value={`${config.passingScore}/100`} label="Pass Standard"/><Stat icon={<ShieldCheck className="h-4 w-4"/>} value="0" label="Critical Misses"/><Stat icon={<CreditCard className="h-4 w-4"/>} value="Protected" label="Verification"/></div></section><Framework value={config.framework}/><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Payment authority standard</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Mini label="Sales authority" value={config.operatingStandard?.salesAuthority||''}/><Mini label="Verification" value={config.operatingStandard?.verificationRule||''}/><Mini label="Source of truth" value={config.operatingStandard?.sourceOfTruth||''}/><Mini label="Activation" value={config.operatingStandard?.activationRule||''}/></div></section>{latest&&!latest.passed&&<Notice><strong>Previous attempt:</strong> {latest.score??0}/100 with {latest.criticalMisses??0} critical miss(es). Your 30 lessons remain complete; review the coaching and retry the scenarios.</Notice>}{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}<div className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-1"><Tab active={view==='learn'} onClick={()=>setView('learn')}>1. Learn the Payment Process</Tab><Tab active={view==='assessment'} disabled={!lessonsDone} onClick={()=>{setView('assessment');setConfirmStage(false)}}>2. Payment Scenario Certification</Tab></div>
 {view==='learn'&&lessons[lessonIndex]&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">{phase.title} · Lesson {lessonIndex+1} of {lessons.length}</div><h3 className="mt-1 text-lg font-black text-slate-950">{lessons[lessonIndex].title}</h3></div><BookOpen className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="prose prose-slate max-w-none rounded-2xl bg-slate-50 p-6 text-sm leading-7"><ReactMarkdown>{lessons[lessonIndex].content||''}</ReactMarkdown></div><div className="mt-5 flex items-center justify-between gap-3"><button disabled={lessonIndex===0} onClick={()=>setLessonIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button>{lessonIndex<config.lessonsCompleted?<button onClick={()=>setLessonIndex(i=>Math.min(lessons.length-1,i+1))} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-xs font-bold">Review Next<ArrowRight className="h-4 w-4"/></button>:!lessonsDone&&<button disabled={busy||!progress} onClick={()=>void completeLesson()} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">I Reviewed the Lesson & Practice Prompt<ArrowRight className="h-4 w-4"/></button>}</div></section>}
 {view==='assessment'&&!confirmStage&&currentQuestion&&<section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Payment situation {questionIndex+1} of {config.questions.length} · Progress saved</div><h3 className="mt-2 max-w-4xl text-base font-black leading-6 text-slate-950">{currentQuestion.prompt}</h3></div><Target className="h-6 w-6 shrink-0 text-[#000080]"/></div><div className="mt-5 grid gap-3">{currentQuestion.options.map((option,index)=><button key={index} type="button" onClick={()=>setAnswers(previous=>previous.map((v,i)=>i===questionIndex?index:v))} className={`rounded-2xl border p-4 text-left text-sm leading-6 transition ${answers[questionIndex]===index?'border-[#000080] bg-blue-50 text-blue-950 ring-2 ring-blue-100':'border-slate-200 bg-white text-slate-700 hover:border-slate-300'}`}><span className="mr-2 font-black">{String.fromCharCode(65+index)}.</span>{option}</button>)}</div><div className="mt-6 flex justify-between"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>Math.max(0,i-1))} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Previous</button><button disabled={answers[questionIndex]<0} onClick={()=>{if(questionIndex>=config.questions.length-1)setConfirmStage(true);else setQuestionIndex(i=>i+1)}} className="inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40">{questionIndex>=config.questions.length-1?'Review Standards':'Next Situation'}<ArrowRight className="h-4 w-4"/></button></div></section>}
 {view==='assessment'&&confirmStage&&<section className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Final certification check · Progress saved</div><h3 className="mt-1 text-lg font-black">Confirm the ProFox payment standards</h3><p className="mt-1 text-xs leading-5 text-slate-500">Every required acknowledgement must be confirmed before the server scores your payment scenarios.</p></div><div className="grid gap-3">{config.acknowledgements.map(item=><label key={item.id} className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6"><input type="checkbox" checked={!!acks[item.id]} onChange={e=>setAcks(previous=>({...previous,[item.id]:e.target.checked}))} className="mt-1"/><span>{item.statement}{item.required&&<strong className="ml-1 text-red-600">*</strong>}</span></label>)}</div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><strong>Scoring rule:</strong> At least {config.passingScore}/100 and zero critical misses. Customer confirmation, screenshots or verbal promises never replace the protected verification workflow.</div><div className="flex flex-col gap-3 sm:flex-row"><button onClick={()=>{setConfirmStage(false);setQuestionIndex(config.questions.length-1)}} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-xs font-black"><ArrowLeft className="h-4 w-4"/>Review Answers</button><button disabled={busy||!allAnswered||!allAcks} onClick={()=>void submit()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><ShieldCheck className="h-4 w-4"/>{busy?'Scoring securely...':'Submit Payment Certification'}</button></div></section>}{view==='result'&&!certified&&<FailedResult result={result||latest as any} passingScore={config.passingScore} onRetake={retake}/>}</div>;
}
function FailedResult({result,passingScore,onRetake}:{result:any;passingScore:number;onRetake:()=>void}){const feedback=Array.isArray(result?.feedback)?result.feedback.filter((item:any)=>!item.correct):[];return <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-start gap-3"><RefreshCw className="mt-1 h-6 w-6 shrink-0 text-amber-700"/><div className="flex-1"><div className="text-[10px] font-black uppercase tracking-widest text-amber-700">Retry Required</div><h3 className="mt-1 text-xl font-black text-amber-950">Review the payment decisions that need coaching.</h3><p className="mt-2 text-sm leading-6 text-amber-900">Score: {result?.score??0}/100 · Required: {passingScore}/100 · Critical misses: {result?.criticalMisses??0}. Your completed lessons are preserved; only the payment scenarios restart.</p>{feedback.length>0&&<div className="mt-4 space-y-2">{feedback.map((item:any)=><div key={`${item.questionId}-${item.sortOrder}`} className="rounded-xl bg-white p-3 text-xs leading-5 text-slate-700"><strong>Situation {item.sortOrder}{item.criticalMiss?' · Critical':''}:</strong> {item.explanation}</div>)}</div>}<button onClick={onRetake} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white"><RefreshCw className="h-4 w-4"/>Retry Payment Scenarios</button></div></div></section>}
function Framework({value}:{value:string}){return <section className="rounded-3xl border border-blue-100 bg-blue-50 p-5"><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">ProFox Payment Framework</div><div className="mt-2 text-sm font-black leading-6 text-blue-950">{value}</div></section>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-2xl bg-white/10 p-3"><div className="flex items-center gap-2 text-white/75">{icon}<span className="text-[9px] font-black uppercase tracking-wider">{label}</span></div><div className="mt-1 text-sm font-black">{value}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</div><p className="mt-1 text-xs font-bold leading-5 text-slate-700">{value}</p></div>}
function Tab({active,disabled,onClick,children}:{active:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button disabled={disabled} onClick={onClick} className={`flex-1 rounded-xl px-4 py-2.5 text-xs font-black transition disabled:cursor-not-allowed disabled:opacity-35 ${active?'bg-[#000080] text-white':'text-slate-600 hover:bg-slate-50'}`}>{children}</button>}
function Notice({children,danger=false}:{children:React.ReactNode;danger?:boolean}){return <div className={`rounded-2xl border p-4 text-sm leading-6 ${danger?'border-red-200 bg-red-50 text-red-800':'border-blue-200 bg-blue-50 text-blue-900'}`}>{children}</div>}