import React,{useEffect,useState}from'react';
import{CheckCircle2,ExternalLink,FileCheck2,Loader2,Send,ShieldCheck}from'lucide-react';
import type{UserProgress}from'../../lib/trainingService';

const input='w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-3 text-sm outline-none focus:border-[#000080] focus:ring-4 focus:ring-blue-100';

export default function UIUXFinalCertificationView({progress,latestSubmission,isSubmitting,onSubmit,onRequestFinalApproval,userStatus}:{progress?:UserProgress;latestSubmission?:any;isSubmitting:boolean;onSubmit:(data:any)=>Promise<void>;onRequestFinalApproval:()=>Promise<void>;userStatus?:string}){
 const[figmaUrl,setFigmaUrl]=useState(latestSubmission?.figmaUrl||''),[rationale,setRationale]=useState(latestSubmission?.rationale||''),[responsive,setResponsive]=useState(latestSubmission?.responsive||''),[system,setSystem]=useState(latestSubmission?.designSystem||''),[accessibility,setAccessibility]=useState(latestSubmission?.accessibility||''),[handoff,setHandoff]=useState(latestSubmission?.handoff||'');
 useEffect(()=>{if(latestSubmission){setFigmaUrl(latestSubmission.figmaUrl||'');setRationale(latestSubmission.rationale||'');setResponsive(latestSubmission.responsive||'');setSystem(latestSubmission.designSystem||'');setAccessibility(latestSubmission.accessibility||'');setHandoff(latestSubmission.handoff||'')}},[latestSubmission]);
 const passed=progress?.status==='Passed',submitted=progress?.status==='Submitted',retry=progress?.status==='Retry Required';
 const ready=/^https?:\/\//i.test(figmaUrl)&&[rationale,responsive,system,accessibility,handoff].every(v=>v.trim().length>=30);
 const submit=async()=>onSubmit({type:'uiux_final_certification',figmaUrl:figmaUrl.trim(),rationale:rationale.trim(),responsive:responsive.trim(),designSystem:system.trim(),accessibility:accessibility.trim(),handoff:handoff.trim(),submittedAt:new Date().toISOString()});
 return <div className="space-y-6">
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl bg-[#000080] p-3 text-white"><FileCheck2 className="h-6 w-6"/></div><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#FF0E0E]">Final production-readiness gate</div><h2 className="mt-1 text-2xl font-black text-slate-900">UI/UX Final Certification</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-slate-500">Submit one controlled design exercise that demonstrates the same behaviors required in PF-SOP-08 delivery. Management independently reviews the evidence; completing the form does not activate production access.</p></div></div>
   <div className="mt-6 grid gap-3 sm:grid-cols-3"><State label="Submission" value={submitted?'Under review':passed?'Passed':retry?'Retry required':'Not submitted'} success={passed}/><State label="Minimum standard" value="90 / 100"/><State label="Production access" value={userStatus==='active'?'Active':'Locked'} success={userStatus==='active'}/></div>
  </section>

  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="mb-5 border-b border-slate-100 pb-4"><h3 className="text-base font-black text-slate-900">Certification evidence</h3><p className="mt-1 text-xs leading-5 text-slate-500">Use the Figma file created from the supplied certification brief. Explain your decisions briefly enough for an independent reviewer to verify the work.</p></div>
   <label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wide text-slate-500">Figma / design file URL *</span><div className="relative"><input type="url" className={input} value={figmaUrl} disabled={submitted||passed} onChange={e=>setFigmaUrl(e.target.value)} placeholder="https://www.figma.com/..."/>{/^https?:\/\//i.test(figmaUrl)&&<a href={figmaUrl} target="_blank" rel="noreferrer" className="absolute right-3 top-1/2 -translate-y-1/2 text-[#000080]"><ExternalLink className="h-4 w-4"/></a>}</div></label>
   <Area label="UX / business rationale *" value={rationale} set={setRationale} disabled={submitted||passed} placeholder="Problem, user goal, hierarchy, conversion decisions and important assumptions..."/>
   <Area label="Responsive approach & interaction states *" value={responsive} set={setResponsive} disabled={submitted||passed}/>
   <Area label="Components, variables/tokens & design-system decisions *" value={system} set={setSystem} disabled={submitted||passed}/>
   <Area label="Accessibility considerations *" value={accessibility} set={setAccessibility} disabled={submitted||passed}/>
   <Area label="Developer handoff note *" value={handoff} set={setHandoff} disabled={submitted||passed} placeholder="Approved version, responsive/state coverage, components, content/assets and anything the Developer must know..."/>
   {progress?.feedback&&<div className={`mt-5 rounded-2xl border p-4 text-xs leading-5 ${retry?'border-red-200 bg-red-50 text-red-700':'border-blue-200 bg-blue-50 text-blue-800'}`}><strong>Management feedback:</strong> {progress.feedback}</div>}
   {!passed&&!submitted&&<button onClick={()=>void submit()} disabled={!ready||isSubmitting} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{isSubmitting?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}{retry?'Resubmit Certification':'Submit for Management Review'}</button>}
   {submitted&&<div className="mt-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-800"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/><span>Your evidence is locked for this review attempt. Management must record a structured Pass or Retry Required decision.</span></div>}
  </section>

  {passed&&<section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-6 w-6 shrink-0 text-emerald-600"/><div><h3 className="font-black text-emerald-900">Certification passed</h3><p className="mt-1 text-xs leading-5 text-emerald-800">Your final design evidence passed Management review. Request Final Approval to move into the protected account-activation gate.</p><button onClick={()=>void onRequestFinalApproval()} disabled={isSubmitting||userStatus==='active'} className="mt-4 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white disabled:opacity-40">Request Final Approval</button></div></div></section>}
 </div>
}
function Area({label,value,set,disabled,placeholder}:{label:string;value:string;set:(v:string)=>void;disabled?:boolean;placeholder?:string}){return <label className="mt-4 block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</span><textarea rows={3} className={input} value={value} disabled={disabled} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
function State({label,value,success}:{label:string;value:string;success?:boolean}){return <div className={`rounded-2xl border p-4 ${success?'border-emerald-200 bg-emerald-50':'border-slate-200 bg-slate-50'}`}><div className="text-[9px] font-black uppercase tracking-wide text-slate-400">{label}</div><div className={`mt-1 text-sm font-black ${success?'text-emerald-700':'text-slate-800'}`}>{value}</div></div>}
