-- Module 13B — Google Calendar busy-time synchronization and conflict protection.
-- Native ProFox meetings remain authoritative. Google busy ranges are an additional availability constraint only.

CREATE TABLE IF NOT EXISTS public.google_calendar_busy_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  calendar_id text NOT NULL DEFAULT 'primary',
  start_at timestamptz NOT NULL,
  end_at timestamptz NOT NULL,
  window_start timestamptz NOT NULL,
  window_end timestamptz NOT NULL,
  fetched_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_at > start_at),
  CHECK (window_end > window_start)
);
CREATE INDEX IF NOT EXISTS idx_google_busy_user_range ON public.google_calendar_busy_blocks(user_id,start_at,end_at);
ALTER TABLE public.google_calendar_busy_blocks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.google_calendar_busy_blocks FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.service_replace_google_busy_blocks(
  p_user_id uuid,
  p_calendar_id text,
  p_window_start timestamptz,
  p_window_end timestamptz,
  p_busy jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
DECLARE v_item jsonb; v_start timestamptz; v_end timestamptz; v_count integer:=0;
BEGIN
  IF p_user_id IS NULL OR p_window_start IS NULL OR p_window_end IS NULL OR p_window_end<=p_window_start THEN
    RAISE EXCEPTION 'Invalid Google busy synchronization window.';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM public.google_calendar_connections c WHERE c.user_id=p_user_id AND c.status='connected' AND c.sync_enabled) THEN
    RAISE EXCEPTION 'Google Calendar is not connected for this user.';
  END IF;
  IF jsonb_typeof(COALESCE(p_busy,'[]'::jsonb))<>'array' OR jsonb_array_length(COALESCE(p_busy,'[]'::jsonb))>2000 THEN
    RAISE EXCEPTION 'Invalid Google busy payload.';
  END IF;
  DELETE FROM public.google_calendar_busy_blocks WHERE user_id=p_user_id;
  FOR v_item IN SELECT value FROM jsonb_array_elements(COALESCE(p_busy,'[]'::jsonb)) LOOP
    BEGIN
      v_start:=(v_item->>'start')::timestamptz; v_end:=(v_item->>'end')::timestamptz;
    EXCEPTION WHEN OTHERS THEN RAISE EXCEPTION 'Invalid busy timestamp returned by Google.'; END;
    IF v_end<=v_start OR v_start<p_window_start-interval '1 minute' OR v_end>p_window_end+interval '1 minute' THEN
      RAISE EXCEPTION 'Google busy interval is outside the requested synchronization window.';
    END IF;
    INSERT INTO public.google_calendar_busy_blocks(user_id,calendar_id,start_at,end_at,window_start,window_end,fetched_at)
    VALUES(p_user_id,COALESCE(NULLIF(p_calendar_id,''),'primary'),v_start,v_end,p_window_start,p_window_end,now());
    v_count:=v_count+1;
  END LOOP;
  UPDATE public.google_calendar_connections
  SET last_attempt_at=now(),last_successful_sync_at=now(),last_error=NULL,status='connected',updated_at=now()
  WHERE user_id=p_user_id;
  UPDATE public.user_calendar_settings SET connection_status='Connected',updated_at=now() WHERE user_id=p_user_id;
  RETURN v_count;
END;
$$;
REVOKE ALL ON FUNCTION public.service_replace_google_busy_blocks(uuid,text,timestamptz,timestamptz,jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_replace_google_busy_blocks(uuid,text,timestamptz,timestamptz,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.has_google_calendar_conflict(
  p_user_id uuid,p_start_at timestamptz,p_end_at timestamptz,p_ignore_meeting_id uuid DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path=public,pg_temp
AS $$
DECLARE v_before integer:=0; v_after integer:=0; v_old_start timestamptz; v_old_end timestamptz; v_external text;
BEGIN
  IF p_user_id IS NULL OR p_start_at IS NULL OR p_end_at IS NULL OR p_end_at<=p_start_at THEN RETURN true; END IF;
  IF NOT EXISTS(SELECT 1 FROM public.google_calendar_connections c WHERE c.user_id=p_user_id AND c.status='connected' AND c.sync_enabled) THEN RETURN false; END IF;
  SELECT COALESCE(buffer_before_minutes,0),COALESCE(buffer_after_minutes,0) INTO v_before,v_after FROM public.user_calendar_settings WHERE user_id=p_user_id;
  IF p_ignore_meeting_id IS NOT NULL THEN
    SELECT start_at,end_at,external_event_id INTO v_old_start,v_old_end,v_external FROM public.sales_meetings WHERE id=p_ignore_meeting_id;
  END IF;
  RETURN EXISTS(
    SELECT 1 FROM public.google_calendar_busy_blocks b
    WHERE b.user_id=p_user_id
      AND b.start_at < p_end_at + make_interval(mins=>GREATEST(v_after,0))
      AND b.end_at > p_start_at - make_interval(mins=>GREATEST(v_before,0))
      AND NOT (p_ignore_meeting_id IS NOT NULL AND NULLIF(v_external,'') IS NOT NULL AND b.start_at=v_old_start AND b.end_at=v_old_end)
  );
END;
$$;
REVOKE ALL ON FUNCTION public.has_google_calendar_conflict(uuid,timestamptz,timestamptz,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.has_google_calendar_conflict(uuid,timestamptz,timestamptz,uuid) TO authenticated,service_role;

CREATE OR REPLACE FUNCTION public.guard_google_busy_sales_meeting()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
BEGIN
  IF NEW.status NOT IN ('Scheduled','Rescheduled') THEN RETURN NEW; END IF;
  IF TG_OP='UPDATE' AND NEW.start_at=OLD.start_at AND NEW.end_at=OLD.end_at AND NEW.salesperson_id=OLD.salesperson_id THEN RETURN NEW; END IF;
  IF public.has_google_calendar_conflict(NEW.salesperson_id,NEW.start_at,NEW.end_at,CASE WHEN TG_OP='UPDATE' THEN OLD.id ELSE NULL END) THEN
    RAISE EXCEPTION 'This time conflicts with the connected Google Calendar.' USING ERRCODE='P0001';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_guard_google_busy_sales_meeting ON public.sales_meetings;
CREATE TRIGGER trg_guard_google_busy_sales_meeting BEFORE INSERT OR UPDATE OF salesperson_id,start_at,end_at,status ON public.sales_meetings FOR EACH ROW EXECUTE FUNCTION public.guard_google_busy_sales_meeting();
REVOKE ALL ON FUNCTION public.guard_google_busy_sales_meeting() FROM PUBLIC,anon,authenticated;

-- Preserve the current mature native-slot implementation as an internal base, then add Google busy filtering outside it.
ALTER FUNCTION public.get_public_booking_slots(uuid,date,integer) RENAME TO get_public_booking_slots_native_base;
REVOKE ALL ON FUNCTION public.get_public_booking_slots_native_base(uuid,date,integer) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.get_public_booking_slots(p_salesperson_id uuid,p_from_date date DEFAULT NULL,p_days integer DEFAULT 14)
RETURNS TABLE(start_at timestamptz,end_at timestamptz,timezone text,duration_minutes integer)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
  SELECT s.start_at,s.end_at,s.timezone,s.duration_minutes
  FROM public.get_public_booking_slots_native_base(p_salesperson_id,p_from_date,p_days) s
  WHERE NOT public.has_google_calendar_conflict(p_salesperson_id,s.start_at,s.end_at,NULL)
  ORDER BY s.start_at;
$$;
REVOKE ALL ON FUNCTION public.get_public_booking_slots(uuid,date,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_public_booking_slots(uuid,date,integer) TO anon,authenticated,service_role;

-- The public self-service reschedule path uses this predicate. Keep its native validation and layer Google busy on top.
ALTER FUNCTION public.is_public_reschedule_slot_available(uuid,timestamptz,integer,uuid) RENAME TO is_public_reschedule_slot_available_native_base;
REVOKE ALL ON FUNCTION public.is_public_reschedule_slot_available_native_base(uuid,timestamptz,integer,uuid) FROM PUBLIC,anon,authenticated;
CREATE OR REPLACE FUNCTION public.is_public_reschedule_slot_available(p_salesperson_id uuid,p_start_at timestamptz,p_duration_minutes integer,p_ignore_meeting_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
  SELECT public.is_public_reschedule_slot_available_native_base(p_salesperson_id,p_start_at,p_duration_minutes,p_ignore_meeting_id)
     AND NOT public.has_google_calendar_conflict(p_salesperson_id,p_start_at,p_start_at+make_interval(mins=>p_duration_minutes),p_ignore_meeting_id);
$$;
REVOKE ALL ON FUNCTION public.is_public_reschedule_slot_available(uuid,timestamptz,integer,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_public_reschedule_slot_available(uuid,timestamptz,integer,uuid) TO anon,authenticated,service_role;
