-- Sales Academy Module 8 — Meeting Booking practical certification bank.
-- Correct answers and critical flags remain Admin-only; learner RPCs expose only sanitized questions.

WITH m AS (SELECT id FROM public.training_modules WHERE slug='meeting-booking')
INSERT INTO public.training_assessment_questions(
  module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical,created_at,updated_at
)
SELECT m.id,q.prompt,q.options,q.correct_index,q.explanation,q.sort_order,true,q.assessment_section,q.case_key,q.critical,now(),now()
FROM m CROSS JOIN (VALUES
('A roofing contractor replies: “Yes, we are looking at rebuilding the website this year. Most leads still come through referrals.” What is the strongest next step?',jsonb_build_array('Send the complete ProFox service list and every package immediately','Acknowledge the issue, explain why a short discovery conversation would be useful, and offer an easy booking path','Ask only for their budget before saying anything else','Send a booking link with no context'),1,'Qualified interest should be moved toward a useful conversation with context, value, and a low-friction next step.',1,'scenario','interested_roofing_contractor',false),
('A prospect replies only “Interesting.” What should you do?',jsonb_build_array('Assume they are ready and book a meeting immediately','Send three follow-ups in the same day','Respond to the interest and qualify enough to understand whether a meeting is useful','Mark the opportunity as won'),2,'Interest is a signal to qualify, not proof that a meeting is already justified.',2,'scenario','courtesy_interest',false),
('A prospect asks: “Before we book anything, what does a website cost?” Which response follows the ProFox standard?',jsonb_build_array('Refuse to discuss price until they attend a meeting','Say every website costs $5,799','Share the current approved package starting points accurately, explain that fit depends on the goal, and offer discovery as an option','Invent a temporary discount to secure the call'),2,'Known approved pricing should be transparent. Use the live Sales Catalog and never hide price solely to force a meeting.',3,'scenario','price_first',true),
('A prospect says: “Can you just send me something to look at first?” What is the best response?',jsonb_build_array('Tell them information is only available on a sales call','Send a giant generic brochure and begin daily follow-up','Send something relevant to their stated problem and leave a low-pressure next step','Close the lead immediately'),2,'Respect the request and provide relevant context instead of fighting the buyer’s preferred next step.',4,'scenario','send_information',false),
('During a live phone conversation, a qualified prospect agrees that a discovery meeting makes sense. What should happen next?',jsonb_build_array('End the call and hope they reply to a scheduling email later','Ask whether they have their calendar available and secure the time while momentum exists','Send a proposal before choosing a time','Create a meeting without confirming with them'),1,'When practical, convert live agreement into an actual calendar commitment while both sides are present.',5,'scenario','live_verbal_agreement',false),
('A qualified prospect gives a positive reply by email. Which booking message is strongest?',jsonb_build_array('Here is my calendar.','Book now.','Explain why a short conversation would help, what it should accomplish, and provide an easy scheduling option','Send the full presentation deck before answering their message'),2,'Async booking should explain the reason and value of the meeting before presenting the scheduling path.',6,'scenario','async_positive_reply',false),
('An international prospect writes: “Thursday at 3 works.” What must happen before the meeting is booked?',jsonb_build_array('Assume they mean the salesperson’s timezone','Confirm the prospect timezone and the exact date/time before booking','Create two meetings in two timezones','Ask them to calculate the timezone conversion alone'),1,'Timezone ambiguity must be resolved explicitly before creating the meeting.',7,'scenario','timezone_ambiguity',true),
('A contact says: “I am collecting options for my boss. She will make the final decision.” What is the best response?',jsonb_build_array('End the conversation because they are not the signer','Pretend the contact is the final decision maker in CRM','Respect their role, understand what they are evaluating, and ask who else should be involved in discovery','Ask for the boss’s private phone number without permission'),2,'Influencers and researchers can be valuable. Handle stakeholder context respectfully and accurately.',8,'scenario','stakeholder_context',false),
('A prospect says: “This looks interesting but this month is crazy.” What is the best action?',jsonb_build_array('Create fake urgency so they book today','Agree a specific future follow-up or offer an easy booking option for when things settle down','Mark the lead lost immediately','Message them every morning until they respond'),1,'Protect the relationship and create a real next action without pressure.',9,'scenario','busy_prospect',false),
('A prospect clearly needs a service ProFox does not provide and has no relevant approved need. What should the seller do?',jsonb_build_array('Book anyway to increase meeting numbers','Invent a ProFox capability','Do not force a meeting; handle the poor fit honestly and record the outcome appropriately','Create a fake opportunity value'),2,'A calendar full of bad-fit meetings is not productive selling.',10,'scenario','poor_fit',false),
('For an initial qualified sales conversation, which meeting type is normally appropriate?',jsonb_build_array('Discovery Meeting','Project Kickoff','Payment Verification','Internal QA Review'),0,'Initial qualified sales conversations normally use the Discovery Meeting type unless the true purpose is different.',11,'knowledge','meeting_type',false),
('How should a seller choose the meeting duration?',jsonb_build_array('Always use 60 minutes','Use whatever duration the prospect guesses','Use the live Admin-configured ProFox meeting settings and the real purpose of the meeting','Create a personal duration rule outside ProFox'),2,'Meeting durations are operational configuration. Use the live ProFox standard rather than stale memory.',12,'knowledge','meeting_duration',false),
('Which set of details best represents a correctly confirmed booking?',jsonb_build_array('Only the prospect name','Date, time, timezone, attendee details, meeting purpose, correct ProFox record, and access information','A screenshot of the seller’s calendar','Only a verbal promise to speak later'),1,'A professional meeting is operationally complete only when the important booking details are accurate and recorded.',13,'knowledge','booking_accuracy',false),
('A prospect needs to move tomorrow’s meeting. What should the seller do?',jsonb_build_array('Create a brand-new unrelated meeting and leave the old one active','Delete all meeting history','Reschedule the existing ProFox meeting so history and CRM context are preserved','Tell the prospect rescheduling is not allowed'),2,'Rescheduling should update the existing meeting instead of creating duplicate records.',14,'scenario','reschedule_existing',true),
('A prospect cancels a meeting. What is the strongest CRM behavior?',jsonb_build_array('Ignore the cancellation','Record the cancellation accurately and understand whether the reason is timing, project delay, fit, interest, or stakeholder-related','Mark the deal won','Delete the contact'),1,'Cancellation is business information. Record it accurately and understand the reason.',15,'scenario','cancellation',false),
('A qualified prospect no-shows. What is the strongest response?',jsonb_build_array('Send an angry message','Immediately mark them as fraudulent','Send a calm recovery message, make rescheduling easy if still relevant, and update CRM','Book another meeting without asking them'),2,'No-show recovery should preserve trust while keeping CRM history accurate.',16,'scenario','no_show',false),
('A seller tells a prospect: “Only two slots are left this month” even though that is not true. How should this be judged?',jsonb_build_array('Excellent urgency technique','Acceptable if it gets a meeting','A serious trust failure because the scarcity is fabricated','Required ProFox policy'),2,'Fake scarcity and misleading urgency are prohibited.',17,'scenario','fake_urgency',true),
('A seller knows the approved package pricing but hides it only to force a prospect onto a call. How should this be judged?',jsonb_build_array('Correct because meetings are more important than transparency','A serious failure; approved pricing should not be concealed solely to manipulate the booking','Required for all outbound prospects','Acceptable only on LinkedIn'),1,'The meeting should create clarity, not conceal known approved information.',18,'scenario','pricing_manipulation',true),
('A seller promises “Your new website will definitely double your leads” to secure a meeting. How should this be judged?',jsonb_build_array('Strong closing language','Acceptable if the prospect seems interested','A serious failure because guaranteed outcomes are unsupported','Required for Premium prospects'),2,'Do not guarantee business results to manufacture urgency or interest.',19,'scenario','guaranteed_results',true),
('A prospect explicitly says “Please do not contact me again.” What should the seller do?',jsonb_build_array('Continue the cadence from another channel','Respect the request, stop outreach, and record the communication boundary appropriately','Wait one day and try again','Ask another seller to contact them'),1,'Explicit stop/no-contact requests must be respected.',20,'scenario','explicit_stop',true)
) AS q(prompt,options,correct_index,explanation,sort_order,assessment_section,case_key,critical);

WITH m AS (SELECT id FROM public.training_modules WHERE slug='meeting-booking')
INSERT INTO public.training_acknowledgements(module_id,statement,sort_order,required,active,created_at,updated_at)
SELECT m.id,a.statement,a.sort_order,true,true,now(),now()
FROM m CROSS JOIN (VALUES
('I will confirm timezone whenever the time is ambiguous and will not invent availability.',1),
('I will use the live approved ProFox pricing/catalog, will not hide known pricing solely to force a meeting, and will not offer unauthorized discounts.',2),
('I will keep meetings connected to the correct ProFox CRM record and reschedule the existing meeting instead of creating duplicates.',3),
('I will not use fabricated urgency, unsupported guarantees, dishonest CRM data, or misleading claims to obtain a meeting.',4),
('I will respect explicit no-contact requests and protect prospect/client information.',5),
('I understand Module 8 is a one-time onboarding certification; after I pass, normal prospect meetings do not require Admin approval before booking.',6)
) AS a(statement,sort_order);
