update public.career_jobs
set role_details=jsonb_set(jsonb_set(jsonb_set(coalesce(role_details,'{}'::jsonb),'{systemRole}','"developer"'::jsonb,true),'{department}','"Development"'::jsonb,true),'{trainingTrack}','"web_development"'::jsonb,true),
    application_type='general',application_url='/careers/web-developer/apply',application_cta='Apply for Web Developer',requires_intro_video=false,updated_at=now()
where slug='web-developer';

with j as (select id from public.career_jobs where slug='web-developer' limit 1),
p(stage,sort_order,assessment_required,passing_score,sla_hours,interview_required,rubric) as (
values
('New Application',1,false,null::integer,24,false,'[]'::jsonb),
('Code & Portfolio Review',2,true,75,48,false,'[{"key":"shippedWork","label":"Shipped production work and clear contribution","maxPoints":20},{"key":"codeQuality","label":"Code quality, structure and maintainability evidence","maxPoints":20},{"key":"responsive","label":"Responsive implementation quality","maxPoints":15},{"key":"git","label":"Git/GitHub collaboration evidence","maxPoints":15},{"key":"testing","label":"Testing and defect-prevention evidence","maxPoints":10},{"key":"quality","label":"Accessibility/performance/security awareness","maxPoints":10},{"key":"ownership","label":"Clear individual contribution and delivery ownership","maxPoints":10}]'::jsonb),
('Initial Screening',3,true,75,48,false,'[{"key":"communication","label":"Clear professional communication","maxPoints":20},{"key":"experience","label":"Relevant production web-development experience","maxPoints":20},{"key":"stack","label":"Stack readiness for ProFox delivery","maxPoints":15},{"key":"git","label":"Git/GitHub workflow readiness","maxPoints":15},{"key":"quality","label":"Testing/accessibility/performance/security mindset","maxPoints":15},{"key":"delivery","label":"Remote discipline, availability and ownership","maxPoints":15}]'::jsonb),
('Technical Assessment',4,true,80,72,false,'[{"key":"fundamentals","label":"Web/platform fundamentals","maxPoints":20},{"key":"architecture","label":"Implementation and architecture judgment","maxPoints":20},{"key":"debugging","label":"Debugging/problem decomposition","maxPoints":15},{"key":"testing","label":"Testing and regression strategy","maxPoints":15},{"key":"security","label":"Security/data-handling judgment","maxPoints":15},{"key":"performanceAccessibility","label":"Performance and accessibility reasoning","maxPoints":15}]'::jsonb),
('Development Practical',5,true,80,96,false,'[{"key":"fidelity","label":"Accurate implementation against supplied design/requirements","maxPoints":20},{"key":"responsive","label":"Responsive behavior and interaction states","maxPoints":15},{"key":"reuse","label":"Component reuse and maintainable structure","maxPoints":15},{"key":"git","label":"Branch/commit/PR discipline","maxPoints":15},{"key":"testing","label":"Testing and defect handling","maxPoints":15},{"key":"quality","label":"Accessibility/performance/security baseline","maxPoints":15},{"key":"handoff","label":"README/release evidence and handoff clarity","maxPoints":5}]'::jsonb),
('Technical Interview',6,true,80,48,true,'[{"key":"decisionMaking","label":"Engineering judgment and trade-offs","maxPoints":20},{"key":"debugging","label":"Problem-solving/debugging reasoning","maxPoints":15},{"key":"review","label":"Code-review and feedback discipline","maxPoints":15},{"key":"designQa","label":"Designer/QA collaboration and fidelity ownership","maxPoints":15},{"key":"securityQuality","label":"Security, testing and release-quality ownership","maxPoints":20},{"key":"communication","label":"Communication, documentation and accountability","maxPoints":15}]'::jsonb),
('Selected',7,false,null::integer,24,false,'[]'::jsonb),('Agreement Pending',8,false,null::integer,72,false,'[]'::jsonb),('Developer Academy',9,false,null::integer,168,false,'[]'::jsonb),('Final Approval',10,false,null::integer,24,false,'[]'::jsonb),('Ready for System Access',11,false,null::integer,24,false,'[]'::jsonb),('Activated',12,false,null::integer,0,false,'[]'::jsonb)
)
insert into public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric,updated_at)
select j.id,p.stage,p.sort_order,true,p.assessment_required,p.passing_score,p.sla_hours,p.interview_required,p.rubric,now() from j cross join p
on conflict(job_id,stage) do update set sort_order=excluded.sort_order,active=true,assessment_required=excluded.assessment_required,passing_score=excluded.passing_score,sla_hours=excluded.sla_hours,interview_required=excluded.interview_required,rubric=excluded.rubric,updated_at=now();