update public.notification_templates
set subject_template='Set up your ProFox Sales Academy onboarding access',
    body_template=E'Hi {{fullName}},\n\nYour verified ProFox Independent Sales Partner Agreement is complete, and your protected Sales Academy onboarding account is ready.\n\nSet up your account using this secure link:\n{{accountInviteUrl}}\n\nYour onboarding track contains the required 20-module ProFox Sales Academy. Your 10-day completion window starts only after you successfully open this secure link, create your password and enter the Academy.\n\nImportant access rules:\n- This account is for onboarding and training while recruitment is still in progress.\n- Do not create a second account. If this link does not work, contact ProFox Recruitment.\n- Live CRM, customer and active Sales permissions remain locked until the required Academy gates, Final Approval and activation are complete.\n\nApplication reference: {{applicationReference}}\nSupport: {{supportEmail}}\n\nProFox Recruitment Team\nProFox Web Designer\nhttps://www.profoxwebdesigner.com/',
    html_template='<!doctype html><html><body style="margin:0;background:#f4f5fb;font-family:Arial,Helvetica,sans-serif;color:#0f172a"><table role="presentation" width="100%"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="640" style="width:100%;max-width:640px;background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden"><tr><td style="height:4px;background:#000080"></td></tr><tr><td style="padding:28px"><div style="font-size:11px;font-weight:700;letter-spacing:1.2px;color:#000080">SALES ACADEMY ONBOARDING</div><h1 style="font-size:24px;line-height:32px;margin:8px 0 16px">Set up your protected Academy access</h1><p style="font-size:15px;line-height:24px;color:#334155">Hi {{fullName}},<br><br>Your verified Sales Partner Agreement is complete. Your ProFox Sales Academy onboarding account is ready.</p><p><a href="{{accountInviteUrl}}" style="display:inline-block;background:#000080;color:#fff;text-decoration:none;padding:13px 20px;border-radius:9px;font-weight:700">Set Up Sales Academy Account</a></p><div style="margin-top:20px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px;font-size:14px;line-height:23px;color:#334155"><strong>10-day completion window</strong><br>Your 10-day Academy deadline starts only after you successfully use this secure link, create your password and enter the Academy. The required 20-module track includes products and packages, niche training, lead research, outreach, meeting booking, discovery, call practice, mock call review, presentation, objections, closing, quotations, payments, CRM, calendar setup, confidentiality and final certification.</div><p style="font-size:13px;line-height:21px;color:#64748b">This account is onboarding-only. Live CRM, customer and active Sales permissions remain locked until Academy completion, Final Approval and activation. Do not create a second account.</p><p style="font-size:13px;color:#64748b">Application reference: {{applicationReference}}<br>Support: {{supportEmail}}</p></td></tr></table></td></tr></table></body></html>',
    updated_at=now()
where template_key='recruitment_account_invite';

update public.notification_templates
set subject_template='Your ProFox Sales Academy access is ready',
    body_template=E'Hi {{fullName}},\n\nYour verified agreement is complete and your protected ProFox Sales Academy account is ready.\n\nComplete account setup using the most recent Academy invitation email. Your 10-day training completion window begins only after successful account setup.\n\nComplete every required module, assessment, candidate-controlled practical submission and final certification requirement in the assigned 20-module Sales Academy.\n\nTraining access is not live Sales access. CRM, customer and active selling permissions remain protected until Academy completion, Final Approval and activation.\n\nApplication reference: {{applicationReference}}\nSupport: {{supportEmail}}\n\nProFox Sales Academy\nProFox Web Designer\nhttps://www.profoxwebdesigner.com/',
    html_template='<!doctype html><html><body style="margin:0;background:#f4f5fb;font-family:Arial,Helvetica,sans-serif;color:#0f172a"><table role="presentation" width="100%"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="640" style="width:100%;max-width:640px;background:#fff;border:1px solid #e2e8f0;border-radius:14px;overflow:hidden"><tr><td style="height:4px;background:#000080"></td></tr><tr><td style="padding:28px"><div style="font-size:11px;font-weight:700;letter-spacing:1.2px;color:#000080">SALES ACADEMY</div><h1 style="font-size:24px;line-height:32px;margin:8px 0 16px">Your protected Academy access is ready</h1><p style="font-size:15px;line-height:24px;color:#334155">Hi {{fullName}},<br><br>Your verified agreement is complete. Use the most recent Sales Academy account invitation email to finish account setup.</p><div style="margin-top:20px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px;font-size:14px;line-height:23px;color:#334155"><strong>Your 10-day training window has not started yet.</strong><br>It begins only after you successfully create your password and enter the Academy. Once started, complete all required modules, assessments, candidate-controlled practical submissions and final certification requirements within the protected training window.</div><p style="font-size:13px;line-height:21px;color:#64748b">Training access is not live Sales access. CRM, customer and active Sales permissions remain locked until Academy completion, Final Approval and activation.</p><p style="font-size:13px;color:#64748b">Application reference: {{applicationReference}}<br>Support: {{supportEmail}}</p></td></tr></table></td></tr></table></body></html>',
    updated_at=now()
where template_key='recruitment_training';

update public.notification_templates
set body_template=E'Hi {{fullName}},\n\nYour ProFox Sales Academy training window has started.\n\nYou have 10 days to complete all required modules, assessments, candidate-controlled practical submissions and final certification requirements.\n\nDeadline: {{deadlineLabel}}\nOpen Sales Academy: {{academyUrl}}\n\nYour dashboard shows the live countdown and current completion progress. Complete the work steadily rather than leaving modules until the final day.\n\nIf a required item is waiting for ProFox Management review, your countdown is paused while that review is pending.\n\nApplication reference: {{applicationReference}}\nSupport: {{supportEmail}}\n\nProFox Sales Academy\nProFox Web Designer',
    updated_at=now()
where template_key='recruitment_academy_started';

update public.notification_templates
set body_template=E'Hi {{fullName}},\n\nThis is a reminder about your ProFox Sales Academy completion deadline.\n\nStatus: {{deadlineStatus}}\nTime remaining: {{daysRemaining}} day(s)\nDeadline: {{deadlineLabel}}\nOpen Sales Academy: {{academyUrl}}\n\nCurrent progress: {{progressPercent}}%\nCompleted required modules: {{completedModules}} of {{totalModules}}\n\nPlease continue the remaining candidate-controlled training and submissions. If a required item is already waiting for Management review, your countdown is paused until the required ProFox review is resolved.\n\nApplication reference: {{applicationReference}}\nSupport: {{supportEmail}}\n\nProFox Sales Academy\nProFox Web Designer',
    updated_at=now()
where template_key='recruitment_academy_deadline_reminder';

update public.career_jobs
set selection_process=jsonb_set(
      selection_process,
      '{6,text}',
      to_jsonb('After the agreement is verified, approved candidates receive a protected onboarding account for the required 20-module Sales Academy. The 10-day completion window begins after successful account setup. Required Management-review waiting time does not consume the candidate training window.'::text),
      false
    ),
    updated_at=now()
where slug='independent-sales-representative'
  and jsonb_typeof(selection_process)='array'
  and jsonb_array_length(selection_process)>6;