-- Module 20 — 30 final judgment scenarios + 8 operating commitments.
-- Answer distribution: A=8, B=8, C=7, D=7. Exactly 15 critical scenarios.

do $$ declare v_module uuid; begin
 select id into v_module from public.training_modules where slug='final-certification';
 if v_module is null then raise exception 'Module 20 final-certification is missing.'; end if;
 delete from public.training_assessment_questions where module_id=v_module;
 delete from public.training_acknowledgements where module_id=v_module;
 insert into public.training_assessment_questions(module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical) values
 (v_module,'A company matches the target market but you cannot identify any meaningful digital friction yet. What is the strongest qualification action?',
  '["Research further before treating it as a qualified opportunity","Create an opportunity immediately","Assume every business needs a redesign","Send a quotation first"]'::jsonb,0,'Qualification should follow evidence, not the existence of a company record.',1,true,'final_judgment','qualification_evidence',false),
 (v_module,'You cannot verify a prospect’s revenue, so you enter a large estimate as fact to make the account look attractive. What is correct?',
  '["Acceptable if the estimate seems realistic","Never fabricate prospect facts; mark unknown or verify them","Round the estimate down","Ask another rep to enter it"]'::jsonb,1,'Fabricating buyer information corrupts qualification, reporting and trust.',2,true,'final_judgment','fabricated_prospect_data',true),
 (v_module,'A company-generated lead looks promising and you want the self-generated commission bonus. What should happen?',
  '["Change lead source after the first call","Create a duplicate self-generated lead","Preserve the truthful approved lead source","Delete the source field"]'::jsonb,2,'Commission incentives never justify falsifying attribution.',3,true,'final_judgment','lead_source_integrity',true),
 (v_module,'Which first outreach is strongest after you find a specific mobile quote-form problem?',
  '["Send the full price list","Write a generic agency introduction","Ask for a one-hour demo immediately","Reference the real observation, connect it to possible business impact, offer a useful direction and use a low-friction CTA"]'::jsonb,3,'Relevant outreach starts from evidence and earns the next conversation.',4,true,'final_judgment','outreach_relevance',false),
 (v_module,'A prospect has not replied to the first personalized message. What should guide the next follow-up?',
  '["Use the approved cadence and add relevant value/context instead of repeating the same demand","Send messages every hour","Change channels until they answer","Create false urgency"]'::jsonb,0,'Follow-up should be consistent and relevant without becoming pressure or spam.',5,true,'final_judgment','follow_up',false),
 (v_module,'A prospect explicitly says, “Please do not contact me again.” What is the correct action?',
  '["Wait a day and try another channel","Record and respect the no-contact instruction through the approved suppression process","Ask another seller to contact them","Keep automated meetings active"]'::jsonb,1,'An explicit no-contact instruction must be respected.',6,true,'final_judgment','no_contact',true),
 (v_module,'A buyer says “Thursday at 11” but no timezone is stated. What should you do?',
  '["Assume your timezone","Use UTC silently","Confirm the buyer-facing timezone/time before saving the meeting","Book twice in both possible timezones"]'::jsonb,2,'A legitimate meeting requires both sides to understand the same real time.',7,true,'final_judgment','timezone',false),
 (v_module,'During discovery the buyer says, “We need a better website.” What is the best response?',
  '["Recommend the highest package","Start showing templates","Ask budget only","Continue diagnosing current state, gap, impact, outcome, urgency and decision process before recommending"]'::jsonb,3,'The statement is a starting point, not enough diagnosis to prescribe.',8,true,'final_judgment','discovery_depth',false),
 (v_module,'You identify a likely solution halfway through discovery. What should you do?',
  '["Keep listening and validate enough business context before prescribing","Interrupt and pitch immediately","Send the quotation during the call","Close the discovery record"]'::jsonb,0,'Premature recommendations risk solving the wrong problem.',9,true,'final_judgment','premature_recommendation',false),
 (v_module,'Sarah strongly supports the project, but the owner Daniel must approve commercial commitment. What is the correct next step?',
  '["Mark the deal Won","Secure a legitimate review/decision step involving Daniel","Treat Sarah as the final approver","Skip the stakeholder field"]'::jsonb,1,'Positive influence is not the same as final decision authority.',10,true,'final_judgment','stakeholder_authority',false),
 (v_module,'A buyer asks whether an unfamiliar third-party system can be integrated. You have not validated it. What should you say?',
  '["Promise it to preserve momentum","Say all integrations are included","Explain the desired outcome, record the requirement and validate feasibility before promising","Tell the buyer to assume it works"]'::jsonb,2,'Unverified technical capability must be validated instead of invented.',11,true,'final_judgment','feature_fit_uncertainty',false),
 (v_module,'Two catalog directions could work. The larger one pays more commission, but discovery evidence fits the smaller direction better. What should you recommend?',
  '["The higher-commission option","Whichever sounds more premium","Both, without recommendation","The evidence-based best fit, regardless of commission"]'::jsonb,3,'Seller compensation must never distort recommendation quality.',12,true,'final_judgment','commission_bias',true),
 (v_module,'A prospect asks for a feature ProFox has not confirmed it can deliver. What is correct?',
  '["Do not invent capability; route the requirement for validation or an approved custom path","Say yes and let Development solve it later","Promise it only verbally","Add it to CRM as confirmed"]'::jsonb,0,'Inventing capability is a critical integrity failure.',13,true,'final_judgment','invented_capability',true),
 (v_module,'A buyer asks, “Can you guarantee this will double our revenue?” What should the seller do?',
  '["Guarantee it if they sign today","Refuse unsupported guarantees and discuss measurable goals, evidence and controllable outcomes","Guarantee only 50% growth","Put the guarantee in notes but not quotation"]'::jsonb,1,'ProFox can discuss goals and evidence but cannot invent business-outcome guarantees.',14,true,'final_judgment','unauthorized_guarantee',true),
 (v_module,'A buyer says a competitor is 30% cheaper. What is the strongest first response?',
  '["Attack the competitor","Offer a 30% discount","Clarify what they are comparing and isolate whether the concern is value, budget, risk or scope","End the call"]'::jsonb,2,'Objection handling starts with understanding rather than discounting or arguing.',15,true,'final_judgment','competitor_price',false),
 (v_module,'The buyer will sign today only if you give an unapproved discount. What should you do?',
  '["Give it privately","Hide it inside an add-on","Promise it and seek approval later","Stay within authority and route the commercial exception for approval"]'::jsonb,3,'Urgency does not create pricing authority.',16,true,'final_judgment','unauthorized_discount',true),
 (v_module,'The buyer has understood the recommendation, addressed key objections and appears ready. What should you do next?',
  '["Ask clearly for the legitimate decision/commitment and then pause","Keep presenting features","Avoid discussing a decision","Create another discovery call automatically"]'::jsonb,0,'Closing requires clear, respectful decision leadership.',17,true,'final_judgment','closing_readiness',false),
 (v_module,'The buyer says, “I like it, but I need to think.” What is the strongest response?',
  '["Say the offer expires in ten minutes","Clarify what they still need to evaluate and establish an appropriate next decision step","Mark Lost immediately","Offer a discount before asking why"]'::jsonb,1,'Clarify hesitation rather than creating pressure.',18,true,'final_judgment','buyer_hesitation',false),
 (v_module,'A standard package fits, but the buyer requests materially different payment terms. How should the quotation route be treated?',
  '["Standard no-review route","Ignore the change","Treat the altered commercial term as an approval-required exception","Let the customer edit the quotation"]'::jsonb,2,'Approval follows the actual commercial promise, not only the package label.',19,true,'final_judgment','commercial_exception',false),
 (v_module,'A custom/non-catalog commercial line is added, but the seller wants to send the quotation before review. What is correct?',
  '["Send because the buyer is waiting","Remove the approval flag","Ask the buyer to accept verbally first","Do not bypass the required Manager/Admin quotation approval route"]'::jsonb,3,'Bypassing required quotation approval is a critical commercial-control failure.',20,true,'final_judgment','quotation_bypass',true),
 (v_module,'The buyer says they accept, but the CRM quotation record still shows Draft and no accepted record exists. What is the operational truth?',
  '["The quotation is not yet operationally Accepted; use the approved acceptance workflow","Mark payment Verified","Create the project","Change Won status manually"]'::jsonb,0,'Customer conversation and system commercial state must be reconciled through the approved workflow.',21,true,'final_judgment','quotation_state',false),
 (v_module,'A buyer sends a screenshot saying they paid. What should the seller do?',
  '["Mark Won","Treat it as information, acknowledge it and wait for protected ProFox verification","Change amount_paid manually","Start delivery immediately"]'::jsonb,1,'Customer evidence is not protected financial verification.',22,true,'final_judgment','payment_evidence',false),
 (v_module,'The buyer is urgent, so you manually set the payment record to Verified after receiving their screenshot. What is correct?',
  '["Acceptable for small deals","Acceptable if the screenshot looks real","Never manually bypass the protected verification workflow","Only do it on Fridays"]'::jsonb,2,'Manual payment verification is a critical financial-control violation.',23,true,'final_judgment','manual_verified',true),
 (v_module,'A buyer says they paid and wants work started immediately, but qualifying verification is incomplete. What should the opportunity state be?',
  '["Won","Delivered","Client Active","Remain in the truthful pre-Won state until the protected qualifying condition is confirmed"]'::jsonb,3,'Won is a protected business transition, not a seller convenience.',24,true,'final_judgment','premature_won',true),
 (v_module,'Your pipeline target is behind, so you move several opportunities to a later stage even though exit criteria are not met. What should happen?',
  '["Keep stages truthful to completed business conditions","Advance them only until month-end","Create duplicate opportunities instead","Hide the stage history"]'::jsonb,0,'Pipeline reporting must never override CRM truth.',25,true,'final_judgment','stage_manipulation',true),
 (v_module,'An active opportunity has good notes but no next action. What should you add?',
  '["Nothing if the buyer sounded positive","A specific ACTION + OWNER + DATE + PURPOSE / EXPECTED OUTCOME","A generic “follow up” note","A fake meeting"]'::jsonb,1,'An active deal without a legitimate next action is operationally incomplete.',26,true,'final_judgment','missing_next_step',false),
 (v_module,'You missed a customer call and want the dashboard to look better. What should you record?',
  '["Completed","Rescheduled without buyer agreement","The truthful missed/no-show outcome and the legitimate recovery action","Delete the activity"]'::jsonb,2,'Fabricating meetings or activity history is a critical integrity failure.',27,true,'final_judgment','fake_activity',true),
 (v_module,'A customer sends an admin password and OTP in a sales message. What should you do?',
  '["Paste them into CRM","Save them in a spreadsheet","Send them to another rep","Do not store/use them in ordinary sales systems; move the situation to the approved secure process"]'::jsonb,3,'Credentials and authentication secrets require the approved secure process.',28,true,'final_judgment','credential_handling',true),
 (v_module,'A prospect asks you to show a private quotation from another customer to prove your pricing. What should you do?',
  '["Refuse to disclose the other customer’s confidential information and use approved proof/examples instead","Share it with the name removed only if convenient","Screen-share it briefly","Forward it from a personal account"]'::jsonb,0,'Cross-client confidential disclosure is prohibited.',29,true,'final_judgment','cross_client_confidentiality',true),
 (v_module,'You think you clicked a phishing link while working a deal, but nothing looks wrong. What should you do?',
  '["Wait for visible damage","Stop, protect the account/device as authorized, report immediately, preserve evidence and follow incident instructions","Delete browser history and tell nobody","Finish the quotation first"]'::jsonb,1,'Hiding or delaying a material security incident increases risk and violates the operating standard.',30,true,'final_judgment','incident_concealment',true);

 insert into public.training_acknowledgements(module_id,statement,sort_order,required,active) values
 (v_module,'I will diagnose before recommending and sell only solutions that genuinely fit the customer situation.',1,true,true),
 (v_module,'I will never invent ProFox capabilities, guarantees, discounts, commercial terms or delivery commitments to secure a sale.',2,true,true),
 (v_module,'I will keep CRM, meeting, quotation and customer records truthful even when truth makes my pipeline appear weaker.',3,true,true),
 (v_module,'I will treat customer payment confirmation as information and protected ProFox verification as financial truth.',4,true,true),
 (v_module,'I will keep every legitimate active opportunity moving through a clear next action with owner, date and purpose/outcome.',5,true,true),
 (v_module,'I will protect customer, prospect and ProFox confidential information and immediately report security, privacy or commercial incidents.',6,true,true),
 (v_module,'I will use AI, automation and ProFox systems to increase productivity without surrendering human judgment, customer trust or business accuracy.',7,true,true),
 (v_module,'I understand that ProFox certification is permission to represent the company professionally—not permission to bypass its controls or automatic production activation.',8,true,true);
end $$;
