-- Module 20 — 12 sequential end-to-end synthetic deal missions.

do $$ declare v_module uuid; begin
 select id into v_module from public.training_modules where slug='final-certification';
 if v_module is null then raise exception 'Module 20 final-certification is missing.'; end if;
 delete from public.final_certification_missions where module_id=v_module;
 insert into public.final_certification_missions(module_id,mission_key,title,objective,instructions,scenario_data,sort_order,active) values
 (v_module,'research_account','Research the Account','Separate useful public evidence from assumptions before outreach.','Review the synthetic Apex Roofing account and capture verified facts, personalization, unknowns and assumptions you must not make.',
  '{"company":"Apex Roofing & Exteriors","market":"United States","industry":"Residential and commercial roofing","publicSignals":["Outdated mobile website","Manual quote-request form","Recent social posts promote storm-response service","Multiple service areas"],"primaryContact":"Sarah Mitchell — Marketing Director","decisionMakerHypothesis":"Owner likely involved in commercial approval"}'::jsonb,1,true),
 (v_module,'qualify_prospect','Qualify the Prospect','Decide whether Apex deserves active pursuit based on fit and evidence.','Choose Pursue, Nurture or Disqualify and explain the business reasoning. Do not create an opportunity merely because an email exists.',
  '{"company":"Apex Roofing & Exteriors","evidence":"Established service business, reachable marketing lead, visible digital friction, target-market fit","expectedDecision":"pursue"}'::jsonb,2,true),
 (v_module,'personalized_outreach','Build Personalized Outreach','Turn research into a concise, relevant first-message direction.','Use OBSERVATION → RELEVANCE → VALUE → LOW-FRICTION CTA. Do not invent results or claim you already know their internal problem.',
  '{"company":"Apex Roofing & Exteriors","contact":"Sarah Mitchell","channel":"Approved ProFox outbound channel","focus":"Mobile lead experience and follow-up visibility"}'::jsonb,3,true),
 (v_module,'handle_reply_book','Handle the Reply & Book the Meeting','Respond to interest without overpitching and create the correct next conversation.','Sarah replies: “Possibly interested. Can you show me what you mean?” Write the reply, choose the meeting type, confirm buyer timezone and define the next action.',
  '{"reply":"Possibly interested. Can you show me what you mean?","buyerTimezone":"America/New_York","expectedMeetingType":"Discovery","meetingGoal":"Understand current lead journey and business outcome before recommending"}'::jsonb,4,true),
 (v_module,'prepare_discovery','Prepare for Discovery','Enter the buyer conversation with context, purposeful questions and a desired outcome.','Prepare what is known, unknown, worth asking, the meeting objective and the legitimate next step you want to earn.',
  '{"known":"Outdated mobile experience, manual quote request, marketing contact engaged","unknown":"Lead volume, follow-up process, operational impact, buying process, technical constraints","contact":"Sarah Mitchell"}'::jsonb,5,true),
 (v_module,'conduct_discovery','Conduct Discovery','Apply CURRENT → GAP → IMPACT → OUTCOME → WHY NOW → DECISION → FIT → NEXT STEP.','Document the full synthetic discovery picture from the supplied buyer facts. Your notes must distinguish Sarah’s influence from Daniel’s final commercial authority.',
  '{"current":"Website generates enquiries but mobile experience is weak and lead distribution is manual","gap":"Inconsistent follow-up and poor visibility after form submission","impact":"Marketing cannot see which leads receive timely action and opportunities may be lost","outcome":"Connected website + clearer lead flow + measurable follow-up","whyNow":"Important seasonal period approaching","decisionProcess":"Sarah recommends; Daniel Cole, Owner, gives final commercial approval","fit":"ProFox website and approved automation/integration direction","nextStep":"Recommend solution and secure decision-maker review"}'::jsonb,6,true),
 (v_module,'recommend_solution','Recommend the Right Solution','Choose the best-fit live catalog direction based on discovery—not commission.','Select from the current live Sales Catalog and explain the fit. Identify any integration detail that still requires technical validation instead of inventing certainty.',
  '{"case":"Apex Roofing — established business, custom UI/CMS/conversion architecture + approved lead-flow integration direction","expectedProductCode":"PF-WEB-GROWTH","validationNeeded":"Confirm exact lead-routing/integration requirements before promising implementation detail"}'::jsonb,7,true),
 (v_module,'handle_objection','Handle the Competitive Price Objection','Diagnose resistance before responding.','Sarah says: “Another agency is about 30% cheaper.” Apply PAUSE → CLARIFY → VALIDATE → ISOLATE → RESPOND → CONFIRM → ADVANCE without an automatic discount.',
  '{"objection":"Another agency is about 30% cheaper.","possibleUnderlyingConcerns":["Value comparison","Risk","Budget","Internal justification"],"forbidden":"Unauthorized discount or competitor attack"}'::jsonb,8,true),
 (v_module,'close_real_decision','Close for a Real Decision','Secure the legitimate buying action when the current contact is not the final approver.','Sarah is positive but Daniel must approve. Choose the correct decision and describe the commitment you will secure.',
  '{"contact":"Sarah Mitchell","finalDecisionMaker":"Daniel Cole — Owner","expectedDecision":"schedule_decision_maker_review","forbidden":"Marking the opportunity Won from Sarah’s positive reaction"}'::jsonb,9,true),
 (v_module,'commercial_path','Build the Commercial Path','Translate buyer direction into the correct catalog/quotation/approval/payment route.','Use the same live catalog recommendation. Choose the quotation route and state payment terms from the live catalog rather than memory.',
  '{"expectedProductCode":"PF-WEB-GROWTH","expectedRoute":"catalog_auto","rule":"Standard active catalog package follows its live approval/payment configuration; exceptions route for Management review."}'::jsonb,10,true),
 (v_module,'payment_judgment','Protect Payment Truth','Respond professionally when the buyer says they paid before protected verification is complete.','Buyer message: “We’ve paid. Start immediately.” Choose the correct business-state decision and write the customer-facing response.',
  '{"buyerMessage":"We’ve paid. Start immediately.","providerState":"Customer evidence received; protected ProFox verification not complete","expectedDecision":"wait_for_verified_payment","forbidden":"Manual Verified/Won/project-start bypass"}'::jsonb,11,true),
 (v_module,'final_crm_handoff','Final CRM & Handoff Audit','Leave one complete, truthful commercial record another authorized team member can continue from.','Summarize company/contact/stakeholders, lead source/stage, commercial/payment state, next action and handoff context. Do not invent a Won state.',
  '{"company":"Apex Roofing & Exteriors","stakeholders":["Sarah Mitchell — Marketing Director / champion","Daniel Cole — Owner / final commercial decision maker"],"leadSource":"Synthetic company-generated certification lead","commercialTruth":"Recommendation/quotation/payment state must match the verified simulation facts","handoffTest":"Could another authorized ProFox teammate continue without asking you what happened?"}'::jsonb,12,true);
end $$;
