-- Historical alignment marker.
-- This migration was applied directly to Supabase production as
-- 20260828145518_content_creator_project_agreement_gate.
-- The complete idempotent final state is reconciled by
-- 20260828153000_content_creator_recruitment_final_reconciliation.sql.
