-- Module 19 — 10 synthetic confidentiality/security missions

do $$ declare v_module uuid; begin
 select id into v_module from public.training_modules where slug='confidentiality-data-protection';
 if v_module is null then raise exception 'Module 19 missing.'; end if;
 delete from public.confidentiality_training_missions where module_id=v_module;
 insert into public.confidentiality_training_missions(module_id,mission_key,title,objective,instructions,scenario_data,sort_order,active) values
(v_module,'classify_information','Classify the Information','Recognize handling sensitivity before acting.','Review the synthetic items and choose the classification behaviour that protects the most sensitive item.',jsonb_build_object('facts','Website address; internal sales playbook; customer quotation; CRM contact; API key; OTP','options',jsonb_build_array(jsonb_build_object('value','treat_all_public','label','Treat everything as public because some items are public'),jsonb_build_object('value','classify_by_sensitivity','label','Classify each item and protect API key/OTP as Restricted'),jsonb_build_object('value','store_everything_in_crm','label','Store all items together in CRM for convenience'))),1,true),
(v_module,'minimize_record','Minimize the CRM Record','Keep only data that serves a legitimate sales purpose.','A synthetic record contains useful sales context plus unrelated personal details and secrets. Choose the safe cleanup action.',jsonb_build_object('facts','Useful: stakeholder role, need, timeline, next step. Unnecessary: family gossip, ID copy, password, unrelated private detail.','options',jsonb_build_array(jsonb_build_object('value','keep_everything','label','Keep everything in case it is useful later'),jsonb_build_object('value','keep_decision_useful_only','label','Keep legitimate decision-useful sales context and remove unnecessary/sensitive data'),jsonb_build_object('value','move_secrets_to_notes','label','Keep secrets but move them into a hidden CRM note'))),2,true),
(v_module,'spot_phishing','Spot the Phishing Request','Verify unusual high-impact requests independently.','A synthetic “CEO” email urgently requests a full prospect export to an unfamiliar link. Choose the safe action.',jsonb_build_object('facts','Urgent tone; unfamiliar upload domain; large customer-data export request.','options',jsonb_build_array(jsonb_build_object('value','export_immediately','label','Export immediately because the CEO appears to have asked'),jsonb_build_object('value','reply_to_email_only','label','Reply to the same email asking if it is genuine'),jsonb_build_object('value','verify_and_report','label','Pause, verify through a trusted channel, and report the suspicious request'))),3,true),
(v_module,'unexpected_mfa','Handle an Unexpected MFA Prompt','Recognize a possible account-takeover attempt.','A login approval prompt appears even though you are not signing in.',jsonb_build_object('facts','Unexpected authentication prompt on work account.','options',jsonb_build_array(jsonb_build_object('value','approve_to_clear','label','Approve it so the notification stops'),jsonb_build_object('value','deny_secure_report','label','Deny the request, secure the account, and report it'),jsonb_build_object('value','ignore_only','label','Ignore it and continue working'))),4,true),
(v_module,'dangerous_share','Fix a Dangerous File Share','Prevent wrong-recipient, wrong-file and unapproved-channel disclosure.','A synthetic proposal is addressed to Client A, contains Client B material, and uses a personal cloud link.',jsonb_build_object('facts','Wrong attachment + personal storage link + customer recipient.','options',jsonb_build_array(jsonb_build_object('value','send_then_correct','label','Send it now and correct any mistake later'),jsonb_build_object('value','fix_recipient_file_channel','label','Stop and verify recipient, correct file, permission and approved channel before sending'),jsonb_build_object('value','remove_filename_only','label','Rename the file and send from the personal link'))),5,true),
(v_module,'safe_screen_share','Prepare a Safe Screen Share','Prevent cross-client and internal disclosure during a meeting.','Your synthetic desktop contains Client A material, Client B quotation, internal chat, password manager and the presentation.',jsonb_build_object('facts','Multiple sensitive windows are open before a customer call.','options',jsonb_build_array(jsonb_build_object('value','share_entire_desktop','label','Share the entire desktop so switching is easier'),jsonb_build_object('value','share_only_required_window','label','Close/hide unrelated sensitive windows and share only the required application/window'),jsonb_build_object('value','leave_notifications_visible','label','Leave everything open but ask the customer not to look'))),6,true),
(v_module,'safe_crm_note','Rewrite a Dangerous CRM Note','Preserve useful commercial context without storing secrets.','A synthetic CRM note includes a password, irrelevant family detail and a legitimate next action.',jsonb_build_object('facts','Password + unrelated personal detail + valid business next step.','options',jsonb_build_array(jsonb_build_object('value','keep_full_note','label','Keep the full note for completeness'),jsonb_build_object('value','remove_secrets_keep_business_context','label','Remove secrets/unnecessary details and keep only decision-useful business context'),jsonb_build_object('value','email_note_personally','label','Move the full note to personal email instead'))),7,true),
(v_module,'public_prospect_data','Handle Public Prospect Data','Use public information through the approved outreach process without assuming unlimited permission.','You find a company email, LinkedIn profile, personal Gmail address and an old forum entry.',jsonb_build_object('facts','Some contact details are public but permitted use is not automatically clear.','options',jsonb_build_array(jsonb_build_object('value','contact_everything','label','Use every public contact detail because it is visible online'),jsonb_build_object('value','approved_outreach_only','label','Use only the approved ProFox research/outreach workflow and respect suppression rules'),jsonb_build_object('value','store_all_personal_data','label','Copy every public detail into CRM first'))),8,true),
(v_module,'safe_ai_use','Use AI Safely','Gain AI productivity without leaking confidential information.','A synthetic discovery transcript contains customer name, private phone, password and business problem.',jsonb_build_object('facts','The task is to draft a follow-up; the transcript contains unnecessary sensitive details.','options',jsonb_build_array(jsonb_build_object('value','paste_everything_any_ai','label','Paste the full transcript into any convenient AI tool'),jsonb_build_object('value','approved_ai_minimized_context','label','Use an approved AI tool with only the minimum authorized business context and remove secrets'),jsonb_build_object('value','include_password_for_context','label','Keep the password because more context improves the answer'))),9,true),
(v_module,'incident_response','Respond to a Security Incident','Contain a disclosure quickly and preserve evidence.','You accidentally send a synthetic confidential quotation to the wrong prospect.',jsonb_build_object('facts','Wrong-recipient confidential quotation; mistake noticed immediately.','options',jsonb_build_array(jsonb_build_object('value','hide_and_delete','label','Delete local evidence and hope nobody notices'),jsonb_build_object('value','stop_protect_report_preserve_follow','label','Stop, protect where authorized, report immediately, preserve evidence and follow incident instructions'),jsonb_build_object('value','wait_for_customer_complaint','label','Wait to see whether the recipient complains before reporting'))),10,true);
end $$;
