-- Module 16 — Payment Process scenario certification
-- 25 scenarios, answer-key distribution A/B/C/D = 7/6/6/6, 12 critical controls.

do $$ declare v_module uuid; begin
  select id into v_module from public.training_modules where slug='payment-process';
  if v_module is null then raise exception 'Module 16 payment-process is missing.'; end if;
  delete from public.training_assessment_questions where module_id=v_module;
  delete from public.training_acknowledgements where module_id=v_module;

  insert into public.training_assessment_questions(module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical) values
  (v_module,'A customer has formally accepted a standard Launch quotation. What should Sales do next?', '["Prepare the approved first payment milestone from the accepted quotation","Mark the opportunity Won","Create the client manually","Ask for any amount the buyer prefers"]'::jsonb,0,'Acceptance hands off to the approved payment request process; it is not itself financial verification.',1,true,'scenario','accepted_quote_next_payment',false),
  (v_module,'The customer sends a transfer screenshot and says “Paid.” What is the safest next action?', '["Tell Delivery to start","Thank them and follow the protected payment-verification status","Change amount_paid to match the screenshot","Create a second payment record"]'::jsonb,1,'Customer evidence is useful information, but ProFox financial truth comes from the protected verification process.',2,true,'scenario','screenshot_not_verification',false),
  (v_module,'A seller wants to set the payment to Verified so onboarding can begin faster. What is correct?', '["Allowed when screenshot looks genuine","Allowed for the assigned seller","Do not do it; verification is protected/Admin-only","Set Won first and verify later"]'::jsonb,2,'Sales cannot self-verify money or settlement fields.',3,true,'scenario','manual_verified_bypass',true),
  (v_module,'A Launch buyer asks to replace the approved schedule with a different installment structure. What should Sales do?', '["Agree immediately","Create a Custom Milestone yourself","Change the package schedule for this buyer","Treat it as a commercial exception and obtain the required approval"]'::jsonb,3,'Changing an approved payment schedule is a commercial exception, not seller discretion.',4,true,'scenario','unapproved_installment_change',true),
  (v_module,'The payment request amount does not match the accepted commercial record. What should happen?', '["Stop and reconcile the quotation, schedule and payment before sending","Send it and adjust later","Ask the buyer to choose the amount","Edit the quotation silently"]'::jsonb,0,'Material amount mismatches must be resolved before collection.',5,true,'scenario','payment_amount_mismatch',true),
  (v_module,'A customer asks for the salesperson’s personal account because it is easier. Correct response?', '["Accept it and forward the money later","Use only an approved ProFox payment channel","Use a colleague’s account instead","Accept only if the amount is small"]'::jsonb,1,'Business funds must never be routed through personal or improvised accounts.',6,true,'scenario','personal_payment_account',true),
  (v_module,'The customer asks which payment is due now. What should the seller use?', '["Memory of the package","The largest remaining balance","The accepted quotation and current Admin-configured milestone schedule","A generic 50% request"]'::jsonb,2,'The accepted commercial record and live configured schedule are the source of truth.',7,true,'scenario','current_milestone_truth',false),
  (v_module,'The official payment link fails for the customer. What is the correct response?', '["Send personal bank details","Keep asking them to retry forever","Use a random older link","Check the request/link state and use the approved resend or reissue process"]'::jsonb,3,'Technical payment friction should be resolved through the approved payment workflow.',8,true,'scenario','payment_link_failure',false),
  (v_module,'The provider shows an intermediate payment state, but the customer wants work to start immediately. What controls?', '["The ProFox protected verification state controls activation","Any gateway email is enough","Customer confidence is enough","Sales may override for priority clients"]'::jsonb,0,'Intermediate provider states do not replace ProFox verification.',9,true,'scenario','intermediate_state_activation',true),
  (v_module,'A payment request is only partially paid. What should Sales understand?', '["The full milestone is complete","The payment remains partially satisfied until the required amount is confirmed","The opportunity should be Won","The remaining amount can be deleted"]'::jsonb,1,'A partial receipt is not full milestone verification and does not trigger the stronger qualifying-payment transition.',10,true,'scenario','partial_payment_meaning',false),
  (v_module,'Two identical payment webhook notifications appear. What should Sales do?', '["Create two payments","Tell the buyer they paid twice","Let the idempotent backend/payment record determine truth","Create two commissions"]'::jsonb,2,'Repeated notifications can be duplicate events; the protected backend and payment reference control.',11,true,'scenario','duplicate_payment_event',false),
  (v_module,'A customer offers to send card details and an OTP over WhatsApp so the seller can complete checkout. What is correct?', '["Accept only the OTP","Store it temporarily in CRM","Use it if the customer gives permission","Refuse to receive/use credentials and direct the customer to secure checkout"]'::jsonb,3,'Sales must never request, retain or use card credentials, passwords, PINs or OTPs.',12,true,'scenario','sensitive_payment_credentials',true),
  (v_module,'The customer’s payment link has expired. What should Sales do?', '["Use the approved process to issue/resend the current valid request","Edit the expired URL","Use another customer’s link","Tell them to transfer personally"]'::jsonb,0,'Expired/cancelled requests must be replaced or reissued through the approved workflow.',13,true,'scenario','expired_payment_request',false),
  (v_module,'The customer appears to have paid a different amount than the request. What should happen?', '["Change amount_due to match","Flag and reconcile the mismatch through the authorized process","Mark full payment anyway","Delete the existing request"]'::jsonb,1,'Financial discrepancies must remain visible and be reconciled rather than hidden.',14,true,'scenario','wrong_amount_received',true),
  (v_module,'A customer asks to settle an accepted USD quotation in another currency. What is the safest judgment?', '["Convert it yourself using today’s web rate","Always refuse every currency request","Treat it as an exception unless the commercial arrangement already authorizes it","Change the currency field and keep the same number"]'::jsonb,2,'Currency is part of the commercial agreement; changes require the appropriate authority.',15,true,'scenario','currency_change_request',false),
  (v_module,'The customer asks for another copy of the official payment link. What should Sales do?', '["Create a new deal","Send a personal account","Change the milestone","Resend/reissue through the approved process while preserving the same commercial context"]'::jsonb,3,'Helping the customer access the approved request is normal payment support.',16,true,'scenario','resend_payment_link',false),
  (v_module,'A qualifying Advance is fully Verified by the protected workflow. What should happen next?', '["Allow the protected Won/client/handoff workflow to proceed and verify the CRM result","Sales creates another client manually","Sales edits commission records","Create a second Advance request"]'::jsonb,0,'Verified qualifying payment can trigger the protected downstream business transition.',17,true,'scenario','verified_payment_handoff',false),
  (v_module,'The buyer says: “Start today; I promise the required payment will come tomorrow.” What is correct?', '["Start because the quote is accepted","Do not bypass the required qualifying-payment verification","Mark Won temporarily","Create the client and wait"]'::jsonb,1,'A promise to pay does not satisfy a required verified-payment condition.',18,true,'scenario','start_before_verification',true),
  (v_module,'A chargeback/dispute is reported. What should the seller do?', '["Delete uncomfortable messages","Ask the buyer to cancel the dispute before helping","Preserve records and escalate through the authorized dispute process","Alter the quotation to improve the case"]'::jsonb,2,'Disputes require truthful evidence preservation and authorized handling.',19,true,'scenario','payment_dispute_handling',true),
  (v_module,'A customer asks the salesperson to refund their deposit immediately. What may Sales do?', '["Promise a full refund","Send personal money","Set the payment to Refunded","Document the request and use the authorized refund/commercial process"]'::jsonb,3,'Refunds are controlled financial actions; Sales cannot independently promise or execute them.',20,true,'scenario','unauthorized_refund',true),
  (v_module,'An old payment request contains the wrong customer context. What should happen?', '["Correct/cancel/reissue through the approved workflow before using it","Send it because the amount is right","Change only the email in a screenshot","Tell the customer to ignore the name"]'::jsonb,0,'Payment requests must remain linked to the correct customer and accepted commercial record.',21,true,'scenario','wrong_customer_payment_request',false),
  (v_module,'An approved add-on is already part of the accepted quotation and its legitimate milestone is due. What controls the request?', '["A new sales negotiation","The accepted commercial terms and current approved milestone","The add-on’s marketing description only","Whatever amount makes collection easiest"]'::jsonb,1,'Approved scope is collected according to the accepted commercial structure.',22,true,'scenario','approved_addon_payment',false),
  (v_module,'A customer has already sent an OTP and asks the seller to use it. What is correct?', '["Use it quickly before expiry","Save it for Finance","Do not use or retain it; direct the customer to secure checkout and follow security procedure","Forward it to another seller"]'::jsonb,2,'OTP and other sensitive credentials must never be used or stored by Sales.',23,true,'scenario','received_otp',true),
  (v_module,'The seller cannot tell whether a requested payment exception was approved. What should they do?', '["Assume it was approved","Choose the most customer-friendly option","Use the old schedule","Stop and verify the approved commercial source of truth"]'::jsonb,3,'Uncertain authority is a reason to verify, not improvise.',24,true,'scenario','unclear_exception_authority',false),
  (v_module,'The buyer verbally promises payment tomorrow and the seller wants to mark the opportunity Won today. Correct judgment?', '["Never do it; Won follows the protected qualifying-payment workflow","Allowed after verbal promise","Allowed if probability is above 90%","Allowed to help forecasting"]'::jsonb,0,'Pipeline state must reflect verified business events, not hoped-for payment.',25,true,'scenario','manual_won_before_payment',true);

  insert into public.training_acknowledgements(module_id,statement,sort_order,required,active) values
  (v_module,'I understand that customer confirmation or a payment screenshot does not equal ProFox payment verification.',1,true,true),
  (v_module,'I will use only approved ProFox payment methods and will never request payment to my personal account.',2,true,true),
  (v_module,'I will never request, store or handle a client card credential, CVV, PIN, banking password or OTP.',3,true,true),
  (v_module,'I will follow the accepted quotation and live Admin-configured payment schedule rather than inventing payment terms.',4,true,true),
  (v_module,'I will not manually mark a payment Verified, an opportunity Won or a project ready to start to bypass the protected payment workflow.',5,true,true),
  (v_module,'I will escalate payment mismatches, refunds, disputes, unusual requests and commercial exceptions instead of improvising.',6,true,true),
  (v_module,'I understand that my job is to make payment easy and professional while protecting the accuracy of ProFox financial records.',7,true,true);
end $$;
