-- Module 9 — 25 scenario certification questions + 7 required acknowledgements.
WITH m AS (SELECT id FROM public.training_modules WHERE slug='discovery-script')
INSERT INTO public.training_assessment_questions(
  module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical,created_at,updated_at
)
SELECT m.id,q.prompt,q.options,q.correct_index,q.explanation,q.sort_order,true,q.section,q.case_key,q.critical,now(),now()
FROM m CROSS JOIN (VALUES
('A prospect opens with “We need a better website.” What is the strongest first discovery move?',jsonb_build_array('Present the Premium package','Ask what is making them feel the current website needs to change','Tell them the website is outdated','Ask for the maximum budget'),1,'The stated request is a symptom or desired solution. Diagnose what is driving it before recommending.',1,'diagnosis','website_symptom',false),
('You researched the company before the call. How should that research be used?',jsonb_build_array('Treat every finding as confirmed fact','Use it as a hypothesis and ask the buyer to validate or correct it','Hide the fact that you researched them','Use it to skip discovery entirely'),1,'Preparation improves relevance, but research is not the same as buyer-confirmed truth.',2,'preparation','research_hypothesis',false),
('Which opening best follows the ProFox discovery standard?',jsonb_build_array('Let me show you our portfolio first','I want to understand what is happening today, what you want to improve and why it matters; if we can genuinely help I will explain how, and if not I will tell you','How much can you spend?','I have 27 questions, so let us begin'),1,'A strong opening creates clarity, permission and a low-pressure agenda.',3,'opening','agenda_permission',false),
('A buyer says slow lead follow-up is a problem. What is the best next question?',jsonb_build_array('Would you like our automation package?','What normally happens when follow-up is delayed?','Can you sign today?','Do you want a discount?'),1,'Move from the problem statement into business impact before prescribing a service.',4,'impact','slow_followup',false),
('A prospect says referrals are their main source of business. Which follow-up is strongest?',jsonb_build_array('Referrals are bad; you need paid ads','Is the issue that referrals are declining, or that you want a more predictable additional channel?','How much cash is in the bank?','We guarantee more leads'),1,'Clarify the actual business gap rather than assuming referrals are a problem.',5,'root_cause','referral_dependency',false),
('A seller tells a buyer, “Our automation will definitely recover $15,000 every month,” based on a hypothetical scenario. How is this judged?',jsonb_build_array('Excellent value selling','Acceptable if the buyer seems convinced','A critical failure because hypothetical ROI was presented as guaranteed','Required for high-ticket selling'),2,'Use buyer-supplied numbers to explore scenarios, never to manufacture guaranteed ROI.',6,'trust','fabricated_roi',true),
('A buyer cannot quantify the exact revenue impact of a manual process. What should the seller do?',jsonb_build_array('Invent a reasonable number','Record the unknown, explore other measurable impact and decide whether data must be gathered later','Assume there is no value','End discovery immediately'),1,'Lack of precise data is not permission to fabricate precision.',7,'value','unknown_metrics',false),
('Which question best uncovers desired future state?',jsonb_build_array('Which ProFox feature do you like most?','If this worked the way you wanted, what would be different six months from now?','Can you pay today?','Which competitor do you dislike?'),1,'Desired outcome should be expressed in business terms before solution features.',8,'outcome','future_state',false),
('Discovery uncovers seven problems. What is the strongest next move?',jsonb_build_array('Sell seven separate services immediately','Ask which issue matters most and which improvement would create the biggest difference','Ignore all but the easiest technical issue','Send every package'),1,'Broad discovery should narrow toward the most important business priority.',9,'priority','many_problems',false),
('A buyer says they want the project “soon,” but gives no business reason. What should the seller do?',jsonb_build_array('Create a fake deadline','Ask why the timing matters and whether a real event or consequence is driving it','Mark the opportunity urgent in CRM','Offer an unauthorized discount expiring today'),1,'Discover the customer’s real clock; do not manufacture urgency.',10,'urgency','vague_timing',false),
('A seller says, “Only one implementation slot is left,” knowing this is false. How is this judged?',jsonb_build_array('Strong scarcity technique','A critical failure: fabricated urgency damages trust','Acceptable for Premium prospects','Fine if the seller needs quota'),1,'Scarcity and deadlines must be truthful and approved.',11,'trust','false_urgency',true),
('A prospect says nothing serious happens if they postpone the project for a year. What should the seller do?',jsonb_build_array('Invent consequences','Accept that urgency may be low and qualify/nurture accordingly','Pressure them harder','Record a fake critical event'),1,'Good discovery can reveal low urgency. Truth is more useful than pipeline theatre.',12,'status_quo','low_urgency',false),
('A contact says their business partner makes the final decision. What is the best response?',jsonb_build_array('Dismiss the contact as unqualified','Respect their role, understand the decision process and ask whether the partner should join the next relevant conversation','Contact the partner secretly','Record the current contact as sole decision maker'),1,'Understand the decision system without devaluing or bypassing the current contact.',13,'decision','stakeholder_role',false),
('A seller knowingly records a researcher as the “final decision maker” to improve qualification metrics. How is this judged?',jsonb_build_array('Acceptable CRM simplification','A critical failure because CRM decision data was intentionally falsified','Good forecasting practice','Fine if the lead is promising'),1,'CRM qualification data must represent known truth.',14,'trust','false_decision_data',true),
('Which question best uncovers decision criteria?',jsonb_build_array('Do you like navy or red?','When you compare possible partners, what will matter most in the decision?','Can we be your cheapest option?','Will you promise to choose us?'),1,'Decision criteria reveal how the buyer will evaluate solutions and partners.',15,'decision','decision_criteria',false),
('A buyer asks the price before agreeing to another meeting. The seller knows the current approved package pricing. What should happen?',jsonb_build_array('Hide all pricing until they book','Share approved current pricing accurately and explain that fit depends on scope/goals','Invent a lower price','Quote a custom application without scoping'),1,'Known approved pricing should not be concealed solely to manipulate progression.',16,'commercial','price_transparency',false),
('A seller offers a 25% discount that has not been approved to keep the opportunity moving. How is this judged?',jsonb_build_array('Good negotiation','A critical failure because the seller made an unauthorized commercial commitment','Acceptable during discovery','Required if budget is low'),1,'Only approved pricing, discount and commercial terms may be offered.',17,'trust','unauthorized_discount',true),
('A prospect asks whether ProFox can build a complex integration the seller has never verified. What is the strongest answer?',jsonb_build_array('Promise it immediately','Say the requirement needs technical validation before ProFox commits to scope or feasibility','Say every integration is easy','Add it to the quote anyway'),1,'Custom functionality must not be promised before feasibility and scope are understood.',18,'service_fit','technical_unknown',false),
('A seller promises a complex integration is definitely possible without validation. How is this judged?',jsonb_build_array('Strong confidence','A critical failure because ProFox capability was knowingly misrepresented','Fine if engineering can investigate later','Required to maintain momentum'),1,'Do not misrepresent capabilities or make unapproved technical commitments.',19,'trust','capability_misrepresentation',true),
('The prospect answers a question with “Our team wastes hours copying data.” What is the best listening move?',jsonb_build_array('Move immediately to the next scripted question','Clarify/deepen the answer and use the buyer’s own language to understand where the time is lost','Rename it digital transformation and start pitching','Interrupt with the application feature list'),1,'Discovery should follow meaning, not a rigid question sequence.',20,'listening','follow_meaning',false),
('Before recommending a solution, what should the seller do?',jsonb_build_array('Summarize the important current state, gap, impact, outcome, timing and decision context and ask the buyer to confirm','Send a quote immediately','Assume the notes are correct','Describe every ProFox service'),0,'A validated summary earns the right to prescribe and catches misunderstandings.',21,'validation','summary_before_prescribe',false),
('A seller writes in CRM that the prospect loses “$50,000 monthly” even though the prospect never stated or supported that number. How is this judged?',jsonb_build_array('Helpful forecasting','A critical failure because prospect/business information was fabricated','Acceptable estimate','Fine if marked high priority'),1,'Business impact and CRM notes must not contain invented facts presented as prospect truth.',22,'trust','fabricated_business_data',true),
('A buyer explicitly says, “Please stop contacting me.” What should the seller do?',jsonb_build_array('Continue from another channel','Respect the request and record the communication boundary appropriately','Wait two days and call','Ask another seller to contact them'),1,'Explicit stop/no-contact requests must be respected.',23,'trust','explicit_stop',true),
('A prospect shares confidential internal operating information during discovery. What is the correct standard?',jsonb_build_array('Post it in a public sales channel','Use and store it only through approved business systems and protect it according to ProFox confidentiality/data rules','Forward it to unrelated prospects as proof','Put it in a public case study'),1,'Prospect information must be handled only for legitimate business purposes in approved systems.',24,'trust','confidential_information',true),
('Which closing structure best ends a legitimate discovery call?',jsonb_build_array('Sounds good, let me know','RECAP → CONFIRM FIT → AGREE NEXT STEP → OWNER → DATE','Send a quote regardless of fit','Mark Won if the prospect was friendly'),1,'Discovery should end with a truthful outcome, a mutually understood next action, an owner and timing.',25,'next_step','clear_next_step',false)
) AS q(prompt,options,correct_index,explanation,sort_order,section,case_key,critical);

WITH m AS (SELECT id FROM public.training_modules WHERE slug='discovery-script')
INSERT INTO public.training_acknowledgements(module_id,statement,sort_order,required,active,created_at,updated_at)
SELECT m.id,a.statement,a.sort_order,true,true,now(),now()
FROM m CROSS JOIN (VALUES
('I will diagnose before prescribing and will not manufacture a business problem to create a sale.',1),
('I will use buyer-supported facts and clearly labelled scenarios; I will not invent ROI, revenue loss, guarantees, or prospect statements.',2),
('I will use only the live approved ProFox pricing and commercial terms and will not offer unauthorized discounts or hide known pricing solely to force progression.',3),
('I will not promise unverified functionality, integrations, delivery outcomes, or other capabilities before they are approved and properly scoped.',4),
('I will record discovery information, stakeholder roles, business impact and next steps truthfully in ProFox CRM.',5),
('I will respect explicit no-contact requests and protect confidential prospect information in approved systems.',6),
('I understand Module 9 certifies discovery knowledge and judgment; Module 10 provides practice and Module 11 remains the human-reviewed Mock Sales Call proof.',7)
) AS a(statement,sort_order);
