-- Admin-only, read-only previews of one real team member dashboard per department.
-- The authenticated Admin identity never changes, so previews cannot inherit an
-- employee's mutation permissions or accidentally modify their live work.

create table if not exists public.admin_team_dashboard_preview_events (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.user_profiles(id) on delete restrict,
  previewed_user_id uuid not null references public.user_profiles(id) on delete restrict,
  department text not null,
  role_snapshot text not null,
  status_snapshot text not null,
  opened_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint admin_team_dashboard_preview_events_different_users
    check (admin_user_id <> previewed_user_id)
);

create index if not exists admin_team_dashboard_preview_events_admin_opened_idx
  on public.admin_team_dashboard_preview_events(admin_user_id, opened_at desc);
create index if not exists admin_team_dashboard_preview_events_target_opened_idx
  on public.admin_team_dashboard_preview_events(previewed_user_id, opened_at desc);

alter table public.admin_team_dashboard_preview_events enable row level security;
revoke all on table public.admin_team_dashboard_preview_events from public, anon, authenticated;
revoke all on sequence public.admin_team_dashboard_preview_events_id_seq from public, anon, authenticated;

create or replace function public.admin_record_team_dashboard_preview(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_admin_id uuid := auth.uid();
  v_target public.user_profiles%rowtype;
  v_event_id bigint;
  v_department text;
begin
  if v_admin_id is null or not public.is_admin() then
    raise exception 'Administrator access is required.';
  end if;
  if p_user_id is null or p_user_id = v_admin_id then
    raise exception 'Choose a current team member to preview.';
  end if;

  select * into v_target
  from public.user_profiles
  where id = p_user_id;

  if not found then
    raise exception 'Team member was not found.';
  end if;
  if v_target.role in ('admin','customer','pending')
     or v_target.status = 'pending'
     or lower(coalesce(v_target.email,'')) like '%@profoxwebdesigner.test' then
    raise exception 'Only a real current team member dashboard can be previewed.';
  end if;

  v_department := case
    when v_target.role in ('sales','sales_rep','sales_team') then 'Sales'
    when v_target.role in ('project_manager','site_manager') then 'Project Management'
    when v_target.role in ('content_writer','editor') then 'Content'
    when v_target.role = 'uiux_designer' then 'UI/UX Design'
    when v_target.role in ('developer','web_developer','developer_designer') then 'Development'
    when v_target.role = 'qa' then 'Quality Assurance'
    when v_target.role in ('finance','accountant') then 'Finance'
    else null
  end;

  if v_department is null then
    raise exception 'This account is not assigned to a supported internal department.';
  end if;

  insert into public.admin_team_dashboard_preview_events(
    admin_user_id, previewed_user_id, department, role_snapshot, status_snapshot, metadata
  ) values (
    v_admin_id, v_target.id, v_department, v_target.role, v_target.status,
    jsonb_build_object('mode','read_only','source','admin_team_dashboard_preview')
  ) returning id into v_event_id;

  return jsonb_build_object(
    'eventId', v_event_id,
    'userId', v_target.id,
    'department', v_department,
    'role', v_target.role,
    'status', v_target.status,
    'openedAt', now(),
    'readOnly', true
  );
end;
$function$;

revoke all on function public.admin_record_team_dashboard_preview(uuid) from public, anon, authenticated;
grant execute on function public.admin_record_team_dashboard_preview(uuid) to authenticated;

comment on table public.admin_team_dashboard_preview_events is
  'Append-only audit trail for Admin read-only previews of real team dashboards.';
comment on function public.admin_record_team_dashboard_preview(uuid) is
  'Authorizes and audits an Admin opening a read-only real-team dashboard preview.';
