-- Module 12 — Product Presentation — scenario certification
-- 25 buyer situations, 12 critical trust/commercial checks, 7 acknowledgements.

do $$
declare v_module uuid;
begin
  select id into v_module from public.training_modules where slug='presentation-skills';
  if v_module is null then raise exception 'Module 12 presentation-skills not found.'; end if;

  delete from public.training_assessment_questions where module_id=v_module;
  delete from public.training_acknowledgements where module_id=v_module;

  insert into public.training_assessment_questions
    (module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical)
  values
  (v_module,'A roofing buyer said the main issue is unpredictable qualified enquiries, with outdated visuals as a secondary concern. What should you present first?',jsonb_build_array('A full tour of ProFox design styles','The trust and enquiry journey tied to qualified lead generation','Every available website feature','The most expensive package'),1,'Presentation order should follow the buyer’s verified priority. Outdated visuals may matter, but the commercial priority is the trust/conversion journey.',1,true,'scenario','priority-order',false),

  (v_module,'You open a presentation for a custom-app prospect. Which first business section is strongest?',jsonb_build_array('About ProFox and company history','Technology stack overview','What We Heard: current workflow, bottleneck, impact and desired change','A complete feature roadmap'),2,'Start by proving you understood the buyer. The recommendation should follow a confirmed recap of their world.',2,true,'scenario','what-we-heard',false),

  (v_module,'Discovery produced seven problems. What is the best presentation approach?',jsonb_build_array('Give each problem equal presentation time','Choose the 1–3 priorities with the strongest buyer-verified impact and keep the rest secondary','Only show the easiest features to demo','Let the seller choose based on personal preference'),1,'Strong presentations narrow discovery into the few priorities that matter most to the buying decision.',3,true,'scenario','focus',false),

  (v_module,'A prospect asks whether a specific third-party API will definitely integrate with the proposed custom app. You have not validated it. What should you say?',jsonb_build_array('Yes, ProFox can integrate with anything','It should probably work, so include it as committed scope','Capture the exact API/version and have the technical team verify feasibility before committing','Avoid answering and move to another slide'),2,'Unverified technical commitments create delivery and trust risk. State the uncertainty clearly and verify it with the technical team.',4,true,'scenario','technical-validation',true),

  (v_module,'You do not have a case study from the buyer’s exact industry. What is the strongest action?',jsonb_build_array('Invent a similar project so the buyer feels confident','Use the closest verified evidence and explain honestly why it is relevant','Claim a confidential project cannot be named','Show an unrelated famous logo without context'),1,'Never manufacture proof. Use the closest verified case, capability evidence, process evidence or expertise and explain the relevance honestly.',5,true,'scenario','proof-integrity',true),

  (v_module,'A buyer says, “Why does mobile responsiveness matter to us?” Which response best translates value?',jsonb_build_array('Because responsive design is standard now','Because ProFox always builds responsive websites','Because prospects may reach you from mobile, so the enquiry journey must remain clear and usable there too','Because Google requires every site to use our framework'),2,'Translate the capability into the buyer’s customer journey and business effect rather than stopping at a technical feature.',6,true,'scenario','value-translation',false),

  (v_module,'A seller wants to tell a buyer, “This new website will double your leads.” There is no verified evidence supporting that claim. What is correct?',jsonb_build_array('Use the claim if the buyer seems excited','Reduce it to “probably double”','Explain the intended conversion improvements and potential business value without guaranteeing a result','Only make the claim verbally, not in writing'),2,'Unsupported ROI or performance claims are prohibited. Explain mechanisms and intended value without presenting hypothetical improvement as guaranteed fact.',7,true,'scenario','roi-integrity',true),

  (v_module,'During a demo the buyer asks a detailed question about one workflow. What should the seller do?',jsonb_build_array('Finish the remaining slides first','Engage the question, clarify what matters, and adapt the presentation if useful','Tell them questions are saved for the end','Ignore it unless it appears on the agenda'),1,'Buyer questions reveal value, uncertainty and risk. Strong presentations are interactive rather than rigid slide performances.',8,true,'scenario','interaction',false),

  (v_module,'You discover during the presentation that a capability you planned to show does not actually exist in the approved ProFox offer. What must you do?',jsonb_build_array('Describe it as coming soon','Say the development team can definitely build it','Correct the expectation and only discuss validated current capability or an approved assessment path','Keep presenting it because it is already in the deck'),2,'Misrepresenting ProFox capability is a critical trust failure. Correct the record immediately and stay within approved capability.',9,true,'scenario','capability-integrity',true),

  (v_module,'A custom-app buyer asks for a six-week delivery guarantee before the technical team has assessed scope. What is the correct response?',jsonb_build_array('Guarantee six weeks to preserve momentum','Promise five weeks to be competitive','Explain that timeline must follow approved scope/technical assessment before commitment','Offer a verbal guarantee but do not write it down'),2,'Delivery commitments must be validated. Presentation does not authorize the seller to promise an unapproved timeline.',10,true,'scenario','timeline-integrity',true),

  (v_module,'Which sequence best fits a controlled ProFox demonstration?',jsonb_build_array('Feature → feature → feature → price','Set context → show relevant capability → explain buyer value → ask for reaction','Company history → portfolio → technology stack','Demo everything → ask which parts they liked'),1,'Use context, relevant demonstration, value translation and buyer engagement. Every shown item should connect to discovery.',11,true,'scenario','demo-control',false),

  (v_module,'The buyer likes the solution but asks for a 25% discount that you are not authorized to give. What should you do?',jsonb_build_array('Approve it to keep the deal moving','Invent a temporary promotion','Explain that you cannot authorize that change and follow the approved commercial process','Change scope secretly while keeping the same promise'),2,'Unauthorized discounts or commercial commitments are critical failures. Stay within approved authority and escalate correctly.',12,true,'scenario','commercial-authority',true),

  (v_module,'The buyer has a founder, marketing manager and operations lead in the room. What is the best presentation behavior?',jsonb_build_array('Give each person a different version of the facts','Ask what each stakeholder most needs to understand and adapt emphasis while keeping one consistent truth','Speak only to the founder','Present only technical details so everyone gets the same content'),1,'Adapt emphasis to stakeholder concerns, but never change facts, scope or certainty between stakeholders.',13,true,'scenario','stakeholders',false),

  (v_module,'A buyer asks the price of the relevant approved package. The seller knows the current live catalog price. What is prohibited?',jsonb_build_array('Answering transparently and then clarifying fit','Checking the live Sales Catalog before quoting','Hiding the approved price solely to force another meeting','Explaining why a different direction may fit better'),2,'Deliberately hiding approved pricing to manipulate progression violates the ProFox presentation standard.',14,true,'scenario','pricing-transparency',true),

  (v_module,'A seller wants the higher commission and recommends Premium even though discovery clearly supports the smaller approved package. What is correct?',jsonb_build_array('Premium should always be recommended first','Recommend the best-fit direction even when it is lower priced','Offer Premium and hide the smaller option','Tell the buyer the smaller option is unavailable'),1,'Intentionally recommending a materially unsuitable higher-priced option for commission is a critical integrity failure.',15,true,'scenario','fit-over-commission',true),

  (v_module,'A buyer says their priority changed since discovery. What should you do?',jsonb_build_array('Continue the original deck because preparation is already complete','Pause, understand and validate the change, then adapt the recommendation','Tell them the change must wait until the next meeting','Ignore it unless it changes price'),1,'Presentation is a continuation of discovery. If the business context changes, revalidate before prescribing.',16,true,'scenario','changed-priority',false),

  (v_module,'You have a screenshot from another client’s internal dashboard containing names and private operational data. What should you do?',jsonb_build_array('Show it because it proves capability','Blur one name and show the rest','Do not expose it; use only approved, non-confidential presentation assets','Show it only if screen sharing is not recorded'),2,'Confidential client information must never be used as presentation proof without appropriate authorization and sanitization.',17,true,'scenario','confidentiality',true),

  (v_module,'The buyer asks, “How would this improve our current process?” Which answer structure is strongest?',jsonb_build_array('List the programming languages','Before → required change → improved operating state','Read the package inclusions','Show unrelated portfolio work'),1,'The Before → Change → After structure makes the buyer’s transformation clear without requiring fabricated outcome guarantees.',18,true,'scenario','story',false),

  (v_module,'You realize the package you described does not actually include an essential item you told the buyer was included. What is required?',jsonb_build_array('Leave it uncorrected until quotation','Correct the scope immediately and verify the live catalog/approved solution','Ask delivery to include it later for free','Change the CRM notes to match what you said'),1,'Misrepresenting scope or deliverables is a critical failure. Correct the expectation and use the approved source of truth.',19,true,'scenario','scope-integrity',true),

  (v_module,'A non-technical owner is evaluating a custom app. What should you emphasize first?',jsonb_build_array('Database engine and frontend framework','Workflow problem, proposed operating model, controls and business effect','Detailed API documentation','Every future technical possibility'),1,'Match presentation depth to the stakeholder. Business leaders normally need the problem, operating change, risk and value before implementation details.',20,true,'scenario','audience-depth',false),

  (v_module,'There is no genuine deadline, but the seller says, “This price disappears tonight, so you must decide now.” What is the correct standard?',jsonb_build_array('Use urgency whenever it increases conversion','Only create urgency if the buyer seems uncertain','Never manufacture urgency or scarcity; use only genuine approved commercial/timing facts','Say it verbally so it cannot be audited'),2,'Fake urgency/scarcity is a critical trust violation. Urgency must come from real buyer/business events or approved commercial terms.',21,true,'scenario','urgency-integrity',true),

  (v_module,'After showing a relevant workflow, what is a stronger engagement question than “Does that make sense?”',jsonb_build_array('Can we move to pricing now?','How does this compare with the way your team handles it today?','Do you like our design?','Should I show every other feature?'),1,'Open, buyer-specific questions create useful dialogue and help validate whether the recommendation solves the real problem.',22,true,'scenario','dialogue',false),

  (v_module,'A buyer clearly needs only a website, but the seller records that the buyer requested automation so the opportunity appears larger. What is correct?',jsonb_build_array('Acceptable if automation might help later','Acceptable if it improves forecast value','Prohibited: CRM presentation outcomes and buyer requirements must remain truthful','Only prohibited after quotation is issued'),2,'Intentionally falsifying buyer requirements or presentation outcomes in CRM is a critical integrity failure.',23,true,'scenario','crm-truth',true),

  (v_module,'The presentation reveals that the final technical approver is absent and must validate security requirements. What is the best next step?',jsonb_build_array('Push directly to payment','Schedule the appropriate validation/stakeholder step before committing scope','Tell the current contact to approve on their behalf','Ignore the technical approver because discovery is finished'),1,'A successful presentation advances to the correct next decision. Missing required validation should be resolved before unsupported commercial commitment.',24,true,'scenario','next-step',false),

  (v_module,'The buyer asks whether ProFox guarantees first-page Google rankings. What must the seller do?',jsonb_build_array('Guarantee it for Premium buyers','Say yes if SEO work is included','Do not guarantee rankings; explain approved SEO scope/capability accurately and set realistic expectations','Promise rankings only if the buyer signs quickly'),2,'Guaranteeing search rankings or other uncontrolled outcomes is a critical misrepresentation. Explain only approved scope and realistic, non-guaranteed expectations.',25,true,'scenario','guarantee-integrity',true);

  insert into public.training_acknowledgements(module_id,statement,sort_order,required,active) values
  (v_module,'I will build presentations from verified discovery and buyer priorities, not assumptions or generic pitch material.',1,true,true),
  (v_module,'I will recommend the best-fit ProFox direction rather than the highest-priced option or the option that maximizes my commission.',2,true,true),
  (v_module,'I will not fabricate proof, ROI, case studies, testimonials, rankings, leads, revenue or other buyer results.',3,true,true),
  (v_module,'I will not make technical, integration, timeline, pricing, discount, scope or delivery commitments outside my approved authority.',4,true,true),
  (v_module,'I will protect customer and prospect confidential information and use only approved presentation assets.',5,true,true),
  (v_module,'I will verify current packages, prices and approved commercial information in the live ProFox Sales Catalog before presenting them.',6,true,true),
  (v_module,'I understand Module 12 presentation certification does not authorize me to bypass objection handling, closing, quotation, payment verification or other later ProFox processes.',7,true,true);
end $$;
