-- Module 13C/D — Durable Google event synchronization and optional Google Meet.
-- Network calls never occur inside the ProFox booking transaction. Meeting changes enqueue after-commit work.

CREATE TABLE IF NOT EXISTS public.google_calendar_event_links (
  meeting_id uuid PRIMARY KEY REFERENCES public.sales_meetings(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  calendar_id text NOT NULL DEFAULT 'primary',
  external_event_id text NOT NULL,
  conference_request_id text NOT NULL,
  meet_url text NOT NULL DEFAULT '',
  etag text NOT NULL DEFAULT '',
  conference_status text NOT NULL DEFAULT 'none' CHECK (conference_status IN ('none','pending','success','failed')),
  last_operation text NOT NULL DEFAULT 'upsert' CHECK (last_operation IN ('upsert','delete','reconcile')),
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id,calendar_id,external_event_id)
);

CREATE TABLE IF NOT EXISTS public.google_calendar_sync_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  meeting_id uuid REFERENCES public.sales_meetings(id) ON DELETE CASCADE,
  job_type text NOT NULL CHECK (job_type IN ('refresh_busy','upsert_event','delete_event','reconcile_event')),
  dedupe_key text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','retry','succeeded','reconnect_required','failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts>=0),
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  locked_at timestamptz,
  completed_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_google_sync_jobs_due ON public.google_calendar_sync_jobs(status,next_attempt_at,id) WHERE status IN ('pending','retry','processing');
CREATE INDEX IF NOT EXISTS idx_google_sync_jobs_meeting ON public.google_calendar_sync_jobs(meeting_id,created_at DESC) WHERE meeting_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.google_calendar_sync_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  meeting_id uuid REFERENCES public.sales_meetings(id) ON DELETE SET NULL,
  job_id bigint REFERENCES public.google_calendar_sync_jobs(id) ON DELETE SET NULL,
  operation text NOT NULL,
  status text NOT NULL,
  http_status integer,
  detail text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_google_sync_audit_user_created ON public.google_calendar_sync_audit(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_google_sync_audit_meeting_created ON public.google_calendar_sync_audit(meeting_id,created_at DESC) WHERE meeting_id IS NOT NULL;

ALTER TABLE public.google_calendar_event_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.google_calendar_sync_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.google_calendar_sync_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.google_calendar_event_links FROM PUBLIC,anon,authenticated;
REVOKE ALL ON TABLE public.google_calendar_sync_jobs FROM PUBLIC,anon,authenticated;
REVOKE ALL ON TABLE public.google_calendar_sync_audit FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.queue_google_calendar_sync(
  p_user_id uuid,
  p_job_type text,
  p_meeting_id uuid DEFAULT NULL,
  p_force boolean DEFAULT false
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
DECLARE v_connection public.google_calendar_connections%ROWTYPE; v_meeting public.sales_meetings%ROWTYPE; v_basis text; v_key text; v_id bigint;
BEGIN
  IF p_job_type NOT IN ('refresh_busy','upsert_event','delete_event','reconcile_event') THEN RAISE EXCEPTION 'Invalid Google sync job type.'; END IF;
  SELECT * INTO v_connection FROM public.google_calendar_connections WHERE user_id=p_user_id;
  IF NOT FOUND OR v_connection.status<>'connected' OR v_connection.sync_enabled IS NOT TRUE THEN RETURN NULL; END IF;
  IF p_job_type<>'refresh_busy' THEN
    IF p_meeting_id IS NULL THEN RAISE EXCEPTION 'Meeting is required for event synchronization.'; END IF;
    SELECT * INTO v_meeting FROM public.sales_meetings WHERE id=p_meeting_id AND salesperson_id=p_user_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Meeting does not belong to this Google connection.'; END IF;
    v_basis:=concat_ws('|',v_meeting.id::text,v_meeting.start_at::text,v_meeting.end_at::text,v_meeting.title,v_meeting.description,v_meeting.attendee_name,v_meeting.attendee_email,v_meeting.status,p_job_type);
  ELSE
    v_basis:=concat_ws('|',p_user_id::text,p_job_type,to_char(date_trunc('minute',now()),'YYYYMMDDHH24MI'));
  END IF;
  v_key:=p_user_id::text||':'||p_job_type||':'||encode(digest(v_basis,'sha256'),'hex');
  INSERT INTO public.google_calendar_sync_jobs(user_id,meeting_id,job_type,dedupe_key,status,next_attempt_at,updated_at)
  VALUES(p_user_id,p_meeting_id,p_job_type,v_key,'pending',now(),now())
  ON CONFLICT(dedupe_key) DO UPDATE SET
    status=CASE WHEN p_force THEN 'pending' ELSE public.google_calendar_sync_jobs.status END,
    next_attempt_at=CASE WHEN p_force THEN now() ELSE public.google_calendar_sync_jobs.next_attempt_at END,
    last_error=CASE WHEN p_force THEN NULL ELSE public.google_calendar_sync_jobs.last_error END,
    updated_at=now()
  RETURNING id INTO v_id;
  IF p_meeting_id IS NOT NULL AND p_job_type IN ('upsert_event','delete_event','reconcile_event') THEN
    UPDATE public.sales_meetings SET sync_status='Pending',sync_error=NULL WHERE id=p_meeting_id;
  END IF;
  RETURN v_id;
END;
$$;
REVOKE ALL ON FUNCTION public.queue_google_calendar_sync(uuid,text,uuid,boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.queue_google_calendar_sync(uuid,text,uuid,boolean) TO service_role;

CREATE OR REPLACE FUNCTION public.queue_google_sync_from_meeting()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.google_calendar_connections c WHERE c.user_id=NEW.salesperson_id AND c.status='connected' AND c.sync_enabled) THEN RETURN NEW; END IF;
  IF TG_OP='INSERT' THEN
    IF NEW.status IN ('Scheduled','Rescheduled') THEN PERFORM public.queue_google_calendar_sync(NEW.salesperson_id,'upsert_event',NEW.id,false); END IF;
    RETURN NEW;
  END IF;
  IF NEW.status='Cancelled' AND OLD.status IS DISTINCT FROM 'Cancelled' THEN
    PERFORM public.queue_google_calendar_sync(NEW.salesperson_id,'delete_event',NEW.id,false);
  ELSIF NEW.status IN ('Scheduled','Rescheduled') AND (
    NEW.start_at IS DISTINCT FROM OLD.start_at OR NEW.end_at IS DISTINCT FROM OLD.end_at OR NEW.title IS DISTINCT FROM OLD.title OR
    NEW.description IS DISTINCT FROM OLD.description OR NEW.attendee_name IS DISTINCT FROM OLD.attendee_name OR NEW.attendee_email IS DISTINCT FROM OLD.attendee_email OR
    NEW.status IS DISTINCT FROM OLD.status
  ) THEN
    PERFORM public.queue_google_calendar_sync(NEW.salesperson_id,'upsert_event',NEW.id,false);
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_queue_google_sync_from_meeting ON public.sales_meetings;
CREATE TRIGGER trg_queue_google_sync_from_meeting AFTER INSERT OR UPDATE OF start_at,end_at,title,description,attendee_name,attendee_email,status ON public.sales_meetings FOR EACH ROW EXECUTE FUNCTION public.queue_google_sync_from_meeting();
REVOKE ALL ON FUNCTION public.queue_google_sync_from_meeting() FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.service_claim_google_sync_jobs(p_limit integer DEFAULT 20)
RETURNS SETOF public.google_calendar_sync_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
BEGIN
  -- Recover abandoned worker claims after 10 minutes.
  UPDATE public.google_calendar_sync_jobs SET status='retry',next_attempt_at=now(),locked_at=NULL,updated_at=now()
  WHERE status='processing' AND locked_at<now()-interval '10 minutes';
  RETURN QUERY
  WITH picked AS (
    SELECT j.id FROM public.google_calendar_sync_jobs j
    WHERE j.status IN ('pending','retry') AND j.next_attempt_at<=now()
    ORDER BY j.next_attempt_at,j.id FOR UPDATE SKIP LOCKED LIMIT LEAST(GREATEST(COALESCE(p_limit,20),1),100)
  )
  UPDATE public.google_calendar_sync_jobs j SET status='processing',attempts=j.attempts+1,locked_at=now(),updated_at=now()
  FROM picked p WHERE j.id=p.id RETURNING j.*;
END;
$$;

CREATE OR REPLACE FUNCTION public.service_finish_google_sync_job(
  p_job_id bigint,p_status text,p_error text DEFAULT NULL,p_retry_seconds integer DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
DECLARE v_job public.google_calendar_sync_jobs%ROWTYPE;
BEGIN
  IF p_status NOT IN ('succeeded','retry','reconnect_required','failed') THEN RAISE EXCEPTION 'Invalid sync job result.'; END IF;
  SELECT * INTO v_job FROM public.google_calendar_sync_jobs WHERE id=p_job_id FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;
  UPDATE public.google_calendar_sync_jobs SET status=p_status,last_error=left(COALESCE(p_error,''),2000),locked_at=NULL,
    next_attempt_at=CASE WHEN p_status='retry' THEN now()+make_interval(secs=>LEAST(GREATEST(COALESCE(p_retry_seconds,60),5),21600)) ELSE next_attempt_at END,
    completed_at=CASE WHEN p_status IN ('succeeded','reconnect_required','failed') THEN now() ELSE NULL END,updated_at=now()
  WHERE id=p_job_id;
  IF v_job.meeting_id IS NOT NULL THEN
    UPDATE public.sales_meetings SET sync_status=CASE WHEN p_status='succeeded' THEN 'Synced' WHEN p_status='retry' THEN 'Pending' ELSE 'Error' END,
      sync_error=CASE WHEN p_status='succeeded' THEN NULL ELSE left(COALESCE(p_error,''),2000) END WHERE id=v_job.meeting_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.service_upsert_google_event_link(
  p_meeting_id uuid,p_user_id uuid,p_calendar_id text,p_event_id text,p_conference_request_id text,p_meet_url text,p_etag text,p_conference_status text,p_operation text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
BEGIN
  IF p_conference_status NOT IN ('none','pending','success','failed') THEN RAISE EXCEPTION 'Invalid conference state.'; END IF;
  INSERT INTO public.google_calendar_event_links(meeting_id,user_id,calendar_id,external_event_id,conference_request_id,meet_url,etag,conference_status,last_operation,last_synced_at,updated_at)
  VALUES(p_meeting_id,p_user_id,COALESCE(NULLIF(p_calendar_id,''),'primary'),p_event_id,p_conference_request_id,COALESCE(p_meet_url,''),COALESCE(p_etag,''),p_conference_status,p_operation,now(),now())
  ON CONFLICT(meeting_id) DO UPDATE SET calendar_id=EXCLUDED.calendar_id,external_event_id=EXCLUDED.external_event_id,conference_request_id=EXCLUDED.conference_request_id,
    meet_url=EXCLUDED.meet_url,etag=EXCLUDED.etag,conference_status=EXCLUDED.conference_status,last_operation=EXCLUDED.last_operation,last_synced_at=now(),updated_at=now();
  UPDATE public.sales_meetings SET provider='Google',external_calendar_id=COALESCE(NULLIF(p_calendar_id,''),'primary'),external_event_id=p_event_id,
    meeting_url=CASE WHEN trim(COALESCE(p_meet_url,''))<>'' THEN p_meet_url ELSE meeting_url END,sync_status='Synced',sync_error=NULL,updated_at=now()
  WHERE id=p_meeting_id AND salesperson_id=p_user_id;
  UPDATE public.crm_opportunities o SET meeting_url=m.meeting_url,updated_at=now() FROM public.sales_meetings m
  WHERE m.id=p_meeting_id AND o.id=m.opportunity_id AND trim(COALESCE(m.meeting_url,''))<>'';
END;
$$;

CREATE OR REPLACE FUNCTION public.service_log_google_sync(p_user_id uuid,p_meeting_id uuid,p_job_id bigint,p_operation text,p_status text,p_http_status integer,p_detail text)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path=public,pg_temp AS $$
 INSERT INTO public.google_calendar_sync_audit(user_id,meeting_id,job_id,operation,status,http_status,detail)
 VALUES(p_user_id,p_meeting_id,p_job_id,left(COALESCE(p_operation,''),80),left(COALESCE(p_status,''),40),p_http_status,left(COALESCE(p_detail,''),2000));
$$;

REVOKE ALL ON FUNCTION public.service_claim_google_sync_jobs(integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_finish_google_sync_job(bigint,text,text,integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_upsert_google_event_link(uuid,uuid,text,text,text,text,text,text,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.service_log_google_sync(uuid,uuid,bigint,text,text,integer,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.service_claim_google_sync_jobs(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_finish_google_sync_job(bigint,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_upsert_google_event_link(uuid,uuid,text,text,text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.service_log_google_sync(uuid,uuid,bigint,text,text,integer,text) TO service_role;

-- Existing native meetings become eligible for sync only when they are subsequently changed or explicitly reconciled.
-- This avoids surprising historical event creation immediately when a user first connects Google.
