-- Module 15 — Quotation Process scenario certification

do $$ declare v_module uuid; begin
  select id into v_module from public.training_modules where slug='quotation-process';
  if v_module is null then raise exception 'Module 15 quotation-process is missing.'; end if;
  delete from public.training_assessment_questions where module_id=v_module;
  delete from public.training_acknowledgements where module_id=v_module;

  insert into public.training_assessment_questions(module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical) values
  (v_module,'Standard active package, catalog price, standard terms, no custom work. Which route?', '["Normal catalog route; no separate manager approval","Manual Admin approval for every quote","Convert it to custom","Wait for Finance to approve the package"]'::jsonb,0,'Catalog products configured without manager approval use the standard route.',1,true,'scenario','standard_package_no_approval',false),
  (v_module,'Standard package plus an approved no-review add-on. What should happen?', '["Remove the add-on","Quote both through the normal catalog route","Create the add-on as custom","Ask Admin to approve only the add-on"]'::jsonb,1,'Approved catalog add-ons do not create a manual approval requirement.',2,true,'scenario','approved_addon_no_approval',false),
  (v_module,'Custom portal requirements are still high level and no custom commercial structure is approved. What next?', '["Hide it in the largest package","Choose an arbitrary amount","Complete custom scoping and approval","Stack unrelated add-ons"]'::jsonb,2,'Custom scope must be defined and approved before final issue.',3,true,'scenario','custom_scope_readiness',false),
  (v_module,'The selected Custom catalog product requires manager approval. What may the seller do?', '["Issue it first","Change the catalog flag","Promise it outside the quote","Submit it through the required approval route"]'::jsonb,3,'Approval-required products cannot bypass authorization.',4,true,'scenario','bypass_custom_approval',true),
  (v_module,'A standard package buyer requests an unapproved discount. What is correct?', '["Treat the discount as an approval-required exception","No approval because the product is standard","Hide it as free scope","Alter quantity to disguise the change"]'::jsonb,0,'Standard product authority does not authorize non-standard discounts.',5,true,'scenario','unauthorized_discount_exception',true),
  (v_module,'Training shows an old price but the live Sales Catalog shows another. Which controls?', '["Use the lower number","Use the live Sales Catalog","Average them","Use training permanently"]'::jsonb,1,'The live Admin-configured catalog is commercial source of truth.',6,true,'scenario','live_catalog_truth',false),
  (v_module,'A proprietary integration has not been technically verified. How should the quote handle it?', '["List it as certain","Promise it conditionally","Validate it before committing it as deliverable scope","Use a generic add-on regardless of fit"]'::jsonb,2,'Technical unknowns must not become committed scope without validation.',7,true,'scenario','unverified_technical_commitment',true),
  (v_module,'The entry package genuinely fits, but a larger package pays more commission. What should be quoted?', '["Largest package","Middle package","Largest plus free scope","Best-fit approved scope"]'::jsonb,3,'Buyer fit controls the recommendation, not commission size.',8,true,'scenario','best_fit_package',false),
  (v_module,'A quotation uses a vague deliverable that nobody has defined. What should happen?', '["Replace it with verified concrete scope or return to scoping","Leave it vague","Make it unlimited","Clarify only after acceptance"]'::jsonb,0,'Quotation scope must represent a deliverable ProFox can actually honor.',9,true,'scenario','scope_misrepresentation',true),
  (v_module,'All selected products are active catalog items configured without manager approval. Seller submits the draft. Expected result?', '["Always wait for a manager","Server routes it to Approved automatically","Seller fills approved_by personally","Send the Draft directly"]'::jsonb,1,'The server removes unnecessary human review for fully standard catalog quotes.',10,true,'scenario','catalog_auto_approval',false),
  (v_module,'Buyer requests a non-standard payment schedule on otherwise standard products. What is correct?', '["Agree verbally","No approval because products are standard","Treat it as a commercial exception requiring authorization","Put it only in internal notes"]'::jsonb,2,'Non-standard terms remain approval-controlled.',11,true,'scenario','unauthorized_payment_terms',true),
  (v_module,'An approved add-on name is close to the request, but the actual work is materially beyond its approved scope. What next?', '["Use it anyway","Increase quantity","Hide the extra requirement in notes","Treat the excess as custom/non-standard scope"]'::jsonb,3,'Catalog authority applies only within approved product scope.',12,true,'scenario','addon_scope_boundary',false),
  (v_module,'Seller wants the quotation to guarantee an uncontrolled business outcome. What is correct?', '["Quote deliverables without guaranteeing the outcome","Guarantee only on Premium","Call it a forecast guarantee","Hide it in notes"]'::jsonb,0,'Uncontrolled business results are not quotation guarantees.',13,true,'scenario','guaranteed_outcome',true),
  (v_module,'Buyer requests a launch date that Delivery has not approved. What should the seller do?', '["Promise it","Record the request accurately and avoid an unapproved commitment","Remove all dates","Promise an earlier date"]'::jsonb,1,'Requested and committed dates are different states.',14,true,'scenario','timeline_language',false),
  (v_module,'A custom quote is still waiting for required approval. Can the seller issue an outside version as final?', '["Yes","Yes if marked unofficial","No; complete the authorized approval route first","Yes through another channel"]'::jsonb,2,'Required approval cannot be bypassed through a parallel document.',15,true,'scenario','unofficial_custom_quote',true),
  (v_module,'The scope and commercial notes conflict before issue. What should happen?', '["Send and clarify later","Delete one section","Use the higher-value version","Correct the inconsistency before issue"]'::jsonb,3,'Pre-issue QA must resolve conflicting commercial information.',16,true,'scenario','pre_issue_consistency',false),
  (v_module,'A material feature is requested after a quotation was issued. What is correct?', '["Use the approved revision/version workflow","Edit the issued record silently","Promise it verbally","Overwrite history"]'::jsonb,0,'Material changes require traceable revision.',17,true,'scenario','silent_issued_change',true),
  (v_module,'Two quotation versions exist with different totals. What should the seller do?', '["Let the buyer choose","Identify the current valid version and preserve prior history","Delete the old record","Combine them informally"]'::jsonb,1,'One current commercial truth must be clear while history stays traceable.',18,true,'scenario','version_clarity',false),
  (v_module,'Buyer gives positive feedback, but no formal acceptance event occurred. What may be recorded?', '["Formal acceptance","Acceptance with seller timestamp","Positive feedback only until the approved acceptance event occurs","Final downstream status"]'::jsonb,2,'Formal acceptance must come from the approved mechanism.',19,true,'scenario','fabricated_acceptance',true),
  (v_module,'Buyer questions an exclusion during quotation review. What should happen?', '["Dismiss it","Remove it without checking impact","Avoid the topic","Clarify and revise properly if a legitimate change is agreed"]'::jsonb,3,'Material misunderstandings must be resolved before acceptance.',20,true,'scenario','review_scope_question',false),
  (v_module,'The quotation is formally accepted. What happens next?', '["Hand it to Module 16 and follow the approved payment-verification workflow before stronger downstream states","Skip directly to final sales state","Create downstream records manually","Treat acceptance as full financial verification"]'::jsonb,0,'Formal quotation acceptance hands off to the protected payment workflow.',21,true,'scenario','premature_downstream_state',true),
  (v_module,'A standard quote was auto-approved because every product is configured no-review. What does that mean?', '["Seller became an Admin approver","System confirmed the quote used pre-approved catalog authority","Future edits are automatically approved","Customer accepted it"]'::jsonb,1,'Catalog auto-approval is a routing result, not expanded seller authority.',22,true,'scenario','auto_approval_meaning',false),
  (v_module,'Seller knows a custom exception exists but records the quote as standard to improve pipeline appearance. What is correct?', '["Allowed when likely to close","Allowed below a value threshold","Not allowed; commercial state and approval route must remain truthful","Only matters after delivery"]'::jsonb,2,'Commercial records must reflect the real approval and buyer state.',23,true,'scenario','false_commercial_record',true),
  (v_module,'Standard package plus multiple approved no-review add-ons, with no exception. Which statement is correct?', '["Every add-on needs review","Only package can auto-route","Seller must approve each line","The combined quote can stay on the standard route"]'::jsonb,3,'Several approved catalog items do not create a review requirement by themselves.',24,true,'scenario','combined_standard_route',false),
  (v_module,'Seller deliberately uses a simple approved add-on label for materially custom work to avoid review. Correct judgment?', '["Prohibited; route the true custom scope for approval","Allowed because item is in catalog","Allowed if total is sufficient","Allowed if buyer agrees"]'::jsonb,0,'Deliberately disguising custom work under standard catalog authority is a critical integrity failure.',25,true,'scenario','disguise_custom_as_addon',true);

  insert into public.training_acknowledgements(module_id,statement,sort_order,required,active) values
  (v_module,'I will build quotations from verified buyer requirements and the current live ProFox Sales Catalog.',1,true,true),
  (v_module,'I understand that active standard packages and approved add-ons configured without manager approval use the normal route without separate human approval.',2,true,true),
  (v_module,'I will route custom packages, non-catalog/custom scope, approval-required products and non-standard commercial exceptions for authorization.',3,true,true),
  (v_module,'I will not offer unauthorized pricing, discounts, payment terms, delivery commitments, scope or technical capabilities.',4,true,true),
  (v_module,'I will preserve quotation history and use the approved revision/version workflow.',5,true,true),
  (v_module,'I will use the approved acceptance mechanism and then follow Module 16 before any stronger downstream financial or delivery state.',6,true,true),
  (v_module,'I will keep quotation, approval-route, buyer-decision and commercial information truthful so all teams work from one approved commercial truth.',7,true,true);
end $$;
