-- Historical alignment marker.
-- This migration was applied directly to Supabase production as
-- 20260828145635_content_creator_certification_final_access.
-- The complete idempotent final state is reconciled by
-- 20260828153000_content_creator_recruitment_final_reconciliation.sql.
