-- Final, idempotent Content Creator recruitment reconciliation.
-- Replays the production state after the historical 20260828145436..150508
-- migrations while preserving shared Sales/UIUX/Developer recruitment behavior.

DO $$
DECLARE v_job_id uuid;
BEGIN
  SELECT id INTO v_job_id
  FROM public.career_jobs
  WHERE slug='content-writer' AND application_type='content_writer'
  LIMIT 1;
  IF v_job_id IS NULL THEN
    RAISE EXCEPTION 'Content Creator career job was not found.';
  END IF;

  UPDATE public.career_jobs
  SET title='Content Creator',
      engagement_type='Independent Contractor / Project-Based',
      requires_intro_video=true,
      role_details=coalesce(role_details,'{}'::jsonb)
        || jsonb_build_object(
          'systemRole','content_writer',
          'department','Content',
          'trainingTrack','content_writer',
          'engagementModel','project_based_contractor',
          'portfolioTiming','post_screening',
          'portfolioMinimumCaseStudies',3,
          'practicalPassingScore',90,
          'agreementRequiredBeforeAcademy',true,
          'finalApprovalRequired',true,
          'systemAccessRequiredBeforeActivation',true,
          'applicationForm',coalesce(role_details->'applicationForm','{}'::jsonb)
            || jsonb_build_object('cvRequired',true,'portfolioRequired',false,'portfolioDeferred',true,'minimumWeeklyHours',coalesce((role_details->'applicationForm'->>'minimumWeeklyHours')::int,20))
        ),
      selection_process=jsonb_build_array(
        jsonb_build_object('title','Application','text','Submit your application with a current resume/CV and a short introduction video.'),
        jsonb_build_object('title','Video + Resume Review','text','We review communication, relevant experience, reliability and role fit.'),
        jsonb_build_object('title','Portfolio Review','text','Shortlisted candidates receive a secure link to submit at least three structured case studies.'),
        jsonb_build_object('title','Content Assessment','text','Complete the role-specific content assessment against the ProFox quality rubric.'),
        jsonb_build_object('title','Conditional Selected','text','Candidates who pass the assessment are conditionally selected, subject to agreement and certification.'),
        jsonb_build_object('title','Project-Based Agreement','text','Review and sign the approved project-based Content Creator agreement.'),
        jsonb_build_object('title','Content Academy','text','Complete the ProFox content operating model, PF-SOP-07 and niche/playbook learning.'),
        jsonb_build_object('title','Practical Certification','text','Submit a production-style practical. Independent review requires a minimum 90% score.'),
        jsonb_build_object('title','Final Approval','text','Management verifies all gates before production access can be approved.'),
        jsonb_build_object('title','System Access','text','Approved production access is provisioned before activation.'),
        jsonb_build_object('title','Activated','text','You become eligible for approved ProFox content projects and remain subject to independent quality review.')
      ),
      updated_at=now()
  WHERE id=v_job_id;

  UPDATE public.recruitment_stage_policies SET active=false,updated_at=now() WHERE job_id=v_job_id;

  UPDATE public.recruitment_stage_policies SET sort_order=1,active=true,assessment_required=false,passing_score=null,sla_hours=24,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='New Application';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'New Application',1,true,false,null,24,false,'[]'::jsonb); END IF;

  UPDATE public.recruitment_stage_policies SET sort_order=2,active=true,assessment_required=true,passing_score=75,sla_hours=48,interview_required=false,rubric='[{"key":"communication","label":"Introduction video communication","maxPoints":25},{"key":"relevant_experience","label":"Relevant content experience","maxPoints":30},{"key":"resume_evidence","label":"Resume evidence and progression","maxPoints":20},{"key":"reliability_fit","label":"Reliability and role fit","maxPoints":25}]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Video & Resume Review';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Video & Resume Review',2,true,true,75,48,false,'[{"key":"communication","label":"Introduction video communication","maxPoints":25},{"key":"relevant_experience","label":"Relevant content experience","maxPoints":30},{"key":"resume_evidence","label":"Resume evidence and progression","maxPoints":20},{"key":"reliability_fit","label":"Reliability and role fit","maxPoints":25}]'::jsonb); END IF;

  UPDATE public.recruitment_stage_policies SET sort_order=3,active=true,assessment_required=true,passing_score=80,sla_hours=72,interview_required=false,rubric='[{"key":"clarity_structure","label":"Clarity and information structure","maxPoints":20},{"key":"commercial_quality","label":"Commercial / conversion quality","maxPoints":20},{"key":"research_evidence","label":"Research and evidence discipline","maxPoints":20},{"key":"originality_voice","label":"Originality and voice control","maxPoints":15},{"key":"outcomes","label":"Outcome / result awareness","maxPoints":15},{"key":"presentation","label":"Professional presentation","maxPoints":10}]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Portfolio Review';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Portfolio Review',3,true,true,80,72,false,'[{"key":"clarity_structure","label":"Clarity and information structure","maxPoints":20},{"key":"commercial_quality","label":"Commercial / conversion quality","maxPoints":20},{"key":"research_evidence","label":"Research and evidence discipline","maxPoints":20},{"key":"originality_voice","label":"Originality and voice control","maxPoints":15},{"key":"outcomes","label":"Outcome / result awareness","maxPoints":15},{"key":"presentation","label":"Professional presentation","maxPoints":10}]'::jsonb); END IF;

  UPDATE public.recruitment_stage_policies SET sort_order=4,active=true,assessment_required=true,passing_score=85,sla_hours=72,interview_required=false,rubric='[{"key":"user_need","label":"User-need alignment","maxPoints":20},{"key":"message_hierarchy","label":"Message hierarchy","maxPoints":20},{"key":"conversion","label":"Conversion thinking","maxPoints":20},{"key":"clarity","label":"Clarity and scannability","maxPoints":20},{"key":"brand_originality","label":"Brand fit, originality and truthfulness","maxPoints":20}]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Content Assessment';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Content Assessment',4,true,true,85,72,false,'[{"key":"user_need","label":"User-need alignment","maxPoints":20},{"key":"message_hierarchy","label":"Message hierarchy","maxPoints":20},{"key":"conversion","label":"Conversion thinking","maxPoints":20},{"key":"clarity","label":"Clarity and scannability","maxPoints":20},{"key":"brand_originality","label":"Brand fit, originality and truthfulness","maxPoints":20}]'::jsonb); END IF;

  UPDATE public.recruitment_stage_policies SET sort_order=5,active=true,assessment_required=false,passing_score=null,sla_hours=24,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Selected';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Selected',5,true,false,null,24,false,'[]'::jsonb); END IF;
  UPDATE public.recruitment_stage_policies SET sort_order=6,active=true,assessment_required=false,passing_score=null,sla_hours=72,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Agreement Pending';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Agreement Pending',6,true,false,null,72,false,'[]'::jsonb); END IF;
  UPDATE public.recruitment_stage_policies SET sort_order=7,active=true,assessment_required=false,passing_score=null,sla_hours=168,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Content Academy';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Content Academy',7,true,false,null,168,false,'[]'::jsonb); END IF;
  UPDATE public.recruitment_stage_policies SET sort_order=8,active=true,assessment_required=false,passing_score=90,sla_hours=72,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Practical Certification';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Practical Certification',8,true,false,90,72,false,'[]'::jsonb); END IF;
  UPDATE public.recruitment_stage_policies SET sort_order=9,active=true,assessment_required=false,passing_score=90,sla_hours=24,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Final Approval';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Final Approval',9,true,false,90,24,false,'[]'::jsonb); END IF;
  UPDATE public.recruitment_stage_policies SET sort_order=10,active=true,assessment_required=false,passing_score=null,sla_hours=24,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Ready for System Access';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Ready for System Access',10,true,false,null,24,false,'[]'::jsonb); END IF;
  UPDATE public.recruitment_stage_policies SET sort_order=11,active=true,assessment_required=false,passing_score=null,sla_hours=24,interview_required=false,rubric='[]'::jsonb,updated_at=now() WHERE job_id=v_job_id AND stage='Activated';
  IF NOT FOUND THEN INSERT INTO public.recruitment_stage_policies(job_id,stage,sort_order,active,assessment_required,passing_score,sla_hours,interview_required,rubric) VALUES(v_job_id,'Activated',11,true,false,null,24,false,'[]'::jsonb); END IF;
END $$;

UPDATE public.recruitment_task_templates
SET active=false,updated_at=now()
WHERE system_role='content_writer' AND stage='Portfolio Review' AND task_key<>'content_writer_portfolio_v2';
UPDATE public.recruitment_task_templates
SET title='Content Creator Portfolio - 3 Case Studies',
    description='Submit three structured examples that show what you wrote, why you made the decisions you made, and the business/user outcome. Do not submit confidential client material.',
    target_market='International',target_niche='Multi-industry',required_items=3,deadline_hours=72,estimated_minutes=60,max_attempts=2,
    instructions='["Submit three or more structured case studies. For each case include project/title, industry/niche, content type/channel, brief/problem, your exact contribution, research/process, sample URL or permitted evidence, and result/outcome.","Identify your contribution honestly. If work was collaborative, state exactly which portions you personally produced or owned.","Protect confidential information. Use public links or authorized samples. Never submit private client credentials, personal data or confidential material.","Choose work that represents your current standard. We review clarity, commercial thinking, evidence discipline, originality, outcomes and presentation."]'::jsonb,
    active=true,updated_at=now()
WHERE task_key='content_writer_portfolio_v2' AND system_role='content_writer' AND stage='Portfolio Review';
INSERT INTO public.recruitment_task_templates(task_key,system_role,stage,title,description,target_market,target_niche,required_items,deadline_hours,estimated_minutes,max_attempts,instructions,version,active)
SELECT 'content_writer_portfolio_v2','content_writer','Portfolio Review','Content Creator Portfolio - 3 Case Studies','Submit three structured examples that show what you wrote, why you made the decisions you made, and the business/user outcome. Do not submit confidential client material.','International','Multi-industry',3,72,60,2,'["Submit three or more structured case studies. For each case include project/title, industry/niche, content type/channel, brief/problem, your exact contribution, research/process, sample URL or permitted evidence, and result/outcome.","Identify your contribution honestly. If work was collaborative, state exactly which portions you personally produced or owned.","Protect confidential information. Use public links or authorized samples. Never submit private client credentials, personal data or confidential material.","Choose work that represents your current standard. We review clarity, commercial thinking, evidence discipline, originality, outcomes and presentation."]'::jsonb,2,true
WHERE NOT EXISTS(SELECT 1 FROM public.recruitment_task_templates WHERE task_key='content_writer_portfolio_v2' AND system_role='content_writer' AND stage='Portfolio Review');

UPDATE public.sales_agreement_templates
SET status='Published',title='ProFox Project-Based Content Creator Agreement',subtitle='Independent contractor engagement for approved content projects',
    introduction='This agreement governs project-based content services. It does not create a salaried employment relationship, partnership or authority to bind ProFox.',
    sections='[{"title":"Independent project-based relationship","body":"The Content Creator provides services as an independent contractor on projects separately assigned and accepted. No minimum volume of projects, monthly salary or guaranteed earnings are promised by this agreement."},{"title":"Project scope and commercial terms","body":"Each approved project or work order controls its scope, deliverables, timeline, fee, revision allowance and acceptance requirements. Work outside the approved scope requires written authorization."},{"title":"ProFox quality system","body":"The contractor must follow the current Content Academy standards, PF-SOP-07, client truth/evidence rules, applicable niche playbooks, review requirements and secure UI/UX handoff process."},{"title":"Confidentiality, data and security","body":"Client and ProFox information must be used only for authorized work, protected from unauthorized access, and returned or deleted when required."},{"title":"Originality and intellectual property","body":"Deliverables must be original, lawful and properly licensed. Rights transfer is governed by the applicable project and client terms; pre-existing tools remain subject to disclosed licenses."},{"title":"Accuracy and prohibited conduct","body":"The contractor must not fabricate facts, testimonials, research, results or client claims; plagiarize; use unapproved confidential material; or make representations on behalf of ProFox beyond written authority."},{"title":"Review, revisions and production access","body":"Independent quality review is mandatory. Production/client access is granted only after Academy completion, Practical Certification at 90% or higher, Final Approval and System Access authorization."},{"title":"Termination and surviving duties","body":"Either party may end the engagement subject to active project obligations and applicable law. Confidentiality, data-return/deletion, intellectual-property and accrued payment obligations survive where applicable."}]'::jsonb,
    acknowledgements='[{"key":"independent_contractor","label":"I understand this is a project-based independent contractor arrangement and not a guaranteed salaried position."},{"key":"quality_sop","label":"I agree to follow ProFox content SOPs, evidence standards, review and handoff requirements."},{"key":"confidentiality","label":"I agree to protect ProFox and client confidential information and data."},{"key":"truth_originality","label":"I will not fabricate claims, plagiarize, or misrepresent authorship, research or results."}]'::jsonb,
    agreement_type='content_writer',target_role='content_writer',published_at=coalesce(published_at,now()),updated_at=now()
WHERE template_key='content_creator_project_contractor' AND version=1;
INSERT INTO public.sales_agreement_templates(template_key,version,version_label,status,title,subtitle,introduction,sections,acknowledgements,agreement_type,target_role,published_at)
SELECT 'content_creator_project_contractor',1,'v1.0','Published','ProFox Project-Based Content Creator Agreement','Independent contractor engagement for approved content projects','This agreement governs project-based content services. It does not create a salaried employment relationship, partnership or authority to bind ProFox.','[{"title":"Independent project-based relationship","body":"The Content Creator provides services as an independent contractor on projects separately assigned and accepted. No minimum volume of projects, monthly salary or guaranteed earnings are promised by this agreement."},{"title":"Project scope and commercial terms","body":"Each approved project or work order controls its scope, deliverables, timeline, fee, revision allowance and acceptance requirements. Work outside the approved scope requires written authorization."},{"title":"ProFox quality system","body":"The contractor must follow the current Content Academy standards, PF-SOP-07, client truth/evidence rules, applicable niche playbooks, review requirements and secure UI/UX handoff process."},{"title":"Confidentiality, data and security","body":"Client and ProFox information must be used only for authorized work, protected from unauthorized access, and returned or deleted when required."},{"title":"Originality and intellectual property","body":"Deliverables must be original, lawful and properly licensed."},{"title":"Accuracy and prohibited conduct","body":"The contractor must not fabricate facts, testimonials, research, results or client claims; plagiarize; use unapproved confidential material; or make representations on behalf of ProFox beyond written authority."},{"title":"Review, revisions and production access","body":"Independent quality review is mandatory. Production/client access is granted only after Academy completion, Practical Certification at 90% or higher, Final Approval and System Access authorization."},{"title":"Termination and surviving duties","body":"Either party may end the engagement subject to active project obligations and applicable law."}]'::jsonb,'[{"key":"independent_contractor","label":"I understand this is a project-based independent contractor arrangement and not a guaranteed salaried position."},{"key":"quality_sop","label":"I agree to follow ProFox content SOPs, evidence standards, review and handoff requirements."},{"key":"confidentiality","label":"I agree to protect ProFox and client confidential information and data."},{"key":"truth_originality","label":"I will not fabricate claims, plagiarize, or misrepresent authorship, research or results."}]'::jsonb,'content_writer','content_writer',now()
WHERE NOT EXISTS(SELECT 1 FROM public.sales_agreement_templates WHERE template_key='content_creator_project_contractor' AND version=1);

INSERT INTO public.notification_templates(template_key,name,subject_template,body_template,html_template,active,description)
VALUES
('content_recruitment_portfolio','Content Creator portfolio task','Portfolio Review - submit your 3 ProFox case studies','Hi {{candidateName}},\n\nYou passed the Video and Resume Review and have moved to Portfolio Review.\n\nPlease use the secure link below to submit at least three structured portfolio case studies:\n{{taskUrl}}\n\nFor each case, explain the project, niche, content type, brief/problem, your exact contribution, research/process, authorized sample evidence, and the result or intended outcome. Do not submit confidential client material.\n\nDeadline: {{taskDueDate}}\nExpected time: {{taskEstimatedTime}}\n\nRegards,\nProFox Recruitment Team',null,true,'Secure Content Creator portfolio review invitation.'),
('content_recruitment_portfolio_retry','Content Creator portfolio retry','Action required: update your ProFox Portfolio Review','Hi {{candidateName}},\n\nYour Portfolio Review needs another submission. Please use the secure link below and address the reviewer feedback shown in the task workspace:\n{{taskUrl}}\n\nFeedback: {{taskFeedback}}\nDeadline: {{taskDueDate}}\n\nRegards,\nProFox Recruitment Team',null,true,'Secure Content Creator portfolio retry invitation.'),
('content_recruitment_portfolio_submitted','Content Creator portfolio submitted','Your ProFox Portfolio Review has been submitted','Hi {{candidateName}},\n\nWe have received your structured Content Creator portfolio submission. It is now read-only and queued for review.\n\nRegards,\nProFox Recruitment Team',null,true,'Candidate confirmation after Content Creator portfolio submission.'),
('content_recruitment_agreement_ready','Content Creator agreement ready','Your ProFox project-based agreement is ready','Hi {{candidateName}},\n\nYou have successfully completed the Content Assessment and have been conditionally selected for the next phase.\n\nPlease review and sign your project-based Content Creator Agreement using the secure link below:\n{{agreementUrl}}\n\nAcademy access is unlocked only after the agreement is verified. This is a project-based independent contractor opportunity; it does not guarantee a fixed monthly salary or project volume.\n\nRegards,\nProFox Recruitment Team',null,true,'Secure Content Creator project-based agreement invitation.'),
('content_recruitment_practical_submitted','Content practical submitted','Your ProFox Practical Certification is under review','Hi {{candidateName}},\n\nWe have received your Content Creator Practical Certification submission. It is now locked for independent review against PF-SOP-07 and the current quality standard.\n\nA passing score of 90% or higher is required.\n\nRegards,\nProFox Recruitment Team',null,true,'Candidate confirmation after Content practical submission.'),
('content_recruitment_practical_passed','Content practical passed','You passed ProFox Practical Certification','Hi {{candidateName}},\n\nCongratulations. Your Content Creator Practical Certification has passed independent review at the required standard.\n\nYour application is now in Final Approval. Production access is still locked until Management completes Final Approval and System Access authorization.\n\nRegards,\nProFox Recruitment Team',null,true,'Candidate notice after practical certification passes.'),
('content_recruitment_practical_retry','Content practical retry','Action required: revise your ProFox Practical Certification','Hi {{candidateName}},\n\nYour Practical Certification needs revision before it can pass. Please review the feedback in your Academy workspace, update the required areas, and resubmit through the controlled certification workflow.\n\nRegards,\nProFox Recruitment Team',null,true,'Candidate practical retry notification.'),
('content_recruitment_final_approved','Content final approval','Final Approval complete - system access is next','Hi {{candidateName}},\n\nYour Content Creator Final Approval is complete. Your candidate record is now at Ready for System Access.\n\nThe ProFox team will confirm your production access before activation.\n\nRegards,\nProFox Recruitment Team',null,true,'Candidate Final Approval and System Access notification.')
ON CONFLICT(template_key) DO UPDATE SET name=excluded.name,subject_template=excluded.subject_template,body_template=excluded.body_template,html_template=excluded.html_template,active=true,description=excluded.description,updated_at=now();

UPDATE public.notification_templates SET subject_template='Application received - ProFox Content Creator',body_template='Hi {{candidateName}},\n\nThank you for applying to the ProFox Content team. We have securely received your application, resume/CV and introduction video.\n\nOur first review covers your resume, communication, relevant experience and role fit. Please do not send portfolio material yet. If you pass the first review, we will send a secure Portfolio Review link with the required three-case-study format.\n\nApplication reference: {{applicationReference}}\n\nRegards,\nProFox Recruitment Team',updated_at=now() WHERE template_key='content_recruitment_application_received';
UPDATE public.notification_templates SET subject_template='Conditional selection - ProFox Content Creator',body_template='Hi {{candidateName}},\n\nYou have passed the required pre-onboarding Content Creator assessments and have been conditionally selected.\n\nThis is not activation and does not grant client or production access. The remaining gates are: project-based agreement, Content Academy, Practical Certification (90%+ independent review), Final Approval, and System Access.\n\nRegards,\nProFox Recruitment Team',updated_at=now() WHERE template_key='content_recruitment_selected';
UPDATE public.notification_templates SET subject_template='Welcome - your ProFox Content Creator access is active',body_template='Hi {{candidateName}},\n\nYour Content Creator onboarding is complete and your ProFox production access has been activated. You are now eligible for approved content projects assigned through the ProFox system.\n\nContinue to follow PF-SOP-07, applicable niche/playbook requirements, confidentiality rules, and independent quality review for every project.\n\nRegards,\nProFox Recruitment Team',updated_at=now() WHERE template_key='content_recruitment_activated';

CREATE OR REPLACE FUNCTION public.content_portfolio_submission_ready(p_applicant_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
  SELECT EXISTS(
    SELECT 1
    FROM public.recruitment_task_instances ti
    JOIN public.recruitment_task_submissions ts ON ts.task_instance_id=ti.id
    WHERE ti.applicant_id=p_applicant_id
      AND ti.stage='Portfolio Review'
      AND ti.status IN('Submitted','Under Review','Passed')
      AND jsonb_typeof(ts.final_data->'portfolioCases')='array'
      AND jsonb_array_length(ts.final_data->'portfolioCases')>=3
  );
$$;

CREATE OR REPLACE FUNCTION public.assert_recruitment_task_answers(p_answers jsonb,p_required_items integer,p_final boolean DEFAULT false)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_cases jsonb;v_case jsonb;v_count integer;v_text text;v_leads jsonb;v_lead jsonb;v_urls jsonb;v_url jsonb;
BEGIN
 IF p_answers IS NULL OR jsonb_typeof(p_answers)<>'object' THEN RAISE EXCEPTION 'Task answers must be a JSON object.';END IF;
 IF octet_length(p_answers::text)>120000 THEN RAISE EXCEPTION 'Task draft is too large.';END IF;
 IF p_answers ? 'portfolioCases' THEN
   v_cases:=coalesce(p_answers->'portfolioCases','[]'::jsonb);IF jsonb_typeof(v_cases)<>'array' THEN RAISE EXCEPTION 'Portfolio cases must be an array.';END IF;v_count:=jsonb_array_length(v_cases);
   IF v_count>20 THEN RAISE EXCEPTION 'Too many portfolio cases were submitted.';END IF;
   IF p_final AND v_count<p_required_items THEN RAISE EXCEPTION 'Complete at least % portfolio case studies before final submission.',p_required_items;END IF;
   FOR v_case IN SELECT value FROM jsonb_array_elements(v_cases) LOOP
     IF jsonb_typeof(v_case)<>'object' THEN RAISE EXCEPTION 'Each portfolio case must be an object.';END IF;
     IF char_length(coalesce(v_case->>'projectTitle',''))>180 THEN RAISE EXCEPTION 'Portfolio project title is too long.';END IF;
     IF char_length(coalesce(v_case->>'industry',''))>160 THEN RAISE EXCEPTION 'Portfolio industry is too long.';END IF;
     IF char_length(coalesce(v_case->>'contentType',''))>180 THEN RAISE EXCEPTION 'Portfolio content type is too long.';END IF;
     IF char_length(coalesce(v_case->>'briefProblem',''))>3000 THEN RAISE EXCEPTION 'Portfolio brief is too long.';END IF;
     IF char_length(coalesce(v_case->>'contribution',''))>3000 THEN RAISE EXCEPTION 'Portfolio contribution is too long.';END IF;
     IF char_length(coalesce(v_case->>'researchProcess',''))>4000 THEN RAISE EXCEPTION 'Portfolio research process is too long.';END IF;
     IF char_length(coalesce(v_case->>'resultOutcome',''))>3000 THEN RAISE EXCEPTION 'Portfolio outcome is too long.';END IF;
     IF char_length(coalesce(v_case->>'sampleUrl',''))>700 THEN RAISE EXCEPTION 'Portfolio sample URL is too long.';END IF;
     v_text:=btrim(coalesce(v_case->>'sampleUrl',''));IF v_text<>'' AND v_text!~*'^https?://[^[:space:]]+$' THEN RAISE EXCEPTION 'Portfolio sample URL must be a valid http(s) URL.';END IF;
     IF p_final THEN
       IF btrim(coalesce(v_case->>'projectTitle',''))='' THEN RAISE EXCEPTION 'Project title is required for every portfolio case.';END IF;
       IF btrim(coalesce(v_case->>'industry',''))='' THEN RAISE EXCEPTION 'Industry or niche is required for every portfolio case.';END IF;
       IF btrim(coalesce(v_case->>'contentType',''))='' THEN RAISE EXCEPTION 'Content type or channel is required for every portfolio case.';END IF;
       IF char_length(btrim(coalesce(v_case->>'briefProblem','')))<40 THEN RAISE EXCEPTION 'Explain the brief or problem clearly for every portfolio case.';END IF;
       IF char_length(btrim(coalesce(v_case->>'contribution','')))<40 THEN RAISE EXCEPTION 'Explain your exact contribution clearly for every portfolio case.';END IF;
       IF char_length(btrim(coalesce(v_case->>'researchProcess','')))<40 THEN RAISE EXCEPTION 'Explain your research or content process for every portfolio case.';END IF;
       IF char_length(btrim(coalesce(v_case->>'resultOutcome','')))<20 THEN RAISE EXCEPTION 'Explain the result, outcome, or intended impact for every portfolio case.';END IF;
       IF v_text='' THEN RAISE EXCEPTION 'A public or authorized sample URL is required for every portfolio case.';END IF;
     END IF;
   END LOOP;RETURN;
 END IF;
 v_leads:=coalesce(p_answers->'leads','[]'::jsonb);IF jsonb_typeof(v_leads)<>'array' THEN RAISE EXCEPTION 'Leads must be an array.';END IF;v_count:=jsonb_array_length(v_leads);
 IF v_count>p_required_items THEN RAISE EXCEPTION 'This task accepts exactly % leads.',p_required_items;END IF;
 IF p_final AND v_count<>p_required_items THEN RAISE EXCEPTION 'Complete all % leads before final submission.',p_required_items;END IF;
 FOR v_lead IN SELECT value FROM jsonb_array_elements(v_leads) LOOP
   IF jsonb_typeof(v_lead)<>'object' THEN RAISE EXCEPTION 'Each lead must be an object.';END IF;
   v_text:=btrim(coalesce(v_lead->>'website',''));IF v_text<>'' AND v_text!~*'^https?://[^[:space:]]+$' THEN RAISE EXCEPTION 'Business website must be a valid http(s) URL.';END IF;
   v_text:=btrim(coalesce(v_lead->>'decisionMakerSourceUrl',''));IF v_text<>'' AND v_text!~*'^https?://[^[:space:]]+$' THEN RAISE EXCEPTION 'Decision-maker source must be a valid http(s) URL.';END IF;
   v_urls:=coalesce(v_lead->'evidenceUrls','[]'::jsonb);IF jsonb_typeof(v_urls)<>'array' OR jsonb_array_length(v_urls)>8 THEN RAISE EXCEPTION 'Evidence URLs must be an array with at most 8 links.';END IF;
   FOR v_url IN SELECT value FROM jsonb_array_elements(v_urls) LOOP IF jsonb_typeof(v_url)<>'string' OR trim(v_url#>>'{}')!~*'^https?://[^[:space:]]+$' THEN RAISE EXCEPTION 'Every evidence source must be a valid http(s) URL.';END IF;END LOOP;
   IF p_final THEN
     IF btrim(coalesce(v_lead->>'businessName',''))='' THEN RAISE EXCEPTION 'Business name is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'website',''))='' THEN RAISE EXCEPTION 'Business website is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'location',''))='' THEN RAISE EXCEPTION 'Business location is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'niche',''))='' THEN RAISE EXCEPTION 'Business niche is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'fitReason',''))='' THEN RAISE EXCEPTION 'Qualification reasoning is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'qualificationSignals',''))='' THEN RAISE EXCEPTION 'Qualification evidence is required for every lead.';END IF;
     IF jsonb_array_length(v_urls)=0 THEN RAISE EXCEPTION 'At least one evidence URL is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'decisionMakerName',''))='' OR btrim(coalesce(v_lead->>'decisionMakerRole',''))='' THEN RAISE EXCEPTION 'Decision-maker name and role are required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'decisionMakerSourceUrl',''))='' THEN RAISE EXCEPTION 'Decision-maker source URL is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'digitalProblem',''))='' THEN RAISE EXCEPTION 'Digital problem or opportunity is required for every lead.';END IF;
     IF btrim(coalesce(v_lead->>'serviceFit',''))='' OR btrim(coalesce(v_lead->>'serviceFitReason',''))='' THEN RAISE EXCEPTION 'ProFox service fit and reasoning are required for every lead.';END IF;
     IF lower(btrim(coalesce(v_lead->>'priority',''))) NOT IN('high','medium','low') THEN RAISE EXCEPTION 'Priority must be High, Medium, or Low.';END IF;
   END IF;
 END LOOP;
END;$$;

CREATE OR REPLACE FUNCTION public.submit_public_content_writer_application(p_application jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_job public.career_jobs%rowtype;v_email text;v_name text;v_id uuid;v_reference text;v_existing uuid;v_answers jsonb:=coalesce(p_application,'{}');v_hours integer;v_start date;v_cv text;v_video text;
BEGIN
 SELECT * INTO v_job FROM public.career_jobs WHERE slug='content-writer' AND application_type='content_writer' AND status='Published' AND (closes_at IS NULL OR closes_at>now()) LIMIT 1;IF NOT FOUND THEN RETURN jsonb_build_object('success',false,'error','The Content Creator role is not currently accepting applications.');END IF;
 v_name:=btrim(coalesce(v_answers->>'fullName',''));v_email:=lower(btrim(coalesce(v_answers->>'email','')));IF length(v_name)<2 THEN RETURN jsonb_build_object('success',false,'field','fullName','error','Please provide your full name.');END IF;IF v_email!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' THEN RETURN jsonb_build_object('success',false,'field','email','error','Please provide a valid email address.');END IF;
 v_cv:=btrim(coalesce(v_answers->>'cvStoragePath',''));v_video:=btrim(coalesce(v_answers->>'videoStoragePath',''));IF v_cv='' OR v_cv NOT LIKE 'applications/%' THEN RETURN jsonb_build_object('success',false,'field','cv','error','A securely uploaded CV or resume is required.');END IF;IF v_video='' OR v_video NOT LIKE 'applications/%' THEN RETURN jsonb_build_object('success',false,'field','video','error','A securely uploaded introduction video is required.');END IF;
 BEGIN v_hours:=greatest(0,coalesce((v_answers->>'availableHoursPerWeek')::integer,0));EXCEPTION WHEN OTHERS THEN v_hours:=0;END;IF v_hours<1 OR v_hours>80 THEN RETURN jsonb_build_object('success',false,'field','availableHoursPerWeek','error','Please provide valid weekly availability.');END IF;
 IF char_length(btrim(coalesce(v_answers->>'contentExperience','')))<30 THEN RETURN jsonb_build_object('success',false,'field','contentExperience','error','Please describe your relevant content-writing experience.');END IF;IF char_length(btrim(coalesce(v_answers->>'researchApproach','')))<30 THEN RETURN jsonb_build_object('success',false,'field','researchApproach','error','Please describe how you research before writing.');END IF;IF char_length(btrim(coalesce(v_answers->>'qualityProcess','')))<30 THEN RETURN jsonb_build_object('success',false,'field','qualityProcess','error','Please describe how you check quality and accuracy.');END IF;
 IF lower(coalesce(v_answers->>'hasLaptopInternet','false')) NOT IN('true','1') THEN RETURN jsonb_build_object('success',false,'field','hasLaptopInternet','error','A reliable laptop and internet connection are required.');END IF;IF lower(coalesce(v_answers->>'consentAccurate','false')) NOT IN('true','1') OR lower(coalesce(v_answers->>'consentPrivacy','false')) NOT IN('true','1') THEN RETURN jsonb_build_object('success',false,'field','consent','error','Accuracy and privacy confirmations are required.');END IF;
 BEGIN v_start:=nullif(btrim(coalesce(v_answers->>'earliestStartDate','')),'')::date;EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('success',false,'field','earliestStartDate','error','Please provide a valid earliest start date.');END;
 SELECT a.id INTO v_existing FROM public.applicants a WHERE a.career_job_id=v_job.id AND lower(btrim(a.email))=v_email AND coalesce(btrim(a.refusal_reason),'')='' ORDER BY a.created_at DESC LIMIT 1;IF v_existing IS NOT NULL THEN RETURN jsonb_build_object('success',true,'duplicate',true,'applicant_id',v_existing,'message','An active Content Creator application already exists for this email.');END IF;
 v_reference:='PF-CC-'||to_char(now(),'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
 INSERT INTO public.applicants(full_name,email,phone,country,timezone,position,linkedin_url,skills,source,stage,rating,notes,onboarding_status,onboarding_progress,final_approval,application_reference,application_version,application_policy_version,application_submitted_at,current_job_title,weekly_availability,available_hours_per_week,earliest_start_date,motivation,has_laptop_internet,accuracy_confirmed_at,privacy_consent_at,cv_storage_path,video_storage_path,career_job_id,application_policy_snapshot,application_answers)
 VALUES(v_name,v_email,btrim(coalesce(v_answers->>'phone','')),btrim(coalesce(v_answers->>'country','')),coalesce(nullif(btrim(v_answers->>'timezone'),''),'UTC'),'Content Creator',nullif(btrim(v_answers->>'linkedinUrl'),''),left(coalesce(v_answers->>'skills',''),5000),'ProFox Website','New Application',0,nullif(left(btrim(coalesce(v_answers->>'message','')),10000),''),'not_started',0,false,v_reference,'content_creator_v2','content_creator_v2',now(),nullif(btrim(v_answers->>'currentRole'),''),nullif(btrim(v_answers->>'weeklyAvailability'),''),v_hours,v_start,nullif(left(btrim(coalesce(v_answers->>'motivation','')),10000),''),true,now(),now(),v_cv,v_video,v_job.id,jsonb_build_object('jobId',v_job.id,'jobSlug',v_job.slug,'jobUpdatedAt',v_job.updated_at,'roleDetails',v_job.role_details),(v_answers-'fullName'-'email'-'portfolioUrl'-'writingSamples')||jsonb_build_object('portfolioDeferred',true,'portfolioMinimumCaseStudies',3)) RETURNING id INTO v_id;
 RETURN jsonb_build_object('success',true,'applicant_id',v_id,'reference',v_reference,'stage','New Application');
EXCEPTION WHEN OTHERS THEN RAISE WARNING 'Content Creator application failed: %',sqlerrm;RETURN jsonb_build_object('success',false,'error','We could not submit your application right now. Please try again.');END;$$;

CREATE OR REPLACE FUNCTION public.public_open_recruitment_task(p_token text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_task public.recruitment_task_instances%rowtype;v_app public.applicants%rowtype;v_submission public.recruitment_task_submissions%rowtype;v_now timestamptz:=now();v_can_edit boolean;v_task_key text;v_default jsonb;
BEGIN
 IF char_length(coalesce(p_token,''))<40 OR char_length(p_token)>200 THEN RAISE EXCEPTION 'Invalid task link.';END IF;SELECT * INTO v_task FROM public.recruitment_task_instances WHERE token_hash IS NOT NULL AND token_hash=public.recruitment_task_token_hash(p_token) FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'This task link is invalid or no longer active.';END IF;PERFORM public.check_recruitment_task_rate_limit(v_task.id,'open',120);SELECT * INTO v_app FROM public.applicants WHERE id=v_task.applicant_id;SELECT * INTO v_submission FROM public.recruitment_task_submissions WHERE task_instance_id=v_task.id;IF v_task.status='Revoked' THEN RAISE EXCEPTION 'This task link has been revoked. Contact the ProFox Recruitment Team.';END IF;
 v_task_key:=coalesce(v_task.template_snapshot->>'taskKey','');v_default:=case when v_task_key='content_writer_portfolio_v2' then '{"portfolioCases":[]}'::jsonb else '{"leads":[]}'::jsonb end;
 IF v_task.viewed_at IS NULL THEN UPDATE public.recruitment_task_instances SET viewed_at=v_now,status=case when status='Issued' then 'Viewed' else status end,updated_at=v_now WHERE id=v_task.id RETURNING * INTO v_task;INSERT INTO public.applicant_events(applicant_id,category,event_type,title,detail,actor_type,source_table,source_id,metadata) VALUES(v_task.applicant_id,'Recruitment','Task Viewed',coalesce(v_task.template_snapshot->>'title','Recruitment task')||' opened','Candidate opened secure recruitment task attempt '||v_task.attempt_no||'.','Candidate','recruitment_task_instances',v_task.id,jsonb_build_object('stage',v_task.stage,'attemptNo',v_task.attempt_no,'taskKey',v_task_key));END IF;
 v_can_edit:=v_task.status IN('Issued','Viewed','In Progress') AND v_task.due_at>=v_now AND v_app.closed_at IS NULL AND v_app.stage=v_task.stage;
 RETURN jsonb_build_object('taskKey',v_task_key,'stage',v_task.stage,'title',v_task.template_snapshot->>'title','description',v_task.template_snapshot->>'description','targetMarket',v_task.template_snapshot->>'targetMarket','targetNiche',v_task.template_snapshot->>'targetNiche','requiredItems',(v_task.template_snapshot->>'requiredItems')::integer,'estimatedMinutes',(v_task.template_snapshot->>'estimatedMinutes')::integer,'instructions',coalesce(v_task.template_snapshot->'instructions','[]'::jsonb),'attemptNo',v_task.attempt_no,'maxAttempts',(v_task.template_snapshot->>'maxAttempts')::integer,'candidateName',v_app.full_name,'applicationReference',v_app.application_reference,'status',v_task.status,'issuedAt',v_task.issued_at,'dueAt',v_task.due_at,'submittedAt',v_task.submitted_at,'retryFeedback',v_task.retry_feedback,'expired',v_task.due_at<v_now,'canEdit',v_can_edit,'answers',case when v_task.submitted_at is null then coalesce(v_submission.draft_data,v_default) else coalesce(v_submission.final_data,v_submission.draft_data,v_default) end);
END;$$;

CREATE OR REPLACE FUNCTION public.public_submit_recruitment_task(p_token text,p_answers jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_task public.recruitment_task_instances%rowtype;v_app public.applicants%rowtype;v_required integer;v_admin record;v_payload jsonb;v_task_key text;v_is_content boolean;v_title text;
BEGIN
 IF char_length(coalesce(p_token,''))<40 OR char_length(p_token)>200 THEN RAISE EXCEPTION 'Invalid task link.';END IF;SELECT * INTO v_task FROM public.recruitment_task_instances WHERE token_hash IS NOT NULL AND token_hash=public.recruitment_task_token_hash(p_token) FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'This task link is invalid or no longer active.';END IF;PERFORM public.check_recruitment_task_rate_limit(v_task.id,'submit',20);IF v_task.status IN('Submitted','Under Review','Passed','Retry Required','Failed') THEN RETURN jsonb_build_object('success',true,'alreadySubmitted',true,'submittedAt',v_task.submitted_at);END IF;SELECT * INTO v_app FROM public.applicants WHERE id=v_task.applicant_id;IF v_task.status='Revoked' THEN RAISE EXCEPTION 'This task link has been revoked.';END IF;IF v_task.due_at<now() THEN RAISE EXCEPTION 'This task deadline has passed. Contact the ProFox Recruitment Team if you need an extension.';END IF;IF v_app.closed_at IS NOT NULL OR v_app.stage<>v_task.stage THEN RAISE EXCEPTION 'This recruitment task is no longer active.';END IF;
 v_required:=(v_task.template_snapshot->>'requiredItems')::integer;v_task_key:=coalesce(v_task.template_snapshot->>'taskKey','');v_is_content:=v_task_key='content_writer_portfolio_v2';v_title:=coalesce(v_task.template_snapshot->>'title','Recruitment task');PERFORM public.assert_recruitment_task_answers(p_answers,v_required,true);
 INSERT INTO public.recruitment_task_submissions(task_instance_id,draft_data,final_data,save_count,last_saved_at,submitted_at,updated_at) VALUES(v_task.id,p_answers,p_answers,1,now(),now(),now()) ON CONFLICT(task_instance_id) DO UPDATE SET draft_data=excluded.draft_data,final_data=excluded.final_data,save_count=public.recruitment_task_submissions.save_count+1,last_saved_at=now(),submitted_at=now(),updated_at=now();UPDATE public.recruitment_task_instances SET status='Submitted',submitted_at=now(),last_saved_at=now(),updated_at=now() WHERE id=v_task.id RETURNING * INTO v_task;
 INSERT INTO public.applicant_events(applicant_id,category,event_type,title,detail,actor_type,source_table,source_id,metadata) VALUES(v_task.applicant_id,'Recruitment','Task Submitted',v_title||' submitted','Candidate submitted secure recruitment task attempt '||v_task.attempt_no||' for review.','Candidate','recruitment_task_instances',v_task.id,jsonb_build_object('stage',v_task.stage,'attemptNo',v_task.attempt_no,'submittedAt',v_task.submitted_at,'taskKey',v_task_key));
 v_payload:=public.recruitment_notification_payload(v_app)||jsonb_build_object('taskTitle',v_title,'taskAttempt',v_task.attempt_no,'taskSubmittedAt',to_char(v_task.submitted_at at time zone 'UTC','Mon DD, YYYY HH24:MI "UTC"'));PERFORM public.enqueue_notification('recruitment-task:'||v_task.id::text||':submitted',case when v_is_content then 'content_recruitment_portfolio_submitted' else 'recruitment_task_submission_received' end,v_app.email,null,v_payload,now());
 FOR v_admin IN SELECT id FROM public.user_profiles WHERE status='active' AND (role='admin' OR (v_is_content AND role IN('editor','site_manager'))) LOOP PERFORM public.enqueue_in_app_notification(v_admin.id,'Recruitment',v_title||' ready for review',v_app.full_name||' submitted '||v_title||' attempt '||v_task.attempt_no||'.','/admin/content-recruitment?applicantId='||v_task.applicant_id::text||'&taskId='||v_task.id::text,'recruitment-task-review:'||v_task.id::text||':'||v_admin.id::text);END LOOP;
 RETURN jsonb_build_object('success',true,'submittedAt',v_task.submitted_at,'status','Submitted');
END;$$;

CREATE OR REPLACE FUNCTION public.service_prepare_recruitment_task_delivery(p_task_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_task public.recruitment_task_instances%rowtype;v_app public.applicants%rowtype;v_token text;v_task_key text;v_is_assessment_hub boolean;v_task_url text;
BEGIN
 IF auth.role() IS DISTINCT FROM 'service_role' THEN RAISE EXCEPTION 'Service role required.';END IF;SELECT * INTO v_task FROM public.recruitment_task_instances WHERE id=p_task_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Recruitment task not found.';END IF;SELECT * INTO v_app FROM public.applicants WHERE id=v_task.applicant_id;v_task_key:=coalesce(v_task.template_snapshot->>'taskKey','');v_is_assessment_hub:=v_task_key='sales_assessment_hub';
 IF v_task.status NOT IN('Issued','Viewed','In Progress') THEN RAISE EXCEPTION 'Recruitment task is not eligible for link delivery.';END IF;IF v_task.due_at<now() THEN RAISE EXCEPTION 'Recruitment task deadline has passed.';END IF;IF v_app.closed_at IS NOT NULL THEN RAISE EXCEPTION 'Recruitment task is no longer active.';END IF;
 IF v_is_assessment_hub THEN IF v_app.stage NOT IN('Shortlisted','Sales Assessment','Lead Research Test','CRM Assessment','Selected','Agreement Pending','Sales Academy Training','Final Approval','Ready for System Access','Activated') THEN RAISE EXCEPTION 'Assessment Preparation Center access is not available for the current recruitment stage.';END IF;ELSIF v_app.stage<>v_task.stage THEN RAISE EXCEPTION 'Recruitment task is no longer active.';END IF;
 v_token:=encode(extensions.gen_random_bytes(32),'hex');UPDATE public.recruitment_task_instances SET token_hash=public.recruitment_task_token_hash(v_token),updated_at=now() WHERE id=v_task.id;
 v_task_url:=case when v_is_assessment_hub then 'https://calabtayklhltyiriiwo.supabase.co/functions/v1/sales-assessment-hub?token='||v_token when v_task_key='content_writer_portfolio_v2' then 'https://www.profoxwebdesigner.com/recruitment/content-portfolio/'||v_token else 'https://www.profoxwebdesigner.com/recruitment/task/'||v_token end;
 RETURN jsonb_build_object('taskUrl',v_task_url,'taskKey',v_task_key,'taskTitle',v_task.template_snapshot->>'title','taskDueDate',to_char(v_task.due_at at time zone 'UTC','Mon DD, YYYY HH24:MI "UTC"'),'taskEstimatedTime',(v_task.template_snapshot->>'estimatedMinutes')||' minutes','taskRequiredItems',v_task.template_snapshot->>'requiredItems','taskTargetMarket',v_task.template_snapshot->>'targetMarket','taskTargetNiche',v_task.template_snapshot->>'targetNiche','taskAttempt',v_task.attempt_no,'taskFeedback',v_task.retry_feedback);
END;$$;

CREATE OR REPLACE FUNCTION public.create_content_writer_agreement_internal(p_applicant_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE a public.applicants%rowtype;j public.career_jobs%rowtype;t public.sales_agreement_templates%rowtype;ctx jsonb;token uuid:=gen_random_uuid();token_hash text;number text;agreement_id uuid;base text;sign_url text;doc_hash text;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required.';END IF;SELECT * INTO a FROM public.applicants WHERE id=p_applicant_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate not found.';END IF;SELECT * INTO j FROM public.career_jobs WHERE id=a.career_job_id;IF j.application_type<>'content_writer' THEN RAISE EXCEPTION 'Candidate is not in the Content Creator workflow.';END IF;IF coalesce(trim(a.refusal_reason),'')<>'' THEN RAISE EXCEPTION 'A closed candidate cannot receive an agreement.';END IF;IF a.stage NOT IN('Selected','Agreement Pending') THEN RAISE EXCEPTION 'Candidate must be conditionally selected before the Content Creator agreement is issued.';END IF;IF EXISTS(SELECT 1 FROM public.sales_partner_agreements x WHERE x.applicant_id=a.id AND x.status IN('Partner Signed','Verified') AND x.agreement_type='content_writer') THEN RAISE EXCEPTION 'A signed Content Creator agreement already exists.';END IF;
 SELECT * INTO t FROM public.sales_agreement_templates WHERE template_key='content_creator_project_contractor' AND status='Published' ORDER BY version DESC LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'Published Content Creator agreement template is unavailable.';END IF;ctx:=public.build_candidate_agreement_snapshot(a.id);number:='PF-CC-AGR-'||to_char(clock_timestamp(),'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));token_hash:=encode(extensions.digest(token::text,'sha256'),'hex');doc_hash:=encode(extensions.digest((jsonb_build_object('agreementNumber',number,'templateVersion',t.version,'partner',ctx->'partner','company',ctx->'company','commercial',ctx->'commercial','training',ctx->'training','hiring',ctx->'hiring','template',jsonb_build_object('title',t.title,'subtitle',t.subtitle,'introduction',t.introduction,'sections',t.sections,'acknowledgements',t.acknowledgements)))::text,'sha256'),'hex');
 UPDATE public.sales_partner_agreements SET status='Superseded',superseded_at=now(),updated_at=now() WHERE applicant_id=a.id AND status IN('Sent','Viewed') AND agreement_type='content_writer';INSERT INTO public.sales_partner_agreements(agreement_number,applicant_id,template_id,template_version,status,token_hash,token_expires_at,partner_snapshot,company_snapshot,commercial_snapshot,training_snapshot,hiring_snapshot,template_snapshot,document_hash,agreement_type,career_job_id,target_role,target_department) VALUES(number,a.id,t.id,t.version,'Sent',token_hash,now()+interval '14 days',ctx->'partner',ctx->'company',ctx->'commercial',ctx->'training',ctx->'hiring',jsonb_build_object('title',t.title,'subtitle',t.subtitle,'introduction',t.introduction,'sections',t.sections,'acknowledgements',t.acknowledgements,'versionLabel',t.version_label),doc_hash,'content_writer',j.id,'content_writer','Content') RETURNING id INTO agreement_id;
 INSERT INTO public.sales_agreement_events(agreement_id,event_type,actor_type,actor_user_id,actor_email,metadata) VALUES(agreement_id,'Issued','Admin',auth.uid(),coalesce((SELECT email FROM public.user_profiles WHERE id=auth.uid()),''),jsonb_build_object('templateVersion',t.version,'documentHash',doc_hash,'agreementType','content_writer'));SELECT coalesce(config_value->>'publicBaseUrl','https://www.profoxwebdesigner.com') INTO base FROM public.system_configuration WHERE config_key='notification_settings';sign_url:=rtrim(coalesce(nullif(base,''),'https://www.profoxwebdesigner.com'),'/')||'/agreement/sign/'||token::text;PERFORM public.enqueue_notification('content-agreement:'||agreement_id::text||':issued','content_recruitment_agreement_ready',a.email,null,public.recruitment_notification_payload(a)||jsonb_build_object('agreementUrl',sign_url,'agreementNumber',number,'agreementId',agreement_id),now());PERFORM set_config('profox.agreement_issue_stage','1',true);PERFORM set_config('profox.agreement_workflow_rpc','1',true);PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET stage='Agreement Pending',agreement_status='sent',updated_at=now() WHERE id=a.id;RETURN jsonb_build_object('agreementId',agreement_id,'agreementNumber',number,'signingUrl',sign_url,'documentHash',doc_hash,'agreementType','content_writer');
END;$$;

CREATE OR REPLACE FUNCTION public.admin_issue_candidate_agreement(p_applicant_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE a public.applicants%rowtype;v_role text;v_type text;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required.';END IF;SELECT * INTO a FROM public.applicants WHERE id=p_applicant_id;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate not found.';END IF;SELECT application_type INTO v_type FROM public.career_jobs WHERE id=a.career_job_id;v_role:=coalesce(public.career_job_system_role(a.career_job_id),'sales');IF v_type='content_writer' OR v_role='content_writer' THEN RETURN public.create_content_writer_agreement_internal(a.id);END IF;IF v_role='developer' THEN RETURN public.create_web_developer_agreement_internal(a.id);END IF;IF v_role='uiux_designer' THEN RETURN public.create_uiux_designer_agreement_internal(a.id);END IF;IF v_role='sales' THEN RETURN public.admin_issue_sales_partner_agreement(a.id);END IF;RAISE EXCEPTION 'No approved agreement workflow is configured for this role.';
END;$$;

CREATE OR REPLACE FUNCTION public.service_link_invited_candidate(p_applicant_id uuid,p_target_user_id uuid,p_account_invite_url text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_app public.applicants%rowtype;v_job public.career_jobs%rowtype;v_profile public.user_profiles%rowtype;v_outbox uuid;
BEGIN
 IF current_user NOT IN('postgres','service_role') AND coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' THEN RAISE EXCEPTION 'Service role required.';END IF;SELECT * INTO v_app FROM public.applicants WHERE id=p_applicant_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate not found.';END IF;SELECT * INTO v_job FROM public.career_jobs WHERE id=coalesce(v_app.career_job_id,public.recruitment_job_for_applicant(v_app.id));IF v_job.application_type='sales_representative' THEN RETURN public.service_link_invited_sales_candidate(p_applicant_id,p_target_user_id,p_account_invite_url);END IF;IF v_job.application_type<>'content_writer' THEN RAISE EXCEPTION 'This account invitation workflow does not support the candidate job type.';END IF;IF coalesce(btrim(v_app.refusal_reason),'')<>'' THEN RAISE EXCEPTION 'Closed candidates cannot receive onboarding access.';END IF;IF v_app.stage NOT IN('Agreement Pending','Content Academy') THEN RAISE EXCEPTION 'Content Creator must reach the signed-agreement onboarding stage before Academy access.';END IF;IF lower(coalesce(v_app.agreement_status,''))<>'signed' THEN RAISE EXCEPTION 'A verified project-based Content Creator agreement is required before Academy access.';END IF;
 IF length(btrim(coalesce(p_account_invite_url,'')))<20 OR p_account_invite_url!~*'^https?://' THEN RAISE EXCEPTION 'A valid secure account setup URL is required.';END IF;SELECT * INTO v_profile FROM public.user_profiles WHERE id=p_target_user_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Invited user profile not found.';END IF;IF lower(btrim(coalesce(v_profile.email,'')))<>lower(btrim(coalesce(v_app.email,''))) THEN RAISE EXCEPTION 'Invited account email must exactly match the candidate application.';END IF;IF v_profile.role IN('admin','customer') THEN RAISE EXCEPTION 'This account cannot be linked as a Content Creator trainee.';END IF;IF EXISTS(SELECT 1 FROM public.applicants x WHERE x.linked_user_id=p_target_user_id AND x.id<>p_applicant_id AND x.stage<>'Activated' AND coalesce(btrim(x.refusal_reason),'')='') THEN RAISE EXCEPTION 'This account is already linked to another active candidate.';END IF;
 PERFORM set_config('profox.recruitment_stage_rpc','1',true);PERFORM set_config('profox.content_writer_invite_rpc','1',true);UPDATE public.applicants SET linked_user_id=p_target_user_id,stage='Content Academy',onboarding_status='in_progress',onboarding_progress=0,onboarding_invite_sent_at=coalesce(onboarding_invite_sent_at,now()),onboarding_invite_last_sent_at=now(),onboarding_invite_count=onboarding_invite_count+1,updated_at=now() WHERE id=p_applicant_id;UPDATE public.user_profiles SET full_name=coalesce(nullif(btrim(v_app.full_name),''),full_name),phone=coalesce(nullif(btrim(v_app.phone),''),phone),country=coalesce(nullif(btrim(v_app.country),''),country),timezone=coalesce(nullif(btrim(v_app.timezone),''),timezone),role='content_writer',department='Content',status='onboarding',onboarding_status='in_progress',onboarding_progress=0,updated_at=now() WHERE id=p_target_user_id;v_outbox:=public.enqueue_notification('recruitment:'||p_applicant_id::text||':content-account-invite:'||(v_app.onboarding_invite_count+1)::text,'content_recruitment_account_invite',lower(btrim(v_app.email)),p_target_user_id,public.recruitment_notification_payload(v_app)||jsonb_build_object('accountInviteUrl',p_account_invite_url,'applicationReference',v_app.application_reference),now());PERFORM public.log_applicant_event(p_applicant_id,'account','content_academy_account_invited','Content Academy account invitation sent','Signed agreement verified; candidate account linked in Content Academy onboarding mode.',v_profile.status,'onboarding','system',null,'user_profiles',p_target_user_id,jsonb_build_object('inviteNumber',v_app.onboarding_invite_count+1,'outboxId',v_outbox));RETURN jsonb_build_object('success',true,'linkedUserId',p_target_user_id,'stage','Content Academy','status','onboarding','inviteNumber',v_app.onboarding_invite_count+1,'applicationType','content_writer');
END;$$;

CREATE OR REPLACE FUNCTION public.admin_advance_applicant_stage(p_applicant_id uuid,p_target_stage text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_app public.applicants%rowtype;v_job public.career_jobs%rowtype;v_target text;v_policy public.recruitment_stage_policies%rowtype;v_from_rank integer;v_to_rank integer;v_role text;
BEGIN
 SELECT * INTO v_app FROM public.applicants WHERE id=p_applicant_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate not found.';END IF;SELECT * INTO v_job FROM public.career_jobs WHERE id=v_app.career_job_id;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate career job is missing.';END IF;IF NOT public.is_admin() AND NOT(v_job.application_type='content_writer' AND public.can_manage_content_applicant(v_app.id)) THEN RAISE EXCEPTION 'Recruitment management access required.';END IF;IF coalesce(trim(v_app.refusal_reason),'')<>'' THEN RAISE EXCEPTION 'Closed candidates cannot progress.';END IF;
 v_role:=coalesce(public.career_job_system_role(v_app.career_job_id),case when v_job.application_type='sales_representative' then 'sales' else 'pending' end);v_target:=coalesce(p_target_stage,public.recruitment_next_stage_for_job(v_app.career_job_id,v_app.stage));IF v_target IS NULL THEN RAISE EXCEPTION 'No next stage is available.';END IF;v_from_rank:=public.recruitment_stage_rank_for_job(v_app.career_job_id,v_app.stage);v_to_rank:=public.recruitment_stage_rank_for_job(v_app.career_job_id,v_target);IF v_from_rank IS NULL OR v_to_rank IS NULL OR v_to_rank<>v_from_rank+1 THEN RAISE EXCEPTION 'Recruitment stages must progress sequentially through the selected job workflow.';END IF;
 IF v_job.application_type='sales_representative' OR v_role='sales' THEN IF v_app.stage='New Application' AND v_target='Video Pending' AND(coalesce(v_app.video_url,'')<>'' OR coalesce(v_app.video_storage_path,'')<>'') THEN v_target:='Video Review';END IF;IF v_app.stage='Video Pending' AND v_target='Video Review' AND coalesce(v_app.video_url,'')='' AND coalesce(v_app.video_storage_path,'')='' THEN RAISE EXCEPTION 'Introduction video is required before Video Review.';END IF;END IF;
 SELECT * INTO v_policy FROM public.recruitment_stage_policies WHERE job_id=v_app.career_job_id AND stage=v_app.stage AND active=true;IF FOUND AND v_policy.assessment_required AND NOT public.recruitment_latest_assessment_passed(v_app.id,v_app.stage) THEN RAISE EXCEPTION 'A passed structured assessment for % is required before progression.',public.recruitment_candidate_stage_label(v_app.stage);END IF;IF FOUND AND v_policy.interview_required AND NOT public.recruitment_interview_requirement_satisfied(v_app.id,v_app.stage) THEN RAISE EXCEPTION 'A completed or administratively skipped structured interview for % is required before progression.',public.recruitment_candidate_stage_label(v_app.stage);END IF;
 IF v_job.application_type='content_writer' THEN
   IF v_app.stage='New Application' THEN IF coalesce(v_app.cv_storage_path,'')='' THEN RAISE EXCEPTION 'Resume/CV is required before Video & Resume Review.';END IF;IF coalesce(v_app.video_storage_path,'')='' AND coalesce(v_app.video_url,'')='' THEN RAISE EXCEPTION 'Introduction video is required before Video & Resume Review.';END IF;END IF;
   IF v_app.stage='Portfolio Review' AND NOT public.content_portfolio_submission_ready(v_app.id) THEN RAISE EXCEPTION 'At least three structured portfolio case studies must be submitted before Portfolio Review can pass.';END IF;
   IF v_app.stage='Selected' THEN RAISE EXCEPTION 'Issue the approved project-based Content Creator agreement before Academy onboarding.';END IF;IF v_app.stage='Agreement Pending' THEN RAISE EXCEPTION 'A verified agreement and protected Academy account invitation are required before Content Academy.';END IF;IF v_app.stage='Content Academy' THEN RAISE EXCEPTION 'Content Academy completion and practical submission control the next stage.';END IF;IF v_app.stage='Practical Certification' THEN RAISE EXCEPTION 'Independent practical certification review controls progression to Final Approval.';END IF;IF v_app.stage='Final Approval' THEN RAISE EXCEPTION 'Use the protected Content Creator Final Approval action.';END IF;IF v_app.stage='Ready for System Access' OR v_target='Activated' THEN RAISE EXCEPTION 'Use protected Content Creator activation after system access is confirmed.';END IF;
 ELSE
   IF v_app.stage='Selected' THEN RAISE EXCEPTION 'Issue the approved candidate agreement to move a Conditional Selected candidate into Agreement.';END IF;IF v_app.stage='Agreement Pending' THEN RAISE EXCEPTION 'A verified agreement and protected account invitation are required before Sales Academy.';END IF;
   IF v_role='sales' AND v_app.stage='Sales Academy Training' THEN IF v_app.linked_user_id IS NULL THEN RAISE EXCEPTION 'A linked Sales Academy account is required before post-Academy assessment.';END IF;IF lower(coalesce(v_app.agreement_status,''))<>'signed' THEN RAISE EXCEPTION 'A verified Sales Partner Agreement is required before post-Academy assessment.';END IF;IF v_app.academy_started_at IS NULL OR v_app.academy_due_at IS NULL THEN RAISE EXCEPTION 'Sales Academy must be started before post-Academy assessment.';END IF;IF v_app.academy_review_wait_started_at IS NOT NULL THEN RAISE EXCEPTION 'Sales Academy progression is locked while a required Management review is pending.';END IF;IF v_app.academy_completed_at IS NULL AND now()>v_app.academy_due_at THEN RAISE EXCEPTION 'The Sales Academy deadline has passed. Complete the controlled Management review process before progression.';END IF;IF NOT public.sales_academy_training_phase_ready(v_app.linked_user_id) THEN RAISE EXCEPTION 'Complete every required Sales Academy training module and Management review before Sales Practical Assessment.';END IF;ELSIF v_app.stage IN('Design Academy','Developer Academy') THEN RAISE EXCEPTION 'The candidate must complete the assigned Academy and request Final Approval through the protected workflow.';END IF;IF v_role='sales' AND v_app.stage='Final Certification' THEN RAISE EXCEPTION 'Complete Final Certification and use the protected Final Approval request.';END IF;IF v_app.stage='Final Approval' THEN RAISE EXCEPTION 'Use the protected Final Approval action.';END IF;IF v_app.stage='Ready for System Access' THEN RAISE EXCEPTION 'Use protected workforce activation.';END IF;
 END IF;
 PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET stage=v_target,updated_at=now() WHERE id=v_app.id;RETURN jsonb_build_object('success',true,'fromStage',v_app.stage,'toStage',v_target,'systemRole',v_role,'applicationType',v_job.application_type);
END;$$;

CREATE OR REPLACE FUNCTION public.sync_content_writer_training_stage()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_module public.training_modules%rowtype;v_app public.applicants%rowtype;
BEGIN
 SELECT * INTO v_module FROM public.training_modules WHERE id=new.module_id;IF v_module.academy_key<>'content_writer' THEN RETURN new;END IF;SELECT a.* INTO v_app FROM public.applicants a JOIN public.career_jobs j ON j.id=a.career_job_id WHERE a.linked_user_id=new.user_id AND j.application_type='content_writer' AND coalesce(btrim(a.refusal_reason),'')='' ORDER BY a.created_at DESC LIMIT 1;IF v_app.id IS NULL OR v_app.stage='Activated' THEN RETURN new;END IF;
 IF v_module.slug='content-practical-certification' AND new.status='Submitted' AND v_app.stage='Content Academy' THEN PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET stage='Practical Certification',onboarding_progress=95,updated_at=now() WHERE id=v_app.id;PERFORM public.enqueue_notification('recruitment:'||v_app.id::text||':content-practical-submitted','content_recruitment_practical_submitted',lower(btrim(v_app.email)),new.user_id,public.recruitment_notification_payload(v_app),now());PERFORM public.service_queue_active_admins_operational_notification('content-practical-review:'||v_app.id::text||':'||new.id::text,'content_recruitment_practical_review','Recruitment','Content practical requires review - '||v_app.full_name,'Review the submitted Content Creator certification against PF-SOP-07.','/admin/content-recruitment?applicantId='||v_app.id::text,jsonb_build_object('applicantId',v_app.id,'progressId',new.id,'candidateName',v_app.full_name),now());ELSIF public.content_academy_required_complete(new.user_id,true) THEN UPDATE public.user_profiles SET onboarding_progress=least(90,greatest(coalesce(onboarding_progress,0),90)),updated_at=now() WHERE id=new.user_id;UPDATE public.applicants SET onboarding_progress=least(90,greatest(coalesce(onboarding_progress,0),90)),updated_at=now() WHERE id=v_app.id;END IF;RETURN new;
END;$$;

CREATE OR REPLACE FUNCTION public.approve_content_writer_final(p_applicant_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_app public.applicants%rowtype;v_progress public.user_training_progress%rowtype;v_review public.training_reviews%rowtype;v_module public.training_modules%rowtype;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Only an active Admin may grant final Content Creator approval.';END IF;SELECT * INTO v_app FROM public.applicants WHERE id=p_applicant_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate not found.';END IF;IF v_app.stage='Ready for System Access' AND v_app.final_approval=true THEN RETURN jsonb_build_object('success',true,'stage',v_app.stage,'alreadyApproved',true);END IF;IF v_app.stage<>'Final Approval' THEN RAISE EXCEPTION 'Candidate must pass Practical Certification before Final Approval.';END IF;IF v_app.linked_user_id IS NULL THEN RAISE EXCEPTION 'A linked candidate account is required.';END IF;IF lower(coalesce(v_app.agreement_status,''))<>'signed' THEN RAISE EXCEPTION 'Verified project-based Content Creator agreement is required.';END IF;IF NOT public.content_academy_required_complete(v_app.linked_user_id,false) THEN RAISE EXCEPTION 'All required Content Academy modules and Practical Certification must be complete.';END IF;
 SELECT * INTO v_module FROM public.training_modules WHERE academy_key='content_writer' AND slug='content-practical-certification' AND active=true LIMIT 1;SELECT * INTO v_progress FROM public.user_training_progress WHERE user_id=v_app.linked_user_id AND module_id=v_module.id AND status='Passed' ORDER BY updated_at DESC LIMIT 1;IF NOT FOUND OR coalesce(v_progress.score,0)<90 THEN RAISE EXCEPTION 'Practical Certification must be passed with a score of at least 90%%.';END IF;SELECT * INTO v_review FROM public.training_reviews WHERE progress_id=v_progress.id AND status='Passed' ORDER BY created_at DESC,id DESC LIMIT 1;IF NOT FOUND OR v_review.reviewer_id IS NULL OR v_review.reviewer_id=v_app.linked_user_id OR coalesce(v_review.score,0)<90 THEN RAISE EXCEPTION 'Independent Practical Certification review at 90%% or above is required.';END IF;
 PERFORM set_config('profox.final_approval_rpc','1',true);PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET final_approval=true,stage='Ready for System Access',onboarding_status='in_progress',onboarding_progress=99,updated_at=now() WHERE id=v_app.id;UPDATE public.user_profiles SET status='onboarding',onboarding_status='in_progress',onboarding_progress=99,updated_at=now() WHERE id=v_app.linked_user_id;PERFORM public.enqueue_notification('recruitment:'||v_app.id::text||':content-final-approved','content_recruitment_final_approved',lower(btrim(v_app.email)),v_app.linked_user_id,public.recruitment_notification_payload(v_app),now());PERFORM public.log_applicant_event(v_app.id,'approval','content_final_approved','Final Approval granted','All Content Academy, agreement and independent practical certification gates verified.','Final Approval','Ready for System Access','admin',auth.uid(),'applicants',v_app.id,jsonb_build_object('practicalScore',v_progress.score,'reviewerId',v_review.reviewer_id));RETURN jsonb_build_object('success',true,'stage','Ready for System Access','finalApproval',true);
END;$$;

CREATE OR REPLACE FUNCTION public.activate_content_writer(p_applicant_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_app public.applicants%rowtype;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION 'Only an active Admin may activate a Content Creator.';END IF;SELECT * INTO v_app FROM public.applicants WHERE id=p_applicant_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Candidate not found.';END IF;IF v_app.stage='Activated' THEN RETURN jsonb_build_object('success',true,'stage','Activated','alreadyActivated',true);END IF;IF v_app.stage<>'Ready for System Access' OR v_app.final_approval IS NOT TRUE THEN RAISE EXCEPTION 'Final Approval and Ready for System Access are required before activation.';END IF;IF v_app.linked_user_id IS NULL THEN RAISE EXCEPTION 'System access account must be linked before activation.';END IF;IF lower(coalesce(v_app.agreement_status,''))<>'signed' THEN RAISE EXCEPTION 'Verified Content Creator agreement is required before activation.';END IF;PERFORM set_config('profox.content_writer_activation_rpc','1',true);PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET stage='Activated',onboarding_status='completed',onboarding_progress=100,updated_at=now() WHERE id=v_app.id;UPDATE public.user_profiles SET role='content_writer',department='Content',status='active',onboarding_status='completed',onboarding_progress=100,updated_at=now() WHERE id=v_app.linked_user_id;PERFORM public.enqueue_notification('recruitment:'||v_app.id::text||':content-activated-v2','content_recruitment_activated',lower(btrim(v_app.email)),v_app.linked_user_id,public.recruitment_notification_payload(v_app),now());PERFORM public.log_applicant_event(v_app.id,'activation','content_writer_activated','Content Creator activated','Final Approval and production system access confirmed. Candidate is eligible for approved projects subject to independent quality review.','Ready for System Access','Activated','admin',auth.uid(),'user_profiles',v_app.linked_user_id,'{}'::jsonb);RETURN jsonb_build_object('success',true,'stage','Activated','linkedUserId',v_app.linked_user_id);
END;$$;

-- Keep candidate practical review separate from Final Approval and Activation.
CREATE OR REPLACE FUNCTION public.admin_review_training_progress(p_progress_id uuid,p_status text,p_feedback text DEFAULT '',p_score integer DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','pg_temp' AS $$
DECLARE v_progress public.user_training_progress%rowtype;v_module public.training_modules%rowtype;v_score integer;v_submission_count integer;v_submission jsonb;v_event_time timestamptz:=clock_timestamp();v_missing_prior integer;v_app public.applicants%rowtype;v_exam_score integer;
BEGIN
 SELECT * INTO v_progress FROM public.user_training_progress WHERE id=p_progress_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Training progress record not found.';END IF;SELECT * INTO v_module FROM public.training_modules WHERE id=v_progress.module_id AND active=true;IF NOT FOUND THEN RAISE EXCEPTION 'Training module is missing or inactive.';END IF;
 IF v_module.academy_key='content_writer' THEN IF NOT public.content_recruitment_manager() THEN RAISE EXCEPTION 'Content Academy review access required.';END IF;ELSIF NOT public.is_admin() THEN RAISE EXCEPTION 'Unauthorized: only an active Admin may review Sales Academy submissions.';END IF;IF auth.uid()=v_progress.user_id THEN RAISE EXCEPTION 'A candidate cannot review their own certification.';END IF;IF p_status NOT IN('Passed','Retry Required') THEN RAISE EXCEPTION 'Training review status must be Passed or Retry Required.';END IF;IF v_module.requires_admin_review IS NOT TRUE THEN RAISE EXCEPTION 'This module does not require an independent review.';END IF;
 IF v_module.academy_key='sales' AND v_module.slug='lead-research' THEN RAISE EXCEPTION 'Use the dedicated Lead Research rubric review workflow for Module 5.';END IF;IF v_module.academy_key='sales' AND v_module.slug='loom-outreach' THEN RAISE EXCEPTION 'Use the dedicated Personalized Loom Outreach rubric review workflow for Module 6.';END IF;IF v_module.academy_key='sales' AND v_module.slug='outreach-cadence' THEN RAISE EXCEPTION 'Use the dedicated Outreach Messaging rubric review workflow for Module 7.';END IF;IF p_status='Passed' AND v_progress.status<>'Submitted' THEN RAISE EXCEPTION 'The trainee must submit or resubmit this module before it can be passed.';END IF;
 SELECT count(*) INTO v_submission_count FROM public.training_assignments WHERE progress_id=v_progress.id AND user_id=v_progress.user_id AND module_id=v_progress.module_id;SELECT submission_data INTO v_submission FROM public.training_assignments WHERE progress_id=v_progress.id AND user_id=v_progress.user_id AND module_id=v_progress.module_id ORDER BY created_at DESC,id DESC LIMIT 1;IF v_module.slug IN('mock-call-test','crm-training','final-certification','content-practical-certification') AND v_submission_count=0 THEN RAISE EXCEPTION 'A trainee submission is required before this module can be reviewed.';END IF;
 IF v_module.slug='content-practical-certification' AND p_status='Passed' THEN IF coalesce(v_submission->>'type','')<>'content_writer_practical' THEN RAISE EXCEPTION 'A valid Content Creator practical submission is required.';END IF;IF char_length(coalesce(v_submission->>'content',''))<300 AND coalesce(v_submission->>'contentUrl','')='' THEN RAISE EXCEPTION 'The practical must include substantial sample copy or a secure content URL.';END IF;IF char_length(coalesce(v_submission->>'researchNotes',''))<80 THEN RAISE EXCEPTION 'Research/source notes are required for the practical.';END IF;IF char_length(coalesce(v_submission->>'handoffNotes',''))<80 THEN RAISE EXCEPTION 'A UI/UX handoff note is required for the practical.';END IF;END IF;
 IF v_module.slug='final-certification' THEN IF coalesce(v_submission->>'type','')<>'final_certification_exam' OR jsonb_typeof(v_submission->'answers') IS DISTINCT FROM 'array' OR jsonb_array_length(v_submission->'answers')<>15 THEN RAISE EXCEPTION 'A server-scored 15-question Final Certification submission is required.';END IF;BEGIN v_exam_score:=(v_submission->>'score')::integer;EXCEPTION WHEN OTHERS THEN RAISE EXCEPTION 'Final Certification server score is missing or invalid.';END;v_score:=v_exam_score;ELSE v_score:=coalesce(p_score,case when p_status='Passed' then 100 else 50 end);END IF;IF v_score<0 OR v_score>100 THEN RAISE EXCEPTION 'Training review score must be between 0 and 100.';END IF;IF p_status='Passed' AND v_module.passing_score IS NOT NULL AND v_score<v_module.passing_score THEN RAISE EXCEPTION 'A score of at least % is required to pass this module.',v_module.passing_score;END IF;
 IF v_module.slug='final-certification' AND p_status='Passed' THEN SELECT count(*) INTO v_missing_prior FROM public.training_modules m WHERE m.academy_key='sales' AND m.active=true AND m.required=true AND m.sort_order<v_module.sort_order AND NOT EXISTS(SELECT 1 FROM public.user_training_progress p WHERE p.user_id=v_progress.user_id AND p.module_id=m.id AND p.status IN('Passed','Completed') AND (m.passing_score IS NULL OR coalesce(p.score,0)>=m.passing_score));IF v_missing_prior>0 THEN RAISE EXCEPTION 'Final Certification cannot pass until all previous required modules are complete. Missing: %',v_missing_prior;END IF;END IF;IF v_module.slug='content-practical-certification' AND p_status='Passed' AND NOT public.content_academy_required_complete(v_progress.user_id,true) THEN RAISE EXCEPTION 'All required Content Academy learning modules must be complete before practical certification can pass.';END IF;
 INSERT INTO public.training_reviews(progress_id,reviewer_id,status,feedback,score,created_at) VALUES(v_progress.id,auth.uid(),p_status,coalesce(p_feedback,''),v_score,v_event_time);UPDATE public.user_training_progress SET status=case when p_status='Passed' then 'Passed' else 'Retry Required' end,review_status=p_status,reviewed_by=auth.uid(),reviewed_at=v_event_time,feedback=coalesce(p_feedback,''),score=v_score,progress_percent=case when p_status='Passed' then 100 else 50 end,completed_at=case when p_status='Passed' then v_event_time else null end,updated_at=v_event_time WHERE id=v_progress.id;
 IF v_module.slug='content-practical-certification' THEN SELECT a.* INTO v_app FROM public.applicants a JOIN public.career_jobs j ON j.id=a.career_job_id WHERE a.linked_user_id=v_progress.user_id AND j.application_type='content_writer' AND coalesce(btrim(a.refusal_reason),'')='' ORDER BY a.created_at DESC LIMIT 1 FOR UPDATE OF a;IF v_app.id IS NULL THEN RAISE EXCEPTION 'Linked Content Creator candidate record not found.';END IF;IF p_status='Passed' THEN IF lower(coalesce(v_app.agreement_status,''))<>'signed' THEN RAISE EXCEPTION 'Verified Content Creator agreement is required before practical certification can pass.';END IF;PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET stage='Final Approval',final_approval=false,onboarding_status='in_progress',onboarding_progress=97,updated_at=now() WHERE id=v_app.id;UPDATE public.user_profiles SET status='onboarding',onboarding_status='in_progress',onboarding_progress=97,updated_at=now() WHERE id=v_progress.user_id;PERFORM public.enqueue_notification('recruitment:'||v_app.id::text||':content-practical-passed','content_recruitment_practical_passed',lower(btrim(v_app.email)),v_progress.user_id,public.recruitment_notification_payload(v_app)||jsonb_build_object('score',v_score),now());PERFORM public.log_applicant_event(v_app.id,'certification','content_practical_passed','Practical Certification passed','Independent Content Creator practical review passed at the required standard.','Practical Certification','Final Approval','admin',auth.uid(),'user_training_progress',v_progress.id,jsonb_build_object('progressId',v_progress.id,'score',v_score));ELSE PERFORM set_config('profox.recruitment_stage_rpc','1',true);UPDATE public.applicants SET stage='Content Academy',onboarding_progress=90,updated_at=now() WHERE id=v_app.id;PERFORM public.enqueue_notification('recruitment:'||v_app.id::text||':content-practical-retry:'||v_progress.id::text,'content_recruitment_practical_retry',lower(btrim(v_app.email)),v_progress.user_id,public.recruitment_notification_payload(v_app)||jsonb_build_object('feedback',coalesce(p_feedback,'')),now());END IF;END IF;
END;$$;

GRANT EXECUTE ON FUNCTION public.create_content_writer_agreement_internal(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_content_writer_final(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.activate_content_writer(uuid) TO authenticated;
