-- Ensure a custom-priced primary catalog offer can always resolve a valid payment schedule.
-- This closes the PF-CUSTOM gap where custom line items already received an automatic
-- schedule, but the PF-CUSTOM primary product incorrectly failed send-readiness.

create or replace function public.resolve_quotation_payment_schedule(p_quotation_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_count int;
  v_product record;
  v_schedule jsonb;
  v_total numeric;
  v_first_type text;
  v_cfg jsonb:=public.quotation_cpq_settings_safe();
  v_custom_count int;
  v_quotation_total numeric;
  v_auto_generated boolean:=false;
begin
  select total into v_quotation_total from public.quotations where id=p_quotation_id;
  if not found then raise exception 'Quotation not found.'; end if;

  select count(*) into v_count
  from public.quotation_items qi
  join public.sales_products sp on sp.id=qi.sales_product_id
  where qi.quotation_id=p_quotation_id
    and qi.optional_for_client=false
    and qi.line_type='product'
    and sp.product_type in ('package','discovery','custom');

  if v_count>1 then
    raise exception 'Only one primary pricing plan may be selected per quotation. Keep one package or discovery offer and add any additional services as add-ons.';
  end if;

  if v_count=1 then
    select qi.product_code_snapshot,qi.product_name_snapshot,sp.payment_schedule,sp.standard_payment_terms,sp.price_mode
    into v_product
    from public.quotation_items qi
    join public.sales_products sp on sp.id=qi.sales_product_id
    where qi.quotation_id=p_quotation_id
      and qi.optional_for_client=false
      and qi.line_type='product'
      and sp.product_type in ('package','discovery','custom')
    order by qi.sort_order,qi.created_at
    limit 1;

    v_schedule:=v_product.payment_schedule;

    -- Custom-priced primary catalog offers (including PF-CUSTOM) use the same
    -- established amount-based automatic schedule as standalone custom offers
    -- when no explicit approved catalog schedule has been configured.
    if v_product.price_mode='custom' then
      if v_schedule is null or jsonb_typeof(v_schedule)<>'array' then
        v_schedule:=public.auto_custom_quotation_payment_schedule(v_quotation_total);
        v_product.product_code_snapshot:=coalesce(nullif(v_product.product_code_snapshot,''),'CUSTOM')||'-AUTO-V1';
        v_auto_generated:=true;
      elsif jsonb_array_length(v_schedule)=0 then
        v_schedule:=public.auto_custom_quotation_payment_schedule(v_quotation_total);
        v_product.product_code_snapshot:=coalesce(nullif(v_product.product_code_snapshot,''),'CUSTOM')||'-AUTO-V1';
        v_auto_generated:=true;
      end if;
    end if;
  else
    select count(*) into v_custom_count
    from public.quotation_items
    where quotation_id=p_quotation_id
      and optional_for_client=false
      and line_type='custom';

    if v_custom_count=0 then
      raise exception 'Quotation must contain one committed primary package or custom offer before payment can be configured.';
    end if;

    v_schedule:=coalesce(v_cfg->'customPaymentSchedule','[]'::jsonb);
    v_product.product_code_snapshot:='CUSTOM';
    v_product.product_name_snapshot:='Custom Proposal';
    v_product.standard_payment_terms:=nullif(btrim(coalesce(v_cfg->>'standardTerms','')),'');

    if v_schedule is null or jsonb_typeof(v_schedule)<>'array' or jsonb_array_length(v_schedule)=0 then
      v_schedule:=public.auto_custom_quotation_payment_schedule(v_quotation_total);
      v_product.product_code_snapshot:='CUSTOM-AUTO-V1';
      v_auto_generated:=true;
    end if;
  end if;

  if v_schedule is null or jsonb_typeof(v_schedule)<>'array' or jsonb_array_length(v_schedule)=0 then
    raise exception 'The selected offer does not have an approved payment schedule. Configure it before sending the quotation.';
  end if;

  select coalesce(sum((x->>'percentage')::numeric),0)
  into v_total
  from jsonb_array_elements(v_schedule) x;

  if round(v_total,4)<>100 then
    raise exception 'The approved payment schedule must total 100 percent.';
  end if;

  select x->>'paymentType'
  into v_first_type
  from jsonb_array_elements(v_schedule) x
  order by (x->>'milestoneNumber')::int
  limit 1;

  if v_first_type not in ('Advance','Full Payment') then
    raise exception 'The first approved payment milestone must be Advance or Full Payment so the verified sale can enter delivery.';
  end if;

  return jsonb_build_object(
    'sourceCode',v_product.product_code_snapshot,
    'sourceName',v_product.product_name_snapshot,
    'schedule',v_schedule,
    'standardPaymentTerms',v_product.standard_payment_terms,
    'autoGenerated',v_auto_generated
  );
end;
$function$;
