-- Restore Admin-issued sessions for the four retained synthetic departmental
-- identities without activating them as production staff. Their profile status
-- remains inactive so production RLS and workforce reporting stay closed.

create table if not exists public.test_staff_login_audit (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.user_profiles(id) on delete restrict,
  test_user_id uuid not null references public.user_profiles(id) on delete restrict,
  test_role text not null check (test_role in ('sales','content_writer','uiux_designer','developer')),
  origin text,
  issued_at timestamptz not null default now(),
  constraint test_staff_login_audit_different_users check (admin_user_id <> test_user_id)
);

create index if not exists test_staff_login_audit_admin_issued_idx
  on public.test_staff_login_audit(admin_user_id, issued_at desc);
create index if not exists test_staff_login_audit_user_issued_idx
  on public.test_staff_login_audit(test_user_id, issued_at desc);

alter table public.test_staff_login_audit enable row level security;
revoke all on table public.test_staff_login_audit from public, anon, authenticated;
revoke all on sequence public.test_staff_login_audit_id_seq from public, anon, authenticated;
grant insert on table public.test_staff_login_audit to service_role;
grant usage, select on sequence public.test_staff_login_audit_id_seq to service_role;

comment on table public.test_staff_login_audit is
  'Append-only audit of active Admins requesting isolated synthetic departmental sessions.';

do $do$
declare v_invalid integer;
begin
  select count(*) into v_invalid
  from public.user_profiles p
  where lower(p.email) in (
    'sales.demo@profoxwebdesigner.test',
    'content.demo@profoxwebdesigner.test',
    'designer.demo@profoxwebdesigner.test',
    'developer.demo@profoxwebdesigner.test'
  )
    and not (
      p.status='inactive'
      and p.onboarding_status='completed'
      and p.onboarding_progress=100
      and p.role in ('sales','content_writer','uiux_designer','developer')
    );
  if v_invalid > 0 then
    raise exception 'Retained test staff profiles do not satisfy the isolated test-account boundary.';
  end if;
end;
$do$;
