-- Module 19 — 20 server-scored confidentiality/data-protection scenarios + 7 acknowledgements

do $$ declare v_module uuid; begin
 select id into v_module from public.training_modules where slug='confidentiality-data-protection';
 if v_module is null then raise exception 'Module 19 missing.'; end if;
 delete from public.training_assessment_questions where module_id=v_module;
 delete from public.training_acknowledgements where module_id=v_module;
 insert into public.training_assessment_questions(module_id,prompt,options,correct_index,explanation,sort_order,active,assessment_section,case_key,critical) values
(v_module,'A company work email is publicly listed on its website. What is the strongest ProFox rule?','["Use it for any purpose because it is public","Use it only through the approved ProFox research/outreach process and respect suppression rules","Copy it to every personal prospecting tool","Assume it is permanent consent"]'::jsonb,1,'Public visibility does not create unrestricted permission. Use approved outreach rules.',1,true,'scenario','public_contact',false),
(v_module,'A teammate requests a customer/prospect export unrelated to their assigned work. What should you do?','["Send it because they work at ProFox","Upload it to personal Drive first","Verify legitimate need/authorization and use the approved access or sharing path","Give them your account instead"]'::jsonb,2,'Need-to-know access applies even inside the same company.',2,true,'scenario','need_to_know',false),
(v_module,'A customer sends their website admin password in ordinary chat. What should Sales do?','["Do not retain it in ordinary notes; move the credential issue to the approved secure process","Paste it into CRM so Development can find it","Email it to yourself","Reuse it to test the site immediately"]'::jsonb,0,'Passwords are Restricted information and do not belong in ordinary CRM/chat storage.',3,true,'scenario','customer_password',true),
(v_module,'An unexpected MFA approval prompt appears while you are not signing in. What is correct?','["Approve it so the notification stops","Ignore it for the day","Ask a coworker to approve it","Deny it, secure the account and report the event"]'::jsonb,3,'Unexpected MFA may indicate account takeover. Deny, secure and report.',4,true,'scenario','unexpected_mfa',true),
(v_module,'An urgent “CEO” email requests a full customer export to an unfamiliar link. What should you do?','["Upload the export immediately","Pause, verify through a trusted independent channel and report the suspicious request","Reply only to the same email asking if it is real","Forward the link to customers"]'::jsonb,1,'Urgency is not authority. Sensitive unusual requests require independent verification.',5,true,'scenario','phishing_export',true),
(v_module,'You accidentally email Client A confidential material to Client B. What is the correct first operating response?','["Delete your sent copy and stay quiet","Wait for Client B to complain","Stop, take authorized protective action, report immediately, preserve evidence and follow incident instructions","Edit the CRM to hide the error"]'::jsonb,2,'Fast reporting improves containment. Concealing the disclosure makes the incident worse.',6,true,'scenario','wrong_recipient',true),
(v_module,'During screen share you notice another customer record is visible. What should you do?','["Stop/limit the share immediately, protect the information and follow the appropriate reporting process","Keep sharing but scroll quickly","Ask the customer not to look","Delete the other customer record"]'::jsonb,0,'Screen sharing is data sharing; accidental cross-client exposure must be stopped and handled truthfully.',7,true,'scenario','screen_share',false),
(v_module,'A seller wants to record discovery calls using a personal recording app. What is correct?','["Always record because notes are useful","Record only if the seller promises not to share it","Record personal audio but delete it later","Use only the approved ProFox recording workflow and required notice/consent process"]'::jsonb,3,'Recording creates additional confidential/personal data and must use the approved process.',8,true,'scenario','recording',false),
(v_module,'A prospect explicitly asks ProFox not to contact them again. What should Sales do?','["Record and honor the approved no-contact/suppression process","Contact them from a personal number instead","Ask another rep to contact them","Continue quarterly outreach"]'::jsonb,0,'A clear no-contact instruction must be handled through the approved suppression process.',9,true,'scenario','no_contact',false),
(v_module,'A seller uploads customer files to personal cloud storage because it is convenient. What is correct?','["Fine if the folder is private","Use personal storage only overnight","Do not use unapproved personal storage; keep customer information in approved ProFox systems","Fine if the customer does not know"]'::jsonb,1,'Personal/unapproved storage creates uncontrolled copies and access risk.',10,true,'scenario','personal_storage',true),
(v_module,'You want AI to draft a follow-up from a confidential discovery transcript. What is the strongest approach?','["Paste the entire transcript into any AI site","Include credentials because more context helps","Use an approved AI tool with only the minimum authorized context and remove unnecessary sensitive information","Post the transcript publicly first"]'::jsonb,2,'AI productivity does not override confidentiality. Use approved tools and data minimization.',11,true,'scenario','ai_minimization',false),
(v_module,'An approved temporary CRM export is no longer needed. What should happen?','["Keep it forever just in case","Email it to your personal account","Create another backup first","Follow the approved retention/deletion process and remove unnecessary copies"]'::jsonb,3,'Exports are extra copies. When the legitimate purpose ends, approved retention/deletion rules apply.',12,true,'scenario','retention',false),
(v_module,'A CRM phone number is confirmed to be factually wrong. What is the best action?','["Leave it because historical data should never change","Correct or route the correction through the authorized CRM process","Guess a replacement number","Delete the entire customer record"]'::jsonb,1,'Accurate data supports both customer rights and sales productivity.',13,true,'scenario','accuracy',false),
(v_module,'A prospect asks for another customer’s private project details to compare vendors. What should you do?','["Refuse to disclose confidential customer information; use only approved public proof/case studies","Share the details if it may help close","Show screenshots but hide the company name","Ask the other customer later"]'::jsonb,0,'Cross-client disclosure destroys trust and is a critical confidentiality failure.',14,true,'scenario','cross_client_disclosure',true),
(v_module,'A teammate asks for your login because their access has not been created yet. What should you do?','["Share it for one day","Write the password on a call","Do not share accounts; request the correct authorized access","Create a shared password"]'::jsonb,2,'One person should use one authorized account so access and audit trails remain trustworthy.',15,true,'scenario','shared_account',false),
(v_module,'Your work laptop with CRM access is lost. What is the correct response?','["Wait 24 hours in case it is found","Only change your personal email password","Buy a replacement first","Report immediately and follow the approved device/account containment process"]'::jsonb,3,'Lost devices can expose active sessions and customer data; fast containment is critical.',16,true,'scenario','lost_device',true),
(v_module,'A customer messages their card CVV and an OTP and asks you to finish the payment. What should Sales do?','["Do not use or retain the secrets; direct the customer to the approved secure payment process","Use them once and delete the message","Paste them into the payment note","Forward them to another seller"]'::jsonb,0,'CVV/OTP are restricted secrets and must never be handled through ordinary sales channels.',17,true,'scenario','payment_secrets',true),
(v_module,'A customer asks, “Give me everything ProFox stores about me.” What should Sales do?','["Promise immediate legal deletion instead","Recognize, record and route the request through the approved privacy/Admin process","Ignore the request","Send an unrestricted database export"]'::jsonb,1,'Formal privacy/data requests should be recognized and routed rather than improvised by Sales.',18,true,'scenario','privacy_request',false),
(v_module,'A seller emails a CRM CSV to their personal account to work from home. What is correct?','["Fine if the file is password protected","Fine for high performers","Do not create the personal copy; use approved ProFox systems/access methods","Delete it next month"]'::jsonb,2,'Personal copies weaken access control and create retention/security problems.',19,true,'scenario','personal_export',false),
(v_module,'You think you may have clicked a phishing link but nothing unusual has happened yet. What should you do?','["Wait until visible damage appears","Clear browser history and say nothing","Keep using the account normally","Report immediately and follow the approved containment/security process"]'::jsonb,3,'Early reporting matters even before visible damage appears.',20,true,'scenario','phishing_click',false);

 insert into public.training_acknowledgements(module_id,statement,sort_order,required,active) values
(v_module,'I will access and use customer, prospect, employee and ProFox information only for authorized business purposes and only to the extent required for my role.',1,true,true),
(v_module,'I will never share accounts or store passwords, OTPs, authentication tokens, API keys, card credentials or other Restricted secrets inside ordinary CRM notes, chats or documents.',2,true,true),
(v_module,'I will use only ProFox-approved systems, communication channels, storage locations, AI tools and credential processes for company/customer information.',3,true,true),
(v_module,'I will independently verify unusual or sensitive requests and will never approve an authentication request I did not initiate.',4,true,true),
(v_module,'I understand that publicly available contact information does not automatically mean unrestricted permission to use it, and I will follow ProFox approved outreach and suppression rules.',5,true,true),
(v_module,'I will not disclose one customer’s confidential information, pricing, documents, strategy, project details or communications to another customer unless specifically authorized.',6,true,true),
(v_module,'I will report suspected loss, disclosure, phishing, unauthorized access or other security/privacy incidents immediately and will never conceal an incident or alter evidence to protect myself.',7,true,true);
end $$;
