import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,CalendarClock,CheckCircle2,ExternalLink,Loader2,RefreshCw,Save,ShieldAlert,Target,UserRound,XCircle}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{EvaluatorQueueItem,EvaluatorSession,mockCallTrainingService}from'../../lib/mockCallTrainingService';

const fmt=(v?:string|null,tz?:string)=>{if(!v)return 'Not scheduled';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'full',timeStyle:'short',timeZone:tz||undefined}).format(new Date(v))}catch{return new Date(v).toLocaleString()}};
const nice=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());

export default function MockCallEvaluatorWorkspace(){
 const navigate=useNavigate();const[queue,setQueue]=useState<EvaluatorQueueItem[]>([]);const[selected,setSelected]=useState<EvaluatorSession|null>(null);
 const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');
 const[scores,setScores]=useState<Record<string,number>>({});const[critical,setCritical]=useState<Record<string,boolean>>({});const[feedback,setFeedback]=useState('');const[meetingUrl,setMeetingUrl]=useState('');
 const total=useMemo(()=>selected?.rubric.reduce((sum,item)=>sum+(scores[item.id]||0),0)||0,[selected,scores]);
 const max=useMemo(()=>selected?.rubric.reduce((sum,item)=>sum+item.maxPoints,0)||100,[selected]);const normalized=max?Math.round(total*100/max):0;
 const loadQueue=async()=>{setLoading(true);setError('');const{data,error:e}=await mockCallTrainingService.getEvaluatorQueue();if(e)setError(e.message||'Evaluator assignments could not be loaded.');else setQueue(data);setLoading(false);};
 const openSession=async(id:string)=>{setBusy(true);setError('');const{data,error:e}=await mockCallTrainingService.getEvaluatorSession(id);if(e||!data)setError(e?.message||'Evaluator scenario could not be loaded.');else{setSelected(data);setScores(Object.fromEntries(data.rubric.map(r=>[r.id,Math.round(r.maxPoints*.7)])));setCritical(Object.fromEntries(data.criticalRules.map(r=>[r.id,false])));setFeedback(data.feedback||'');setMeetingUrl(data.meetingUrl||'');}setBusy(false);};
 useEffect(()=>{void loadQueue()},[]);
 const saveLink=async()=>{if(!selected)return;setBusy(true);setError('');const{error:e}=await mockCallTrainingService.updateMeetingLink(selected.id,meetingUrl);if(e)setError(e.message||'Meeting link could not be saved.');else{setMessage('Meeting link saved and the trainee was notified.');await openSession(selected.id);}setBusy(false);};
 const decline=async()=>{if(!selected)return;const reason=window.prompt('Why can you not take this mock call? The system will immediately find another eligible evaluator.','Scheduling conflict');if(reason===null)return;if(!reason.trim()){setError('Add a short reason before releasing the assignment.');return;}setBusy(true);setError('');const{error:e}=await mockCallTrainingService.declineAssignment(selected.id,reason.trim());if(e)setError(e.message||'Assignment could not be released.');else{setSelected(null);setMessage('Assignment released. ProFox is reassigning the trainee automatically.');await loadQueue();}setBusy(false);};
 const submit=async()=>{if(!selected)return;if(feedback.trim().length<20){setError('Give the trainee specific coaching feedback before submitting the evaluation.');return;}setBusy(true);setError('');const criticalIds=selected.criticalRules.filter(r=>critical[r.id]).map(r=>r.id);const{data,error:e}=await mockCallTrainingService.submitEvaluation(selected.id,scores,criticalIds,feedback.trim());if(e)setError(e.message||'Mock call evaluation could not be submitted.');else{setMessage((data as any)?.passed?'Evaluation passed. The trainee can continue.':'Retry Required. A fresh scenario and retry are being scheduled automatically.');setSelected(null);await loadQueue();}setBusy(false);};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="h-8 w-8 animate-spin text-[#000080]"/></div>;
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white px-5 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex items-center gap-3"><button onClick={()=>navigate('/admin/workspace')} className="rounded-xl border border-slate-200 p-2"><ArrowLeft className="h-4 w-4"/></button><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#000080]">ProFox Sales Academy</div><h1 className="text-xl font-black">Mock Call Evaluator Workspace</h1><p className="text-xs text-slate-500">Role-play the prospect first. Coach and score only after the call.</p></div></div><button onClick={()=>void loadQueue()} className="rounded-xl border border-slate-200 p-2.5"><RefreshCw className="h-4 w-4"/></button></div></header><main className="mx-auto grid max-w-7xl gap-6 p-5 lg:grid-cols-[330px_1fr]">{error&&<Notice danger>{error}</Notice>}{message&&<Notice>{message}</Notice>}
  <aside className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-sm font-black">Assigned mock calls</h2><span className="rounded-full bg-[#000080]/10 px-2.5 py-1 text-[10px] font-black text-[#000080]">{queue.length}</span></div>{!queue.length?<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-500">No mock calls currently require your evaluation.</div>:queue.map(item=><button key={item.id} onClick={()=>void openSession(item.id)} className={`w-full rounded-2xl border p-4 text-left transition ${selected?.id===item.id?'border-[#000080] bg-blue-50':'border-slate-200 bg-white hover:border-blue-200'}`}><div className="text-xs font-black">{item.traineeName}</div><div className="mt-1 text-[11px] text-slate-500">Attempt {item.attemptNo} · {item.scenarioName}</div><div className="mt-2 flex items-center gap-1.5 text-[10px] font-bold text-slate-600"><CalendarClock className="h-3.5 w-3.5"/>{fmt(item.scheduledStartAt,item.timezone)}</div></button>)}</aside>
  <section>{busy&&!selected?<div className="flex justify-center p-10"><Loader2 className="h-6 w-6 animate-spin"/></div>:!selected?<div className="rounded-3xl border border-slate-200 bg-white p-10 text-center"><UserRound className="mx-auto h-10 w-10 text-slate-300"/><h2 className="mt-3 font-black">Choose an assigned mock call</h2><p className="mt-1 text-sm text-slate-500">The confidential evaluator brief opens only for the assigned evaluator or Admin.</p></div>:<div className="space-y-6">
   <section className="rounded-3xl bg-gradient-to-r from-[#000080] to-[#FF0E0E] p-6 text-white"><div className="text-[10px] font-black uppercase tracking-widest text-white/70">Attempt {selected.attemptNo} · Confidential Evaluator Brief</div><h2 className="mt-1 text-2xl font-black">{selected.traineeName} · {selected.scenarioName}</h2><p className="mt-2 text-sm text-white/80">{fmt(selected.scheduledStartAt,selected.timezone)} · Status: {selected.status.replaceAll('_',' ')}</p></section>
   <section className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm leading-6 text-red-950"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-red-600"/><div><strong>Stay in prospect mode during the call.</strong> Do not coach the trainee, reveal hidden facts for free, or tell them which rubric item they missed. Give the information a genuine prospect would give when an appropriate question earns it.</div></div></section>
   <div className="grid gap-5 xl:grid-cols-2"><BriefSection title="What the trainee knows" data={selected.sellerBrief}/><BriefSection title="Your private prospect scenario" data={selected.evaluatorBrief}/></div>
   <section className="rounded-3xl border border-slate-200 bg-white p-5"><div className="text-[10px] font-black uppercase tracking-widest text-[#000080]">Evaluator instructions</div><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{selected.evaluatorInstructions}</p></section>
   <section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black">Meeting access</h3><p className="mt-1 text-xs text-slate-500">Use your approved call link. Saving it updates this session and notifies the trainee.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={meetingUrl} onChange={e=>setMeetingUrl(e.target.value)} placeholder="https://meet.google.com/... or approved Zoom/Teams link" className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#000080]"/><button onClick={()=>void saveLink()} disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#000080] px-4 py-2.5 text-xs font-black text-white"><Save className="h-4 w-4"/>Save Link</button>{selected.meetingUrl&&<a href={selected.meetingUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-black">Open<ExternalLink className="h-4 w-4"/></a>}</div><button onClick={()=>void decline()} disabled={busy} className="mt-3 inline-flex items-center gap-2 text-xs font-black text-red-600"><XCircle className="h-4 w-4"/>I cannot take this call — auto reassign</button></section>
   <section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><Target className="h-5 w-5 text-[#000080]"/><h3 className="font-black">Post-call scoring rubric</h3></div><p className="mt-1 text-xs text-slate-500">Complete this only after the live role-play. The frozen rubric belongs to this attempt even if Admin changes future standards.</p><div className="mt-5 space-y-3">{selected.rubric.map(item=><div key={item.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-sm font-black">{item.title}</div><p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p></div><div className="flex items-center gap-2"><input type="number" min={0} max={item.maxPoints} value={scores[item.id]??0} onChange={e=>setScores(s=>({...s,[item.id]:Math.max(0,Math.min(item.maxPoints,Number(e.target.value)||0))}))} className="w-20 rounded-xl border border-slate-200 px-3 py-2 text-center text-sm font-black"/><span className="text-xs font-bold text-slate-400">/ {item.maxPoints}</span></div></div></div>)}</div><div className="mt-4 rounded-2xl bg-blue-50 p-4 text-sm font-black text-blue-950">Current score: {normalized}/100</div></section>
   <section className="rounded-3xl border border-red-200 bg-white p-6"><h3 className="font-black text-red-900">Critical failures</h3><p className="mt-1 text-xs text-slate-500">Check a rule only if the trainee actually committed that critical failure. Any checked rule forces Retry Required regardless of the numerical score.</p><div className="mt-4 space-y-2">{selected.criticalRules.map(rule=><label key={rule.id} className={`flex items-start gap-3 rounded-2xl border p-4 text-sm ${critical[rule.id]?'border-red-300 bg-red-50':'border-slate-200'}`}><input type="checkbox" checked={!!critical[rule.id]} onChange={e=>setCritical(c=>({...c,[rule.id]:e.target.checked}))} className="mt-1"/><span><strong>{rule.title}</strong><br/><span className="text-xs leading-5 text-slate-500">{rule.description}</span></span></label>)}</div></section>
   <section className="rounded-3xl border border-slate-200 bg-white p-6"><h3 className="font-black">Coaching feedback</h3><p className="mt-1 text-xs text-slate-500">Be specific: what the seller did well, what weakened the conversation, and what to deliberately practise before the next real call or retry.</p><textarea rows={6} value={feedback} onChange={e=>setFeedback(e.target.value)} className="mt-3 w-full rounded-2xl border border-slate-200 p-4 text-sm leading-6 outline-none focus:border-[#000080]" placeholder="Example: Your opening was concise and your root-cause follow-ups were strong. You moved to a recommendation before fully mapping the decision process. On your next rehearsal..."/><button onClick={()=>void submit()} disabled={busy||!selected.scheduledStartAt||Date.now()<new Date(selected.scheduledStartAt).getTime()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#000080] px-5 py-3 text-xs font-black text-white disabled:opacity-40"><CheckCircle2 className="h-4 w-4"/>{busy?'Submitting securely...':'Submit Live Evaluation'}</button>{selected.scheduledStartAt&&Date.now()<new Date(selected.scheduledStartAt).getTime()&&<p className="mt-2 text-center text-[11px] text-slate-400">Scoring unlocks when the scheduled live call begins.</p>}</section>
  </div>}</section>
 </main></div>;
}
function BriefSection({title,data}:{title:string;data:Record<string,any>}){return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-4 space-y-3">{Object.entries(data||{}).map(([key,value])=><div key={key} className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">{nice(key)}</div>{Array.isArray(value)?<ul className="mt-1 list-disc space-y-1 pl-4 text-sm leading-6">{value.map((v,i)=><li key={i}>{String(v)}</li>)}</ul>:<div className="mt-1 whitespace-pre-wrap text-sm leading-6">{typeof value==='object'?JSON.stringify(value,null,2):String(value??'')}</div>}</div>)}</div></section>}
function Notice({danger=false,children}:{danger?:boolean;children:React.ReactNode}){return <div className={`lg:col-span-2 rounded-2xl border p-4 text-sm ${danger?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{children}</div>}
